-- additional fields
ALTER TABLE `useraccount` 	
ADD COLUMN `locations` varchar(50) DEFAULT NULL,
ADD COLUMN `wheretosell` varchar(255) DEFAULT NULL,
ADD COLUMN `willingtopay` tinyint(4) unsigned DEFAULT NULL,
ADD COLUMN `preferredcommunication` varchar(255) DEFAULT NULL,
ADD COLUMN `whentopay` varchar(50) DEFAULT NULL,
ADD COLUMN `isorgpaying` tinyint(4) unsigned DEFAULT NULL,
ADD COLUMN `radiostations` varchar(255) DEFAULT NULL,
ADD COLUMN `radioshows` varchar(255) DEFAULT NULL,
ADD COLUMN `nameofbank` varchar(255) DEFAULT NULL,
ADD COLUMN `budgettracking` tinyint(4) unsigned DEFAULT NULL,
ADD COLUMN `earnedlastwk` varchar(50) DEFAULT NULL,
ADD COLUMN `spentlastwk` varchar(50) DEFAULT NULL,
ADD COLUMN `earnedlastmonth` varchar(50) DEFAULT NULL,
ADD COLUMN `spentlastmonth` varchar(50) DEFAULT NULL,
ADD COLUMN `earnedlastyear` varchar(50) DEFAULT NULL,
ADD COLUMN `spentlastyear` varchar(50) DEFAULT NULL,
ADD COLUMN `moneybehavior` varchar(50) DEFAULT NULL,
ADD COLUMN `moneyplace` varchar(50) DEFAULT NULL,
ADD COLUMN `savingplan` varchar(255) DEFAULT NULL,
ADD COLUMN `takenloan` tinyint(4) unsigned DEFAULT NULL,
ADD COLUMN `paybackperiod` varchar(50) DEFAULT NULL,
ADD COLUMN `paydifficulty` varchar(50) DEFAULT NULL,	 
ADD COLUMN `oldageplan` varchar(255) DEFAULT NULL,
ADD COLUMN `eatless` varchar(255) DEFAULT NULL,
ADD COLUMN `childlackoffunds` varchar(255) DEFAULT NULL,
ADD COLUMN `seizedforloan` varchar(255) DEFAULT NULL,
ADD COLUMN `unpaidbills` varchar(255) DEFAULT NULL,
ADD COLUMN `selloutassets` varchar(255) DEFAULT NULL,
ADD COLUMN `runoutrevenue` varchar(255) DEFAULT NULL;