<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid); 
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("name","description"));
	$paginate->setDefaultSortBy("name");	
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE c.id <> '' ";
	
	$paginate->processPost($request->getParams());
	$all_results_query = "select c.* from `company` `c` WHERE c.name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('company/list');
	$title = "FARMIS Partners";
	$listitems = "Partners";
	$this->headTitle($title.$browserappend);
	$description = '';
	
?>
<script>
$(document).ready(function() {
	$("#levelone_icon").addClass('icon-list');
	$("#levelone_link").attr('href', '<?php echo $listurl; ?>').html('<?php echo $title; ?>');
	$("#leveltwo_link").html('');

});
</script>
<div>
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
        <div class="container-fluid">
            <div class="row margin0 maxwidth">
                <form action="<?php echo $this->baseUrl("partner/listsearch"); ?>" method="get" id="listform" class="form-search makerelative">
                    <h1><?php echo $title; ?></h1>
                    <div class="wellcontent">
                    	<div class="blocked clear makerelative">
                            <ul class="peoplegroup">
                                <li>
                                    <?php if($acl->checkPermission('Partner', ACTION_CREATE)) { ?>	
                                        <a href="<?php echo $this->baseUrl('company'); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> New Partner</a>
                                    <?php } ?>
                                </li>
                                <li style="float:right;"><input name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" type="text" class="input-medium" placeholder="Search">
                                    <button type="submit" id="searchbutton" class="btn btn-primary noround"><i class="icon-search icon-white"></i></button>
                                </li>
                            </ul>
                      	</div>
						<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                            <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                            <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                        <?php } ?>
                        	
                        <?php if ($has_no_data) { ?>
                            <div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("global_list_norecords"); ?></div>
                        <?php } else { ?>
                        	<div class="makerelative">
                            	<div class="xpaginatecustom align-right"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            </div>
                            <div class="divider2"></div>
                            <div class="container-fluid makerelative">
                            	<div class="row" style="margin-left:-12px; margin-right:-12px;">
                                    <div class="peoplelist">
                                    <?php 				  
                                    	$counter = 1;		
                                    		foreach($result as $line){
												$id = $line['id'];
												$name = $line['name'];
												$description = $line['description'];
												
												$viewurl = $this->baseUrl('company/view/id/'.encode($id));
												$counter_mod = $counter % 2;
												$modclass = '';
												// debugMessage('mod is '.$counter_mod);
												if($counter_mod == 0){
													$modclass = ' odd';
												}
                                    ?>
										<?php if($counter_mod == 1){ ?>
                                        <div class="row-fluid">
                                        <?php } ?>
                                        <div class="span6">
                                            <div class="peoplewrapper well clearfix">
                                                <div class="thumbwrapper" style="height:85px; width:110px;">
                                                    <div class="thumb">
                                                        <div id="thumbinfo"> 
                                                            <a href="<?php echo $viewurl; ?>"><img class="ximagecontainer" src="<?php echo $this->baseUrl('uploads/farmgroups/default/medium_group.jpg'); ?>" /></a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="peopleinfo">
                                                    <h4><a href="<?php echo $viewurl; ?>"><?php echo $name; ?></a></h4>
                                                    <ul>
                                                        <li>&nbsp;</li>
                                                        <li><span class="bolded">Description:</span> <?php echo $description; ?></li>
                                                    </ul>
                                                </div>
                                            </div>
										<?php if($counter_mod == 0){ ?>
                                        </div>
                                        <?php } ?>
                                    </div>
                                    <?php $counter++; } ?>
                                    </div>
                                    <?php echo $paginate->getPaginationLinks(); ?>  
                                </div>
                            </div>
                     	<?php } ?>
                    </div>
              	</form>
       		</div>
    	</div>
   	</div>
</div>    