<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country);
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array());
	$paginate->setFilterColumns(array());
	// $paginate->setDefaultSortBy("u.datecreated");	
	// $paginate->setDefaultSortOrder("DESC");
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " ";
	
	// filter by start and end of profiling
	$startdate = $request->getParam('startdate');
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
	}
	
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) >= TO_DAYS('".$startdate."')) ";
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) <= TO_DAYS('".$enddate."')) ";
	}
	
	// age group filter 
	$range = $request->getParam('range');
	if(!isEmptyString($range)){
		switch($range){
			case 1:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (0 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (14 * 365.25)) ";
				break;
			case 2:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (15 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (24 * 365.25)) ";
				break;
			case 3:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (25 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (29 * 365.25)) ";
				break;
			case 4:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (30 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (39 * 365.25)) ";
				break;
			case 5:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (40 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (49 * 365.25)) ";
				break;
			case 6:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (50 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (59 * 365.25)) ";
				break;
			case 7:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) >= (30 * 365.25) AND DATEDIFF(CURRENT_DATE, u.dateofbirth) <= (60 * 365.25)) ";
				break;
			case 8:
				$where_query .= " AND (DATEDIFF(CURRENT_DATE, u.dateofbirth) > (60 * 365.25)) ";
				break;
		}
	}
	
	// farming since
	$farmingsince = $request->getParam('farmingsince');
	if(!isEmptyString($farmingsince)){
		switch($farmingsince){
			case 1: // less than 3 years
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear BETWEEN 0 and 2 ";
				break;
			case 2: // 3 to 5 years
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear BETWEEN 3 and 5 ";
				break;
			case 3: // 6 - 10 years
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear BETWEEN 6 and 10 ";
				break;
			case 4: // 11 - 20 years
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear BETWEEN 11 and 20 ";
				break;
			case 5: // 21 - 30 years
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear BETWEEN 21 and 30 ";
				break;
			case 6: // 
				$where_query .= " AND YEAR(CURRENT_DATE()) - u.bizstartyear >= 31  ";
				break;
		}
	}
	
	// acrage
	$landusage = $request->getParam('landusage');
	if(!isEmptyString($landusage)){
		switch($landusage){
			case 1: // less than 3 years
				$where_query .= " AND u.landsize BETWEEN 0 and 2 ";
				break;
			case 2: // 3 to 5 years
				$where_query .= " AND u.landsize BETWEEN 3 and 5 ";
				break;
			case 3: // 6 - 10 years
				$where_query .= " AND u.landsize BETWEEN 6 and 10 ";
				break;
			case 4: // 11 - 20 years
				$where_query .= " AND u.landsize BETWEEN 11 and 20 ";
				break;
			case 5: // 21 - 30 years
				$where_query .= " AND u.landsize BETWEEN 21 and 30 ";
				break;
			case 6: // 
				$where_query .= " AND u.landsize >= 31  ";
				break;
		}
	}
	
	$partner_query = ""; $partner_details = array(); $indtype = ''; 
	/*if($loggedinuser->isPartner()){
		$allowedlist = $loggedinuser->getCompany()->getAllocationDetails(true);
		$partnertype = $loggedinuser->getCompany()->getFarmisType();
		$indtype = $loggedinuser->getCompany()->getShowInd();
		switch($partnertype){
			case 2:
			case 3:
				$partner_query = " AND l.regionid in(".$allowedlist.") ";
				if($indtype == 0){
					$partner_query .= " AND u.farmgroupid <> '' ";
				}
				$partner_details = array("type"=>$partnertype, "allowedlist"=>$allowedlist, "regionlist" => $partner_query);
				break;
			case 4:
			case 5:
				$partner_query = " AND u.locationid in(".$allowedlist.") "; 
				if($indtype == 0){
					$partner_query .= " AND u.farmgroupid <> '' ";
				}
				$partner_details = array("type"=>$partnertype, "allowedlist"=>$allowedlist, "districtlist" => $partner_query);
				break;
			case 6:
			case 7:
				$partner_query = " AND u.farmgroupid in(".$allowedlist.") ";
				$partner_query_dna = " AND f.id in(".$allowedlist.") ";
				if($indtype == 0){
					$partner_query .= " AND u.farmgroupid <> '' ";
				}
				$partner_details = array("type"=>$partnertype, "allowedlist"=>$allowedlist, "dnalist" => $partner_query);
				break;
			default:
				break;
		}
	}
	*/
	$paginate->processPost($request->getParams());
	$all_results_query = "
			SELECT l.id as id,
			l.name as district, 
			count(u.id) as totalfarmers, 
			SUM(u.landsize) as totalacreage,
			SUM(IF(u.landsize BETWEEN 0 and 2,u.landsize,0)) as lessthantwo, 
			SUM(IF(u.landsize BETWEEN 0 and 2,1,0)) as lessthantwo_count, 
			SUM(IF(u.landsize BETWEEN 3 and 5,u.landsize,0)) as btn3and5, 
			SUM(IF(u.landsize BETWEEN 3 and 5,1,0)) as btn3and5_count, 
			SUM(IF(u.landsize BETWEEN 6 and 10,u.landsize,0)) as btn6and10, 
			SUM(IF(u.landsize BETWEEN 6 and 10,1,0)) as btn6and10_count, 
			SUM(IF(u.landsize BETWEEN 11 and 20,u.landsize,0)) as btn11and20, 
			SUM(IF(u.landsize BETWEEN 11 and 20,1,0)) as btn11and20_count, 
			SUM(IF(u.landsize BETWEEN 21 and 30,u.landsize,0)) as btn21and30, 
			SUM(IF(u.landsize BETWEEN 21 and 30,1,0)) as btn21and30_count, 
			SUM(IF(u.landsize > 31,u.landsize,0)) as greaterthan30,	
			SUM(IF(u.landsize > 31,1,0)) as greaterthan30_count			 
			from useraccount u
			left join location l on (u.locationid = l.id and l.locationtype = 2)
			where LOWER(u.country) = LOWER('".$session->getVar('country')."') ".$where_query.$partner_query."
			GROUP BY u.locationid 
			HAVING count(u.id) > 0 
			order by totalfarmers desc";
	
	// debugMessage($all_results_query); // exit;
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($all_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	// debugMessage($result);
	$total = count($result); // debugMessage($croptotal);
	
	$title = "Acreage and Land Utilization Report";
	$this->headTitle($title); 
	
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/custom/table2CSV.js'); ?>"></script>
<script>
$(document).ready(function() {
	<?php if($request->print == 1){ ?>
		$("#headercontainer, #leftcolumn, .footer, #blankrow").remove().hide();
		$(".printpage").html($("#printer_page_action_buttons").html());
	<?php } ?>
	
	datepickerOpts.dateFormat = '<?php echo $config->dateandtime->javascriptmediumformat; ?>'; 
	$("#startdate, #enddate").datepicker(datepickerOpts); 
	
	<?php if($request->print == 1 || $request->excel == 1){ ?>
		$("body").addClass('print');
		$("body.print .hideonprint").html('').remove();
		$("body.print a.sortlink").removeAttr('href').removeAttr('title');
	<?php } ?>
	
	$("#searchbutton").click(function(e){
		e.preventDefault();
		alert('clicked');
		//$("#reportform").attr('action', '<?php //echo $this->baseUrl('report/acreagesearch'); ?>').attr('method', 'get').submit();
	});
	$(".submitexcel").click(function(e){
		e.preventDefault();
		var csv_value = $('#data').table2CSV({delivery:'value'});
		var decoded_value = base64_encode(csv_value);	// alert(decoded_value);
		$("#csv_text").val(decoded_value);	/**/
		
		$("#reportform").attr('action', '<?php echo $this->baseUrl('download/excel'); ?>').attr('method', 'post').submit();
		return true;
	});
});
</script>
<style>
#contentcolumn {
	min-height:600px;
}
#centercolumn {
	padding: 5px 0;
	width: 100%;
	margin-left:0;
	float:left;
}
#centercolumn h1, #centercolumn h2 {
	font-family:calibri, Telex, sans-serif;
}
#pageleft {
	margin:0 5px 0 0;
	width:100%;
	float:left;
	position:relative;
}
#pageleft .widgetsection {
	width:98%;
}
.widgetsection {
	margin-bottom:10px;
}
.widgetsection h3 {
	font-size:15px;
}
.contenttable {
	border:solid 1px #b3b3b3;
	border-collapse: separate;
 	*border-collapse: collapsed;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}
.contenttable h2 {
	margin: 0;
	padding: 8px 0 8px 0;
	line-height:auto;
	text-align: left;
	border-bottom:1px solid #c4c2c2;
	color:#498D0F;
	font-size:18px;
	width:100%;
	font-weight:bold;
	line-height:16px;
}
.contenttable#estimates thead tr td {
	font-weight:bold;
	font-size:12px;
}
#outlength {
	width:72%;
}
.reportcontainer {
	height:auto; 
	min-height:400px; 
	display:block; 
	margin-top:10px;
	position:relative;
}
.reportlabel {
	display:inline-block;
	font-weight:bold;
	font-size:16px;
	padding-right:5px;
}
.reportfilter {
	margin-top:0; 
	float:right;
	margin-right:-10px;
	width:100%;
}
.reportlinks {
	margin-top:-10px;
}
#generate {
	margin-top:-10px;
}
.printpage {
	display:none;
}
pdfquicklinks {
	position:absolute; 
	left:10px; 
	top:8px;
}
.widgetsection h3.reportpagetitle {
	color:#282727;
}
.control-label {
	font-size:12px;
	white-space:nowrap;
	display:block;
	width:100%;
	text-align:left;
}
.contenttable .control-label {
	width:auto;
	white-space:normal;
	text-align:left;
	display:block;
}
.control-label.notbolded {
	font-size:11px !important;
}
.table#data tr td {
	white-space:nowrap;
}
.paginatecustom {
	position:absolute;
	left:12px;
	top:10px;
	width:auto;
	text-align:left;
	float:left;
}
.pager {
	text-align:right;
}
<?php if($request->print == 1) { ?> 
#contentwrapper {
	margin: 10px 0 5px;
}
#centercolumn {
	float:left;
	width:90%;
}
#maincontainer.container {
	margin-left:20px;
	margin-top:10px;
}
#printer_page_action_buttons {
	margin:10px;
}
.hideonprint {
	display:none;
}
.printpage {
	margin:10px;
	display:block;
}
<?php } ?>
</style>
<form action="<?php echo $this->baseUrl("report/acreagesearch"); ?>" method="get" id="reportform" class="form-search margin0" style="margin-top:5px;">

<div>
  <div id="centercolumn">
  	<div class="printpage"></div>
    <?php if($request->print == 1){ ?>
    	<table class="table border0 table-condensed nohover nobg margin0">
        	<tr>
                <td style="width:118px;">
					<?php if($acl->checkPermission('Crop Profiling Aggregated Report', ACTION_EXPORT)) { ?>	
                        <a title="Export to Excel" class="btn export gonowhere " ><i class="icon-download-alt"></i> Export Data </a>&nbsp;
                    <?php } ?>
               	</td>
                <td></td>
           	</tr>
		</table>            
    <?php } ?>
    <div class="hideonprint" style="width:100%;">
        <span class="reportfilter">
        	<table class="table table-condensed noborder margin0" style="width:auto; display:inline-block;">
            	<tr>
                	<td style="width:120px;"><label class="control-label inline" style="font-size:12px;">Added From:</label>
                        <input name="startdate"  id="startdate" type="text" class="datefield startdate inline input-width-small width110" value="<?php echo $request->startdate; ?>" />
                    </td>
                    <td style="width:120px;"><label class="control-label inline" style="font-size:12px;">Added To:</label>
                        <input name="enddate" id="enddate" type="text" class="datefield input-width-small width110"  value="<?php echo $request->enddate; ?>" />
                    </td>
                    <td style="width:100px;">
                            <label class="control-label">Age Group:</label>
                            <?php
                                $allgenders = array('' => 'All','1'=>'0-14','2'=>'15-24','3'=>'25-29','4'=>'30-39','5'=>'40-49','6'=>'50-59','7'=>'Btn 30 and 60','8'=>'Greater than 60');
                                $dropdown = new Zend_Form_Element_Select('range',
                                                    array(
                                                        'multiOptions' => $allgenders,
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('gender','width100'),
                                                        'title' => 'Filter By Age Group'		
                                                    )
                                );  
                                $dropdown->setValue($request->getParam('range')); 
                                echo $dropdown->render();
                            ?>
                        </td>
                    <td style="width:100px;">
                    	<label class="control-label">Duration in Farming:</label>
						<?php
                            $allgenders = array('' => 'All Ranges','1'=>'Less than 3yrs','2'=>'3-5yrs','3'=>'6-10yrs','4'=>'11-20yrs','5'=>'21-30yrs','6'=>'More than 30yrs');
                            $dropdown = new Zend_Form_Element_Select('farmingsince',
                                                array(
                                                    'multiOptions' => $allgenders,
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                    'class' => array('gender','width100'),
                                                    'title' => 'Filter By Duration in Farming'		
                                                )
                            );  
                            $dropdown->setValue($request->getParam('farmingsince')); 
                            echo $dropdown->render();
                        ?>
                    </td>
                    <td style="width:100px; vertical-align:bottom;">
                        <button type="submit" id="searchbutton" class="btn btn-primary" style="padding:6px 10px;"><i class="icon-white icon-search"></i> Generate</button>
                        <input type="hidden" name="country" id="country" value="<?php echo $country; ?>" />
                    </td>
                    <?php if (!$has_no_data) { ?>
                    <td>
                    	<label class="control-label">&nbsp;</label>
                    	<input type="hidden" name="csv_text" id="csv_text" value="" />
                        <?php if($acl->checkPermission('Crop Profiling Aggregated Report', ACTION_EXPORT)) { ?>
                        <button type="button" class="btn btn-primary submitexcel" title="Export to Excel" style="padding:6px 10px;"><i class='icon-download-alt icon-white'></i> Export to Excel</button>
                        <?php } ?>
                    </td>
                    <?php } ?>
                    <td><label class="control-label">&nbsp;</label><a href="<?php echo $this->baseUrl('report/acreage');; ?>" id="reset" class="btn" title="Reset Report">Reset</a></td>
                </tr>
                <tr>
                    <?php if($loggedinuser->isUgandan() && isUganda() && $acl->checkPermission('Is UG Admin can Administer KE', ACTION_YESNO)){ ?>
						<td colspan="2">
							<?php if(isEmptyString($request->country) || $countryreq == 'ug'){ ?>
                                <a class="btn" href="<?php echo $this->baseUrl('report/acreage/country/ke'); ?>" title="Browse Kenya"><i class="icon-list"></i> Browse Kenya</a>
                            <?php } ?>
                        </td>
                    <?php } ?>    
                    <?php if($loggedinuser->isUgandan() && isKenya() && $acl->checkPermission('Is UG Admin can Administer KE', ACTION_YESNO)){ ?>
                    	<td colspan="2">
							<?php if(!isEmptyString($request->country) && $countryreq == 'ke'){ ?>
                                <a class="btn" href="<?php echo $this->baseUrl('report/acreage/country/ug'); ?>" title="Browse Uganda"><i class="icon-list"></i> Browse Uganda</a>
                            <?php } ?>
                        </td>
                    <?php } ?>
				</tr>                    
            </table>
    	</span>
    </div>
    <div class="pull-left" id="pageleft">
        <div class="widgetsection reportcontainer">
        	<h3 class="reportpagetitle"><?php echo $title; ?></h3>
			<?php if ($has_no_data) { ?>
                <div style="clear:both;" class="alert alert-info margin5">There are no records for this report</div>
            <?php } else { ?>
                <div style="width:100%; display:block; height:30px;; position:relative;">
                    <div class="paginatecustom"><?php echo "Viewing records for ".count($result).' Locations'; ?></div>
                </div>
                <div style="width:100%; height:auto; overflow:auto; margin-bottom:10px; display:block;">
                    
                    <table id="data" class="table table-bordered" style="margin:10px 0 10px 0; width:auto;">
                        <thead>
                            <tr>
                                <td style="width:25px;" rowspan="2"><label class="control-label">#</label></td>
                                <td style="width:150px;" rowspan="2"><label class="control-label">Location</label></td>
                                <td style="width:90px;"><label class="control-label bolded">Total Farmers</label></td>
                                <td style="width:90px;"><label class="control-label bolded">Total Acreage</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign"><= 2 Acres</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign">Btn 3-5 Acres</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign">Btn 6-10 Acres</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign">Btn 11-20 Acres</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign">Btn 21-30 Acres</label></td>
                                <td style="width:130px; text-align:center;" colspan="3"><label class="control-label centeralign">>=31 Acres</label></td>
                            </tr>
                            <tr>
                                <td><label class="control-label notbolded">No of Farmers (NOF)</label></td>
                                <td><label class="control-label notbolded">No of Acres (NOA)</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label bolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label notbolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label notbolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label notbolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label notbolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                                <td><label class="control-label notbolded">NOF</label></td>
                                <td><label class="control-label notbolded">%age</label></td>
                                <td><label class="control-label notbolded">NOA</label></td>
                                
                            </tr>
                        </thead>
                        <tbody>
                            <?php
								 $counter = 1;
								 $total = 0;
								 $maletotal = 0; $femaletotal = 0; $phonetotal = 0; $nophonetotal = 0;
                                 foreach($result as $line){
									 /*$malepctg = round(($line['male']/$line['totalfarmers'])*100,1);
									 $femalepctg = round(($line['female']/$line['totalfarmers'])*100,1);
									 $phonepctg = round(($line['withphone']/$line['totalfarmers'])*100,1);
									 $nophonepctg = round(($line['nophone']/$line['totalfarmers'])*100, 1);*/
                            ?>
                            <tr>
                            	<td><span class="nullifempty"><?php echo $counter; ?></span></td>
                                <td><span class="nullifempty bolded"><?php echo $line['district']; ?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['totalfarmers'],0); ?></span></td>
                                <td class="rightalign"><span class="xnullifempty"><?php echo $line['totalacreage'] == '' ? '0' : formatNumber($line['totalacreage'],0); ?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['lessthantwo_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['lessthantwo_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['lessthantwo']); ?></span></td>
                                
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn3and5_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['btn3and5_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn3and5']); ?></span></td>
                                
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn6and10_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['btn6and10_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn6and10']); ?></span></td>
                                
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn11and20_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['btn11and20_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn11and20']); ?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn21and30_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['btn21and30_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['btn21and30']); ?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['greaterthan30_count']); ?></span></td>
                                <td class="rightalign bolded"><span class="nullifempty"><?php echo formatNumber($line['greaterthan30_count']/$line['totalfarmers']*100) ;?></span></td>
                                <td class="rightalign"><span class="nullifempty"><?php echo formatNumber($line['greaterthan30']); ?></span></td>
                             </tr>
                            <?php $counter++; } ?>
                        </tbody>
                    </table>
                </div>
            <?php } ?>
		</div>
  	</div>
</div>
</div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>