<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	// require_once(APPLICATION_PATH.'/../'.PUBLICFOLDER.'/dompdf/dompdf_config.inc.php');
		
	$title = "Farmers Bio Data Report";
	$this->headTitle($title); 
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country);
	
?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('assets/js/custom/table2CSV.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('assets/js/custom/jquery.doubleScroll.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('assets/js/custom/jquery.slimscroll.min.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('assets/js/custom/jquery.slimscroll.horizontal.min.js')); ?>"></script>
<script>
$(document).ready(function() {
	datepickerOpts.dateFormat = '<?php echo $config->dateandtime->javascriptmediumformat; ?>'; 
	$("#startdate, #enddate").datepicker(datepickerOpts); 
	
	$(".submitexcel").hide();
	$("#reportdata").html('<label class="labeldescription noresults">Select report parameters and Click Generate</label>');
	$("#searchbutton").click(function(e){
		$("#reportdata").html('<div style="padding-top:50px; padding-bottom:100px; font-weight:bold;" class="centeralign blocked"><label class="centeralign blocked">Loading report data...<br /><br /> A moment please...</label><br />'+$("#wait").html()+'</div>');
		$(".submitexcel").hide();
		
		var startdate = $("#startdate").val();
		var enddate = $("#enddate").val();
		var gender = $("#u__gender").val();
		var range = $("#range").val();
		var maritalstatus = $("#maritalstatus").val();
		var educationlevel = $("#educationlevel").val();
		var farmgroupid = $("#farmgroupid").val();
		var locationid = $("#locationid").val();
		var profiledby = $("#profiledby").val();
		var country = $("#country").val();
		var hasphone = $("#hasphone").val();
		var cropid = $("#cropid").val();
		var farmingsince = $("#farmingsince").val();
		var landusage = $("#landusage").val();
		
		var url = "<?php echo $this->baseUrl('report/allfarmersdata'); ?>/startdate/"+startdate+"/enddate/"+enddate+"/gender/"+gender+"/range/"+range+"/maritalstatus/"+maritalstatus+"/educationlevel/"+educationlevel+"/farmgroupid/"+farmgroupid+"/locationid/"+locationid+"/profiledby/"+profiledby+"/country/"+country+"/hasphone/"+hasphone+"/cropid/"+cropid+"/farmingsince/"+farmingsince+"/landusage/"+landusage;
		// alert(url); 
		$.get(url, 
		   {                        
			cachebuster: new Date().getTime()},                            
			function(data){                        
				// alert(data);                        
				$('#reportdata').html(data);
				$(".submitexcel").show().removeClass('hidden');
				$('div.controls, .nullifempty').each(function() {
					var html = $(this).html();
					if(isEmptyString(html)){
						$(this).html('--');
					}
				});
				
				$(".submitexcel").click(function(e){
					e.preventDefault();
					var csv_value = $('#data').table2CSV({delivery:'value'});
					var decoded_value = base64_encode(csv_value);
					$("#csv_text").val(decoded_value);
					
					$("#listform").attr('action', '<?php echo $this->baseUrl('download/excel'); ?>').attr('method', 'post').submit();
					return true;
				});
				
				$("#all").attr('checked', true);
				$(".iscolumn").attr('checked', true);
				$("#all").click(function(){				
					if (this.checked == true) {			
						$(".iscolumn").attr('checked', true);
						$("#data tr td").removeClass("hidden").addClass("visible");
					} else {			
						$(".iscolumn").attr('checked', false);
						$("#data tr td").removeClass("visible").addClass("hidden");
					} 
				});
				
				$(".iscolumn").click(function(){
					var id = $(this).attr('id');
					if (this.checked == true) {
						$("#data tr td."+id).removeClass("hidden").addClass("visible");
					} else {
						$("#data tr td."+id).removeClass("visible").addClass("hidden");
					}
				});
				
				 // $('#double-scroll').doubleScroll();
				 $(".wrapper1").scroll(function(){
					$(".wrapper2").scrollLeft($(".wrapper1").scrollLeft());
				});
				$(".wrapper2").scroll(function(){
					$(".wrapper1").scrollLeft($(".wrapper2").scrollLeft());
				});
				
				$(".wrapper2").slimScroll({
					height: '500px',
					size: '15px',
					position: 'right',
					color: '#000',
					alwaysVisible: true,
					distance: '1px',
					railVisible: true,
					railColor: '#fff',
					railOpacity: 0.8,
					wheelStep: 10
				});
			}
		);
		$("#listform").attr('action', '').attr('method', '').removeAttr('action').removeAttr('method');
	});
	
});
</script>
<style>
#contentcolumn {
	min-height:600px;
}
#centercolumn {
	padding: 5px 0;
	width: 99%;
	margin-left:0;
	float:left;
}
#centercolumn h1, #centercolumn h2 {
	font-family:calibri, Telex, sans-serif;
}
#pageleft {
	margin:0 5px 0 0;
	width:100%;
	float:left;
	position:relative;
}
#pageleft .widgetsection {
	width:98%;
}
.widgetsection {
	margin-bottom:10px;
}
.widgetsection h3 {
	font-size:15px;
}
.contenttable {
	border:solid 1px #b3b3b3;
	border-collapse: separate;
 	*border-collapse: collapsed;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}
.contenttable .control-label {
	width:auto;
	white-space:normal;
	text-align:left;
	display:block;
}
.contenttable h2 {
	margin: 0;
	padding: 8px 0 8px 0;
	line-height:auto;
	text-align: left;
	border-bottom:1px solid #c4c2c2;
	color:#498D0F;
	font-size:18px;
	width:100%;
	font-weight:bold;
	line-height:16px;
}
.contenttable#estimates thead tr td {
	font-weight:bold;
	font-size:12px;
}
#outlength {
	width:72%;
}
.reportcontainer {
	height:auto; 
	min-height:400px; 
	display:block; 
	margin-top:10px;
	position:relative;
}
.reportlabel {
	display:inline-block;
	font-weight:bold;
	font-size:16px;
	padding-right:5px;
}
.reportfilter {
	margin-top:0; 
	float:right;
	margin-right:-10px;
	width:100%;
}
.reportlinks {
	margin-top:-10px;
}
#generate {
	margin-top:-10px;
}
.printpage {
	display:none;
}
pdfquicklinks {
	position:absolute; 
	left:10px; 
	top:8px;
}
.widgetsection h3.reportpagetitle {
	color:#282727;
}
.control-label {
	font-size:12px;
	white-space:nowrap;
	display:block;
	width:100%;
	text-align:left;
}
.table#data tr td {
	white-space:nowrap;
}
.paginatecustom {
	position:absolute;
	left:12px;
	top:10px;
	width:auto;
	text-align:left;
	float:left;
}
.pager {
	text-align:right;
}
#columnfilter span {
	text-align:left;
	display:inline-block;
	margin-left:5px;
}
input.checkbox {
	margin-right:10px;
	display:inline;
}
.wrapper1, .wrapper2 {
	width: 100%; 
	border: none 0px #cccccc;
	overflow-x: scroll; 
	overflow-y:scroll;
}
.wrapper1 {
	height: 20px; 
}
.wrapper2 {
	height: 600px;
	overflow:scroll;
}
.div1 {
	width:5000px; 
	height: 20px; 
}
.div2 {
	width:3200px; 
	background:none;
	overflow: auto;
}
</style>
<form id="listform" class="form-search margin0" style="margin-top:5px;">
<div>
  <div id="centercolumn">
    <div class="hideonprint" style="width:100%;">
        <?php if((isAdmin() || isFarmGroupAdmin() || isManagement())){ ?>
            <span class="reportfilter">
                <table class="table table-condensed noborder margin0" style="width:auto; display:inline-block;">
                    <tr>
                        <td style="width:120px;"><label class="control-label inline" style="font-size:12px;">Added From:</label>
                            <input name="startdate"  id="startdate" type="text" class="datefield startdate inline input-width-small width110" value="<?php echo $request->startdate; ?>" />
                        </td>
                        <td style="width:120px;"><label class="control-label inline" style="font-size:12px;">Added To:</label>
                            <input name="enddate" id="enddate" type="text" class="datefield input-width-small width110"  value="<?php echo $request->enddate; ?>" />
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">Gender:</label>
                            <?php
                                $allgenders = array('' => 'All','1'=>'Male','2'=>'Female');
                                $genderdropdown = new Zend_Form_Element_Select('u'.HTML_TABLE_COLUMN_SEPARATOR.'gender',
                                                    array(
                                                        'multiOptions' => $allgenders,
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('gender','width125'),
                                                        'title' => 'Filter By Gender'		
                                                    )
                                );  
                                $genderdropdown->setValue($request->getParam('u'.HTML_TABLE_COLUMN_SEPARATOR.'gender')); 
                                echo $genderdropdown->render();
                            ?></td>
                        <td style="width:125px;">
                            <label class="control-label">Age Group:</label>
                            <?php
                                $allgenders = array('' => 'All','1'=>'0-14','2'=>'15-24','3'=>'25-29','4'=>'30-39','5'=>'40-49','6'=>'50-59','7'=>'Btn 30 and 60','8'=>'Greater than 60');
                                $dropdown = new Zend_Form_Element_Select('range',
                                                    array(
                                                        'multiOptions' => $allgenders,
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('gender','width125'),
                                                        'title' => 'Filter By Age Group'		
                                                    )
                                );  
                                $dropdown->setValue($request->getParam('range')); 
                                echo $dropdown->render();
                            ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">Marital Status:</label>
                            <?php
                                $maritalstatuses = getAllMaritalStatuses();
                                $maritalstatusesdropdown = new Zend_Form_Element_Select('maritalstatus',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $maritalstatuses),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125'),
                                                    )
                                                );
                                $maritalstatusesdropdown->setValue($request->getParam('maritalstatus')); 
                                echo $maritalstatusesdropdown->render(); 
                               ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">Education:</label>
                            <?php
                                $educlevels = getAllEducationLevels();
                                $educleveldropdown = new Zend_Form_Element_Select('educationlevel',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $educlevels),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125'),
                                                    )
                                                );
                                $educleveldropdown->setValue($request->getParam('educationlevel')); 
                                echo $educleveldropdown->render(); 
                            ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">DNA:</label>
                            <?php
                                $groupdropdown = new Zend_Form_Element_Select('farmgroupid',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All', '0'=> 'Individual Farmers'), getAllFarmGroups('', $session->getVar('country'))),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125'),
                                                    )
                                                );
                                $groupdropdown->setValue($request->getParam('farmgroupid')); 
                                echo $groupdropdown->render(); 
                           ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label"><?php echo $location_label; ?>:</label>
                            <?php
                                $districts = getDistricts($session->getVar('country'));
                                $districtdropdown = new Zend_Form_Element_Select('locationid',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $districts),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125')
                                                    )
                                                );
                                $districtdropdown->setValue($request->getParam('locationid')); 
                                echo $districtdropdown->render(); 
                              ?>
                        </td>
                        <td style="width:100px; vertical-align:bottom;">
                            <a id="searchbutton" class="btn btn-primary" style="padding:6px 10px;"><i class="icon-white icon-search"></i> Generate</a>
                            <?php if(!isAdmin()){ ?>
                                <input type="hidden" name="farmgroupid" id="farmgroupid" value="<?php echo $request->farmgroupid; ?>" />
                            <?php } ?>
                            <input type="hidden" name="country" id="country" value="<?php echo $country; ?>" />
                            <input type="hidden" name="generate" id="generate" value="<?php echo $request->generate; ?>" />
                        </td>
                    </tr>
                    <tr>
                        <?php if($loggedinuser->isUgandan() && isUganda() && (isAdmin() || isManagement())){ ?>
                            <td colspan="2">
                                <?php if(isEmptyString($request->country) || $countryreq == 'ug'){ ?>
                                    <a class="btn" href="<?php echo $this->baseUrl('report/allfarmers/country/ke'); ?>" title="Browse Kenya Directory"><i class="icon-list"></i> Browse Kenya</a>
                                <?php } ?>
                            </td>
                        <?php } ?>    
                        <?php if($loggedinuser->isUgandan() && isKenya() && (isAdmin() || isManagement())){ ?>
                            <td colspan="2">
                                <?php if(!isEmptyString($request->country) && $countryreq == 'ke'){ ?>
                                    <a class="btn" href="<?php echo $this->baseUrl('report/allfarmers/country/ug'); ?>" title="Browse Uganda Directory"><i class="icon-list"></i> Browse Uganda</a>
                                <?php } ?>
                            </td>
                        <?php } ?>
                        
                        <td>
                            <label class="control-label">Mobile Access:</label>
                            <?php
                                $array = array('1'=>'With Phone', '0'=>'No Phone');
                                $dropdown = new Zend_Form_Element_Select('hasphone',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $array),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('span2'),
                                                        'style' => 'width:125px;'
                                                    )
                                                );
                                $dropdown->setValue($request->getParam('hasphone')); 
                                echo $dropdown->render(); 
                              ?>
                        </td>
                        <td>
                            <label class="control-label">Profiled By:</label>
                            <?php
                                $users = getProfilingUsers($session->getVar('country'));
                                $dropdown = new Zend_Form_Element_Select('profiledby',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $users),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125')
                                                    )
                                                );
                                $dropdown->setValue($request->getParam('profiledby')); 
                                echo $dropdown->render(); 
                              ?>
                        </td>
                        <td>
                            <label class="control-label">Crops:</label>
                            <?php
                                $availablecrops = getFarmisCommodities();
                                $cropdropdown = new Zend_Form_Element_Select('cropid',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $availablecrops),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('width125')
                                                    )
                                                );
                                $cropdropdown->setValue($request->getParam('cropid')); 
                                echo $cropdropdown->render();
                           ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">Duration in Farming:</label>
                            <?php
                                $allgenders = array('' => 'All','1'=>'Less than 3yrs','2'=>'3-5yrs','3'=>'6-10yrs','4'=>'11-20yrs','5'=>'21-30yrs','6'=>'More than 30yrs');
                                $dropdown = new Zend_Form_Element_Select('farmingsince',
                                                    array(
                                                        'multiOptions' => $allgenders,
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('gender','width125'),
                                                        'title' => 'Filter By Duration in Farming'		
                                                    )
                                );  
                                $dropdown->setValue($request->getParam('farmingsince')); 
                                echo $dropdown->render();
                            ?>
                        </td>
                        <td style="width:125px;">
                            <label class="control-label">Average Land Size:</label>
                            <?php
                                $allgenders = array('' => 'All','1'=>'Less than 3Acres','2'=>'3-5Acres','3'=>'6-10Acres','4'=>'11-20Acres','5'=>'21-30Acres','6'=>'More than 30Acres');
                                $dropdown = new Zend_Form_Element_Select('landusage',
                                                    array(
                                                        'multiOptions' => $allgenders,
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('gender','width125'),
                                                        'title' => 'Filter By Land Usage'		
                                                    )
                                );  
                                $dropdown->setValue($request->getParam('landusage')); 
                                echo $dropdown->render();
                            ?>
                        </td>
                    </tr>                    
                </table>
            </span>
		<?php } ?>
    </div>
    <div class="pull-left" id="pageleft">
        <div class="widgetsection reportcontainer" style="height:600px;">
        	<h3 class="reportpagetitle"><?php echo $title; ?></h3>
			<div id="reportdata"></div>
		</div>
  	</div>
</div>
</div>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>