<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Report Dashboard"; 
	$this->headMeta()->appendName('keywords', '');
	$this->headMeta()->appendName('description', $title);
	
	$user = new UserAccount();
	$user->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country);
	
	$this->headTitle($title);
?>
<div>
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
        <div class="widgetsection clearfix" style="min-height:460px; height:auto;">
            <h3 style="color:#282727;"><?php echo $title; ?></h3>
            <div>
                <span class="marginleft0">
                    <ul class="sectionitems">
                    	<?php if($acl->checkPermission('Farmer Membership Certificate', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/certificate'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmer Membership <br /><?php echo isFarmer() ? 'Certificate' : 'Certificates'; ?></h2></a>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('DNA Membership Certificate', ACTION_VIEW) || isFarmGroupAdmin()){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/dnacertificate'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>DNA Membership <br /><?php echo isFarmGroupAdmin() ? 'Certificate' : 'Certificates'; ?></h2></a>
                            </li>
                        <?php } ?>
						<?php if($acl->checkPermission('Farmers Baseline Summary Report', ACTION_VIEW) && !isFarmer()){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/primarybaseline'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmers Profile <br />Summary Report</h2></a>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Farmers Baseline Summary Report', ACTION_VIEW) && isFarmer()){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/primarybaseline/id/'.$userid); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmis Baseline <br />Summary Report</h2></a>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Farmers Baseline Detail Report', ACTION_VIEW) && !isFarmer()){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/baselinedetail'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmers Profile <br />Detailed Report</h2></a>
                            </li>
                        <?php } ?>    
						<?php if($acl->checkPermission('Farmers Baseline Detail Report', ACTION_VIEW) && isFarmer()){ ?>
                        	<li>
                                <a class="list" href="<?php echo $this->baseUrl('report/baselinedetail/id/'.$userid); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmis Baseline <br />Detailed Report</h2></a>
                            </li>
						<?php } ?>
                        <?php if($acl->checkPermission('Farmers Bio Data Report', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/allfarmers'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmers Bio Data <br /> Report</h2></a>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('DNA Profiling Aggregated Report', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/dna'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>DNA Profiling <br />Aggregated Report</h2></a>
                            </li>
                        <?php } ?>  
                        <?php if($acl->checkPermission('District and Location Profiling Report', ACTION_VIEW)){ ?>  
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/location'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2><?php echo $location_label; ?> Profiling <br />Aggregated Report</h2></a>
                            </li>+
                       	<?php } ?>  
                      	<?php if($acl->checkPermission('Crop Profiling Aggregated Report', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/crop'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Crop Profiling<br />Aggregated Report</h2></a>
                            </li>
                       	<?php } ?>  
                        <?php if($acl->checkPermission('Crop Profiling Aggregated Report', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/acreage'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmer Acreage<br /> Report</h2></a>
                            </li>
                       	<?php } ?>  
                       	<?php if($acl->checkPermission('PIA Profiling Performance Report', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl('report/pia'); ?>"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>PIA Profiling<br />Performance Report</h2></a>
                            </li>
						<?php } ?>
                        <?php if($acl->checkPermission('Profit and Loss Statement', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl("report/statement"); ?>"><img src="<?php echo $this->baseUrl('images/topmenu_market.png'); ?>" /><br /><h2>Profit & Loss <br />Statement</h2></a>
                            </li>
                        <?php } ?>    
                        <?php if($acl->checkPermission('Market Prices', ACTION_VIEW)){ ?>
                            <li>
                                <a class="list" href="<?php echo $this->baseUrl("report/prices"); ?>"><img src="<?php echo $this->baseUrl('images/topmenu_market.png'); ?>" /><br /><h2>Current Market <br />Prices Report</h2></a>
                            </li>
                        <?php } ?>
                    </ul>
                </span>
            </div>
        </div>
    </div>
</div>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
