<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country);
	
	$title = "Market Prices";
	$this->headTitle($title); 
	
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/custom/table2CSV.js'); ?>"></script>
<script>
$(document).ready(function() {
	<?php if($request->print == 1){ ?>
		$("#headercontainer, #leftcolumn, .footer, #blankrow").remove().hide();
		$(".printpage").html($("#printer_page_action_buttons").html());
	<?php } ?>
	
	datepickerOpts.dateFormat = '<?php echo $config->dateandtime->javascriptmediumformat; ?>'; 
	$("#startdate, #enddate").datepicker(datepickerOpts); 
	
	<?php if($request->print == 1 || $request->excel == 1){ ?>
		$("body").addClass('print');
		$("body.print .hideonprint").html('').remove();
		$("body.print a.sortlink").removeAttr('href').removeAttr('title');
	<?php } ?>
	
	// auto populate contact details 
	$("#marketprices").html('<div style="padding-top:100px;" class="centeralign blocked"><label class="centeralign blocked">loading...</label><br />'+$("#wait").html()+'</div>');
	$.get("<?php echo $this->baseUrl('graph/allpricesexport/pgc/true'); ?>", 
	   {			
		cachebuster: new Date().getTime()}, 			   
		function(data){			
			// alert(data);			
			$('#marketprices').html(data);
			equalHeight($("#leftcolumn, #centercolumn"));
			$('#centercolumn').css({'height':'1775px'});	
		}
	);
});
</script>
<style>
#contentcolumn {
	min-height:600px;
}
#centercolumn {
	padding: 5px 0;
	width: 100%;
	margin-left:0;
	float:left;
}
#centercolumn h1, #centercolumn h2 {
	font-family:calibri, Telex, sans-serif;
}
#pageleft {
	margin:0 5px 0 0;
	width:100%;
	float:left;
	position:relative;
}
#pageleft .widgetsection {
	width:98%;
}
.widgetsection {
	margin-bottom:10px;
}
.widgetsection h3 {
	font-size:15px;
}
.contenttable {
	border:solid 1px #b3b3b3;
	border-collapse: separate;
 	*border-collapse: collapsed;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
}
.contenttable .control-label {
	width:auto;
	white-space:normal;
	text-align:left;
	display:block;
}
.contenttable h2 {
	margin: 0;
	padding: 8px 0 8px 0;
	line-height:auto;
	text-align: left;
	border-bottom:1px solid #c4c2c2;
	color:#498D0F;
	font-size:18px;
	width:100%;
	font-weight:bold;
	line-height:16px;
}
.contenttable#estimates thead tr td {
	font-weight:bold;
	font-size:12px;
}
#outlength {
	width:72%;
}
.reportcontainer {
	height:auto; 
	min-height:400px; 
	display:block; 
	margin-top:10px;
	position:relative;
}
.reportlabel {
	display:inline-block;
	font-weight:bold;
	font-size:16px;
	padding-right:5px;
}
.reportfilter {
	margin-top:0; 
	float:right;
	margin-right:-10px;
	width:100%;
}
.reportlinks {
	margin-top:-10px;
}
#generate {
	margin-top:-10px;
}
.printpage {
	display:none;
}
pdfquicklinks {
	position:absolute; 
	left:10px; 
	top:8px;
}
.widgetsection h3.reportpagetitle {
	color:#282727;
}
.control-label {
	font-size:12px;
	white-space:nowrap;
	display:block;
	width:100%;
	text-align:left;
}
.table#data tr td {
	white-space:nowrap;
}
.paginatecustom {
	position:absolute;
	left:12px;
	top:10px;
	width:auto;
	text-align:left;
	float:left;
}
.pager {
	text-align:right;
}
<?php if($request->print == 1) { ?> 
#contentwrapper {
	margin: 10px 0 5px;
}
#centercolumn {
	float:left;
	width:90%;
}
#maincontainer.container {
	margin-left:20px;
	margin-top:10px;
}
#printer_page_action_buttons {
	margin:10px;
}
.hideonprint {
	display:none;
}
.printpage {
	margin:10px;
	display:block;
}
<?php } ?>
</style>
<div id="centercolumn">
	<div class="widgetsection" style="min-height:800px; height:auto;">
        <h3 style="color:#282727;"><?php echo $title; ?></h3>
        <div style="padding-left:10px;">
           <span id="marketprices"></span>
        </div>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>