<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	require_once APPLICATION_PATH.'/../'.PUBLICFOLDER.'/mpdf/mpdf.php';
		
	$title = "FARMIS Baseline Summary Report";
	// meta data
	$this->headTitle($title); 
	
	$user = new UserAccount();
	$id = $request->id;
	
	$loggedinfarmer = new UserAccount();
	$loggedinfarmer->populate($userid);
	$farmgroupid = $loggedinfarmer->getFarmGroupID();
	
	if(!isEmptyString($id)){
		$user->populate($id);
	}
	
	$isexport = false;
	$maxwidth = "width: 100%;";
	if($request->pdf == 1 || $request->download == 1){
		$isexport = true;
		$maxwidth = "width: 940px;";
	}
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country); 
		
?>
<script>
$(document).ready(function() {
	<?php if($request->print == 1){ ?>
		$("#headercontainer, #leftcolumn, .footer, #blankrow").remove().hide();
		$(".printpage").html($("#printer_page_action_buttons").html());
	<?php } ?>
	
	// trigger path to farmer report to be generated
	$("#id").change(function(){
		var id = $(this).val()
		var url = '<?php echo $this->baseUrl('report/primarybaseline/id/'); ?>'+id;
		$("#generate").attr('href', url);
	});

});
</script>
<style>

</style>
<div>
  <div id="centercolumn" class="reportpage">
  	<div class="printpage"></div>
    <div class="hideonprint" style="width:100%;">
        <?php if((isAdmin() || isFarmGroupAdmin() || isManagement())){ ?>
        	<table class="table table-condensed noborder margin0" style="width:100%;">
            	<tr>
                    <td>
                        <span class="reportfilter pull-right">
                            <label class="reportlabel cal-font">Farmer: </label>
                            <?php
                                $userarray = getFarmers($farmgroupid, false, false, false, '', $session->getVar('country'));
                                $userdropdown = new Zend_Form_Element_Select('id',
                                                    array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Browse Farmer>'), $userarray),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                            'class' => array('chzn-select', 'width180', 'novalidate')
                                                    )
                                                );
                                $userdropdown->setValue($request->getParam('id')); 
                                echo $userdropdown->render(); 
                              ?>&nbsp;&nbsp;
                             <a id="generate" href="<?php echo $this->baseUrl('report/primarybaseline/id/'); ?>" class="btn btn-primary" title="Generate Report"><i class="icon-list-alt icon-white"></i> Generate</a>&nbsp;
                        </span>
                    </td>
                </tr>
            </table>
		<?php } ?>
    </div>
    
    <?php if(isEmptyString($id)){  ?>
    	<div class="widgetsection reportcontainer">
            <h3 class="reportpagetitle"><?php echo $title; ?></h3>
            <span class="pull-left margin0" style="width:99%; margin-top:10px; min-height:120px; position:relative;"><div class="alert alert-info" style="margin-top:10px;">Filter Farmer and Click Generate to view Report</div></span>
        </div>
    <?php } ?>
    <div class="pull-left" id="pageleft">
    	
      <?php if(!isEmptyString($id)){ 
	  		ob_start();
	  ?>
            <div class="widgetsection reportcontainer">
                <h3 class="reportpagetitle"><?php echo $title; ?></h3>
				<?php if($request->print != 1){ ?>
                    <span class="reportactions hideonprint">
                    	<a href="<?php echo $this->baseUrl('report/primarybaseline/id/'.$user->getID().'/print/1'); ?>" target="_blank" class="btn btn-primary btn-mini" title="Print Report"><i class="icon-print icon-white"></i> Print</a>&nbsp;
                        <a href="<?php echo $this->baseUrl('report/primarybaseline/id/'.$user->getID().'/pdf/1'); ?>" target="_blank" class="btn btn-primary btn-mini" title="View PDF Report"><i class="icon-list-alt icon-white"></i> PDF</a>&nbsp;
                        
                    </span>
                <?php } ?>
            <?php 
				$activationdate = isEmptyString($user->getActivationDate()) ? "--" : changeMySQLDateToPageFormat($user->getActivationDate());
				$country = isEmptyString($user->getCountry()) ? '--' : $user->getCountryName();
				$district = isEmptyString($user->getLocationID()) ? '--' : $user->getLocation()->getName();
				$county = isEmptyString($user->getCountyID()) ? '--' : $user->getCounty()->getName();
				$subcounty = isEmptyString($user->getSubCountyID()) ? '--' : $user->getSubCounty()->getName();
				$parish = isEmptyString($user->getParishID()) ? '--' : $user->getParish()->getName();
				$village = isEmptyString($user->getVillageID()) ? '--' : $user->getVillage()->getName();
				$address = isEmptyString($user->getStreetAddress()) ? '--' : nl2br($user->getStreetAddress());
				$bio = isEmptyString($user->getBio()) ? '--' : nl2br($user->getBio());
				$children = isEmptyString($user->getNumberOfChildren()) ? '--': $user->getNumberOfChildren();
				$dependants = isEmptyString($user->getNumberOfDependants()) ? '--': $user->getNumberOfDependants();
				$households = isEmptyString($user->getTotalHousehold()) ? '--': $user->getTotalHousehold();
				
				if($user->hasFarmGroup()){
					$grouplabel = "Farm Group";
					$thefarmgroup = isEmptyString($user->getFarmGroupID()) ? '--' : $user->getFarmGroup()->getName();
				} else {
					$grouplabel = "Support Provider";
					$thefarmgroup = isEmptyString($user->getSupportProvider()) ? '--' : $user->getSupportProvider();
				}
				
				$maritalstatus = isEmptyString($user->getMaritalStatusText()) ? '--': $user->getMaritalStatusText();
				$educlevel = isEmptyString($user->getEducationLevelText()) ? '--': $user->getEducationLevelText();
				$gpslat = $user->getLatGPSFormatted();
				$gpslng = $user->getLngGPSFormatted();
				
				$phone = isEmptyString($user->getPhone()) ? '--' : $user->getPhone();
				$phone2 = isEmptyString($user->getPhone2()) ? '--' : $user->getPhone2();
				$email = isEmptyString($user->getEmail()) ? '--' : $user->getEmail();
				$email2 = -isEmptyString($user->getEmail2()) ? '--' : $user->getEmail2();
				$keen_name = isEmptyString($user->getNextofkin_name()) ? '--': $user->getNextofkin_name();
				$keen_phone = isEmptyString($user->getNextofkin_phone()) ? '--': $user->getNextofkin_phone();
				$keen_email = isEmptyString($user->getNextofkin_email()) ? '--': $user->getNextofkin_email();
				
				$farmis_logo = $this->serverUrl($this->baseUrl('images/logo_gray.png'));
				$infotrade_logo = $this->serverUrl($this->baseUrl('images/logo_infotrade.png'));
				$profile_image = $this->serverUrl($user->getMediumPicturePath());
				
				$thesubgroup = '';
				if(!isEmptyString($user->getSubGroupID())){
					$thesubgroup = '<tr><td><label class="control-label">Sub Group:</label><?php echo $user->getSubGroup()->getName(); ?></td></tr>';
				}
				$supportlist = $user->getSupportTypesLabel();
				$activitylist = $user->getActivityTypesLabel();
				$farmingtypelist = $user->getFarminigTypesLabel();
				$leadership = isEmptyString($user->getLeadershipRole()) ? '--' : $user->getLeadershipRole();
				
			?>		
				<div>
                  	<table style="margin-top:10px; height:auto; width:100%;">
                        <tr>
                            <td  id="outlength" style="width:<?php echo $isexport == true ? '600px' : '72%'; ?>; vertical-align:top;">
								<table style="width:<?php echo $isexport == true ? '600px' : '100%'; ?>; border-bottom:1px solid #e9e9e9;">
                                    <tr>
                                        <td style="vertical-align:middle; padding-left:10px; padding-top:10px; width:<?php echo $isexport == true ? '250px' : '45%'; ?>; text-align:center; height:<?php echo $isexport == true ? '150px' : '170px'; ?>;"><img style="text-align:center;" src="<?php echo $farmis_logo; ?>" alt="" /></td>
                                        <td style="vertical-align:middle; padding-right:10px; padding-top:20px; text-align:center;"><img style="text-align:center;" src="<?php echo $infotrade_logo; ?>" alt="" /></td>
                                    </tr>
                                </table>
								<table id="summary" class="table xtable-condensed noborder contenttable" style="margin:10px 0 0 0; width:<?php echo $isexport == true ? '600px' : '99%'; ?>;">
                                    <thead>
                                        <tr>
                                            <td colspan="2"><h2>Profile Summary</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="width:<?php echo $isexport == true ? '320px' : '50%'; ?>;"><label class="control-label">Name of Farmer:</label><?php echo $user->getName(); ?><input type="hidden" name="id" id="id" value="<?php echo $user->getID(); ?>" /></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>:</label><?php echo $user->getGenderLabel(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label nowrapping">Farmer Identification (FIN ID#):</label><?php echo $user->getRefNo(); ?></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label><?php echo $user->getBirthDateFormatted(); ?></td> 
                                        </tr>
                                        <tr>
                                            <td></td> <td></td>
                                        </tr>
										<tr>
											<td><label class="control-label"><?php echo $this->translate("farmer_farminigtypes_label"); ?>:</label><?php echo $user->getFarminigTypesLabel(); ?></td>  
                                            <td><label class="control-label"><?php echo $this->translate("farmer_activities_label"); ?>:</label><?php echo $user->getActivityTypesLabel(); ?></td>
										</tr>
										
                                    </tbody>
                                </table>
								<table id="addresss" class="table table-condensed noborder contenttable" style="margin:10px 0 0 0; width:<?php echo $isexport == true ? '635px' : '99%'; ?>;">
                                    <thead>
                                        <tr>
                                            <td colspan="3"><h2>Address</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="width:<?php echo $isexport == true ? '200px' : '35%'; ?>;"><label class="control-label">Country:</label> <?php echo $country; ?>
                                            <td style="width:<?php echo $isexport == true ? '200px' : '35%'; ?>;"><label class="control-label"><?php echo $location_label; ?>:</label><?php echo $district; ?></td>
                                            <td><label class="control-label"><?php echo $county_label; ?>:</label><?php echo $county; ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $subcounty_label; ?>:</label><?php echo $subcounty; ?></td>
                                            <td><?php if($user->isUgandan()){ ?>
                                            		<label class="control-label">Parish:</label><?php echo $parish; ?>
                                                <?php } ?>
                                            </td>
                                            <td><?php if($user->isUgandan()){ ?>
                                            		<label class="control-label">Village:</label><?php echo $village; ?>
                                                <?php } ?>
                                            </td>
                                        </tr>
										 <tr>
                                            <td><label class="control-label">GPS (Latitude):</label><?php echo str_replace('°', '&deg;', $gpslat); ?></td>
                                            <td colspan="2"><label class="control-label">GPS (Longitude):</label><?php echo $gpslng; ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"><label class="control-label">Postal/Street Address</label><?php echo $address; ?></td>
                                        </tr>
                                    </tbody>
                                </table>
								<table id="Biography" class="table table-condensed noborder contenttable" style="margin:10px 0 0 0; width:<?php echo $isexport == true ? '635px' : '99%'; ?>;">
                                    <thead>
                                        <tr>
                                            <td colspan="4"><h2>Biography</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="4"><label class="control-label">About:</label>
                                                <span style="min-height:40px; display:block; width:100%;"><?php echo $bio; ?></span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="4"><label class="control-label">Education Level:</label><?php echo $educlevel; ?></td>
                                        </tr>
                                        <tr>
                                            <td style="width:<?php echo $isexport == true ? '140px' : '25%'; ?>;"><label class="control-label"><?php echo $this->translate("farmer_maritalstatus_label"); ?>:</label><?php echo $maritalstatus; ?></td>  
                                            <td style="width:<?php echo $isexport == true ? '140px' : '25%'; ?>;"><label class="control-label"><?php echo $this->translate("farmer_nochildren_label"); ?>:</label><?php echo $children; ?></td>
                                            <td style="width:<?php echo $isexport == true ? '140px' : '25%'; ?>;"><label class="control-label"><?php echo $this->translate("farmer_nodependants_label"); ?>:</label><?php echo $dependants; ?></td>
											<td><label class="control-label"><?php echo $this->translate("farmer_totalhousehold_label"); ?>:</label><?php echo $households; ?></td>
                                        </tr>
										<tr>
                                            <td colspan="4">&nbsp;</td>
                                        </tr>
                                    </tbody>
                                </table>
							</td>
							<td style="vertical-align:top;">
                                <table style="width:100%;">
                                    <tr>
                                        <td style="height:125px; vertical-align:top; padding:0; text-align:center;">
                                            <div id="profileinfo" style="padding:4px;"> 
                                                <img id="profileimage" src="<?php echo $profile_image; ?>" />
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="paddding0" style="padding-top:20px; padding-left:5px; width:<?php echo $isexport == true ? '200px' : '100%'; ?>;">
											<table id="other" class="table table-condensed noborder contenttable">
                                                <thead>
                                                    <tr>
                                                        <td><h2><?php echo $grouplabel; ?></h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><label class="control-label">Name:</label><?php echo $thefarmgroup; ?></td>
                                                    </tr>
													<?php echo $thesubgroup; ?>
													<tr>
                                                        <td><label class="control-label">Support Received:</label><?php echo $supportlist; ?></td>
                                                    </tr>
													<tr>
                                                        <td></td>
                                                    </tr>
                                                </tbody>
                                            </table>
											<table id="contacts" class="table table-condensed noborder contenttable" style="margin-top:10px; width:<?php echo $isexport == true ? '200px' : '100%'; ?>;">
                                                <thead>
                                                    <tr>
                                                        <td colspan="2"><h2>Contacts</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td style="width:<?php echo $isexport == true ? '110px' : '45%'; ?>;"><label class="control-label">Phone:</label><?php echo $phone; ?></td>
                                                        <td><label class="control-label">Alt Phone:</label><?php echo $phone2; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><label class="control-label">Email:</label><?php echo $email; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><label class="control-label">Alt Email:</label><?php echo $email2; ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table id="keen" class="table table-condensed noborder contenttable" style="margin-top:10px; width:<?php echo $isexport == true ? '200px' : '100%'; ?>;">
                                                <thead>
                                                    <tr>
                                                        <td><h2>Next of Keen</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><label class="control-label">Name:</label><?php echo $keen_name; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><label class="control-label">Phone:</label><?php echo $keen_phone; ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td><label class="control-label">Email:</label><?php echo $keen_email; ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table id="other" class="table table-condensed noborder contenttable" style="margin-top:10px; width:<?php echo $isexport == true ? '200px' : '100%'; ?>;">
                                                <thead>
                                                    <tr>
                                                        <td><h2>Signature</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td style="height:100px;">
														 <?php if($user->hasSignature()){ ?>
                                                            <div class="profileinfo pull-left" id="signinfo"><img id="profileimage" src="<?php echo $user->getSignaturePath(); ?>" width="180" height="90" /></div>
                                                         <?php } else { ?>
                                                            <div>--</div>
                                                         <?php } ?>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
										</td>
									</tr>
								</table>
							</td>
                  		</tr>
					</table>
                </div>
            </div>
        <?php } ?>
        <?php require_once APPLICATION_PATH."/views/scripts/report/pdf.phtml"; ?> 
		<?php if($request->download == 1 || $request->pdf == 1){  ?>
            <script type="text/javascript">
                $(document).ready(function() {
                    var pdfurl = '<?php echo $relativepathtodocument; ?>';
                    window.location.href = pdfurl;
                });
            </script>
            <div class="widgetsection reportcontainer"><h3 class="reportpagetitle">PDF Viewer</h3>
                <div id="embeddiv"></div>
            </div>
        <?php } ?>
    </div>
  </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>