<?php 
	$userid = decode($request->id);
	$user = new UserAccount();
	$user->populate($userid);
	$id = $user->getID();
?>
 <table style="margin-top:10px; height:auto; width:100%;">
                        <tr>
                            <td style="width:72%; vertical-align:top;">
                                <table style="width:100%; height:190px; border-bottom:1px solid #e9e9e9;">
                                    <tr>
                                        <td style="vertical-align:top; padding-left:10px; padding-top:10px;"><span><img src="<?php echo $this->baseUrl('images/logo_gray.png'); ?>" /></span></td>
                                        <td style="vertical-align:top; padding-left:10px; padding-top:10px;"><span><img src="<?php echo $this->baseUrl('images/logo_infotrade.png'); ?>" /></span></td>
                                    </tr>
                                </table>
                                <table id="summary" class="table xtable-condensed noborder contenttable" style="margin:10px 0 0 0; width:99%;">
                                    <thead>
                                        <tr>
                                            <td colspan="2"><h2>Profile Summary</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="width:50%;"><label class="control-label">Name of Farmer:</label>
                                            <?php echo $user->getName(); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label nowrapping">Farmer Identification (FIN ID#):</label>
                                            <?php echo $user->getRegNo(); ?></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>:</label>
                                            <?php echo $user->getGenderLabel(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label>
                                            <?php echo $user->getBirthDateFormatted(); ?></td> 
                                            <td><label class="control-label">Date Registered:</label>
                                            <?php echo isEmptyString($user->getActivationDate()) ? '--' : changeMySQLDateToPageFormat($user->getActivationDate()); ?></td> 
                                        </tr>
                                    </tbody>
                                </table>
                                <table id="addresss" class="table table-condensed noborder contenttable" style="margin:10px 0 0 0; width:99%;">
                                    <thead>
                                        <tr>
                                            <td colspan="4"><h2>Address</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td style="width:35%;"><label class="control-label">Country:</label>
                                            <?php echo isEmptyString($user->getCountry()) ? '--' : $user->getCountryName(); ?>
                                            <td style="width:35%;"><label class="control-label">District:</label>
                                            <?php echo isEmptyString($user->getLocationID()) ? '--' : $user->getLocation()->getName(); ?></td>
                                            <td><label class="control-label">County:</label>
                                            <?php echo isEmptyString($user->getCountyID()) ? '--' : $user->getCounty()->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Sub-county:</label>
                                            <?php echo isEmptyString($user->getSubCountyID()) ? '--' : $user->getSubCounty()->getName(); ?></td>
                                            <td><label class="control-label">Parish:</label>
                                            <?php echo isEmptyString($user->getParishID()) ? '--' : $user->getParish()->getName(); ?></td>
                                            <td><label class="control-label">Village:</label>
                                            <?php echo isEmptyString($user->getVillageID()) ? '--' : $user->getVillage()->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"><label class="control-label">Postal/Street Address</label>
                                            <?php echo isEmptyString($user->getStreetAddress()) ? '--' : nl2br($user->getStreetAddress()); ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table id="Biography" class="table table-condensed noborder contenttable" style="margin:10px 0 0 0; width:99%;">
                                    <thead>
                                        <tr>
                                            <td colspan="3"><h2>Biography</h2></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td colspan="3"><label class="control-label">About:</label>
                                                <span style="min-height:40px; display:block; width:100%;"><?php echo isEmptyString($user->getBio()) ? '--' : nl2br($user->getBio()); ?></span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3"><label class="control-label">Education Level:</label>
                                            <?php echo $user->getEducationLevelText(); ?></td>
                                        </tr>
                                        <tr>
                                            <td style="width:30%"><label class="control-label"><?php echo $this->translate("farmer_maritalstatus_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getMaritalStatusText()) ? '--': $user->getMaritalStatusText(); ?></td>  
                                            <td style="width:30%"><label class="control-label"><?php echo $this->translate("farmer_nochildren_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNumberOfChildren()) ? '--': $user->getNumberOfChildren(); ?></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_nodependants_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNumberOfDependants()) ? '--': $user->getNumberOfDependants(); ?></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                            <td style="vertical-align:top; border-left:1px solid #e1e1e1;">
                                <table style="width:100%;">
                                    <tr>
                                        <td>
                                            <div id="profileinfo" style="padding:4px;"> 
                                                <img id="profileimage" src="<?php echo $user->getMediumPicturePath(); ?>" />
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="paddding0" style="padding-top:20px; padding-left:5px;">
                                            <table id="other" class="table table-condensed noborder contenttable">
                                                <thead>
                                                    <tr>
                                                        <td colspan="4"><h2>Farm Group</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td style="height:90px;"><label class="control-label">Name:</label>
                                                        <?php echo isEmptyString($user->getFarmGroupID()) ? '--' : $user->getFarmGroup()->getName(); ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table id="contacts" class="table table-condensed noborder contenttable" style="margin-top:10px;">
                                                <thead>
                                                    <tr>
                                                        <td colspan="4"><h2>Contacts</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td style="width:45%;"><label class="control-label">Phone:</label>
                                                        <?php echo isEmptyString($user->getPhone()) ? '--' : $user->getPhone(); ?></td>
                                                        <td><label class="control-label">Alt Phone:</label>
                                                        <?php echo isEmptyString($user->getPhone2()) ? '--' : $user->getPhone2(); ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><label class="control-label">Email:</label>
                                                        <?php echo isEmptyString($user->getEmail()) ? '--' : $user->getEmail(); ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><label class="control-label">Alt Email:</label>
                                                        <?php echo isEmptyString($user->getEmail2()) ? '--' : $user->getEmail2(); ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table id="keen" class="table table-condensed noborder contenttable" style="margin-top:10px;">
                                                <thead>
                                                    <tr>
                                                        <td colspan="4"><h2>Next of Keen</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><label class="control-label">Name:</label>
                                                        <?php echo isEmptyString($user->getNextofkin_Name()) ? '--': $user->getNextofkin_Name(); ?>
                                                    </tr>
                                                    <tr>
                                                        <td><label class="control-label">Phone:</label>
                                                        <?php echo isEmptyString($user->getNextofkin_phone()) ? '--': $user->getNextofkin_phone(); ?></td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="2"><label class="control-label">Email:</label>
                                                        <?php echo isEmptyString($user->getNextofkin_email()) ? '--': $user->getNextofkin_email(); ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                            <table id="other" class="table table-condensed noborder contenttable" style="margin-top:10px;">
                                                <thead>
                                                    <tr>
                                                        <td colspan="4"><h2>Signature</h2></td>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td style="height:100px;">
                                                            <div class="profileinfo pull-left" id="signinfo"> 
                                                                <a href="<?php echo $this->baseUrl('profile/picture/id/'.encode($user->getID()).'/type/sign'); ?>" class="editpic" title="Upload Signature Image"><img id="profileimage" src="<?php echo $user->getSignaturePath(); ?>" width="180" height="90" /><pre id="signlink" class="hide absoluteupload"><i class="icon-pencil"></i> Upload Image</pre></a>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                   </table>