<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "New Payment";
	$payment = new Payment();
	$id = decode($request->id);	 
	$posturl = $this->baseUrl('mobile/createaddpayment');
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$locationerror = $this->translate("farmer_district_error");
	$country_params_refno_placeholder = 'placeholder="Auto" maxlength="8" ';
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$session->setVar('country', 'ke');
		$country = 'KE';
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$locationerror = $this->translate("farmer_county_error");
		$country_params_refno_placeholder = 'placeholder="" maxlength="10" ';
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	
	$subcriberid = decode($request->userid);
	$groupid = decode($request->farmgroupid);
	$isfarmer = !isEmptyString($subcriberid) ? true : false;
	$isfarmgroup = !isEmptyString($groupid) ? true : false;
	$days = '365';
	$farmgroupid = '';
	
	if(isEmptyString($request->id)){
		if(!isEmptyString($subcriberid)){
			$isuser = true;
			$title = "New Payment";
			$user = new UserAccount();
			$user->populate($subcriberid);
			
			if(isEmptyString($request->id)){
				$payment->setTrxDate(date('Y-m-d'));
				$payment->getSubscription()->setStartDate($payment->getTrxDate());
				$payment->getSubscription()->setEndDate(date('Y-m-d', strtotime($payment->getSubscription()->getStartDate()) + $days * 24 * 60 * 60));
				$payment->setStatus(3);
				$payment->setVerifiedByID($session->getVar('userid'));
				$payment->setUserID($user->getID());
				$payment->setPhone($user->getPhone());
				$payment->setStem(2);	
				$payment->setItem(2);
				$payment->setPaymentType(1);
				$amount = getServiceAmount();
				$payment->setAmount($amount);
			}
			if(isEmptyString($payment->getUserID())){
				$title = "Browse Farmer";
			}
		}
		# farmgroup payment	
		/*if(!isEmptyString($groupid)){
			$isfarmgroup = true;
			$title = "New DNA Payment"; 
			$farmgroup = new FarmGroup();
			$farmgroup->populate($groupid); 
			$payment->setFarmGroupID($farmgroup->getID());
			$payment->setPhone($farmgroup->getPhone());
			$payment->setStem(1);	
			$payment->setItem(4);
			$payment->setAmount($payment->getDefaultDNAAmount());
		}*/
		# subscriber [user] payment 
	}
	
	if(!isEmptyString($request->id)){
		$payment->populate(decode($request->id));
		$title = "Update Payment"; 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$payment->processPost($session->getVar(FORM_VALUES));	
	}
	
	$user = $payment->getUser();
	$id = $user->getID();	
	$name = $user->getName();
	$firstname = $user->getFirstName();
	$resourcename = 'Farmer';
	if($controllername == 'profile'){
		$resourcename == 'User Account';
	}
	
	# profile for one viewing
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	$metxt = '';
	if($isme){
		$metxt = 'My ';
	}
	$tab = 'subscription';
	$request->setParam('tab', 'subscription');
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		<?php if(!isEmptyString($payment->getUserID())){ ?>
			$("#indexform").validate({		
				// define the validation rules one field at a time
				rules: {
					userid: "required",
					trxcode: "required",
					amount: {
						required: true,
						min:50
					},
					paymenttype: "required",
					phone: {
						required: false, 					
						validnumber: true,
						maxlength: 10,
						minlength: 10,
						<?php if(isUganda()){ ?>
							validate_ug: true
						<?php } ?>
						<?php if(isKenya()){ ?>
							validate_ke: true
						<?php } ?>
					},
					verifiedbyid: "required",
					verifier: "required",
					trxdate: {
						required: true,
					},
					startdate:  {
						required: true/*,
						greaterthantrxdate: true*/
					},
					enddate: "required"
				}, 
				// the messages for each of the fields being validated
				messages: {		
					userid: "Please select a Farmer<?php //echo $this->translate("payment_farmerid_error"); ?>",
					trxcode: "Please enter Reference Number or Receipt Number",
					amount: {
						required: "Please enter Amount",
						min:"Minimum allowed amount is UGX 50"
					},
					paymenttype: "Please select Method",
					phone: {
						validnumber: "Please enter a valid Phone Number",
						maxlength: "Phone Number must have 10 Digits",
						minlength: "Phone Number must have 10 Digits",
						<?php if(isUganda()){ ?>
							validate_ug: "<?php echo $this->translate("globale_phonenumber_format"); ?>"
						<?php } ?>
						<?php if(isKenya()){ ?>
							validate_ke: "<?php echo $this->translate("globale_phonenumber_format_ke"); ?>"
						<?php } ?>
					},
					verifiedbyid: "Please select verifying user",
					verifier: "Please enter Approving user",
					trxdate: {
						required: "Please select Transaction Date"
					},
					startdate: {
						required: "Please select Subscription Start"
					}, 
					enddate: "Please select Subscription End"
				},
				// custom error positions
				errorPlacement: function(error, element) {
					switch(element.attr("name")){					
						default:
							error.appendTo("#"+element.attr("name")+"_error")
							break;
					}			
				},
				ignore: ":hidden:not(select)"
			});
			
			$.validator.addMethod("greaterthantrxdate", function(value, element) {
				var trx = $('#trxdate').val(); var start = $('#startdate').val();
				var t = new Date(trx); var s = new Date(start);
				t_secs = t.getTime(); s_secs = s.getTime();
				return true;
			}, "Start Date should be after Transaction Date");
			
			var dateofoptions = datepickerOpts;
			var startfrom = '<?php echo intval(date('Y'))+3; ?>'; // alert(startfrom);
			dateofoptions.maxDate = new Date("Dec 31, "+startfrom);
			$("#trxdate, #startdate").datepicker(dateofoptions);
					
			$("#bottomactions").html($("#topactions").html());
			
			if(isEmptyString($('#enddate').val())){
				$('#days').val('365');
			}
			$('#days, #startdate').change(function() {
				start = $('#startdate').val();
				var s = new Date(start);
				var e = new Date(s.getFullYear(), s.getMonth(), s.getDate());  // alert(e.getFullYear()+'-'+pad(e.getMonth())+'-'+pad(e.getDate())); 
				var days = parseInt($("#days").val());
				e.setDate(e.getDate() + parseInt(days)); 
				enddate = e.getShortMonthName()+" "+e.getDate()+", "+e.getFullYear();
				$('#enddate').val(enddate);
				
			});
			$('#days, #startdate').change();
		<?php } else {  ?>
			// trigger path to farmer report to be generated
			$("#userid").change(function(){
				var id = $(this).val()
				var url = '<?php echo $this->baseUrl('payment/index/country/'.$country.'/userid/'); ?>'+base64_encode(id);
				window.location.href = url;
			});
		<?php } ?>
	}); 
</script>
<h1><?php echo $payment->getUser()->getName(); ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="subscription">
        	<form id="indexform" class="form-horizontal makerelative desktop" action="<?php echo $posturl; ?>" method="post">
                <h1><?php echo $title; ?></h1>
                <div class="wellcontent">
                    <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                        <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                        <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                    <?php } ?>
                    <?php if(!isEmptyString($payment->getUserID())){ ?>
                        <div class="control-group well lighter actions" id="topactions">
                            <div class="blocked clear makerelative">
                                <ul class="peoplegroup">
                                    <li><a class="btn cancel gonowhere"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                    <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save'); ?></button></li>
                                    <li style="float:right;"></li>
                                </ul>
                            </div>
                        </div>
                    <?php } ?>
                    <fieldset class="fieldsetcontainer well">
                        <legend><?php echo isEmptyString($payment->getUserID()) ? 'Select a Farmer to Continue' : 'Payment Details' ?></legend>
                        <?php if(isEmptyString($payment->getUserID())){ ?>
                            <div class="control-group">
                                <label class="control-label">Farmer:</label>
                                <div class="controls">
                                	<?php
										// $farmgroupid = 65;
										$userarray = getFarmers($farmgroupid, false, false, false, '', $session->getVar('country'));
										$userdropdown = new Zend_Form_Element_Select('userid',
															array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Browse Farmers>'), $userarray),								
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																	'class' => array('chzn-select', 'width180', 'novalidate'),
																	'style' => 'width:350px;'
															)
														);
										$userdropdown->setValue($request->getParam('userid')); 
										echo $userdropdown->render(); 
									  ?>&nbsp;&nbsp;
                                </div>
                            </div>
                        <?php } else { ?>
                            <div class="control-group">
                                <label class="control-label" for="farmer">Farmer:</label>
                                <div class="controls">
                                    <?php echo 'Name('.$payment->getUser()->getName().')'; ?> 
                                    <?php if(!isEmptyString($payment->getUser()->getFarmGroupID())){ ?>
                                        <?php echo ', DNA('.$payment->getUser()->getFarmGroup()->getName().') '; ?>
                                    <?php } ?>
                                    <?php echo ', FIN('.$payment->getUser()->getRefNo().')'; ?> 
                                    &nbsp; <a href="<?php echo $this->baseUrl('payment/index'); ?>" class="btn btn-primary btn-mini" >Select Other Farmer</a>
                                    <input type="hidden" name="entityname" value="Payment" />
                                    <input type="hidden" id="id" name="id" value="<?php echo encode($payment->getID()); ?>" />
                                    <input type="hidden" id="stem" name="stem" value="<?php echo $payment->getStem(); ?>" />
                                    <input type="hidden" id="item" name="item" value="<?php echo $payment->getItem(); ?>" />
                                    <input type="hidden" id="status" name="status" value="<?php echo $payment->getStatus(); ?>" />
                                    <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $payment->getFarmGroupID(); ?>" />
                                    <input type="hidden" id="userid" name="userid" value="<?php echo $payment->getUserID(); ?>" />
                                    <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                                    <input type="hidden" id="regsource" name="regsource" value="0" />
                                    <input type="hidden" id="subscriptionid" name="subscriptionid" value="<?php echo $payment->getSubscriptionID(); ?>" />
                                    <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('farmer/view/id/'.encode($payment->getUserID()).'/tab/subscription')); ?>" />
                                    <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->viewurl); ?>" />
                                    <input type="hidden" name="country" id="country" value="<?php echo $session->getVar('country'); ?>" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Method: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls">
                                    <?php
                                        $types = getPaymentMethods();
                                        $typesdropdown = new Zend_Form_Element_Select('paymenttype',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $types),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('span3'),
                                                                'style' => 'width:130px;'
                                                            )
                                                        );
                                        $typesdropdown->setValue($payment->getPaymentType()); 
                                        echo $typesdropdown->render(); 
                                   ?><div id="paymenttype_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Trx Code: <?php echo $this->translate("global_required_field_marker"); ?> </label>
                                <div class="controls">
                                    <input type="text" name="trxcode" id="trxcode" class="width100" value="<?php echo $payment->getTrxCode(); ?>" />
                                    <div id="trxcode_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Trx Amount: <?php echo $this->translate("global_required_field_marker"); ?> </label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on"><?php echo getCurrencySymbol(); ?></span>
                                        <input type="text" name="amount_select" id="amount_select" class="width80 isamount rightalign disabledfield" style="width:55px;" value="<?php echo $payment->getAmount(); ?>" /><input type="hidden" class="hidden" name="amount" id="amount" value="<?php echo $payment->getAmount(); ?>" />
                                    </div>
                                    <div id="amount_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Trx Date: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls"><input type="text" name="trxdate" id="trxdate" class="datefield span2 width100" style="width:100px;" value="<?php echo changeMySQLDateToPageFormat($payment->getTrxDate()); ?>" /><div id="trxdate_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Service Start: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls"><input type="text" name="startdate" id="startdate" class="datefield span2 width100" style="width:100px;" value="<?php echo changeMySQLDateToPageFormat($payment->getSubscription()->getStartDate()); ?>" /><div id="startdate_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Duration: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls">
                                    <?php
                                        $types = getSubscriptionPeriods();
                                        $typesdropdown = new Zend_Form_Element_Select('days_select',
                                                            array(
                                                                'multiOptions' => $types,								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('span1','disabledfield'),
                                                                'style' => 'width:90px;'
                                                            )
                                                        );
                                        $typesdropdown->setValue($days); 
                                        echo $typesdropdown->render(); 
                                   ?>
                                   <input type="hidden" class="hidden" name="days" id="days" value="<?php echo $days; ?>" />
                                    <div id="days_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Service End: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls">
                                    <input type="text" name="enddate" id="enddate" class="datefield span2" style="width:100px;" value="<?php echo changeMySQLDateToPageFormat($payment->getSubscription()->getEndDate()); ?>" /> (Auto)<div id="enddate_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Phone:</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on"><?php echo '+'.getCurrencyCode(); ?></span>
                                        <input type="text" name="phone" id="phone" maxlength="10" value="<?php echo getShortPhone($payment->getPhone()); ?>" class="span2 minwidth100" style="margin-top:0;" />
                                    </div>
                                    <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="sendconfirmationtophone" id="sendconfirmationtophone" value="1" class="<?php echo isEmptyString($payment->getUser()->getPhone()) || !isEmptyString($payment->getID()) ? 0 : 1; ?>" style="margin-top:0;" />&nbsp;
                                         <label class="lineblocked">Send activation confirmation to Phone</label>
                                    </div>
                                    <div id="phone_error"></div>
                                </div>
                            </div>
                            <?php if(!isEmptyString($payment->getUser()->getEmail())){ ?>
                                <div class="control-group">
                                    <label class="control-label">Email:</label>
                                    <div class="controls">
                                        <?php echo $payment->getUser()->getEmail(); ?><input type="hidden" name="email" id="email" value="<?php echo $payment->getUser()->getEmail(); ?>" />
                                        <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="sendconfirmationtoemail" id="sendconfirmationtoemail" value="1" class="<?php echo !isEmptyString($payment->getID()) ? 0 : 1; ?>1" style="margin-top:0;" />&nbsp;
                                             <label class="lineblocked">Send activation confirmation to Email</label>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                            <div class="control-group">
                                <label class="control-label">Verified By: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="controls">
                                    <input type="text" name="verifier" id="verifier" class="span3" value="<?php echo $payment->getVerifier(); ?>" />
                                    <div id="verifier_error"></div>
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Logged By:</label>
                                <div class="controls">
                                    <?php echo $payment->getverifiedby()->getName(); ?>
                                    <input type="hidden" name="verifiedbyid" id="verifiedbyid" value="<?php echo $payment->getverifiedbyid(); ?>" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Notes:</label>
                                <div class="controls">
                                    <textarea id="description" name="description" class="expanding"><?php echo $payment->getDescription(); ?></textarea>
                                </div>
                            </div>
                     	<?php } ?>
                    </fieldset>
                    <div class="control-group well actions" id="bottomactions"></div>
               	</div>
        	</form>            
        </div>
        <?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?>  
   	</div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>