<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	
	// $infotrade_logo = ''; $farmis_logo ='';
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country);
	
	$theid = decode($request->id);
	if(isEmptyString($theid)){
		$theid = $userid;
	}
	$user->populate($theid);
	$id = $user->getID();
	
	$id = $user->getID();	
	$name = $user->getName();
	$firstname = $user->getFirstName();
	
	# profile for one viewing
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	
	$request->setParam('tab', 'subscription');
	$successurl = $this->viewurl;
	
	$title = $user->getName();
	$this->headTitle($title);
	
?>
<script>
	$(document).ready(function() {
		
	}); 
</script>
<style>

</style>
<?php if(!isFarmer()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="subscription">
        	<h2>Payment History</h2>
            <form id="listform" class="form-horizontal">
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <span class="span6 marginleft0" style="width:97%;">
                    <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                        <?php if(isAdmin()){ ?>
                            <div class="margin0" style="position:absolute; right:10px; top:5px;">
                                <a href="<?php echo $this->baseUrl('payment/index/userid/'.encode($user->getID()).'/pgc/true/country/'.$country); ?>" class="addpopup btn btn-primary btn-mini" title="New Payment" rel="New Payment" id="newppayment" formtitle="indexform" successurl="<?php echo $successurl; ?>" action="<?php echo $this->baseUrl("payment/create"); ?>"><i class="icon-plus icon-white"></i> New</a>
                            </div>
                        <?php } ?>
                        <?php if(isFarmer()){ ?>
                            <div class="margin0" style="position:absolute; left:10px; top:5px;">
                                <a href="<?php echo $this->baseUrl('payment/paynow/id/'.encode($user->getID())); ?>" class="btn btn-primary" title="Pay Now" rel="FARMIS Payment Wizard" id="newppayment"><i class="icon-plus icon-white"></i> Pay Now</a>
                            </div>
                        <?php } ?>
                        <?php
                            $payments = $user->getAllPayments();
                            $pcount = $payments->count();
                            if($pcount == 0) { ?>
                            <div class="alert alert-info" style="margin-top:35px;">No payments available</div>
                        <?php } else { ?>                
                            <label class="labeldescription">Viewing <?php echo $pcount; ?> <?php echo $pcount == 1 ? 'payment' : 'payments'; ?></label>
                            
                            <ul id="datalist" class="nav nav-stacked">
                                <?php 
                                    foreach($payments as $payment){
                                ?>
                                <li>
                                    <table class="table noborder margin0">
                                        <tr>                                
                                            <td width="15%"><label class="control-label" style="margin-bottom:10px; font-size:14px;"><?php echo changeMySQLDateToPageFormat($payment->getTrxDate()); ?></label>
                                                <label class="control-label">Ref#:</label> <span><?php echo $payment->getTrxCode(); ?></span>
                                            </td>
                                            <td class="padding0">
                                                <div style="position:relative;">
                                                    <table class="itemlist table noborder margin0">
                                                        <tr>
                                                            <td colspan="4" style="height:28px;">
                                                                <?php if(isAdmin()){ ?>
                                                                    <div style="position:relative;">
                                                                        <div style="position:absolute; right:0; top:5px;">
                                                                            <a href="<?php echo $this->baseUrl('payment/index/pgc/true/id/'.encode($payment->getID()).'/country/'.$country); ?>" class="addpopup btn btn-mini" title="Edit Payment" rel="Edit Payment" id="editpay_<?php echo $payment->getID(); ?>" formtitle="indexform" successurl="<?php echo $successurl; ?>" action="<?php echo $this->baseUrl('payment/create'); ?>" style="margin-bottom:5px;"><i class="icon-pencil"></i></a><br />
                                                                            <a href="javascript: void(0)" id="deleteline_multiple" title="Delete Entry" class="btn btn-mini deleteline removeline close" action="<?php echo $this->baseUrl('payment/delete/id/'.$payment->getID()."/entityname/Payment/successurl/".encode($successurl)); ?>" message="Are you sure you want to delete this Payment?">&times;</a>
                                                                        </div>
                                                                    </div>
                                                               <?php } ?>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td> <label class="control-label">Subject </label><span><?php echo $payment->getSubject(); ?></span></td>
                                                            <td style="width:20%;"><label class="control-label">Payment Method</label><span><?php echo $payment->getMethod(); ?></span></td>
                                                            <td style="width:20%;"><label class="control-label">Phone</label><span><?php echo isEmptyString($payment->getPhone()) ? '--': getShortPhone($payment->getPhone()); ?></span></td>
                                                            <td style="width:20%;"><label class="control-label">Amount</label><span><?php echo formatNumber($payment->getAmount()); ?></span>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td colspan="2"><label class="control-label">Description </label><span><?php echo isEmptyString($payment->getDescription()) ? '--': $payment->getDescription(); ?></span></td>
                                                            <td><label class="control-label">Status</label><span><?php echo $payment->getPaymentStatus(); ?></span></td>
                                                            
                                                            <td><label class="control-label">Verified By</label><span><?php echo isEmptyString($payment->getVerifier()) ? '--': $payment->getVerifier(); ?></span></td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                </span>
                
                <h2>Subscription History</h2>
                <span class="span6 marginleft0" style="width:97%;">
                    <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                        <?php if(isAdmin()){ ?>
                            <div class="margin0" style="position:absolute; right:10px; top:5px;">
                                <a href="<?php echo $this->baseUrl('payment/subscription/userid/'.encode($user->getID()).'/pgc/true/country/'.$country); ?>" class="addpopup btn btn-primary btn-mini" title="New Subscription Period" rel="New Subscription Period" id="newsubscription" formtitle="indexform" successurl="<?php echo $successurl; ?>" action="<?php echo $this->baseUrl("payment/processsubscription"); ?>"><i class="icon-plus icon-white"></i> New</a>
                            </div>
                        <?php } ?>
                        <?php
                            $subscriptions = $user->getAllSubscription();
                            $scount = $subscriptions->count();
                            if($scount == 0) { ?>
                            <div class="alert alert-info" style="margin-top:35px;">No subscriptions available</div>
                        <?php } else { ?>                
                            <label class="labeldescription">Viewing <?php echo $scount; ?> <?php echo $scount == 1 ? 'subscription' : 'subscriptions'; ?></label>
                            
                            <ul id="datalist" class="nav nav-stacked">
                                <?php 
                                    foreach($subscriptions as $subscription){
                                ?>
                                <li>
                                    <table class="table noborder margin0">
                                        <tr>                                
                                            <td class="padding0">
                                                <div style="position:relative;">
                                                    <table class="itemlist table noborder margin0">
                                                        <tr>
                                                            <td colspan="6" style="height:5px;">
                                                                <?php if(isAdmin()){ ?>
                                                                    <div style="position:relative;">
                                                                        <div style="position:absolute; right:3px; top:2px;">
                                                                            <a href="<?php echo $this->baseUrl('payment/subscription/pgc/true/id/'.encode($subscription->getID()).'/country/'.$country); ?>" class="addpopup btn btn-mini" title="Edit Subscription" rel="Edit Subscription" id="editpay_<?php echo $subscription->getID(); ?>" formtitle="indexform" successurl="<?php echo $successurl; ?>" action="<?php echo $this->baseUrl('payment/processsubscription'); ?>" style="margin-bottom:5px;"><i class="icon-pencil"></i></a><br />
                                                                            <a href="javascript: void(0)" id="deleteline_multiple" title="Delete Entry" class="btn btn-mini deleteline removeline close" action="<?php echo $this->baseUrl('payment/delete/id/'.$subscription->getID()."/entityname/Subscription/successurl/".encode($successurl)); ?>" message="Are you sure you want to delete this Subscription?">&times;</a>
                                                                        </div>
                                                                    </div>
                                                                <?php } ?>                                                                
                                                             </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="width:100px;"><label class="control-label">Start Date</label><span><?php echo changeMySQLDateToPageFormat($subscription->getStartDate()); ?></span></td>
                                                            <td style="width:100px;"><label class="control-label">End Date</label><span><?php echo changeMySQLDateToPageFormat($subscription->getEndDate()); ?></span></td>
                                                            <td><label class="control-label">Membership Plan</label><span><?php echo $subscription->getSubject(); ?></span></td>
                                                            <td style="width:110px;"><label class="control-label">Days Assigned</label><span><?php echo $subscription->getDaysAssigned(); ?></span></td>
                                                            <td style="width:110px;"><label class="control-label">Days Left</label><span><?php echo $subscription->getRemainingDays(); ?></span></td>
                                                            <td style="width:110px;"><label class="control-label">Status</label><span><?php echo $subscription->getStatus(); ?></span>
                                                            
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <?php } ?>
                            </ul>
                        <?php } ?>
                    </div>
                </span>
                
            </form>
        </div>
        <?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?> 
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>