<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	// require_once APPLICATION_PATH.'/includes/OAuth.php';
	
	// debugMessage();
	$title = "IFRAME"; 
	$this->headTitle($title);
?>
<?php require APPLICATION_PATH."/views/scripts/mobile/mobileincludes.phtml"; ?>
<script>
	$(document).ready(function() {
		
		
	});
</script>
<body>
	<div class="container-fluid" id="">
		<div class="row-fluid">
			<h4><?php echo $title; ?></h4>
		</div>
        
    </div>
    <div class="row-fluid">
        <iframe src="<?php echo $this->iframe_src; ?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
        	<p>Browser unable to load iFrame</p>
        </iframe>
    </div>
</body>
</html>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>