<div class="crumbs">
    <ul class="breadcrumb" id="breadcrumbs">
        <li style="width:245px; margin: 0px 0px 0px -6px; padding:0;"><h2 id="quicklink" style="margin-top:-5px;"><i class="icon-indent-left" style="padding:0 3px;"></i>Navigation</h2></li>
        <li>
            <i id="levelone_icon"></i>
            <a id="levelone_link"></a>
        </li>
        <li>
            <a id="leveltwo_link"></a>
        </li>
        <li>
            <a id="levelthree_link"></a>
        </li>
    </ul>
    <ul class="crumb-buttons">
        <li style="width:290px; border:none;">
            <div class="divider5"></div>
            <div class="contentArea">
                <input type="text" class="search" id="inputSearch" placeholder="Search FARMIS" />
                <ul id="divResult"></ul>
            </div>
       </li>
    </ul>
</div>
