<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$commodity = new Commodity(); 
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$commodity->processPost($session->getVar(FORM_VALUES));	
	}
	
	$title = $this->translate("commodity_pagetitle_new"); 
	$this->headTitle($title);
	
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				name: "required",
				categoryid: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				name: "<?php echo $this->translate("commodity_name_error"); ?>",
				categoryid: "<?php echo $this->translate("commodity_category_error"); ?>"			
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		// tooltips in popup
		$(".hastooltip").each(function(){		
			var theid = $(this).attr('id');
			var thepath = '<?php echo $this->baseUrl('images/questionmark.png'); ?>';
			if($(this).attr('title') != "undefined" || $(this).attr('title') != ""){
				$('<a href="javascript: void(0);" class="qcontainer" id="q_'+theid+'"><img src="'+thepath+'" /></a>').insertAfter(this);
				$("#q_"+theid).attr('title', $(this).attr('title')).addClass('qtooltip');
			}	    
		}); 
		$('.qtooltip').tipsy({fade: true, gravity: 'w', html: true, trigger: 'hover', offset: -5});
    	$(".hastooltip").attr('title','');
		
		// reset tab index
		var tabindex = 1;
		$('input,select').each(function() {
			if (this.type != "hidden") {
				var $input = $(this);
				$input.attr("tabindex", tabindex);
				tabindex++;
			}
		});
		
	}); 
</script>
<style>
body {
	overflow:hidden;
}
.form-horizontal.well {
	margin:0;
	padding-top:0;
	padding-bottom:0;
	width:93%;
}
.form-horizontal .control-label {
	font-size: 11px;
	padding-top:3px;
	width: 130px;
}
.form-horizontal .control-label.gender {
	width: 60px;
	display:inline-block;
}
.form-horizontal input {
	height:15px;
}
.form-horizontal select {
	height:25px;
	font-size: 12px;
}
.form-horizontal .table td {
	vertical-align: middle;
}
.form-horizontal .table tr:last-child td {
	height:10px;
}
.form-horizontal .table tbody {
	border-top:none;
}
.radio.inline, .checkbox.inline {
	display:inline-block;
	margin-bottom: 1px;
    padding-top: 0;
}
.radio input[type="radio"], .checkbox input[type="checkbox"] {
	margin-top:1px;
}

</style>
<form class="form-horizontal well span6" id="indexform" action="<?php echo $this->baseUrl("commodity/create"); ?>" method="post">
    <table class="table">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
        <tr>
            <td width="30%"><label class="control-label" for="name"><?php echo $this->translate("commodity_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><input type="text" name="name" id="name" class="span3 hastooltip" value="<?php echo $commodity->getName(); ?>" title="<?php echo $this->translate("commodity_name_tooltip"); ?>" /><div id="name_error"></div>
            <input type="hidden" name="entityname" value="Commodity" />
            <input type="hidden" id="id" name="id" value="<?php echo encode($commodity->getID()); ?>" />
            <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('commodity/addsuccess')); ?>" />
            </td>
        </tr>
        <tr>
          <td><label class="control-label"><?php echo $this->translate("commodity_parent_label"); ?>:</label></td>
          <td><?php 	
				$commoditylist = new LookupType(); 
				$commoditylist->setName("ALL_COMMODITIES");
				$commodities = $commoditylist->getOptionValuesFromQuery();
				$commoditydropdown = new Zend_Form_Element_Select('parentid',
									array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $commodities),	
										'view' => new Zend_View(),
										'decorators' => array('ViewHelper'),
										'class' => array("span3", 'xchzn-select'),
									)
								);
				$commoditydropdown->setValue($commodity->getParentID()); 
				echo $commoditydropdown->render(); 
            ?>
            </td>
       </tr>
        <tr>
          <td><label class="control-label"><?php echo $this->translate("commodity_category_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
          <td><?php 	
				$commoditycategorylist = new LookupType(); 
				$commoditycategorylist->setName("ALL_COMMODITY_CATEGORIES"); 
				$commoditycategorydropdown = new Zend_Form_Element_Select('categoryid',
									array(
										'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $commoditycategorylist->getOptionValuesFromQuery()),								
										'view' => new Zend_View(),
										'decorators' => array('ViewHelper'),
										'class' => array('span3'),
									)
								);
				$commoditycategorydropdown->setValue($commodity->getCategoryID()); 
				echo $commoditycategorydropdown->render(); 
            ?><div id="categoryid_error"></div>
            </td>
       </tr>
       <tr>
          <td><label class="control-label"><?php echo $this->translate("commodity_units_label"); ?>:</label></td>
          <td><?php 	
				$commodityunitdropdown = new Zend_Form_Element_Select('unitid',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getAllStandardUnits()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper'),
									'class' => array('span2')
								)
							);
				$commodityunitdropdown->setValue($commodity->getUnitID()); 
				echo $commodityunitdropdown->render(); 
            ?></td>
        </tr>
  </table>
</form>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>