<div id="farmers">
        	<h2>Farmers</h2>
            <form id="profileform-farmers" class="form-horizontal farmers">
            <?php if($request->tab == 'farmers'){ ?>
        	<div class="row" style="margin-left:0px;">
                 <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
				<?php } ?>
                <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                    <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <span class="marginleft0 span9" style="width:98%;">
                    <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">                        
                        <table class="table"> 
                        	<tr>		                    
                                <td>
                                	<?php if(isAdmin() || $userid == $farmgroup->getManagerID()){ ?>
                                        <a class="btn btn-primary btn-mini addpopup" style="margin-bottom: 10px;" href="<?php echo $this->baseUrl('profile/add/pgc/true/farmgroupid/'.$farmgroup->getID().'/country/'.$country); ?>" rel="Add Farmer | <?php echo $farmgroup->getName(); ?>" title="Add Farmer" id="addfarmer" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/farmers'); ?>" action="<?php echo $this->baseUrl("profile/create"); ?>"><i class="icon-plus icon-white"></i> Add Farmer</a>
                                        <a class="btn btn-primary btn-mini" style="margin-bottom: 10px;" href="<?php echo $this->baseUrl('report/allfarmers/farmgroupid/'.$farmgroup->getID()); ?>" title="View Report"><i class="icon-list icon-white"></i> Bio Data Report</a>
                                        
                                    <?php } ?>
                                    
                                	<label class="labeldescription" style="margin-top:15px;"><?php echo $total_farmers == 0 ? "There are currently no farmers for ".$farmgroup->getName(): "There are currently ".$total_farmers." farmers in ".$farmgroup->getName(); ?></label>
                                    <?php if($user_count > 0){ ?>
                                    <div style="position:absolute; right:30px; top:20px;">
										<?php echo "Viewing ".$user_count." out of ".$total_farmers." farmers "; ?>
                                        <a class="btn btn-primary btn-mini" style="" href="<?php echo $this->baseUrl('profile/list/farmgroupid/'.$farmgroup->getID()); ?>" title="View Report"><i class="icon-list icon-white"></i> List all</a>
                                    </div>
                                    <?php } ?>
                                    <ul id="datalist" class="nav nav-stacked">
									<?php 				  		
                                        foreach($thefarmers as $user){
                                            $id = $user->getID();	
                                            $name = $user->getName();
                                            $firstname = $user->getFirstName();
											$haspic = false;
											if($user->hasProfileImage()){
												$haspic = true;
											}
											$email = $user->getEmail();
											$username = $user->getUserName();
											if(isEmptyString($email)){
												$email = '--';
											}
											if(isEmptyString($username)){
												$username = '--';
											}	
											
											$refno = $user->getRegNo();
											if($user->isKenyan()){
												$refno = $user->getRefNo();
											}
                                    ?>
                                    <li>
                                        <a class="btn btn-primary btn-mini" style="position:absolute; top:10px; right:25px;" href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())); ?>">View Profile</a>
                                        <table class="table noborder margin0">
                                            <tr>                                
                                                <td width="75">
                                                    <div id="thumbinfo" class=""> 
                                                        <a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())); ?>" title="<?php echo $this->translate("person_button_view_profile"); ?>"><img src="<?php echo $user->getThumbnailPicturePath(); ?>" /></a>
                                                    </div>
                                                </td>
                                                <td class="padding0">                                                    
                                                    <table class="itemlist table noborder margin0">
                                                        <tr>
                                                        	<td colspan="4">
                                                            	<h2><a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())); ?>" title="<?php echo "View ".$user->getFirstName()."'s Profile"; ?>"><?php echo $user->getName(); ?></a></h2>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="width:65px;"><label class="control-label">FIN#: </label></td>
                                                            <td style="width:140px;" class="nowrapping"><span><?php echo $refno; ?></span></td>
                                                            <td style="width:60px;"><label class="control-label">Phone: </label></td>
                                                            <td class="nowrapping"><span><?php echo isEmptyString($user->getPhone()) ? '--' : getShortPhone($user->getPhone()); ?></span></td>
                                                        </tr>
                                                        <tr>
                                                            <td><label class="control-label"><?php echo $location_label; ?>:</label></td>
                                                            <td class="nowrapping"><span><?php echo isEmptyString($user->getLocationID()) ? '--' : $user->getLocation()->getName(); ?></span></td>
                                                            <td><label class="control-label">Email: </label></td>
                                                            <td class="nowrapping"><span><?php echo $user->getEmail(); ?></span></td>
                                                        </tr>
                                                        <tr>
                                                            <td><label class="control-label">Subscribed:</label></td>
                                                            <td class="nowrapping"><span><?php echo $user->isSubscribed() ? 'Yes' : 'No'; ?></span></td>
                                                            <td><label class="control-label">Username:</label></td>
                                                            <td class="nowrapping"><span><?php echo $username; ?></span></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                    <?php } ?>    
                                </ul>
                                    
                                </td>
		               		</tr>
                        </table>
                    </div>
                </span>
            </div>
            <?php } ?>
            </form>    
        </div>
        <?php if($farmgroup->hasSubGroups()){ ?>
            <div id="subgroups">
                <h2>Sub Groups</h2>
                <form id="profileform-subgroups" class="form-horizontal subgroups">
                <?php if($request->tab == 'subgroups'){ ?>
                    <div class="row" style="margin-left:0px;">
                        <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                            <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <span class="span6 marginleft0" style="width:100%;">
                        	<div class="well row marginleft0" style="min-height:60px; padding-left:10px;">                        
                                <table class="table"> 
                                    <tr>		                    
                                        <td>
                                            <?php if(isAdmin()){ ?>
                                                <a href="<?php echo $this->baseUrl('farmgroup/add/pgc/true/subgroupid/'.$farmgroup->getID()); ?>" class="addpopup btn btn-primary btn-mini" title="New Sub Group" rel="New Sub Group" id="newsubgroup" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID())."/tab/subgroups"); ?>" action="<?php echo $this->baseUrl("farmgroup/create"); ?>"><i class="icon-plus icon-white"></i> New</a>
                                            <?php } ?>
                                            <label class="labeldescription" style="margin-top:10px;"><?php echo $user_count == 0 ? "There are currently no sub groups for ".$farmgroup->getName(): "Viewing ".$user_count." sub groups(s)"; ?></label>
                                            <ul id="datalist" class="nav nav-stacked">
                                            <?php 				  		
                                                foreach($subgroups as $group){
                                                    $id = $group->getID();	
                                                    $name = $group->getName();
                                                   
                                            ?>
                                            <li>
                                                <a class="btn btn-primary btn-mini" style="position:absolute; top:10px; right:10px;" href="<?php echo $this->baseUrl("farmgroup/view/id/".encode($group->getID())); ?>">View Profile</a>
                                                <table class="table noborder margin0">
                                                    <tr>                                
                                                        <td style="width:18%;">
                                                            <div id="thumbinfo"> 
                                                                <a href="<?php echo $this->baseUrl("farmgroup/view/id/".encode($group->getID())); ?>" title="<?php echo $this->translate("person_button_view_profile"); ?>"><img src="<?php echo $group->getThumbnailLogoPath(); ?>" /></a>
                                                            </div>
                                                        </td>
                                                        <td class="padding0">                                                    
                                                            <table class="itemlist table noborder margin0">
                                                                <tr>
                                                                    <td colspan="4">
                                                                        <h2><a href="<?php echo $this->baseUrl("farmgroup/view/id/".encode($group->getID())); ?>" title="<?php echo "View ".$group->getName()."'s Profile"; ?>"><?php echo $group->getName(); ?></a></h2>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td style="width:100px;"><label class="control-label">District:</label></td>
                                                                    <td style="width:120px;" class="nowrapping"><span><?php echo isEmptyString($group->getDistrictID()) ? '--' : $farmgroup->getDistrict()->getName(); ?></span></td>
                                                                    <td style="width:100px;"><label class="control-label">Reg No#:</label></td>
                                                                    <td class="nowrapping"><span><?php echo isEmptyString($group->getRegNo()) ? '--' : $group->getRegNo(); ?></span></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><label class="control-label">Date Registered: </label></td>
                                                                    <td class="nowrapping"><span><?php echo $group->getRegDateFormatted(); ?></span></td>
                                                                    <td><label class="control-label">Group Type:</label></td>
                                                                    <td class="nowrapping"><span><?php echo $group->getTypeLabel(); ?></span></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><label class="control-label">Contact Phone:</label></td>
                                                                    <td class="nowrapping"><span><?php echo isEmptyString($group->getPhone()) ? '--' : $group->getPhone(); ?></span></td>
                                                                    <td><label class="control-label">Email:</label></td>
                                                                    <td class="nowrapping"><span><?php echo isEmptyString($group->getEmail()) ? '--' : $group->getEmail(); ?></span></td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </li>
                                            <?php } ?>    
                                        </ul>
                                            
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </span>
                    </div>
                <?php } ?> 
                </form> 
            </div>
        <?php } ?>
        <div id="subscription">
        	<h2>Payment History</h2>
            <form id="profileform-subscription" class="form-horizontal subscription">
            	<?php if($request->tab == 'subscription'){ ?>
            		<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    <?php if($sessionhaserror) { ?>
                        <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                    <?php } ?>
                    <span class="span6 marginleft0" style="width:99%;">
                        <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                            <?php if(isAdmin()){ ?>
                                <div class="margin0" style="position:absolute; right:10px; top:5px;">
                                    <a href="<?php echo $this->baseUrl('payment/index/farmgroupid/'.encode($farmgroup->getID()).'/pgc/true'); ?>" class="addpopup btn btn-primary btn-mini" title="New Payment" rel="New Payment" id="newppayment" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'); ?>" action="<?php echo $this->baseUrl("payment/create"); ?>"><i class="icon-plus icon-white"></i> New</a>
                                </div>
                            <?php } ?>
                            <?php
								$payments = $farmgroup->getAllPayments();
								$pcount = $payments->count();
                                if($pcount == 0) { ?>
                                <div class="alert alert-info" style="margin-top:35px;">No payments available</div>
                            <?php } else { ?>                
                                <label class="labeldescription">Viewing <?php echo $pcount; ?> <?php echo $pcount == 1 ? 'payment' : 'payments'; ?></label>
                                
                                <ul id="datalist" class="nav nav-stacked">
                                    <?php 
                                        foreach($payments as $payment){
                                    ?>
                                    <li>
                                    	<table class="table noborder margin0">
                                            <tr>                                
                                                <td width="18%"><label class="control-label" style="margin-bottom:10px; font-size:14px;"><?php echo changeMySQLDateToPageFormat($payment->getTrxDate()); ?></label>
                                                	<label class="control-label">Ref#:</label> <span><?php echo $payment->getTrxCode(); ?></span>
                                                </td>
                                                <td class="padding0">
                                                    <div style="position:relative;">
                                                        <table class="itemlist table noborder margin0">
                                                            <tr>
                                                            	<td colspan="4" style="height:28px;">
                                                                	<?php if(isAdmin()){ ?>
                                                                        <div style="position:relative;">
                                                                            <div style="position:absolute; right:0; top:5px;">
                                                                                <a href="<?php echo $this->baseUrl('payment/index/pgc/true/id/'.encode($payment->getID())); ?>" class="addpopup btn btn-mini" title="Edit Payment" rel="Edit Payment" id="editpay_<?php echo $payment->getID(); ?>" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'); ?>" action="<?php echo $this->baseUrl('payment/create'); ?>" style="margin-bottom:5px;"><i class="icon-pencil"></i></a><br />
                                                                                <a href="javascript: void(0)" id="deleteline_multiple" title="Delete Entry" class="btn btn-mini deleteline removeline close" action="<?php echo $this->baseUrl('payment/delete/id/'.$payment->getID()."/entityname/Payment/successurl/".encode($this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'))); ?>" message="Are you sure you want to delete this Payment?">&times;</a>
                                                                            </div>
                                                                        </div>
                                                                   <?php } ?>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td> <label class="control-label">Subject </label><span><?php echo $payment->getSubject(); ?></span></td>
                                                                <td style="width:150px;"><label class="control-label">Payment Method</label><span><?php echo $payment->getMethod(); ?></span></td>
                                                                <td style="width:110px;"><label class="control-label">Phone</label><span><?php echo isEmptyString($payment->getPhone()) ? '--': getShortPhone($payment->getPhone()); ?></span></td>
                                                                <td style="width:120px;"><label class="control-label">Amount</label><span><?php echo formatNumber($payment->getAmount()); ?></span>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td colspan="2"><label class="control-label">Description </label><span><?php echo isEmptyString($payment->getDescription()) ? '--': $payment->getDescription(); ?></span></td>
                                                                <td><label class="control-label">Status</label><span><?php echo $payment->getPaymentStatus(); ?></span></td>
                                                                
                                                                <td><label class="control-label">Verified By</label><span><?php echo isEmptyString($payment->getVerifier()) ? '--': $payment->getVerifier(); ?></span></td>
                                                            </tr>
                                                        </table>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </span>
                    
                    <h2>Subscription History</h2>
                    <span class="span6 marginleft0" style="width:99%;">
                        <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                            <?php if(isAdmin()){ ?>
                                <div class="margin0" style="position:absolute; right:10px; top:5px;">
                                    <a href="<?php echo $this->baseUrl('payment/subscription/farmgroupid/'.encode($farmgroup->getID()).'/pgc/true'); ?>" class="addpopup btn btn-primary btn-mini" title="New Subscription" rel="New Subscription" id="newsubscription" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'); ?>" action="<?php echo $this->baseUrl("payment/processsubscription"); ?>"><i class="icon-plus icon-white"></i> New</a>
                                </div>
                            <?php } ?>
                            <?php
								$subscriptions = $farmgroup->getAllSubscription();
								$scount = $subscriptions->count();
                                if($scount == 0) { ?>
                                <div class="alert alert-info" style="margin-top:35px;">No subscriptions available</div>
                            <?php } else { ?>                
                                <label class="labeldescription">Viewing <?php echo $scount; ?> <?php echo $scount == 1 ? 'subscription' : 'subscriptions'; ?></label>
                                
                                <ul id="datalist" class="nav nav-stacked">
                                    <?php 
                                        foreach($subscriptions as $subscription){
                                    ?>
                                    <li>
                                    	<table class="table noborder margin0">
                                            <tr>                                
                                                <td class="padding0">
                                                    <div style="position:relative;">
                                                        <table class="itemlist table noborder margin0">
                                                            <tr>
                                                            	<td colspan="6" style="height:5px;">
                                                                	<?php if(isAdmin()){ ?>
                                                                        <div style="position:relative;">
                                                                            <div style="position:absolute; right:3px; top:2px;">
                                                                                <a href="<?php echo $this->baseUrl('payment/subscription/pgc/true/id/'.encode($subscription->getID())); ?>" class="addpopup btn btn-mini" title="Edit Subscription" rel="Edit Subscription" id="editpay_<?php echo $subscription->getID(); ?>" formtitle="indexform" successurl="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'); ?>" action="<?php echo $this->baseUrl('payment/processsubscription'); ?>" style="margin-bottom:5px;"><i class="icon-pencil"></i></a><br />
                                                                                <a href="javascript: void(0)" id="deleteline_multiple" title="Delete Entry" class="btn btn-mini deleteline removeline close" action="<?php echo $this->baseUrl('payment/delete/id/'.$subscription->getID()."/entityname/Subscription/successurl/".encode($this->baseUrl('farmgroup/view/id/'.encode($farmgroup->getID()).'/tab/subscription'))); ?>" message="Are you sure you want to delete this Subscription?">&times;</a>
                                                                            </div>
                                                                        </div>
                                                                    <?php } ?>                                                                
                                                                 </td>
                                                            </tr>
                                                            <tr>
                                                                <td style="width:100px;"><label class="control-label">Start Date</label><span><?php echo changeMySQLDateToPageFormat($subscription->getStartDate()); ?></span></td>
                                                                <td style="width:100px;"><label class="control-label">End Date</label><span><?php echo changeMySQLDateToPageFormat($subscription->getEndDate()); ?></span></td>
                                                                <td><label class="control-label">Membership Plan</label><span><?php echo $subscription->getSubject(); ?></span></td>
                                                                <td style="width:110px;"><label class="control-label">Days Assigned</label><span><?php echo $subscription->getDaysAssigned(); ?></span></td>
                                                                <td style="width:110px;"><label class="control-label">Days Left</label><span><?php echo $subscription->getRemainingDays(); ?></span></td>
                                                                <td style="width:110px;"><label class="control-label">Status</label><span><?php echo $subscription->getStatus(); ?></span>
                                                                
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                        </div>
                    </span>
            	<?php } ?>
            </form>
        </div>
        <?php if(isFarmGroupAdmin()){ ?>
        <div id="account">
        	<h2>Account</h2>
            <form id="profileform-account" class="form-horizontal account">
            <?php if($request->tab == 'account'){ ?>
                <div class="row" style="margin-left:0px;">
					<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                </div>
            <?php } ?>
            </form>
        </div>
        <?php } ?>