<div class="peoplelist">
	<?php 				  
        $counter = 1;		
        foreach($result as $line){
            $id = $line['id'];	
            $name = $line['firstname']." ".$line['lastname']." ".$line['othernames'];
            $firstname = $line['firstname'];
            $lastname = $line['lastname'];
            $groupname = $line['orgname'];
            $thefarmgroupid = $line['fmgroupid'];
            $subgroupname = '';
            if(!isEmptyString($line['subgroupid'])){
                $subgroupname = $line['sorgname'];
            }
            $refno = $line['regno'];
            if(isKenya()){
                $refno = $line['refno'];
            }
            
            $hasprofileimage = false;
            $real_path = BASE_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."user_";
            $real_path = $real_path.$line['userid'].DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."large_".$line['profilephoto'];
            
            if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
                $hasprofileimage = true;
            }
            $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
            
            $photo_path = '';
            $photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_male.jpg';
            if($line['gender'] == 2){
                $photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_female.jpg'; 
            }
            if($hasprofileimage){
                $photo_path = $this->serverUrl($this->baseUrl('/uploads/user_'.$line['userid'].'/avatar/medium_'.$line['profilephoto']));
            }
            $hasdfa = true; $hasgroup = true;
            if(isEmptyString($thefarmgroupid)){
                $hasdfa = false;
            }
            if(isEmptyString($line['subgroupid'])){
                $hasgroup = false;
            }
            
    ?>
        <?php if($counter % 2 == 1){ ?>
        <div class="row-fluid">
        <?php } ?>
          <div class="span6">
            <div class="peoplewrapper well">
              <div class="thumbwrapper">
                  <div class="thumb">
                    <div id="thumbinfo" class="<?php echo $hasprofileimage ? 'new_pic' : 'default_pic'; ?>"> 
                        <a href="<?php echo $this->baseUrl($controllername."/view/id/".encode($id)); ?>"><img class="profileimage" src="<?php echo $photo_path; ?>" /></a>
                    </div>
                  </div>
                  <div class="divider2"></div>
                  <div class="blocked bolded" style="font-size:10px;"><span>FIN#:</span> <?php echo isUganda() ? '' : '<br />'; ?><?php echo $line['refno']; ?></div>
                  <?php if(isUganda()){ ?>
                    <div class="blocked" style="font-size:9px;"><?php echo $line['regno']; ?></div>
                  <?php } ?>
              </div>
              <div class="peopleinfo">
                <h4><a href="<?php echo $this->baseUrl($controllername."/view/id/".encode($id)); ?>"><?php echo $name; ?></a></h4>
                <ul>
                    <li><span><?php echo $location_label; ?>:</span> <?php echo isEmptyString($line['districtid']) ? '--' : $line['district']; ?></li>
                    <?php if($hasdfa){ ?>
                        <li><span>DNA:</span> <?php echo isEmptyString($thefarmgroupid) ? '--' : $groupname; ?></li>
                    <?php } else { ?>
                        <li><span class="off"> Individual Farmer</span></li>
                    <?php } ?>
                    <?php if($hasgroup){ ?>
                        <li><span>Farm Group:</span> </li>
                    <?php } ?>  
                    <li><span>Phone:</span> <?php echo isEmptyString($line['phone']) ? '--' : getShortPhone($line['phone']); ?></li>
                    <li><span>Email:</span> <?php echo isEmptyString($line['email']) ? '--' : $line['email']; ?></li>
                    <li><span>Paid:</span> <?php echo $line['paymentstatus'] == 1 ? 'Yes' : 'No'; ?></li>
                    <li><span>Login Active:</span> <?php echo $line['isactive'] == 1 ? 'Yes' : 'No'; ?></li>
                    <li><span>Profiled By:</span> <?php echo $line['addedby']; ?></li>
                    <li><span>Date:</span> <?php echo formatDateAndTime($line['dateadded'], true); ?></li>
                </ul>
              </div>
              <!--peopleinfo--> 
            </div>
            <!--peoplewrapper--> 
          <?php if($counter % 2 == 0){ ?>
          </div>
          <?php } ?>
        </div>
    <?php $counter++; } ?>
  </div>
<?php echo $paginate->getPaginationLinks(); ?>  