<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$location = new Location();
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$countys_label = "Counties";
	$subcounty_label = $this->translate("global_subcounty_label");
	$subcountys_label = "Sub-counties";
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$countys_label = "Sub-counties";
		$subcounty_label = $this->translate("global_ward_label");
		$subcountys_label = "Wards";		
	}
	$countryreq = strtolower($request->country);
	
	if(!isEmptyString($request->id)) {
		$location->populate(decode($request->id));
	}
	
	$moduleitem = "Location";
	$plural = "Locations";
	$title = "Location Details"; 
	switch($location->getLocationType()){
		case 1:
			$moduleitem = "Region";
			$plural = "Regions";
			break;
		case 2:
			$moduleitem = $location_label;
			$plural = $locations_label;
			break;
		case 3:
			$moduleitem = $county_label;
			$plural = $countys_label;
			break;
		case 4:
			$moduleitem = $subcounty_label;
			$plural = $subcountys_label;
			break;
		case 5:
			$moduleitem = "Parish";
			$plural = "Parishes";
			break;
		case 6:
			$moduleitem = "Village";
			$plural = "Villages";
			break;
		default:
			break;
	}
	$title = $location->getName(); 
	
	$moduleitem_lower = strtolower($moduleitem);
	$listurl = $this->baseUrl("location/list");
	$this->headTitle($title.$browserappend); 
	
?>
<script>
$(document).ready(function() {
	$('div.controls, .nullifempty').each(function() {
		var html = $(this).html();
		if(isEmptyString(html)){
			$(this).html('--');
		}
	});
}); 
</script>	
<div class="popupdiv">
<form class="form-horizontal well span6" id="indexform" method="post">
    <table class="table">
        <tr>
            <td style="width:25%;"><label class="control-label">Type:</label></td>
            <td><?php echo $location->getLocationType(); ?></td>
        </tr>
        <tr class="locationspecific <?php echo strtolower($location_label); ?> <?php echo strtolower($county_label); ?> <?php echo strtolower($subcounty_label); ?> parish village">
            <td><label class="control-label">Region: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td><?php echo $location->getRegion()->getName(); ?></td>
        </tr>
        <tr class="locationspecific <?php echo strtolower($county_label); ?> <?php echo strtolower($subcounty_label); ?> parish village">	
            <td><label class="control-label"><?php echo $location_label; ?>:</label></td>
            <td class="nullifempty"><?php echo $location->getDistrict()->getName(); ?></td>
        </tr>
        <tr class="locationspecific <?php echo strtolower($subcounty_label); ?> parish village">
            <td><label class="control-label"><?php echo $county_label; ?>:</label></td>
            <td class="nullifempty"><?php echo $location->getCounty()->getName(); ?></td>
        </tr>
        <?php if(isUganda()){?>
            <tr class="locationspecific parish village">
                <td><label class="control-label"><?php echo $subcounty_label; ?>:</label></td>
                <td class="nullifempty"><?php echo $location->getSubCounty()->getName(); ?></td>
            </tr>
            <tr class="locationspecific village">
                <td><label class="control-label"><?php echo $this->translate("global_parish_label"); ?>:</label></td>
                <td class="nullifempty"><?php echo $location->getParish()->getName(); ?></td>
            </tr>
        <?php } ?>
        <tr>
            <td><label class="control-label"><?php echo $this->translate("global_name_label")." of Location"; ?>:</label></td>
            <td class="nullifempty"><?php echo $location->getName(); ?></td>
        </tr>
        <tr>
            <td><label class="control-label">Description:</label></td>
            <td class="nullifempty"><?php echo $location->getDescription(); ?></td>
        </tr>
  </table>
</form>
</div>