<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?php
   require_once APPLICATION_PATH.'/includes/commonfunctions.php';
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="<?php echo $this->baseUrl('favicon.ico'); ?>" rel="shortcut icon" type="image/x-icon" /> 
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ?>
<?php
  $request = Zend_Controller_Front::getInstance()->getRequest();
  $config = Zend_Registry::get("config"); 
  $session = SessionWrapper::getInstance();
  $isloggedin = false; 
  $userid = ""; 
  if (!isEmptyString($session->getVar("userid"))) {
	$isloggedin = true; 
	$userid = $session->getVar("userid");  
	$acl = getACLInstance(); 
  }
	   
  // $jsfiles = glob("javascript/*.js");
  $jsfiles = getJsIncludes();
  $cssfiles = glob("stylesheets/*.css");
  
  foreach ($cssfiles as $css) {
	// use baseURL() to output the full URL of the cached file and use it as normal with headLink()
	$this->minifyHeadLink()->appendStylesheet($css);
  } 
  echo $this->minifyHeadLink(); 
  
  foreach ($jsfiles as $js) {
	 //  debugMessage($js);
	// use baseURL() to output the full URL of the cached file and use it as normal with headLink(). also use setFile so that each file is added
	$this->minifyHeadScript()->appendFile($js);
  }  
  echo $this->minifyHeadScript(); 
  $os = browser_detection('os');
  $islinux = false;
  if($os != 'nt'){
	  $islinux = true;
  }
  	$usertype = 2;
	$groupid = '';
	if(isAdmin()){
	  $usertype = 1;
	  $groupid = '';
	}
	if(isFarmGroupAdmin()){
	  $usertype = 3;
	  $groupid = $session->getVar("farmergroupid");
	} 
?>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript">
var datepickerOpts = {
		showOn: 'both', 
		buttonImage: '<?php echo $this->baseUrl('images/calendar.png'); ?>', 
		buttonImageOnly: true,
		changeMonth: true,
		changeYear: true,
		minDate: '-<?php echo $config->dateandtime->mindate; ?>Y',
		maxDate: '+<?php echo $config->dateandtime->maxdate; ?>Y',
		dateFormat: '<?php echo $config->dateandtime->javascriptmediumformat; ?>',
		hideIfNoPrevNext: true,
		showButtonPanel: true, 
		currentText: 'Now'		
	}; 
var dialogOpts = {
		width: 400,
		height: 300,
		resizable: false,
		modal: true,
		autoOpen: false
	};
$(document).ready(function() {
	// auto grow textareaa with class expanding
	$(".expanding").elastic();
	$(".expanding").trigger('update');
	
	// make the datefields readonly
	
	var dateOpts = datepickerOpts;
	dateOpts.yearRange = "-<?php echo date('Y')-2010; ?>:-0"; 
	$(".datefield").attr('readOnly', 'true').datepicker(dateOpts);
	
	$(".readonly, .readonlyfield").each(function(){
		$(this).attr('readonly', true);
	});
	
	$(".disabledfield").each(function(){
		$(this).attr('disabled', true);
	});
		
	// turn select controls to chosen type selects
	$(".chzn-select").chosen();

	// check if user is using less than IE9 and turn off chosen select
	/*if ($.browser.msie) {
		// remove the hidden property
		$(".chzn-select").removeClass('chzn-select')
	}*/
	 
	// if a select field with chosen changes, revalidate the field 
	$("select.chzn-select:not('.novalidate')").chosen().change(function(){
		$("form").validate().element(this);
	});
		
	$(".datefield").change(function(){
		$("form").validate().element(this);
	});
		
	// UI tabs
	$("#tabs").tabs();
	
	// initialise the accordion
	$("#accordion").accordion();
	
	// custom accordion functionality to allow collapsing more than one container at a time
	$("#notaccordion").addClass("ui-accordion ui-widget ui-helper-reset ui-accordion-icons")
.find("h3")
        .addClass("ui-accordion-header ui-helper-reset ui-corner-all ui-state-default")
        .prepend('<span class="ui-icon ui-icon-triangle-1-e"/>')
        .click(function() {
            $(this).toggleClass("ui-accordion-header-active").toggleClass("ui-state-active")
                        .toggleClass("ui-state-default").toggleClass("ui-corner-bottom")
                .find("> .ui-icon").toggleClass("ui-icon-triangle-1-e").toggleClass("ui-icon-triangle-1-s")
                .end().next().slideToggle(function() {
						// resize content column height when toggle is completed
						/*if($("#notaccordion").height() < 500 ){
							$("#contentcolumn").css({'height': 1000});							
						} else {
							$("#contentcolumn").css({'height': $("#notaccordion").height() + 500});						
						}*/
					}).toggleClass("ui-accordion-content-active clicked");
            return false;
        })
        .next().addClass("ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom").hide();
		
	// copy the classes to html radio labels from the containing div elements
	// this is a work around since Zend_Form_Element_Radio generation does not support adding labels to the labels around the containing elements 
	$('div.radio > label').each(function(){
		$(this).addClass($(this).parent().attr('class')); 
	});
	// select all checkboxes with a class Y
	$("input:checkbox.Y, input:checkbox.1, input:radio.Y, input:radio.1").attr('checked', true); 
			
	// If there are any errors in validating a form, make form height and content column equal
	$(":submit").click(function(){
		if(!($("form.form-horizontal, form.form-vertical").valid())){
			resizeContentForm();
		} 
	});	
	
	// auto submit for list filters with the specified class, and all selects in a container with class filter 
	$(".autosubmitsearchform, .filtercontainer select, #itemcountperpage, select.autofilter, input.autofilter").not(".autosubmitsearchform").each(function(){
		$(this).change(function(){
			// clear the values in the search field
			clearValue("searchterm"); 
			// submit the form containing the dropdown
			$(this).parents("form:first").submit(); 
		});
	});
	
	$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
	$("div.alert-success").css({'background': 'url("<?php echo $this->baseUrl('images/tick.png'); ?>") no-repeat #CCDDBB 5px 8px'});
	
	// return to previous page for cancel buttons
	$('a.cancel').click(function(){
        parent.history.back();
        return false;
    });

	// reset tab index
    var tabindex = 1;
    $('input,select,textarea').each(function() {
        if (this.type != "hidden") {
            var $input = $(this);
            $input.attr("tabindex", tabindex);
            tabindex++;
        }
    });

    $("img.ui-datepicker-trigger").attr('title','You may use calendar to select a date');
	// set drop down date from date picker
	$("#dateofbirth").change(function() {
		var thedate = $(this).val();
		if(!isEmptyString(thedate)){
			var d = new Date(thedate);
			// alert(d.getFullYear()+" - "+d.getMonth()+1+" - "+d.getDate());
			$("#birthyear").val(d.getFullYear());
			$("#birthmonth").val(d.getMonth()+1);
			$("#birthday").val(d.getDate());
		}
	});

	$(".hastooltip").each(function(){		
	    var theid = $(this).attr('id');
	    var thepath = '<?php echo $this->baseUrl('images/questionmark.png'); ?>';
		if($(this).attr('title') != "undefined" || $(this).attr('title') != ""){
			$('<a href="javascript: void(0);" class="qcontainer" id="q_'+theid+'"><img src="'+thepath+'" /></a>').insertAfter(this);
		    $("#q_"+theid).attr('title', $(this).attr('title')).addClass('qtooltip');
		}	    
	});
	$(".hastooltip_custom").each(function(){		
	    var theid = $(this).attr('id');
	    var thepath = '<?php echo $this->baseUrl('images/questionmark.png'); ?>';
		if($(this).attr('title') != "undefined" || $(this).attr('title') != ""){
			$("#tooltip_"+theid).html('<a href="javascript: void(0);" class="qcontainer" id="q_'+theid+'"><img src="'+thepath+'" /></a>').addClass('customtooltip');
		    $("#q_"+theid).attr('title', $(this).attr('title')).addClass('qtooltip');
		}	    
	}); 

	// $('.hastooltip').tipsy({fade: true, gravity: 'w', html: true, trigger: 'focus', offset: 15});
    $('.qtooltip, label:has(input#type-1), label:has(input#type-2)').tipsy({fade: true, gravity: 'w', html: true, trigger: 'hover', offset: -5});
    $(".hastooltip").attr('title','');
	
	$('#dialog').modal({
		keyboard: false,
		backdrop: 'static'
	});
	$('#dialog').modal('hide');
	
	$(".disablefield").each(function(){
		$(this).attr('readonly', true).attr('disabled', true);
	});
	
	$("#viewadminprofile, #viewpersonprofile").hide();
	
	// add farmer to group
	$('.addpopup').click(function(e){
		// $("#"+idparam).qtip("hide");
		e.preventDefault();
		var title = $(this).attr('rel');
		var href = $(this).attr('href');
		var formid = $(this).attr('formtitle');
		var posturl = $(this).attr('action');
		var successurl = $(this).attr('successurl');
		var submittext = $(this).attr('submittext'); 
		// alert(href);
		// popup title
		$(".modal-header h3").html(title);
		// load content
		$("#dialogcontent").html($("#dialogbody #loading").html());
		$("#dialogcontent").load(href);  	
		// then show it after the changes have been made
		$('#dialog').modal('toggle');
		
		// check for default submit button text
		if(!isEmptyString(submittext)){
			$("#new #save").html('<i class="icon-ok icon-white"></i> '+submittext);
		}
		
		// save dialog
		$('#save').on('click', function(e){
			// $('#dialog').modal('hide');
			if ($("#"+formid).valid() == true) {
				// disable buttons
				$(".modelcancel").hide();
				$(this).hide();
				// post form
				$.post(  
					posturl,  
					$("#"+formid).serialize(),  
					function(data){
						// alert(data); return false;
						var url = successurl;    
						$(location).attr('href',url);
					}  
				); // close the $.post
				$("#dialogcontent").hide(); 										
				$("#dialogbody #loading").show();
			}
		});
		// cancel model
		$(".modelcancel").on('click', function(e){
			$("#dialog").modal('hide');
		});		
		$('#dialog').on('hidden', function () {
			// location.reload(true);
			$(".dialog, body").css("overflow", "auto");
		});
		
		$(".dialog, body").css("overflow", "hidden");
		 
		return false;
	});
	
	$.validator.addClassRules("greaterthanzero", {
		greaterthanzero: true				
	});
	$.validator.addMethod("greaterthanzero", function(value, element) {				
		if(!isEmptyString(value) && parseFloat(value) <=0){
			return false;
		}
		return true;
	}, "Should be greater than zero");
	
	$.validator.addClassRules("inputrequired", {
		input_not_empty: true				
	});
	$.validator.addMethod("input_not_empty", function(value, element) {				
		if(isEmptyString(value)){
			return false;
		}
		return true;
	}, "Please enter a value");
	
	$.validator.addClassRules("selectrequired", {
		select_not_empty: true				
	});
	$.validator.addMethod("select_not_empty", function(value, element) {				
		if(isEmptyString(value)){
			return false;
		}
		return true;
	}, "Please select");
	
	// Add validation rules for number fields on each line
	$.validator.addClassRules("isnumber", {
		validate_number: true				
	});
	$.validator.addMethod("validate_number", function(value, element) {				
		if(!IsValidAmount(value)){
			return false;
		}
		return true;
	}, "Invalid Number");
	// add the validation for wholesale price to be less than retail price
	$.validator.addMethod("validnumber", function(value, element, params) { 
		if (IsValidAmount(value)) {
			return true; 
		}
		return false;        
	}, "Please enter a valid Phone Number");
	
	$.validator.addClassRules("isdecimal", {
		validate_decimal: true				
	});
	$.validator.addMethod("validate_decimal", function(value, element) {				
		if(!IsValidDecimal(value)){
			return false;
		}
		return true;
	}, "Invalid Size");
	
	$.validator.addClassRules("isamount", {
		validate_amount: true				
	});
	$.validator.addMethod("validate_amount", function(value, element) {				
		if(!IsValidAmount(value)){
			return false;
		}
		return true;
	}, "Invalid Amount");
	
	// Add validation rules for maximum characters for content
	$.validator.addClassRules("max50content", {
		validate_50_string: true				
	});
	$.validator.addMethod("validate_50_string", function(value, element) {				
		if(value.length > 50){
			return false;
		}
		return true;
	}, "Only a maximum of 50 Characters allowed!");
	
	$.validator.addClassRules("max255content", {
		validate_255_string: true				
	});
	$.validator.addMethod("validate_255_string", function(value, element) {				
		if(value.length > 255){
			return false;
		}
		return true;
	}, "Only a maximum of 255 Characters allowed!");
	
	// Add validation rules for maximum characters for content
	$.validator.addClassRules("strictalpha", {
		validate_strict_alpha: true				
	});
	$.validator.addMethod("validate_strict_alpha", function(value, element) {				
		return this.optional(element) || /^[a-zA-Z0-9-_]*$/i.test(value);
	}, "Only letters, digits, underscore and no space are allowed");
	
	// Add validation rules for maximum characters for content
	$.validator.addClassRules("endafterstart", {
		enddateafterstartdate: true				
	});
	
	$.validator.addMethod("validate_ug", function(value, element, params) { 
		if(isEmptyString(value)) {
			return true; 
		}
		if(!isEmptyString(value) && !isUgNumber(value)) {
			return false; 
		}
		return true;        
	}, "<?php echo $this->translate("globale_phonenumber_format"); ?>");
	$.validator.addMethod("validate_ke", function(value, element, params) { 
		if(isEmptyString(value)) {
			return true; 
		}
		if(!isEmptyString(value) && !isKeNumber(value)) {
			return false; 
		}
		return true;        
	}, "<?php echo $this->translate("globale_phonenumber_format_ke"); ?>");
	
	// validate captcha
	$.validator.addMethod("validatecode", function(value, element, params) {
		//alert('code is '+value); //alert('valid is '+$("#validcode").val());
		if ($("#code").val().toLowerCase() == $("#validcode").val().toLowerCase()) {
			return true; 
		}
		return false;        
	}, "Captcha Invalid! <br />Re-enter code or refresh for a new one");
	
	// function to validate the enddate being greater than the start date
	$.validator.addMethod("enddateafterstartdate", function(value, element) {            
		var startDate = $(".startdate").val();  
		if($.trim(value) == ""){
			return true;
		}
		if($.trim(startDate) == ""){
			return false;
		}
		return Date.parse(startDate) <= Date.parse(value);        
	}, "Please select an End Date after the Start Date");
	
	// delete rules
	$("#deleteline, .deleteline").click(function() {
		var message = '<label class="blockcontainer">Are you sure you want to delete this entry? <br /><br /> Click <b>OK</b> to confirm, and <b>Cancel</b> to ignore</label>';
		var custom_msg = $(this).attr('message');
		if(!isEmptyString(custom_msg) && custom_msg != 'undefined'){
			var message = '<label class="blockcontainer">'+custom_msg+' <br /><br /> Click <b>OK</b> to confirm, and <b>Cancel</b> to ignore</label>';
		}
		var url = $(this).attr('action');
		// alert(url);
		removeLine(message, url);
	});
	function removeLine(message, url) {
		bootbox.confirm(message, function(confirmed) {
			if(confirmed){
				window.location.href = url;					
			} else {
				return false;
			}
		});
	}
	
	$("a.confirm-dialog").click(function(e) {
		e.preventDefault();
		var message = '<label class="blockcontainer">Are you sure? <br /><br /> Click <b>OK</b> to confirm, and <b>Cancel</b> to ignore</label>';
		var custom_msg = $(this).attr('message');
		if(!isEmptyString(custom_msg) && custom_msg != 'undefined'){
			var message = '<label class="blockcontainer">'+custom_msg+' <br /><br /> Click <b>OK</b> to confirm, and <b>Cancel</b> to ignore</label>';
		}
		var url = $(this).attr('href');
		confirmDialog(message, url);
	});
	
	function confirmDialog(message, url) {
		bootbox.confirm(message, function(confirmed) {
			if(confirmed){
				window.location.href = url;					
			} else {
				bootbox.hideAll();
				return false;
			}
		});
	}
	
	$(".alert-dialog").click(function(e) {
		e.preventDefault();
		var message = '<label class="blockcontainer"></label>';
		var custom_msg = $(this).attr('message');
		var other_msg = $(this).attr('warning');
		if(other_msg != '' && other_msg != 'undefined'){
			custom_msg = other_msg;
		}
		if(!isEmptyString(custom_msg) && custom_msg != 'undefined'){
			var message = '<label class="blockcontainer">'+custom_msg+'</label>';
		}
		bootbox.alert(message); 
	});
	
	// hover and unhover upload icon
	$("#profileinfo, .profileinfo").hover(function(){
		$("#uploadlink").show();
	}, function() {
    	$("#uploadlink").hide();
	});
	
	// hover and unhover upload icon
	$("#signinfo").hover(function(){
		$("#signlink").show();
	}, function() {
    	$("#signlink").hide();
	});
	
	$('input, textarea').placeholder();
	
	// invite one person
	$("a.invitetrigger").click(function(){
		var id = $(this).attr('id');
		var userid = $("label."+id).html();
		var email = $("input."+id).val();
		var invitedby = $("label."+id).attr('title');
		if(isEmptyString(email)) {
			$("div#invite_"+userid+"_error").html('<div class="alert alert-error">Please enter email to invite</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		if(!isEmptyString(email) && !validateEmail(email)) {
			$("div#invite_"+userid+"_error").html('<div class="alert alert-error">Please enter a valid email</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		
		// check that email is provided
		if(!isEmptyString(email) && validateEmail(email)) {
			$("div#invite_"+userid+"_error").html('');
			$("span#inv_before_"+userid).hide(); 
			$("span#inv_after_"+userid).html($('#loading_'+userid).html()); 
			// post 
			$.post(  
				"<?php echo $this->baseUrl("profile/inviteone"); ?>", {id: userid, email: email},  
				function(data){
					// alert(data); exit();
					if(data.search("Success") != -1){								
						// reload parent on close				
						$("span#inv_after_"+userid).html(data);	
						$("span#inv_hide_"+userid).hide(); 			
					} else {
						var err = 'An error occured while inviting user. Try again later';
						$("span#inv_after_"+userid).html(data);
						$("#inv_before_"+userid).show();
						
					}
					// location.reload(true);
					$("span#inv_after_"+userid+" a").hide(); 
					$("div.alert-success").css({'background': 'url("<?php echo $this->baseUrl('images/tick.png'); ?>") no-repeat #FEF0B6 5px 8px'});
				}  
			); // close the $.post
		}
	});
	
	// invite farmer via phone
	$("a.pinvitetrigger").click(function(){
		var id = $(this).attr('id');
		var userid = $("label."+id).html();
		var phone = $("input."+id).val();
		var invitedby = $("label."+id).attr('title');
		if(isEmptyString(phone)) {
			$("div#pinvite_"+userid+"_error").html('<div class="alert alert-error">Please enter phone to invite</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		if(!isEmptyString(phone) && !IsValidAmount(phone)) {
			$("div#pinvite_"+userid+"_error").html('<div class="alert alert-error">Please enter a valid Phone</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		if(!isEmptyString(phone) && IsValidAmount(phone) && parseInt(phone.length) != 10) {
			$("div#pinvite_"+userid+"_error").html('<div class="alert alert-error">Please enter 10 Digits</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		if(!isEmptyString(phone) && IsValidAmount(phone) && parseInt(phone.length) == 10 && !isUgNumber(phone)) {
			$("div#pinvite_"+userid+"_error").html('<div class="alert alert-error"><?php echo $this->translate("globale_phonenumber_format"); ?></div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		
		// check that email is provided
		if(!isEmptyString(phone) && IsValidAmount(phone) && isUgNumber(phone)) {
			$("div#pinvite_"+userid+"_error").html('');
			$("span#pinv_before_"+userid).hide(); 
			$("span#pinv_after_"+userid).html($('#loading_'+userid).html()); 
			
			// post 
			$.post(  
				"<?php echo $this->baseUrl("profile/inviteonebyphone"); ?>", {id: userid, phone: phone},  
				function(data){
					// alert(data); return false;
					if(data.search("Success") != -1){								
						// reload parent on close				
						$("span#pinv_after_"+userid).html(data);	
						$("span#pinv_hide_"+userid).hide(); 			
					} else {
						var err = 'An error occured while inviting user. Try again later';
						$("span#pinv_after_"+userid).html(data);
						$("#pinv_before_"+userid).show();
						
					}
					// location.reload(true);
					$("span#pinv_after_"+userid+" a").hide(); 
					$("div.alert-success").css({'background': 'url("<?php echo $this->baseUrl('images/tick.png'); ?>") no-repeat #FEF0B6 5px 8px'});
				}  
			); // close the $.post
			
		}
	});
	
	// validate phone number on file
	$("a.validatetrigger").click(function(){
		var id = $(this).attr('id');
		var userid = $("label."+id).html();
		var code = $("input."+id).val();
		var successurl = $(this).attr('successurl');
		
		var validcode = true;
		var clength = code.length;
		if(isEmptyString(code) || (!isEmptyString(code) && clength < 6)) {
			$("div#validate_"+userid+"_error").html('<div class="alert alert-error">Please enter 6 digit code</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			validcode = false;
		}
		
		// check that email is provided
		if(validcode) {
			$("div#validate_"+userid+"_error").html('');
			$("span#phone_before_"+userid).hide(); 
			$("span#phone_after_"+userid+" a").show(); 
			var url = '<?php echo $this->baseUrl("profile/verifyphone"); ?>/userid/'+userid+'/code/'+code+'/successurl/'+successurl;
			// alert(confirmurl);
			window.location.href = url;
		}
	});
	
	$('.validate').keydown(function (event) {
	   var keycode = (event.keyCode ? event.keyCode : event.which);
		if (keycode == '13') {
			$('.validatetrigger').click();
		}
	});
	
	// refresh captcha
	$('img#refresh').click(function() { 			
		change_captcha();
	});
	
	$('img#refresh').click();
	function change_captcha(){
		$("#code").val(''); 
		$.get("<?php echo $this->baseUrl('signup/getcaptcha'); ?>", 
			// parameters for the request along with a cachebuster to stop IE from caching the request
			{cachebuster: new Date().getTime()}, 			   
			function(data){			
				//alert(data);
				$("#validcode").val(data); 
				$("#captcha").html(data).css({'font-size':'20px'});			
			}
		);
	}
	
	// subscribe for newsletter
	$("#newletter_trigger").click(function(){
		var email = $("#subscribe_email").val();
		if(isEmptyString(email)) {
			$("div#process_error").html('<div class="alert alert-error">Please enter email to subscribe</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		if(!isEmptyString(email) && !validateEmail(email)) {
			$("div#process_error").html('<div class="alert alert-error">Please enter a valid email</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
		}
		// check that email is provided
		if(!isEmptyString(email) && validateEmail(email)) {
			var url = '<?php echo $this->baseUrl("newsletter/processadd"); ?>/email/'+email;
			// alert(confirmurl);
			window.location.href = url;
		}
	});
	
	$('#subscribe_email').keydown(function (event) {
	   var keycode = (event.keyCode ? event.keyCode : event.which);
		if (keycode == '13') {
			$('#newletter_trigger').click();
		}
    });
	
	// change password
	$('.changepassword').click(function(e){
		// $("#"+idparam).qtip("hide");
		e.preventDefault();
		
		// popup title
		$(".modal-header h3").html($(this).attr('rel'));
		// load content
		$("#dialogcontent").html($("#dialogbody #loading").html());
		$("#dialogcontent").load($(this).attr('href'));  	
		// then show it after the changes have been made
		$('#dialog').modal('toggle');

		// save dialog
		$('#save').on('click', function(e){
			// $('#dialog').modal('hide');
			if ($("#indexform").valid() == true) {
				bootbox.confirm('<label class="blockcontainer">Are you sure you want to change your Password? <br /><br />Click <b>OK</b> to proceed, and <b>Cancel</b> to ignore</label>', function(confirmed) {
					if(confirmed){
						// disable buttons
						$(".modelcancel").hide();
						$(this).hide();
						// post form
						$.post(  
							"<?php echo $this->baseUrl("profile/processchangepassword"); ?>",  
							$("#indexform").serialize(),  
							function(data){
								// alert(data);
								location.reload(true);
							}  
						); // close the $.post
						$("#dialogcontent").hide(); 										
						$("#dialogbody #loading").show();
					} else {
						return false;
					}
				});
			}
		});
		// cancel model
		$(".modelcancel").on('click', function(e){
			$("#dialog").modal('hide');
		});		
		$('#dialog').on('hidden', function () {
			// location.reload(true);
			$(".dialog, body").css("overflow", "auto");
		});
		$(".dialog, body").css("overflow", "hidden");
		 
		return false;
	});
	
	$('.radio.btn-group label').addClass('btn');
    $(".btn-group label:not(.active)").click(function() {
        var label = $(this);
        var input = $('#' + label.attr('for'));

        if (!input.prop('checked')) {
            label.closest('.btn-group').find("label").removeClass('active btn-success btn-danger btn-primary');
            if (input.val() == '') {
                label.addClass('active btn-primary');
            } else if (input.val() == 0) {
                label.addClass('active btn-danger');
            } else {
                label.addClass('active btn-success');
            }
            input.prop('checked', true);
        }
    });
    $(".btn-group input[checked=checked]").each(function() {
        if ($(this).val() == '') {
            $("label[for=" + $(this).attr('id') + "]").addClass('active btn-primary');
        } else if ($(this).val() == 0) {
            $("label[for=" + $(this).attr('id') + "]").addClass('active btn-danger');
        } else {
            $("label[for=" + $(this).attr('id') + "]").addClass('active btn-success');
        }
    });
	
	$(function(){
		$(".search").keyup(function(e){
			var keyCode = e.keyCode || e.which;
			if(keyCode !== 38 && keyCode !== 40 && keyCode !== 13){
				var inputSearch = $(this).val();
				var type = '<?php echo $usertype; ?>';
				var grp = '<?php echo $groupid; ?>';
				var country = $(this).attr('country');
				// alert('country is '+country);
				var isreport = 0;
				if($(this).hasClass('reportsearch')){
					var isreport = 1;
				}
				// alert(grp);
				// var dataString = 'searchword='+ inputSearch;
				var searchurl = '<?php echo $this->baseUrl('resource/search'); ?>/searchword/'+inputSearch+'/type/'+type+'/grp/'+grp+'/country/'+country;
				var gotourl = '';
				if(isreport == '1'){
					var gotourl = $(this).attr('url');
					var searchurl = '<?php echo $this->baseUrl('resource/search'); ?>/searchword/'+inputSearch+'/type/'+type+'/grp/'+grp+'/country/'+country+'/reporturl/'+gotourl;
				}
				if(!isEmptyString(inputSearch) && inputSearch.length > 2){
					$.ajax({
						type: "POST",
						url: searchurl,
						cache: false,
						success: function(data) {
							// alert(data);
							$("#divResult").html(data).show().css({'display':'block','padding':'0'});
							$('li.display_box:first').addClass('selected');
							
							$("li.display_box").live("mouseover mouseout", function(e) {
							  if(e.type == "mouseover") {
								$(this).addClass("selected");
							  } else {
								$(this).removeClass("selected");
							  }
							});
						}
					});
				}
				var imageurl = '<?php echo $this->baseUrl('images/farmisloader.gif'); ?>';
				if(!isEmptyString(inputSearch)){
					$("#divResult").html("<a id='loading' class='xhidden' style='text-align:center; display:block;'><img style='width:22px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block','padding':'10px 0'});
				} else {
					$("#divResult").html("");
				}
				
			} else {
				if( $('li.display_box').length > 0) {
					var currentLi = $('li.display_box.selected').first();
					/*if(currentLi){
						// alert($(currentLi).html());
					}
					if (e.keyCode == 40) {  
						Navigate(1);
					}
					if(e.keyCode==38){
						Navigate(-1);
					}

					var Navigate = function(diff) {
						displayBoxIndex += diff;
						var oBoxCollection = $("li.display_box");
						if (displayBoxIndex >= oBoxCollection.length)
							 displayBoxIndex = 0;
						if (displayBoxIndex < 0)
							 displayBoxIndex = oBoxCollection.length - 1;
						var cssClass = "selected";
						oBoxCollection.removeClass(cssClass).eq(displayBoxIndex).addClass(cssClass);
					}*/
				}
			}
			return false;    
		});
		$("#divResult").live("click",function(e){ 
			  var $clicked = $(e.target);
			  var $name = $clicked.find('.name').html();
			  var decoded = $("<div/>").html($name).text();
			  $('#inputSearch').val(decoded);
			  
		});
		$(document).live("click", function(e) { 
			  var $clicked = $(e.target);
			  if (! $clicked.hasClass("search")){
			  	$("#divResult").fadeOut(); 
			  }
		});
		$(".display_box").live("click",function(e){ 
			 var url = $(this).attr('url');
			 var isreport = $(this).attr('isreport');
			 var reporturl = $(this).attr('reporturl');
			 if(isreport == '1'){
				 url = reporturl;
			 }
			 // alert(url);
			 window.location.href = url;
		});
		
		$('#inputSearch').click(function(){
			  $("#divResult").fadeIn();
		});
	});
	
	// when a user clicks add new display the first hidden firm which is not shown
	$(".addline").click(function() {
		showNewLine($(this).attr('id'));
	});		
	function showNewLine(type) {
		$(".hidden_row_"+type+":first").removeClass("hidden_row_"+type).addClass("visible_row_"+type);	
		
		// remove disabled attr from the fields
		$("tr.visible_row_"+type+" input").attr("disabled", false);
		$("tr.visible_row_"+type+" select").attr("disabled", false);	
			
		//if the maximum no of rows is added, hide the link to add another row
		if ($("tr.visible_row_"+type+"").size() == 10) {
			$("#"+type).hide();	
		} else {
			$("#"+type).show();	
		}				
	}
	
	// delete rules
	$(".removeline").click(function() {
		removeRow($(this).attr('id'), $(this).attr('rel'));
	});
	function removeRow(lineid, type) {
		var row_to_hide = lineid;
		// confirm popup
		bootbox.confirm("Are you sure you want to delete this entry? <br /><br /> Click <b>'OK'</b> to confirm, and <b>'Cancel'</b> to ignore", function(confirmed) {
			if(confirmed){
				$("tr.visible_row_"+type).has('a#'+row_to_hide).addClass("hidden_row_"+type).removeClass("visible_row_"+type);
				// $("input, select").attr("disabled", true);	
				$("tr."+row_to_hide+" input").val('').attr("disabled", true);
				$("tr."+row_to_hide+" select").val('').attr("disabled", true);	
				//if the maximum no of rows is added, hide the link to add another row
				if ($("tr.visible_row_"+type).size() == 10) {
					$("#"+type).hide();		
				} else {
					$("#"+type).show();	
				}	
			} else {
				return false;
			}
		});
	}
	
	var screenwidth = window.screen.availWidth;
	var screenheight = window.screen.availHeight;
	// alert(screenwidth+' - '+screenheight);
	
	$('div.controls, .nullifempty').each(function() {
		var html = $(this).html();
		if(isEmptyString(html)){
			$(this).html('--');
		}
	});
	
	$("a.gonowhere").each(function(){
		$(this).attr('href', 'javascript: void(0)');
	});
	
	$("#confirmemail").click(function(){
		var code = $("#code").val();
		var id = $(this).attr('userid');
		var ref = $(this).attr('ref');
		
		var validcode = true;
		var clength = code.length;
		if(isEmptyString(code) || (!isEmptyString(code) && clength < 6)) {
			$("div#code_email_error").html('<div class="alert alert-error">Please enter 6 digit code</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			validcode = false;
		}
		// check that email is provided
		if(validcode) {
			$("div#code_email_error").html('');
			var url = '<?php echo $this->baseUrl("profile/changeemail"); ?>/id/'+id+'/actkey/'+code+'/ref/'+ref;
			// alert(url);
			window.location.href = url;
		}
	});
	
	$("#confirmphone").click(function(){
		var code = $("#code").val();
		var id = $(this).attr('userid');
		var ref = $(this).attr('ref');
		
		var validcode = true;
		var clength = code.length;
		if(isEmptyString(code) || (!isEmptyString(code) && clength < 6)) {
			$("div#code_phone_error").html('<div class="alert alert-error">Please enter 6 digit code</div>');
			$("div.alert-error").css({'background': 'url("<?php echo $this->baseUrl('images/cross.png'); ?>") no-repeat #EDDBE3 5px 8px'});
			validcode = false;
		}
		// check that email is provided
		if(validcode) {
			$("div#code_phone_error").html('');
			var url = '<?php echo $this->baseUrl("profile/changephone"); ?>/id/'+id+'/actkey/'+code+'/ref/'+ref;
			// alert(url);
			window.location.href = url;
		}
	});
	
	$('.changesetting').click(function(){
		var userid = $(this).attr('userid');
		var field = $(this).attr('field');
		var value = $(this).val();
		// alert(userid+' - '+field+' - '+value);
		var url = '<?php echo $this->baseUrl("profile/changesettings"); ?>/userid/'+userid+'/field/'+field+'/value/'+value; 
		// alert(url);
		$.post( 
			url,  
			function(data){
				// alert(data); return false;
				$("#"+field+"_wait").addClass('hidden');
			}  
		); // close the $.post
		$("#"+field+"_wait").removeClass('hidden');								
	});
	
	// default search text on chosen dropdown
	$(".chosen-container .chosen-search input").attr('placeholder', 'Type to search');
	
	function numberWithCommas(x) {
		return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
	}
});
//Use window.load and not document.ready for effective equal heights
$(window).load(function() {
	//Make columns equal
	equalHeight($("#leftcolumn, #centercolumn"));
	// $("#contentcolumn, #centercolumn").css({'height':'auto'});
	
	$('.ui-datepicker-div').css({'z-index':'1500'});
	
	<?php if($request->print == 1){ ?>
		$("#headercontainer, #leftcolumn, .footer, #blankrow, .crumbs").remove().hide();
		$(".printpage").html($("#printer_page_action_buttons").html());
		$("#centercolumn").css({'border-left':'none'});
	<?php } ?>
}); 
</script>
</head>
<?php 
	$thecontroller = $request->getControllerName();
	$theaction = $request->getActionName();
	$publiccontrollers = array("index", "signup","aboutus","howitworks","benefits","news","help","user","tour","forum","faqs","testimonials","billing"); 
	if(isEmptyString($userid)){
		$publiccontrollers[] = 'contactus';
	}
	if(($thecontroller == 'index' && $theaction == 'accessdenied')){
		unset($publiccontrollers['0']);
	}
	
	$bodyclass = '';
	$bodyclassonly = '';
	$isInnerPage = false;
	if(in_array($thecontroller, $publiccontrollers)){
		$bodyclass = ' class="publicbody"';
		$bodyclassonly = ' publicbody';
	} else {
		$isInnerPage = true;
	}
	
?>
<body data-spy="scroll" data-target=".subnav" data-offset="50"<?php echo $bodyclass; ?>>

<!--Header Container-->
<div class="navbar <?php echo !$isInnerPage ? 'navbar-fixed-top' : ''; ?> margin0 makerelative" id="headercontainer">
    <div class="navbar-inner header" id="headertop">
		<?php require_once APPLICATION_PATH.'/views/scripts/index/header.phtml'; ?>
        <?php if(isUganda()){ ?>
			<?php if(!$isloggedin){ ?>
            <span class="flag leftflag"><img src="<?php echo $this->baseUrl('images/uganda_left.png'); ?>" /></span>
            <span class="flag rightflag"><img src="<?php echo $this->baseUrl('images/uganda_right.png'); ?>" /></span>
            <?php } ?>
        <?php } ?>
        <?php if(isKenya()){ ?>
            <?php if(!$isloggedin){ ?>
                <span class="flag leftflag"><img src="<?php echo $this->baseUrl('images/kenya_left.png'); ?>" /></span>
            <?php } ?>   
            <span class="flag rightflag"><img src="<?php echo $this->baseUrl('images/kenya_right.png'); ?>" /></span>
        <?php } ?>
    </div>
</div>
<!--Main Container-->
<div class="container prettyprint linenums" id="maincontainer">
	<?php require_once APPLICATION_PATH.'/views/scripts/index/navigation.phtml'; ?>	
	<div class="row-fluid" id="contentwrapper">
		<div id="contentcolumn">
        	<?php if($isloggedin && $isInnerPage){ ?>
        		<?php require_once APPLICATION_PATH.'/views/scripts/index/breadcrumb.phtml'; ?>	
            <?php } ?>
			<?php echo $this->layout()->content; ?>
       	</div>
    </div>
</div>
<footer class="footer well <?php echo $bodyclassonly; ?>"><?php require_once APPLICATION_PATH.'/views/scripts/index/footer.phtml'; ?></footer>
<div class="modal hide" id="dialog">
    <div class="modal-header">
    	<button type="button btn" class="close" data-dismiss="modal">&times;</button>
    	<h3><?php echo $this->translate("person_pagetitle_newrelative"); ?></h3>
    </div>
	<div class='modal-body' id="dialogbody">
        <a id="loading" class="hidden"><img style="margin-left:250px;" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
        <div id="dialogcontent"></div>
	</div>
	<div class="modal-footer">
    	<div id="new">
		<a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_cancel'); ?>"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
		<button type="submit" class="btn btn-primary" id="save" onclick="javascript:doNothing();"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save'); ?></button>
        </div>
        <div id="view" class="hide">
            <a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_close'); ?>"><i class="icon-remove"></i> <?php echo $this->translate('global_button_close'); ?></a>
            <button type="submit" class="btn btn-primary" id="save" onclick="javascript:doNothing();"><i class="icon-pencil icon-white"></i> <?php echo $this->translate('global_button_edit'); ?></button>
        </div>
	</div>
</div>
<a id="loading" class="hidden"><img style="margin-left:250px;" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
<a id="wait" class="hidden blocked centeralign"><img src="<?php echo $this->baseUrl('images/wait.gif'); ?>" /></a>
<div class="hidden" id="printer_page_action_buttons"><a title="Close Window" onClick="window.close()" > <img src="<?php echo $this->baseUrl('images/close.png'); ?>" width="16" height="16" alt="Close Window"> </a> &nbsp;&nbsp; <a title="Print" onClick="window.print()" > <img src="<?php echo $this->baseUrl('images/printer.png'); ?>" width="16" height="16" alt="Print"> </a> </div>
</body>
</html>
<?php //if(false){ ?>
<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
var sc_project=9269846; 
var sc_invisible=1; 
var sc_security="5ab010d0"; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="hits counter"
href="http://statcounter.com/free-hit-counter/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/9269846/0/5ab010d0/1/"
alt="hits counter"></a></div></noscript>-->
<!-- End of StatCounter Code for Default Guide -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44275519-2', 'farmis.ug');
  ga('send', 'pageview');

</script>

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
var sc_project=9269846; 
var sc_invisible=1; 
var sc_security="5ab010d0"; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>
<noscript><div class="statcounter"><a title="web analytics"
href="http://statcounter.com/" target="_blank"><img
class="statcounter"
src="http://c.statcounter.com/9269846/0/5ab010d0/1/"
alt="web analytics"></a></div></noscript>
<!-- End of StatCounter Code for Default Guide -->
<?php // } ?>