<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$message = new Message(); 
	
	$posturl = $this->baseUrl("resource/processbulksms");
	
	$user = new UserAccount();
	$user->populate($userid);
		
	$contents = ''; $farmgroupid = ''; $userids = array();
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){
		$formvalues  = $session->getVar(FORM_VALUES);
		$contents = $formvalues['contents']; $farmgroupid = $formvalues['farmgroupid']; $userids = array();
		// debugMessage($formvalues);
	}
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya() || $user->isKenyan()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country); 
	
	$title = "Bulk SMS";
	$this->headTitle($title); 
?>
<script>
$(document).ready(function(){
	$("#bulksmsform").validate({		
		// define the validation rules one field at a time
		rules: {
			farmgroupid: "required",
			contents: {
				required: true,
				maxlength: 159
			}
		}, 
		// the messages for each of the fields being validated
		messages: {				
			farmgroupid: "<?php echo $this->translate("farmer_farmgroup_error"); ?>",
			contents: {
				required: "<?php echo $this->translate("message_contents_error"); ?>",
				maxlength: "Only up to 159 characters allowed"
			}
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					error.appendTo("#"+element.attr("name")+"_error");
					break;
			}			
		}
	});
	
	disableContainerByID('selectfarmers');
	enableContainerByID('nofarmer');
	
	$('#type-2').click();
	$("#farmercount").html("");
	
	// chained select to load the subcounties for a county
	$('#farmgroupid').selectChain({
		target: $('#farmerids'),
		url: '<?php echo $this->baseUrl('profile/selectchain/'.SELECT_CHAIN_TYPE.'/farmgroup_farmers_phoneonly/country/'.$country)?>',
		data: 'currentvalue=',
		type: 'get'
	});
	$('#farmgroupid').change(function() {
		$("#waitimg").show();
		$("#farmercount").html("Loading Phone List...");
		var id = $(this).val();
		if(!isEmptyString(id)){
			enableContainerByID('selectfarmers');
			disableContainerByID('nofarmer');
			$('#type-2').click();
		} else {
			disableContainerByID('selectfarmers');
			enableContainerByID('nofarmer');
		}
	});		
	$('#farmerids').change(function() {
		$(this).trigger("liszt:updated");
		var farmers = parseInt($('option', this).size());
		if(farmers > 1){
			farmers = farmers - 1;
			$("#farmercount").html("Up to <b>"+farmers+"</b> Farmers with Phone numbers in List");
		} else {
			$("#farmercount").html("No Farmers available in current selection");
		}
		$("#waitimg").hide();
	});
	
	<?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
		$('#farmgroupid').change();
	<?php } ?>
	
	var characters = 159;
	$("#balance").append(characters);
	$("#contents").keyup(function(){
		if($(this).val().length > characters){
			$(this).val($(this).val().substr(0, characters));
		}
		var remaining = characters -  $(this).val().length;
		$("#balance").html(remaining);
		if(remaining <= 10){
			$("#balance").css("color","red");
		} else {
			$("#balance").css("color","black");
		}
	});
	$("#contents").trigger("keyup");
	
	// confirm sending message
	$('#sendmessage').click(function(e) {
		if ($("#bulksmsform").valid() == true) {
			e.preventDefault();
			bootbox.confirm("Are you sure you want to Send this Message? <br /><br /> Click <b>'OK'</b> to confirm, and <b>'Cancel'</b> to ignore", function(confirmed) {
				if(confirmed){
					$("#bulksmsform").submit();
				} else {
					return false;
				}
			});
		}
	});
});
</script>
<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn" class="clearfix">
        <div class="widgetsection" style="min-height:625px; height:auto;">
            <h3 style="color:#282727;"><?php echo $title; ?></h3>
            <div style="margin-top:10px;">
               <form id="bulksmsform" action="<?php echo $posturl; ?>" method="post">
               <table class="table">
                   <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>                   
                       <tr>
                            <td colspan="2"><div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div></td>
                       </tr>
                   <?php } ?>
                   <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                        <tr>
                        	<td colspan="2"><div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
                        </tr>
                   <?php } ?>
                   <?php if(!isEmptyString($session->getVar("custommessage"))){ ?>
                        <tr>
                        	<td colspan="2"><div style="clear:both;" class="alert alert-info clear"><?php echo $session->getVar("custommessage"); ?></div></td>
                        </tr>
                   <?php } ?>
                   <tr>
                        <td width="20%"><label class="control-label">Sender: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                        <td>FARMIS</td>
                   </tr>
                    <tr>
                        <td><label class="control-label"><?php echo $this->translate("farmer_dna_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                        <td>
                            <?php if(isEmptyString($user->getFarmGroupID())) { ?>
                                <?php
                                    $groupdropdown = new Zend_Form_Element_Select('farmgroupid',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Groups', '0'=> 'Individual Farmers'), getAllFarmGroups('', $session->getVar('country'))),	
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('width250', 'hastooltip'),
                                                            'title' => $this->translate("farmer_farmgroupid_tooltip")
                                                        )
                                                    );
                                    $groupdropdown->setValue($farmgroupid); 
                                    echo $groupdropdown->render(); 
                               ?>
                            <?php } else { ?>
                                <?php echo $user->getFarmGroup()->getName(); ?><input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $user->getFarmGroupID(); ?>" />
                            <?php } ?>
                            <div id="farmgroupid_error"></div>
                        </td>
                   </tr>
                   <tr>
                        <td><label class="control-label"><?php echo $this->translate("message_recipient_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label><span class="pagedescription" style="text-align:right; display:block;">(Only farmers with Phones apply)</span>
                        </td>
                        <td>
                        	<div id="nofarmer">Select a Farm Group to filter Reciepients</div>
							<div id="selectfarmers">
								<?php 
									 $users = array();
									 $list = array('2'=>'Select Farmers (maximum 50 per session)',);
									 $typeradio = new Zend_Form_Element_Radio('type',
												  array(
														  'multiOptions' => $list, 
														  'view' => new Zend_View(),
														  'disableLoadDefaultDecorators' => true,
														  'separator' => '&nbsp;&nbsp;&nbsp;&nbsp;',
														  'decorators' => array('ViewHelper',
																			  array('HtmlTag', array('tag' => 'div', 'class' => array('inline', 'radio', 'zendradio'))) // use a sorrounding DIV with classes which are copied to the label by JQuery
																		  )
												  )
										  );
										  $typeradio->setValue('');
										  echo $typeradio->render();
								  ?>
                                  	<div id="farmerlist" style="margin-top:15px;">
										  <?php
                                              $listdropdown = new Zend_Form_Element_Multiselect('farmerids',
                                                      array(
                                                              'multiOptions' => $users,
                                                              'view' => new Zend_View(),
                                                              'decorators' => array(array('ViewHelper')),
                                                              'class' => array('chzn-select','multipleselect','span7', 'hastooltip_custom'),
                                                              'title' => $this->translate("farmer_activitytypes_tooltip")
                                                      )
                                              );
                                              
                                              $listdropdown->setValue('');
                                              $listdropdown->setAttrib("data-placeholder", 'Start typing farmers in category');
                                              echo $listdropdown->render();
                                          ?><span id="tooltip_farmerids"></span>
                              		</div>
                              </div>
                              <img class="hidden" id="waitimg" src="<?php echo $this->baseUrl('images/ui-anim_basic_16x16.gif'); ?>" />
                              <div id="farmercount" class="pagedescription" style="margin-top:10px; display:block;"></div>
                              <div id="type_error"></div><div id="farmerids_error"></div>
						</td>
                   </tr>
                   <tr>
                        <td><label class="control-label"><?php echo $this->translate("message_contents_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                        <td><textarea class="expanding hastooltip" name="contents" id="contents" style="width:240px; min-height:75px;" title="<?php echo $this->translate("message_contents_tooltip"); ?>"><?php echo $contents; ?></textarea>
                        <span class="blocked">Chars Left: &nbsp;<label id="balance"></label></span>
                        <div id="contents_error"></div></td>
                   </tr>
                   <tr>		
                   		<td></td>                    
                        <td>
                            <a href="<?php echo $this->baseUrl('resource'); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <button type="button" class="btn btn-primary savethenview" id="sendmessage" title="<?php echo $this->translate('message_button_sendmessage'); ?>"><i class="icon-ok icon-white"></i> <?php echo $this->translate('message_button_sendmessage'); ?></button>
                        </td>
                   </tr>
               </table> 
               </form>   
            </div>
        </div>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
