<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	$theid = decode($request->id);
	if(isEmptyString($theid)){
		$theid = $userid;
	}
	
	$user->populate($theid);
	
	$posturl = $this->baseUrl("mobile/processgps");
	$title = "Find GPS Location";
?>
<?php require APPLICATION_PATH."/views/scripts/mobile/mobileincludes.phtml"; ?>
<script src="<?php echo $this->serverUrl($this->baseUrl('assets/js/geoPosition.js')); ?>"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
	// initialise the google map
	function initialiseMap(){
		var myOptions = {
			  zoom: 14,
			  mapTypeControl: true,
			  mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
			  navigationControl: true,
			  navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
			  mapTypeId: google.maps.MapTypeId.ROADMAP      
			}        
		map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	}
	function initialise() {
		if(geoPosition.init()){
			document.getElementById('current').innerHTML="Receiving location... please wait...";
			geoPosition.getCurrentPosition(
				showPosition,
				function(){
					document.getElementById('current').innerHTML="Couldn't get location"
				},
				{maximumAge:60000, timeout:10000, enableHighAccuracy:true}
			);
		} else {
			document.getElementById('current').innerHTML="Your Browser is not supported for this function";
		}
	}

	function showPosition(p){
		var latitude = parseFloat(p.coords.latitude);
		latitude = latitude.toFixed(6);
		
		var longitude = parseFloat(p.coords.longitude);
		longitude = longitude.toFixed(6);
		
		$("#lat").val(latitude);
		$("#lng").val(longitude);
		if(!isEmptyString(latitude) && !isEmptyString(longitude)){
			$("#hasgps").val(latitude+','+longitude);
		}
		document.getElementById('current').innerHTML=" Latitude = "+latitude+ " <br />Longitude = "+longitude;
		var pos=new google.maps.LatLng(latitude, longitude);
		map.setCenter(pos);
		map.setZoom(18);

		var infowindow = new google.maps.InfoWindow({
			content: "<strong>Farmer's Location</strong>"
		});

		var marker = new google.maps.Marker({
			position: pos,
			map: map,
			title:"You are here"
		});

		google.maps.event.addListener(marker, 'click', function() {
		  infowindow.open(map,marker);
		});
	}             
</script> 
<script>
	$(document).ready(function() {
		initialiseMap();
		initialise();
		
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				hasgps: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				hasgps: "No location detected"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
	});
</script>
<style>
 #title {background-color:#e22640;padding:5px;}
                #current {font-size:10pt;padding:5px;}
</style>
<body>
<div class="container-fluid viewpage" id="view_farmer">
    <div class="row-fluid">
    	<h4><?php echo $title; ?></h4>
    </div>
    <form class="form-horizontal clearfix" id="indexform" action="<?php echo $posturl; ?>" method="post" style="padding-bottom:25px;">
        <div class="row-fluid control-group well actions" id="topactions">
            <a class="btn" href="<?php echo $this->baseUrl('mobile/home'); ?>"><i class="icon-home"></i> Home</a>
            <a href="<?php echo $this->referer; ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
            <a href="<?php echo $this->baseUrl('mobile/gps/id/'.encode($user->getID())); ?>" class="btn"><i class="icon-refresh"></i> Reload</a>
            <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save')." Position"; ?></button>
            <input type="hidden" name="entityname" value="Farmer" />
            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
            <input type="hidden" id="hasgps" name="hasgps" value="" />
            <input type="hidden" id="lat" name="lat" value="" />
            <input type="hidden" id="lng" name="lng" value="" />
            <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('mobile/view/id/'.encode($user->getID()))); ?>" />
            <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('mobile/gps/id/'.encode($user->getID()))); ?>" />
            <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
        </div>
        <div class="control-group">
        	<div id="hasgps_error"></div>
        </div>
        <div class="row-fluid">
          <div id="current">Initializing...</div>
          <div id="map_canvas" class="span12" style="height:400px; width:100%; margin-left:0;"></div>
        </div>
    </form>
</div>
</body>
</html>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>