<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Farmer Directory";	
	$this->headTitle($title);
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	$countryreq = strtolower($request->country); 
	
	$searchnames = '';
	if(!isEmptyString($request->firstname)){
		$searchnames .= $request->firstname;
	}
	if(!isEmptyString($request->lastname)){
		$searchnames .= " ".$request->lastname;
	}
	
	if (!isEmptyString($request->letter)){
		$searchnames .= "Browse By: <b>".strtoupper($request->letter)."</b>";
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.othernames","u.firstname","u.lastname","u.othernames","u.username","u.email","u.phone","u.phone2","u.refno","u.regno"));
	$paginate->setFilterColumns(array("u.gender","u.locationid","u.farmgroupid"));
	// $paginate->setDefaultSortBy("u.datecreated");	
	// $paginate->setDefaultSortOrder("DESC");
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE u.id <> '' ";
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (u.`firstname` LIKE '".$request->letter."%' OR u.`lastname` LIKE '".$request->letter."%' ";
	}
	
	$customwhere = "";
	if(!isEmptyString($request->searchterm)){
		$customwhere = " OR CONCAT_WS (' ', u.firstname, u.lastname) LIKE '%" .trim($request->searchterm). "%' OR CONCAT_WS (' ', u.lastname, u.firstname) LIKE '%" .trim($request->searchterm). "%'  ";
	}
	
	$addfarmerurl = $this->baseUrl('mobile/farmer/country/'.$country); 
	$listurl = $this->baseUrl('mobile/list');
	if(!isEmptyString($request->country)){
		$listurl = $this->baseUrl('mobile/list/country/'.$country); 
	}
	$farmgroup = new FarmGroup();
	$groupid = trim($request->farmgroupid);
	$groupstring = ""; $dnastring = "";
	if(!isEmptyString($groupid)){
		if($groupid == 0){
			$where_query .= " AND (u.`farmgroupid` IS NULL) ";
		} else {
			$where_query .= " AND (u.`farmgroupid` = '".$groupid."') ";
		}
		$farmgroup->populate($groupid);
		$groupstring = "<span class='namelabel'> [".$farmgroup->getName()."]</span>";
		$dnastring = ' [from '.$farmgroup->getName().']';
		$listurl = $this->baseUrl('mobile/list/farmgroupid/'.$groupid);
		if(!isEmptyString($request->country)){
			$listurl = $this->baseUrl('mobile/list/farmgroupid/'.$groupid.'/country/'.$country); 
		}
		$addfarmerurl = $this->baseUrl('mobile/farmer/farmgroupid/'.$farmgroup->getID().'/country/'.$country);
	}
	
	$locationstring = '';
	$locationid = $request->locationid;
	if(!isEmptyString($locationid)){
		$where_query .= " AND (u.`locationid` = '".$locationid."') ";
		$district = new Location();
		$district->populate($locationid);
		$locationstring = ' [from '.$district->getName().']';
	}
	
	$subgroup = $request->subgroupid;
	if(!isEmptyString($subgroup)){
		$where_query .= " AND (u.`subgroupid` = '".$subgroup."') ";
	}
	
	$profiledby = $request->profiledby;
	$currentprofiler = '';
	if(!isEmptyString($profiledby)){
		$profiler = new UserAccount();
		$profiler->populate($profiledby);
		$currentprofiler = $profiler->getName();
	}
	if($loggedinuser->isDataClerk()){
		$profiledby = $loggedinuser->getID();
		$request->setParam('profiledby', $profiledby);
		$currentprofiler = $loggedinuser->getName();
	}
	if(!isEmptyString($profiledby) || $loggedinuser->isDataClerk()){
		$where_query .= " AND (u.`createdby` = '".$profiledby."') ";
		$searchnames .= 'Farmers Profiled By '.$currentprofiler;
	}
	
	$startdate = $request->getParam('startdate');
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
	}
	
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) >= TO_DAYS('".$startdate."')) ";
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) <= TO_DAYS('".$enddate."')) ";
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
	}
	if($order == 1){
		$order_query = " ORDER BY u.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY u.firstname ASC ";
	}
	if($order == 3){
		$order_query = " ORDER BY u.lastname ASC ";
	}
	if($order == 4){
		$order_query = " ORDER BY u.datecreated ASC ";
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT u.id as id, u.id as userid, u.farmgroupid as fmgroupid, u.firstname, u.lastname, u.othernames, u.subgroupid, u.gender, u.isactive, u.locationid as districtid, u.email as email, u.email as femail, u.refno, u.regno as regno, u.phone as phone, u.regdate as fregdate, u.profilephoto as profilephoto, fg.orgname as orgname, fgs.orgname as sorgname, l.name as district, u.isphoneinvited, u.hasacceptedinvite, u.isinvited, u.selfregistered, concat(ua.firstname, ' ', ua.lastname) as addedby, u.datecreated as dateadded FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type = 2 AND u.country = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere)." GROUP BY u.id ".$order_query;
	
	// debugMessage($all_results_query); // exit();
	// determine total number of records found
	$conn = Doctrine_Manager::connection(); 
	$count_query = "SELECT count(u.id) as total FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type = 2 AND u.country = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere);
	$total = $conn->fetchOne($count_query);
	$paginate->setItemCount($total); // debugMessage('>> '.$total);	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
?>
<?php require APPLICATION_PATH."/views/scripts/mobile/mobileincludes.phtml"; ?>
<body>
<script>
$(document).ready(function() {
	// set hidden field for the alphabet and submit the form
	$(".alphabet").click(function(){
		var letter = $(this).attr('id');
		// alert(letter);
		$('#letter').val(letter);
		$("#listform").submit();
	});
	
	datepickerOpts.dateFormat = '<?php echo $config->dateandtime->javascriptmediumformat; ?>'; 
	$("#startdate, #enddate").datepicker(datepickerOpts); 
	
	<?php if($loggedinuser->isDataClerk()){?>
		$('#profiledby').attr('readonly', true).attr('disabled', true);
	<?php } ?>
}); 
</script>
<div class="container-fluid viewpage" id="list_farmer">
  <h4><?php echo $title; ?></h4>
  <form action="<?php echo $this->baseUrl("mobile/listsearch"); ?>" method="get" id="listform" class="form-search">
	  <?php if($sessionhaserror) { ?>
      <div class="row-fluid">
        <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar("custommessage")) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("custommessage"); ?></div>
      </div>
      <?php } ?>
      <ul class="peoplegroup">
            <li><a class="btn" href="<?php echo $this->baseUrl('mobile/home'); ?>" style="padding:6px 10px;"><i class="icon-home"></i></a></li>
            <?php if(isAdmin() || isManagement() || isDataClerk() || isFarmGroupAdmin()){ ?>
            	<li><a href="<?php echo $addfarmerurl; ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add Farmer</a></li>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isUganda() && (isAdmin() || isManagement())){ ?>
				<?php if(isEmptyString($request->country) || $countryreq == 'ug'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl('mobile/list/country/ke'); ?>" title="Browse Kenya Directory"><i class="icon-list"></i> Browse Kenya</a></li>
                <?php } ?>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isKenya() && (isAdmin() || isManagement())){ ?>
                <?php if(!isEmptyString($request->country) && strtolower($countryreq) == 'ke'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl('mobile/list/country/ug'); ?>" title="Browse Uganda Directory"><i class="icon-list"></i> Browse Uganda</a></li>
                <?php } ?>
            <?php } ?>
            <li>
                <?php
                    $districts = getDistricts($session->getVar('country'));
					$districtdropdown = new Zend_Form_Element_Select('locationid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All '.$locations_label), $districts),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('span2','autofilter')
										)
									);
					$districtdropdown->setValue($request->getParam('locationid')); 
					echo $districtdropdown->render(); 
                  ?>
            </li>
            <?php if(isAdmin() || isManagement() || isDataClerk()){ ?>
            <li>
                <?php
                    $groupdropdown = new Zend_Form_Element_Select('farmgroupid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All DNAs'.$locationstring, '0'=> 'All Individual Farmers'), getAllFarmGroups($request->getParam('locationid'), $session->getVar('country'))),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('span3','autofilter')
										)
									);
					$groupdropdown->setValue($request->getParam('farmgroupid')); 
					echo $groupdropdown->render(); 
               ?>
            </li>
            <?php } ?>
            <?php if($farmgroup->hasSubGroups()){ ?>
                <li>
                    <?php
                        $groupdropdown = new Zend_Form_Element_Select('subgroupid',
                                            array(
                                                'multiOptions' => array_merge_maintain_keys(array('' => 'All Groups'.$dnastring), getAllFarmGroupsInDNA($request->getParam('farmgroupid'), $session->getVar('country'))),								
                                                'view' => new Zend_View(),
                                                'decorators' => array('ViewHelper'),
                                                'class' => array('span3')
                                            )
                                        );
                        $groupdropdown->setValue($request->getParam('subgroupid')); 
                        echo $groupdropdown->render(); 
                   ?>
                </li>
            <?php } else { ?>
                <input type="hidden" name="subgroupid" id="subgroupid" value="<?php echo $request->getParam('subgroupid'); ?>" />
            <?php } ?>
            <li><input name="startdate"  id="startdate" type="text" class="datefield startdate inline form-control input-width-small width100" placeholder="From" value="<?php echo $request->startdate; ?>" /></li>
            <li><input name="enddate" id="enddate" type="text" class="datefield form-control input-width-small width100 autofilter" placeholder="To" value="<?php echo $request->enddate; ?>" /></li>
            <li>
            	<?php
					$users = getProfilingUsers($session->getVar('country'));
					$dropdown = new Zend_Form_Element_Select('profiledby',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Profiling Users'), $users),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('span2','autofilter')
										)
									);
					$dropdown->setValue($request->getParam('profiledby')); 
					echo $dropdown->render(); 
				  ?>
            </li>
            <li><span class="visible-phone lineblocked">Search: &nbsp;</span><input name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" type="text" class="input-medium span2" style="margin-bottom:5px;" placeholder="Search Farmers">
                <button type="submit" id="searchbutton" class="btn" style="padding:6px 10px; vertical-align:top; margin-left:-2px;"><i class="icon-search"></i></button>
                <?php if(!isAdmin() && !isManagement() && !isDataClerk()){ ?>
                    <input type="hidden" name="farmgroupid" id="farmgroupid" value="<?php echo $request->getParam('farmgroupid'); ?>" />
                <?php } ?>
                <a href="<?php echo $listurl; ?>"> &nbsp;Reset list</a>
            </li>
        </ul>
        <?php if (!$has_no_data) { ?>
            	<div class="paginatecustom"><?php echo sprintf($this->translate("farmer_list_counter"), $paginate->getItemCounterText()); ?></div>
            <?php } ?>
        <?php if($has_no_data) { ?>
            <div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("farmer_list_norecords"); ?></div>
        <?php } else { ?>
              <div class="peoplelist">
                <?php 				  
                    $counter = 1;		
                    foreach($result as $line){
                       	$id = $line['id'];	
						$name = $line['firstname']." ".$line['lastname']." ".$line['othernames'];
						$firstname = $line['firstname'];
						$lastname = $line['lastname'];
						$groupname = $line['orgname'];
						$thefarmgroupid = $line['fmgroupid'];
						$subgroupname = '';
						if(!isEmptyString($line['subgroupid'])){
							$subgroupname = $line['sorgname'];
						}
						$refno = $line['regno'];
						if(isKenya()){
							$refno = $line['refno'];
						}
						
						$hasprofileimage = false;
						$real_path = APPLICATION_PATH.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."user_";
						$real_path = $real_path.$line['userid'].DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."large_".$line['profilephoto'];
						
						if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
							$hasprofileimage = true;
						}
						$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
						
						$photo_path = '';
						$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_male.jpg';
						if($line['gender'] == 2){
							$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_female.jpg'; 
						}
						if($hasprofileimage){
							$photo_path = $this->serverUrl($this->baseUrl('/uploads/user_'.$line['userid'].'/avatar/medium_'.$line['profilephoto']));
						}
						$hasdfa = true; $hasgroup = true;
						if(isEmptyString($thefarmgroupid)){
							$hasdfa = false;
						}
						if(isEmptyString($line['subgroupid'])){
							$hasgroup = false;
						}
                        
                ?>
                    <?php if($counter % 2 == 1){ ?>
                    <div class="row-fluid">
                    <?php } ?>
                      <div class="span6">
                        <div class="peoplewrapper well">
                          <div class="thumbwrapper">
                              <div class="thumb">
                                <div id="thumbinfo" class="<?php echo $hasprofileimage ? 'new_pic' : 'default_pic'; ?>"> 
                                    <a href="<?php echo $this->baseUrl("mobile/view/id/".encode($id)); ?>"><img class="profileimage" src="<?php echo $photo_path; ?>" /></a>
                                </div>
                              </div>
                              <div class="blocked bolded" style="font-size:10px;"><span>FIN#:</span> <?php echo isUganda() ? '' : '<br />'; ?><?php echo $line['refno']; ?></div>
                              <?php if(isUganda()){ ?>
                              	<div class="blocked" style="font-size:9px;"><?php echo $line['regno']; ?></div>
                              <?php } ?>
                          </div>
                          <div class="peopleinfo">
                            <h4><a href="<?php echo $this->baseUrl("mobile/view/id/".encode($id)); ?>"><?php echo $name; ?></a></h4>
                            <ul>
                            	<li><span><?php echo $location_label; ?>:</span> <?php echo isEmptyString($line['districtid']) ? '--' : $line['district']; ?></li>
								<?php if($hasdfa){ ?>
                                	<li><span>DNA:</span> <?php echo isEmptyString($thefarmgroupid) ? '--' : $groupname; ?></li>
                                <?php } else { ?>
                              		<li><span class="off"> Individual Farmer</span></li>
                            	<?php } ?>
                            	<?php if($hasgroup){ ?>
                              		<li><span>Farm Group:</span> </li>
                           		<?php } ?>  
                                <li><span>Phone:</span> <?php echo isEmptyString($line['phone']) ? '--' : getShortPhone($line['phone']); ?></li>
                                <li><span>Email:</span> <?php echo isEmptyString($line['email']) ? '--' : $line['email']; ?></li>
                                <li><span>Status:</span> <?php echo $line['isactive'] == 1 ? 'Activated' : 'Inactive'; ?></li>
                                <li><span>Profiled By:</span> <?php echo $line['addedby']; ?></li>
                                <li><span>Date:</span> <?php echo formatDateAndTime($line['dateadded'], true); ?></li>
                            </ul>
                          </div>
                          <!--peopleinfo--> 
                        </div>
                        <!--peoplewrapper--> 
                      <?php if($counter % 2 == 0){ ?>
                      </div>
                      <?php } ?>
                    </div>
                <?php $counter++; } ?>
              </div>
              <!--peoplelist-->
              <?php echo $paginate->getPaginationLinks(); ?>  
		<?php } ?>              
  </form>
</div>
</body>
</html><?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>