<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "System Users";	
	$this->headTitle($title);
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	if(isKenya()){
		$country = 'KE';
		$location_label = 'County';
		$locations_label = 'Counties';
	}
	$countryreq = $request->country; 
	
	$searchnames = '';
	if(!isEmptyString($request->firstname)){
		$searchnames .= $request->firstname;
	}
	if(!isEmptyString($request->lastname)){
		$searchnames .= " ".$request->lastname;
	}
	
	if (!isEmptyString($request->letter)){
		$searchnames .= "Browse By: <b>".strtoupper($request->letter)."</b>";
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.othernames","u.username","u.email","u.phone","u.email","u.refno","u.regno","fg.orgname","u.id"));
	$paginate->setFilterColumns(array("u.gender","u.locationid","u.farmgroupid"));
	// $paginate->setDefaultSortBy("u.datecreated");	
	// $paginate->setDefaultSortOrder("DESC");
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE u.id <> '' ";
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (u.`firstname` LIKE '".$request->letter."%' OR u.`lastname` LIKE '".$request->letter."%') ";
	}
	
	$customwhere = " ";
	if(!isEmptyString($request->searchterm)){
		$customwhere = " OR CONCAT_WS (' ', u.firstname, u.lastname) LIKE '%" .trim($request->searchterm). "%' OR CONCAT_WS (' ', u.lastname, u.firstname) LIKE '%" .trim($request->searchterm). "%'  ";
	}
	
	$listurl = $this->baseUrl('profile/list');
	$groupstring = "";
	
	# user status filter
	$status = trim($request->status);
	if(!isEmptyString($status)){
		$where_query .= " AND (u.`isactive` = ".$status.") ";
		$allowclear = true;
	}
	
	# user type filter
	$type = trim($request->type);
	$role = '';
	$allroles = getUserType();
	if(!isEmptyString($type)){
		$where_query .= " AND (u.type = ".$type.") ";
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
	}
	if($order == 1){
		$order_query = " ORDER BY u.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY u.firstname ASC ";
	}
	if($order == 3){
		$order_query = " ORDER BY u.lastname ASC ";
	}
	if($order == 4){
		$order_query = " ORDER BY u.datecreated ASC ";
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT u.id as id, u.id as userid, u.farmgroupid as fmgroupid, u.firstname, u.lastname, u.othernames, u.subgroupid, u.gender, u.isactive, u.locationid as districtid, u.email as email, u.email as femail, u.refno, u.regno as regno, u.phone as phone, u.regdate as fregdate, u.profilephoto as profilephoto, fg.orgname as orgname, fgs.orgname as sorgname, l.name as district, u.isphoneinvited, u.hasacceptedinvite, u.isinvited, u.selfregistered, concat(ua.firstname, ' ', ua.lastname) as addedby, u.datecreated as dateadded, u.username, u.type as usertype FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type <> 2 AND upper(u.country) = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere)." GROUP BY u.id ".$order_query;
	
	// debugMessage($all_results_query); // exit();
	// determine total number of records found
	$conn = Doctrine_Manager::connection(); 
	$count_query = "SELECT count(u.id) as total FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type <> 2 AND upper(u.country) = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere);
	$total = $conn->fetchOne($count_query);
	$paginate->setItemCount($total); // debugMessage('>> '.$total);	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
?>
<?php require APPLICATION_PATH."/views/scripts/mobile/mobileincludes.phtml"; ?>
<body>
<div class="container-fluid viewpage" id="list_farmer">
  <h4><?php echo $title; ?></h4>
  <form action="<?php echo $this->baseUrl("mobile/userssearch"); ?>" method="get" id="listform" class="form-search">
	  <?php if($sessionhaserror) { ?>
      <div class="row-fluid">
        <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar("custommessage")) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("custommessage"); ?></div>
      </div>
      <?php } ?>
      <ul class="peoplegroup">
            <li><a class="btn" href="<?php echo $this->baseUrl('mobile/home'); ?>" style="padding:6px 10px;"><i class="icon-home"></i></a></li>
            <?php if(isAdmin() || isManagement()){ ?>
           		<li><a href="<?php echo $this->baseUrl('mobile/farmer/type/other/country/'.$country); ?>" class="btn btn-primary"><i class="icon-plus icon-white"></i> Add User</a></li>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isUganda() && (isAdmin() || isManagement())){ ?>
				<?php if(isEmptyString($request->country) || $countryreq == 'ug'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl('mobile/users/country/ke'); ?>" title="Browse Kenya"><i class="icon-list"></i> Browse Kenya</a></li>
                <?php } ?>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isKenya() && (isAdmin() || isManagement())){ ?>
                <?php if(!isEmptyString($request->country) && strtolower($countryreq) == 'ke'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl('mobile/users/country/ug'); ?>" title="Browse Uganda"><i class="icon-list"></i> Browse Uganda</a></li>
                <?php } ?>
            <?php } ?>
            <li>
                <?php
					$allstatus = getUserStatus();
					$dropdown = new Zend_Form_Element_Select('status',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), $allstatus),
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('status','span2')
										)
					);  
					$dropdown->setValue($request->getParam('status')); 
					echo $dropdown->render();
				?>
            </li>
            <li>
				<?php
                    $dropdown = new Zend_Form_Element_Select('type',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Types'), $allroles),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('type','span2')
                                        )
                    );  
                    $dropdown->setValue($request->getParam('type')); 
                    echo $dropdown->render();
                ?>
            </li>
            <li>
                <?php
					$groupdropdown = new Zend_Form_Element_Select('farmgroupid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Groups', '0'=> 'All Individual Farmers'), getAllFarmGroups('', $session->getVar('country'))),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('width180')
										)
									);
					$groupdropdown->setValue($request->getParam('farmgroupid')); 
					echo $groupdropdown->render(); 
			   ?>
            </li>
            <li>
            	 <?php
					$allorders = array('1' => 'Latest First', '2'=>'Alphabetical (Firstname)','3'=>'Alphabetical (Lastname)', '4'=>'Earliest First');
					$ordersdropdown = new Zend_Form_Element_Select('order',
										array(
											'multiOptions' => $allorders,
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('gender','span2'),
											'title' => 'Order list by'		
										)
					);  
					$ordersdropdown->setValue($request->getParam('order')); 
					echo $ordersdropdown->render();
				?>
            </li>
            <li><span class="visible-phone lineblocked">Search: &nbsp;</span><input name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" type="text" class="input-medium span2" style="margin-bottom:5px;" placeholder="Search Users">
                <button type="submit" id="searchbutton" class="btn" style="padding:6px 10px; vertical-align:top; margin-left:-2px;"><i class="icon-search"></i></button>
                <a href="<?php echo $this->baseUrl('mobile/users'); ?>"> &nbsp;Reset list</a>
            </li>
        </ul>
        <?php if (!$has_no_data) { ?>
            <div class="paginatecustom"><?php echo sprintf($this->translate("useraccount_list_counter"), $paginate->getItemCounterText()); ?></div>
        <?php } ?>
        <?php if($has_no_data) { ?>
            <div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("global_list_norecords"); ?></div>
        <?php } else { ?>
              <div class="peoplelist">
                <?php 				  
                    $counter = 1;		
                    foreach($result as $line){
                        $id = $line['id'];	
						$name = $line['firstname']." ".$line['lastname']." ".$line['othernames'];
						$firstname = $line['firstname'];
						$lastname = $line['lastname'];
						$groupname = $line['orgname'];
						$thefarmgroupid = $line['fmgroupid'];
						$subgroupname = '';
						if(!isEmptyString($line['subgroupid'])){
							$subgroupname = $line['sorgname'];
						}
						$refno = $line['regno'];
						if(isKenya()){
							$refno = $line['refno'];
						}
						
						$hasprofileimage = false;
						$real_path = APPLICATION_PATH.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."public".DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."user_";
						$real_path = $real_path.$line['userid'].DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."large_".$line['profilephoto'];
						
						if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
							$hasprofileimage = true;
						}
						$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
						
						$photo_path = '';
						$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_male.jpg';
						if($line['gender'] == 2){
							$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_female.jpg'; 
						}
						if($hasprofileimage){
							$photo_path = $this->serverUrl($this->baseUrl('/uploads/user_'.$line['userid'].'/avatar/medium_'.$line['profilephoto']));
						}
						$hasdfa = true; $hasgroup = true;
						if(isEmptyString($thefarmgroupid)){
							$hasdfa = false;
						}
						if(isEmptyString($line['subgroupid'])){
							$hasgroup = false;
						}
                        
                ?>
                    <?php if($counter % 2 == 1){ ?>
                    <div class="row-fluid">
                    <?php } ?>
                      <div class="span6">
                        <div class="peoplewrapper well">
                          <div class="thumbwrapper">
                              <div class="thumb">
                                <div id="thumbinfo" class="<?php echo $hasprofileimage ? 'new_pic' : 'default_pic'; ?>"> 
                                    <a href="<?php echo $this->baseUrl("mobile/view/id/".encode($id)); ?>"><img class="profileimage" src="<?php echo $photo_path; ?>" /></a>
                                </div>
                              </div>
                              	<?php if($line['usertype'] == 4){ ?>
                                    <div class="blocked bolded" style="font-size:10px; padding-left:5px;"><span>PID#:</span> <?php echo $line['id']; ?></div>
                                <?php } ?>
                          </div>
                          <div class="peopleinfo">
                            <h4><a href="<?php echo $this->baseUrl("mobile/view/id/".encode($id)); ?>"><?php echo $name; ?></a></h4>
                            <ul>
                              <li><span>Type:</span> 
							  	<?php echo getUserType($line['usertype']); ?>
								<?php if($line['usertype'] == 3){
									echo ' (<a href="'.$this->baseUrl('farmgroup/view/id/'.encode($line['fmgroupid'])).'">'.$line['orgname'].'</a>)';
								} 
								?>
                              </li>
                              <li><span>Phone:</span> <?php echo isEmptyString($line['phone']) ? '--' : getShortPhone($line['phone']); ?></li>
                              <li><span>Email:</span> <?php echo isEmptyString($line['email']) ? '--' : $line['email']; ?></li>
                              <li><span>Username:</span> <?php echo isEmptyString($line['username']) ? '--' : $line['username']; ?></li>
                              <li><span>Status:</span> <?php echo $line['isactive'] == 1 ? 'Activated' : 'Inactive'; ?></li>
                              <li><span>Profiled By:</span> <?php echo $line['addedby']; ?></li>
                              <li><span>Date:</span> <?php echo formatDateAndTime($line['dateadded'], true); ?></li>
                            </ul>
                          </div>
                          <!--peopleinfo--> 
                        </div>
                        <!--peoplewrapper--> 
                      <?php if($counter % 2 == 0){ ?>
                      </div>
                      <?php } ?>
                    </div>
                <?php $counter++; } ?>
              </div>
              <!--peoplelist-->
              <?php echo $paginate->getPaginationLinks(); ?>  
		<?php } ?>              
  </form>
</div>
</body>
</html><?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>