<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "System Users";	
	$this->headTitle($title);
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	if(isKenya()){
		$country = 'KE';
		$location_label = 'County';
		$locations_label = 'Counties';
	}
	$countryreq = $request->country; 
	
	$searchnames = '';
	if(!isEmptyString($request->firstname)){
		$searchnames .= $request->firstname;
	}
	if(!isEmptyString($request->lastname)){
		$searchnames .= " ".$request->lastname;
	}
	
	if (!isEmptyString($request->letter)){
		$searchnames .= "Browse By: <b>".strtoupper($request->letter)."</b>";
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.othernames","u.username","u.email","u.phone","u.email","u.refno","u.regno","fg.orgname","u.id"));
	$paginate->setFilterColumns(array("u.gender","u.locationid","u.farmgroupid"));
	// $paginate->setDefaultSortBy("u.datecreated");	
	// $paginate->setDefaultSortOrder("DESC");
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE u.id <> '' ";
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (u.`firstname` LIKE '".$request->letter."%' OR u.`lastname` LIKE '".$request->letter."%') ";
	}
	
	$customwhere = " ";
	if(!isEmptyString($request->searchterm)){
		$customwhere = " OR CONCAT_WS (' ', u.firstname, u.lastname) LIKE '%" .trim($request->searchterm). "%' OR CONCAT_WS (' ', u.lastname, u.firstname) LIKE '%" .trim($request->searchterm). "%'  ";
	}
	
	$listurl = $this->baseUrl('profile/list');
	$groupstring = "";
	
	# user status filter
	$status = trim($request->status);
	if(!isEmptyString($status)){
		$where_query .= " AND (u.`isactive` = ".$status.") ";
		$allowclear = true;
	}
	
	# user type filter
	$type = trim($request->type);
	$role = '';
	$allroles = getUserType();
	if(!isEmptyString($type)){
		$where_query .= " AND (u.type = ".$type.") ";
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
	}
	if($order == 1){
		$order_query = " ORDER BY u.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY u.firstname ASC ";
	}
	if($order == 3){
		$order_query = " ORDER BY u.lastname ASC ";
	}
	if($order == 4){
		$order_query = " ORDER BY u.datecreated ASC ";
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT u.id as id, u.id as userid, u.farmgroupid as fmgroupid, u.firstname, u.lastname, u.othernames, u.subgroupid, u.gender, u.isactive, u.locationid as districtid, u.email as email, u.email as femail, u.refno, u.regno as regno, u.phone as phone, u.regdate as fregdate, u.profilephoto as profilephoto, fg.orgname as orgname, fgs.orgname as sorgname, l.name as district, u.isphoneinvited, u.hasacceptedinvite, u.isinvited, u.selfregistered, concat(ua.firstname, ' ', ua.lastname) as addedby, u.datecreated as dateadded, u.username, u.type as usertype FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type <> 2 AND upper(u.country) = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere)." GROUP BY u.id ".$order_query;
	
	// debugMessage($all_results_query); // exit();
	// determine total number of records found
	$conn = Doctrine_Manager::connection(); 
	$count_query = "SELECT count(u.id) as total FROM useraccount u LEFT JOIN farmgroup as fg on (u.farmgroupid = fg.id) LEFT JOIN location l on (u.locationid = l.id AND l.locationtype = 2) INNER JOIN useraccount ua on (u.createdby = ua.id) LEFT JOIN farmgroup as fgs on (u.subgroupid = fgs.id) ".$where_query." AND u.type <> 2 AND upper(u.country) = UPPER('".$session->getVar('country')."') ".$paginate->getSearchAndFilterSQL($customwhere);
	$total = $conn->fetchOne($count_query);
	$paginate->setItemCount($total); // debugMessage('>> '.$total);	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
?>
<?php require APPLICATION_PATH."/views/scripts/mobile/mobileincludes.phtml"; ?>
<body>
<div class="container-fluid viewpage" id="list_farmer">
  <h4><?php echo $title; ?></h4>
  <form action="<?php echo $this->baseUrl("mobile/userssearch"); ?>" method="get" id="listform" class="form-search">
	  <?php if($sessionhaserror) { ?>
      <div class="row-fluid">
        <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
      </div>
      <?php } ?>
      <?php if(!isEmptyString($session->getVar("custommessage")) ){ ?>
      <div class="row-fluid">
        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("custommessage"); ?></div>
      </div>
      <?php } ?>
      <ul class="peoplegroup">
            <li><a class="btn" href="<?php echo $this->baseUrl('mobile/home'); ?>" style="padding:6px 10px;"><i class="icon-home"></i></a></li>
            <?php if($acl->checkPermission('User Account', ACTION_CREATE)) { ?>	
                <li><a href="<?php echo $this->baseUrl('mobile/farmer/type/other/country/'.$country); ?>" class="btn btn-primary" title="New User"><i class="icon-plus icon-white"></i> New User</a></li>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isUganda() && $acl->checkPermission('Can Administer Kenya', ACTION_VIEW)){ ?>
                <?php if(isEmptyString($request->country) || $countryreq == 'ug'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl($controllername.'/users/country/ke'); ?>" title="Browse Kenya"><i class="icon-list"></i> Browse Kenya</a></li>
                <?php } ?>
            <?php } ?>
            <?php if($loggedinuser->isUgandan() && isKenya() && $acl->checkPermission('Can Administer Kenya', ACTION_VIEW)){ ?>
                <?php if(!isEmptyString($request->country) && $countryreq == 'ke'){ ?>
                    <li><a class="btn" href="<?php echo $this->baseUrl($controllername.'/users/country/ug'); ?>" title="Browse Uganda"><i class="icon-list"></i> Browse Uganda</a></li>
                <?php } ?>
            <?php } ?>
            <li>
                <?php
					$allstatus = getUserStatus();
					$dropdown = new Zend_Form_Element_Select('status',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), $allstatus),
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('status','span2')
										)
					);  
					$dropdown->setValue($request->getParam('status')); 
					echo $dropdown->render();
				?>
            </li>
            <li>
				<?php
                    $dropdown = new Zend_Form_Element_Select('type',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Types'), $allroles),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('type','span2')
                                        )
                    );  
                    $dropdown->setValue($request->getParam('type')); 
                    echo $dropdown->render();
                ?>
            </li>
            <li>
                <?php
					$groupdropdown = new Zend_Form_Element_Select('farmgroupid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Groups', '0'=> 'All Individual Farmers'), getAllFarmGroups('', $session->getVar('country'))),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('width180')
										)
									);
					$groupdropdown->setValue($request->getParam('farmgroupid')); 
					echo $groupdropdown->render(); 
			   ?>
            </li>
            <li>
            	 <?php
					$allorders = array('1' => 'Latest First', '2'=>'Alphabetical (Firstname)','3'=>'Alphabetical (Lastname)', '4'=>'Earliest First');
					$ordersdropdown = new Zend_Form_Element_Select('order',
										array(
											'multiOptions' => $allorders,
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('gender','span2'),
											'title' => 'Order list by'		
										)
					);  
					$ordersdropdown->setValue($request->getParam('order')); 
					echo $ordersdropdown->render();
				?>
            </li>
            <li><span class="visible-phone lineblocked">Search: &nbsp;</span><input name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" type="text" class="input-medium span2" style="margin-bottom:5px;" placeholder="Search Users">
                <button type="submit" id="searchbutton" class="btn" style="padding:6px 10px; vertical-align:top; margin-left:-2px;"><i class="icon-search"></i></button>
                <a href="<?php echo $this->baseUrl('mobile/users'); ?>"> &nbsp;Reset list</a>
            </li>
        </ul>
        <?php if (!$has_no_data) { ?>
            <div class="paginatecustom"><?php echo sprintf($this->translate("useraccount_list_counter"), $paginate->getItemCounterText()); ?></div>
        <?php } ?>
        <?php if($has_no_data) { ?>
            <div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("global_list_norecords"); ?></div>
        <?php } else { ?>
              <?php require APPLICATION_PATH."/views/scripts/profile/userloop.phtml"; ?>
		<?php } ?>              
  </form>
</div>
</body>
</html><?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>