<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$user = new UserAccount();
	$isme = false;
	$has_subgrp = false;
	$dateofbirth = '';  $birthday = ''; $birthmonth = ''; $birthyear = '';
	$type = $request->type;
	$isfarmer = true;
	
	if(isEmptyString($request->id)){
		// when adding a farmer from a farmgroup
		if(!isEmptyString($request->farmgroupid)){
			$farmgrp = new FarmGroup(); 
			$farmgrp->populate($request->farmgroupid);
			$user->setFarmGroupID($request->farmgroupid);
			$subgroups = getSubGroups($user->getFarmGroupID());
			if(count($subgroups) > 0){
				$has_subgrp = true;
			}
		} 
		
		$title = "Add Farmer";
		$posturl = $this->baseUrl("mobile/create");
		$user->setRegDate(changeMySQLDateToPageFormat(date('Y-m-d')));
		$user->setType(2);
		$user->setCreatedBy($userid);
		$thecountry = strtoupper($session->getVar('country'));
		if(!isEmptyString($type)){
			$isfarmer = false;
			$title = "New User";
		}
		if(!isEmptyString($request->companyid)){
			$user->setCompanyID($request->companyid);
			$user->setType(6);
		}
	} else {
		$user->populate(decode($request->id));
		$title = "Update Farmer"; 
		if($user->getID() == $userid || $user->getType() != 2){
			$isme = true;
			$title = "Update Profile"; 
		}
		if($user->getType() != 2){
			$isfarmer = false;
		}
		$posturl = $this->baseUrl("mobile/edit");
		
		if(!isEmptyString($user->getDateOfBirth())){
			$birthday = date('d', strtotime($user->getDateOfBirth())); 
			$birthyear = date('Y', strtotime($user->getDateOfBirth())); 
			$birthmonth = date('m', strtotime($user->getDateOfBirth())); 
		}
		$thecountry =  $user->getCountry();
	}
	$user->setRegSource('0'); // desktop regsource
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){
		$formvalues  = $session->getVar(FORM_VALUES);
		// debugMessage($formvalues);
		$user->processPost($formvalues);
		$birthday = $formvalues['birthday']; $birthmonth = $formvalues['birthmonth']; $birthyear = $formvalues['birthyear']; 
		// debugMessage($user->toArray());
	}
	
	if($birthday == 1 && $birthmonth == 1 && $birthyear == 1970){
		$birthday = ''; $birthmonth = ''; $birthyear = ''; 
	}
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$locationerror = $this->translate("farmer_district_error");
	$country_params_refno_placeholder = 'placeholder="Auto" maxlength="8" ';
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya() || $user->isKenyan()){
		$session->setVar('country', 'ke');
		$country = 'KE';
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$locationerror = $this->translate("farmer_county_error");
		$country_params_refno_placeholder = 'placeholder="" maxlength="10" ';
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	
	$this->headTitle($title);
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				firstname: "required",
				lastname: "required",
				email: {
					"required": false, 
					email: true
				},
				gender: "required",
				locationid2: "required",
				phone: {
					required: false, 					
					validnumber: true,
					maxlength: 10,
					minlength: 10,
					<?php if(isUganda()){ ?>
						validate_ug: true
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: true
					<?php } ?>
				},
				<?php if(isKenya()){ ?>
					refno: {
						required: true, 					
						minlength: 6,
						maxlength: 10					
					},
				<?php } ?>
				birthyear: {
					validbirth: true
				},
				<?php //if(isUganda()){ ?>
					// farmgroupid: "required",
				<?php //} ?>
				type: "required",
				profiledby: "required",
				companyid: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				firstname: "<?php echo $this->translate("farmer_firstname_error"); ?>",
				lastname: "<?php echo $this->translate("farmer_lastname_error"); ?>",
				email: {
					"email": "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
				},
				gender: "<?php echo $this->translate("farmer_gender_error"); ?>",
				locationid2: "<?php echo $locationerror; ?>",
				phone: {
					validnumber: "Please enter a valid Phone Number",
					maxlength: "Phone Number must have 10 Digits",
					minlength: "Phone Number must have 10 Digits",
					<?php if(isUganda()){ ?>
						validate_ug: "<?php echo $this->translate("globale_phonenumber_format"); ?>"
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: "<?php echo $this->translate("globale_phonenumber_format_ke"); ?>"
					<?php } ?>
				},
				<?php if(isKenya()){ ?>
					refno: {
						required: "Please enter ID Number", 					
						minlength: "ID must have more than 6 Digits",
						maxlength: "ID must not exceed 10 Digits"
					},
				<?php } ?>
				birthyear: {
					validbirth: "Please select full Date of Birth"
				},
				<?php //if(isUganda()){ ?>
					//farmgroupid: "Please select DNA",
				<?php //} ?>
				type: "<?php echo $this->translate("farmer_role_error"); ?>",
				profiledby: "Please select profiling user",
				companyid: "Please select a Partner"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		$.validator.addMethod("validbirth", function(value, element, params) { 
			var day = $("#birthday").val();
			var month = $("#birthmonth").val();
			var year = value;
			if ((!isEmptyString(day) && (isEmptyString(month) || isEmptyString(year))) || 
				(!isEmptyString(month) && (isEmptyString(day) || isEmptyString(year)))  || 
				(!isEmptyString(year) && (isEmptyString(day) || isEmptyString(month))) ){
				return false; 
			}
			return true;        
		}, "Please select full Date of Birth");
		
		var dateofregOpts = datepickerOpts;
		dateofregOpts.yearRange = "-5";
		dateofregOpts.maxDate = new Date();
		$("#regdate").datepicker(dateofregOpts);
		$('.ui-datepicker-trigger').hide();
		
		<?php if(isUganda()){ ?>
			var refno = '<?php echo $user->getRefNo(); ?>';
			$("#refno").addClass('readonly');
		<?php } ?>
		
		$(".datefield").attr('readOnly', 'true');
		$(".readonly").each(function(){
			$(this).attr('readonly','readonly');
		});
		
		$("#refno").trigger('keyup');
		
		$('#locationid2').change(function() {
			var locationid = $(this).val();
			var currentvalue = "<?php echo $user->getFarmGroupID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(locationid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/district_dnaprofiles/locationid2/'); ?>"+locationid;
				$("#farmgroupid").find("option:gt(0)").remove();
   				$("#farmgroupid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#farmgroupid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#farmgroupid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#farmgroupid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
					$('#districtid').trigger('keyup').trigger("change");
				});
				$('#farmgroupid').trigger("change");
			}
			$('#districtid').val(locationid).trigger('keyup').trigger('change');
		});
		$('#locationid2').trigger("change");
		
		$('#farmgroupid').change(function() {
			var groupid = $(this).val();
			var currentvalue = "<?php echo $user->getSubGroupID(); ?>"; // alert('cur '+currentvalue);
			var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/farmgroup_children/farmgroupid/'); ?>"+groupid;
			// alert(posturl);
			if(!isEmptyString(groupid)){
				$("#subgroupid").find("option:gt(0)").remove();
   				$("#subgroupid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#subgroupid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#subgroupid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)); 
						} else {
							$('#subgroupid').append($("<option></option>").attr("value",key).text(value)); 
						}
					});
				});
			}
		});
		
		$('#districtid').change(function() {
			var locationid = $(this).val();
			var currentvalue = "<?php echo $user->getCountyID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(locationid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/district_counties/districtid/'); ?>"+locationid;
				$("#countyid").find("option:gt(0)").remove();
   				$("#countyid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#countyid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#countyid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#countyid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				$('#countyid').trigger("change");
			}
		});
		
		$('#countyid').change(function() {
			var countyid = $(this).val();
			var currentvalue = "<?php echo $user->getSubCountyID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(countyid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/county_subcounties/countyid/'); ?>"+countyid;
				$("#subcountyid").find("option:gt(0)").remove();
   				$("#subcountyid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#subcountyid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#subcountyid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#subcountyid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				// $('#subcountyid').trigger("change");
			}
		});
		
		$('#subcountyid').change(function() {
			var subcountyid = $(this).val();
			var currentvalue = "<?php echo $user->getParishID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(subcountyid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/subcounty_parishes/subcountyid/'); ?>"+subcountyid;
				$("#parishid").find("option:gt(0)").remove();
   				$("#parishid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#parishid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#parishid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#parishid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				// $('#subcountyid').trigger("change");
			}
		});
		
		$('#parishid').change(function() {
			var parishid = $(this).val();
			var currentvalue = "<?php echo $user->getVillageID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(parishid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/parish_villages/parishid/'); ?>"+parishid;
				$("#villageid").find("option:gt(0)").remove();
   				$("#villageid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#villageid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#villageid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#villageid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				// $('#subcountyid').trigger("change");
			}
		});
		
		$.validator.addMethod("minstart", function(value, element) {
			var n = new Date();
			var nstamp = n.getTime();
			var syear = $("#bizstartyear").val(); var smonth = $("#bizstartmonth").val(); var sday = 1;
			// alert(nstamp);
			if(!isEmptyString(syear) && !isEmptyString(smonth )){
				var start = smonth+'/'+sday+'/'+syear;
				var s = new Date(start);
				var sstamp = s.getTime();
				if(sstamp > nstamp){
					return false;
				}
			}
			return true;
		}, "Should'nt be after today");
		
		$("#bottomactions").html($("#topactions").html());
		
		<?php if(isEmptyString($user->getID())){ ?>
			$('#firstname, #lastname').change(function() {
				var firstname = $('#firstname').val();
				var lastname = $('#lastname').val();
				$('#businessname').val(firstname+' '+lastname+"'s Farm" );
			});
		<?php } ?>
		
		<?php if(isFarmer() && $isme && $user->isSelfRegistered()){ ?>
			disableContainerByID('groupfarmer');
		<?php } ?>
		
		multipleDisableContainerByClass('parish_text');
		multipleEnableContainerByClass('parish_select');
		$("#parishtrigger").click(function(){
			if($(this).is(':checked')){
				disableContainerByClass('parish_select');
				enableContainerByClass('parish_text');
				$(".parish_select select").val('');
			} else {
				disableContainerByClass('parish_text');
				enableContainerByClass('parish_select');
				$(".parish_text input").val('');
			}
		});
		
		multipleDisableContainerByClass('village_text');
		multipleEnableContainerByClass('village_select');
		$("#villagetrigger").click(function(){
			if($(this).is(':checked')){
				disableContainerByClass('village_select');
				enableContainerByClass('village_text');
				$(".village_select select").val('');
			} else {
				disableContainerByClass('village_text');
				enableContainerByClass('village_select');
				$(".village_text input").val('');
			}
		});
		
		<?php if(!$isfarmer){ ?>
			disableContainerByClass('hideonsuper');
				$('#type').change(function(){
				var type = $(this).val();
				if(type == 3){
					enableContainerByID('groupfarmer');
				} else {
					disableContainerByID('groupfarmer');
				}
			});
			$('#type').change();
		<?php } ?>
		
		multipleDisableContainerByClass('subgroup_text');
		multipleEnableContainerByClass('subgroup_select');
		$("#subgrouptrigger").click(function(){
			if($(this).is(':checked')){
				disableContainerByClass('subgroup_select');
				enableContainerByClass('subgroup_text');
				$(".subgroup_select select").val('');
			} else {
				disableContainerByClass('subgroup_text');
				enableContainerByClass('subgroup_select');
				$(".subgroup_text input").val('');
			}
		});
		
		$("#type").change(function(){
			var type = $(this).val();
			if(type == '6'){
				enableContainerByID("partnerrow");
			} else { 
				disableContainerByID("partnerrow");
			}
		});
		$("#type").trigger('change');
	}); 
</script>
<div>
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
        <div class="container-fluid">
            <div class="row margin0 maxwidth">
                <form class="form-horizontal clearfix desktop" id="indexform" action="<?php echo $posturl; ?>" method="post">
                    <h1><?php echo $title; ?></h1>
                    <div class="wellcontent">
                    	<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                            <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                            <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                        <?php } ?>
                        <?php require APPLICATION_PATH."/views/scripts/profile/addtemplate.phtml"; ?>
                    </div>
              	</form>
          	</div>
      	</div>
   	</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>