<div class="control-group well actions" id="topactions">
      <a href="<?php echo $this->referer; ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
      <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save'); ?></button>
      <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $this->translate("global_save_success"); ?>" /> 
</div>
<fieldset class="fieldsetcontainer well">
    <legend>Account</legend>
    <?php if($isfarmer || $user->isFarmer() || $request->getParam('type') == 2){ ?>
        <div class="control-group hideonsuper">
            <label class="control-label" for="refno"><?php echo isKenya() ? 'National ID#'.$this->translate("global_required_field_marker") : $this->translate("farmer_regno_label"); ?>: </label>
            <div class="controls">
                <input type="text" name="refno" id="refno" value="<?php echo $user->getRefNo(); ?>" class="span2 minwidth100" <?php echo $country_params_refno_placeholder; ?> />
                <div id="regno_error"></div><div id="refno_error"></div>
            </div>
        </div>
        <input type="hidden" id="type" name="type" value="<?php echo $user->getType(); ?>" />
        <input type="hidden" id="isfarmer" name="isfarmer" value="1" />
    <?php } else { ?>
        <div class="control-group">
            <label class="control-label" for="type"><?php echo $this->translate("farmer_type_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
            <div class="controls">
                <?php
                    $allvalues = getUserType('', '2');
					if($acl->checkPermission('Is KE Admin', ACTION_YESNO)){
						unset($allvalues['1']);
						unset($allvalues['8']);
						unset($allvalues['6']);
					}
                    $dropdown = new Zend_Form_Element_Select('type',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span3')
                                        )
                    );  
                    $dropdown->setValue($user->getType()); 
                    echo $dropdown->render();
                ?>
                <div id="type_error"></div>
            </div>
            <input type="hidden" id="isfarmer" name="isfarmer" value="<?php echo $user->isFarmer() ? 0 : 1; ?>" />
        </div>
        <div class="control-group" id="partnerrow">
        	<label class="control-label" for="type">Partner: <?php echo $this->translate("global_required_field_marker"); ?></label>
            <div class="controls">
                <?php
                    $allvalues = getAllPartners($session->getVar('country'));
                    $dropdown = new Zend_Form_Element_Select('companyid',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span3')
                                        )
                    );  
                    $dropdown->setValue($user->getCompanyID()); 
                    echo $dropdown->render();
                ?>
                <div id="companyid_error"></div>
            </div>
        </div>
        <?php if($user->isKenyan()){ ?>
             <div class="control-group">
                <label class="control-label" for="refno"><?php echo 'National ID# '.$this->translate("global_required_field_marker"); ?>: </label>
                <div class="controls">
                    <input type="text" name="refno" id="refno" value="<?php echo $user->getRefNo(); ?>" class="span2 minwidth100" <?php echo $country_params_refno_placeholder; ?> /><div id="refno_error"></div>
                </div>
            </div>
            <?php if($user->isPIA()){ ?>
                <div class="control-group">
                    <label class="control-label" for="refno">PID#: </label>
                    <div class="controls"><?php echo $user->getID(); ?></div>
                </div>
            <?php } ?>
        <?php } ?>
    <?php } ?>
    <div class="control-group">
      <label class="control-label" for="firstname"><?php echo $this->translate("farmer_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
      <div class="controls">
        <input type="text" name="firstname" id="firstname" class="span3" value="<?php echo $user->getFirstName(); ?>" /><div id="firstname_error"></div>
        <input type="hidden" name="entityname" value="Farmer" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
        <input type="hidden" id="userid" name="userid" value="<?php echo $user->getID(); ?>" />
        <input type="hidden" id="selfregistered" name="selfregistered" value="<?php echo $user->getSelfRegistered(); ?>" />
        <input type="hidden" id="regsource" name="regsource" value="<?php echo $user->getRegSource(); ?>" />
        <input type="hidden" id="thecontroller" name="thecontroller" value="<?php echo $controllername; ?>" />
        <input type="hidden" id="theaction" name="theaction" value="<?php echo $controlleraction; ?>" />
        <input type="hidden" id="addedbyid" name="addedbyid" value="<?php echo $userid; ?>" />
        <input type="hidden" name="regdate" id="regdate" value="<?php echo changeMySQLDateToPageFormat($user->getRegDate()); ?>" />
        <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('mobile/farmer')); ?>" />
        <input type="hidden" id="username" name="username" value="<?php echo $user->getusername(); ?>" />
        <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="farmer_add_success" />
        <input type="hidden" id="membershipplanid" name="membershipplanid" value="<?php echo $user->getmembershipplanid(); ?>" />
        <input type="hidden" id="country" name="country" value="<?php echo $country; ?>" />
        <input type="hidden" id="country2" name="country2" value="<?php echo $country; ?>" />
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="lastname"><?php echo $this->translate("farmer_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
      <div class="controls">
        <input type="text" name="lastname" id="lastname" class="span3" value="<?php echo $user->getLastName(); ?>" /><div id="lastname_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="othernames"><?php echo $this->translate("farmer_othernames_label"); ?>:</label>
      <div class="controls">
        <input type="text" name="othernames" id="othernames" class="span3" value="<?php echo $user->getOtherNames(); ?>" /><div id="lastname_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
      <div class="controls">
         <?php						  
              $genderradio = new Zend_Form_Element_Radio('gender',
                      array(
                              'multiOptions' => array('1' => 'Male', '2' => 'Female'), 
                              'view' => new Zend_View(),
                              'disableLoadDefaultDecorators' => true,
                              'separator' => '&nbsp;&nbsp;&nbsp;&nbsp;',
                              'decorators' => array('ViewHelper',
                                                  array('HtmlTag', array('tag' => 'div', 'class' => array('inline', 'radio', 'zendradio'))) // use a sorrounding DIV with classes which are copied to the label by JQuery
                                              )
                      )
              );
              $genderradio->setValue($user->getGender());
              echo $genderradio->render();
          ?>
          <div id="gender_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label>
      <div class="controls">
            <?php
                $daydp = new Zend_Form_Element_Select('birthday',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'Day'), getMonthDays()),	
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('birth'),
                                        'title' => 'Select Day'		
                                    )
                                );
                $daydp->setValue($birthday); 
                echo $daydp->render(); 
            ?>
            <?php
                $monthdp = new Zend_Form_Element_Select('birthmonth',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'Month'), getAllMonthsAsShortNames()),	
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('birth'),
                                        'title' => 'Select Month'		
                                    )
                                );
                $monthdp->setValue($birthmonth); 
                echo $monthdp->render(); 
            ?>
            <?php
                $years = getSubscribeBirthYears();
                $yeardp = new Zend_Form_Element_Select('birthyear',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => 'Year'), $years),	
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('birth'),
                                        'title' => 'Select Year'		
                                    )
                                );
                $yeardp->setValue($birthyear); 
                echo $yeardp->render(); 
            ?>
            <div id="birthday_error"></div><div id="birthmonth_error"></div><div id="birthyear_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="locationid2"><?php echo $location_label; ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
      <div class="controls">
        <?php
            $districts = getDistricts($session->getVar('country'));
            $currentdistrict = '';
            if(!isEmptyString($user->getFarmGroupID())){
                if(!isEmptyString($user->getFarmGroup()->getDistrictID())){
                    $currentdistrict = $user->getFarmGroup()->getDistrictID();
                }
            }
            if(!isEmptyString($user->getID())){
                // debugMessage('>> '.$user->getLocation()->getName());
                $currentdistrict = $user->getLocationID();
            }
            $districtdropdown = new Zend_Form_Element_Select('locationid2',
                                array(
                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districts),								
                                    'view' => new Zend_View(),
                                    'decorators' => array('ViewHelper'),
                                    'class' => array('span3')
                                )
                            );
            $districtdropdown->setValue($currentdistrict); 
            echo $districtdropdown->render(); 
       ?><div id="locationid2_error"></div>
      </div>
    </div>
    <div id="groupfarmer" class="xhideonsuper">
        <div class="control-group">
          <label class="control-label" for="farmgroupid"><?php echo $this->translate("farmgroup_dna_label"); ?>: <?php echo isUganda() ? $this->translate("global_required_field_marker") : ''; ?></label>
          <div class="controls">
                <?php if(!isFarmer()){ ?>
                    <?php
                        $groupdropdown = new Zend_Form_Element_Select('farmgroupid',
                                            array(
                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getAllFarmGroups($session->getVar('country'))),								
                                                'view' => new Zend_View(),
                                                'decorators' => array('ViewHelper'),
                                                'class' => array('span3')
                                            )
                                        );
                        $groupdropdown->setValue($user->getFarmGroupID()); 
                        echo $groupdropdown->render(); 
                   ?>
               <?php } else { ?>
                    <?php echo !$user->hasFarmGroup() ? "--" : $user->getFarmGroup()->getName(); ?>
                    <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $user->getFarmGroupID(); ?>" /> 
               <?php } ?>
            <div id="farmgroupid_error"></div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="subgroupid"><?php echo $this->translate("farmgroup_farmgroup_label"); ?>:</label>
          <div class="controls">
                <?php if(!isFarmer()){ ?>
                    <div class="subgroup_text inline">
                        <input type="text" name="subgroupname" id="subgroupname" class="span3" value="<?php //echo $user->getVillageName(); ?>"  />
                    </div>
                    <div class="subgroup_select inline">
                        <?php
                            $groupdropdown = new Zend_Form_Element_Select('subgroupid',
                                                array(
                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select DNA to Populate>')),								
                                                    'view' => new Zend_View(),
                                                    'decorators' => array('ViewHelper'),
                                                    'class' => array('span3')
                                                )
                                            );
                            $groupdropdown->setValue(''); 
                            echo $groupdropdown->render(); 
                       ?>
                    </div>
                    &nbsp;<input type="checkbox" name="subgrouptrigger" id="subgrouptrigger" class="lineblocked" value="1" title="Switch entry mode" placeholder="enter free text" /> 
                <?php } else { ?>
                    <?php echo isEmptyString($user->getSubGroupID()) ? "--" : $user->getSubGroup()->getName(); ?>
                    <input type="hidden" id="subgroupid" name="subgroupid" value="<?php echo $user->getSubGroupID(); ?>" /> 
                <?php } ?>
          </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="phone"><label class="control-label"><?php echo $this->translate("farmer_phone_label"); ?>: </label>
        <div class="controls">
            <div class="input-prepend" style="width:250px; display:block;">
                <span class="add-on"><?php echo '+'.$countrycode; ?></span>
                <input type="text" name="phone" id="phone" maxlength="10" value="<?php echo getShortPhone($user->getPhone()); ?>" class="span2 minwidth100" style="margin-top:0;" />
            </div>
            <?php if(false){ ?>
				<?php if($user->isUserInActive() || isEmptyString($user->getID())){ ?>
                     <div class="blocked" style="margin-top:5px; width:250px; display:block;"><input type="checkbox" name="isphoneinvited" id="isphoneinvited" value="1" style="margin-top:0;" /> &nbsp;
                     <label class="lineblocked">Invite to activate via Phone</label></div>
                <?php } ?>
            <?php } ?>
            <div id="phone_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="email"><?php echo $this->translate("farmer_email_label"); ?>: </label>
        <div class="controls">
            <input type="text" name="email" id="email" value="<?php echo $user->getEmail(); ?>" class="span3" />
            <?php if($user->isUserInActive() || isEmptyString($user->getID())){ ?>
                 <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="isinvited" id="isinvited" value="1" /> &nbsp;
                 <label class="lineblocked">Invite to activate via Email</label></div>
            <?php } ?>
            <div id="email_error"></div>
        </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="username">Username:</label>
      <div class="controls">
        <input name="username" id="username" type="text" class="span2" value="<?php echo $user->getUsername(); ?>" />
        <?php if(false){ ?>
        
        <?php } ?>
      </div>
    </div>
    <?php if($request->type == 'other' || !$user->isFarmer()){ ?>
        <?php if($user->isUserActive()){ ?>
            <div class="control-group">
              <label class="control-label" for="oldpassword">Current Password:</label>
              <div class="controls">
                <input name="oldpassword" id="oldpassword" type="password" class="span2" value="" />
              </div>
            </div>
        <?php } ?>
        <div class="control-group">
          <label class="control-label" for="username">New Password:</label>
          <div class="controls">
            <input name="password" id="password" type="password" class="span2" value="" />
          </div>
        </div>
        <?php if($user->isUserInActive()){ ?>
            <div class="control-group">
              <label class="control-label" for="confirmpassword">Confirm Password:</label>
              <div class="controls">
                <input name="confirmpassword" id="confirmpassword" type="password" class="span2" value="" />
                <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="adminactivate" id="adminactivate" value="1" /> &nbsp;
                <label class="lineblocked">Activate now</label></div>
                <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="sendlogintophone" id="sendlogintophone" value="1" /> &nbsp;
                <label class="lineblocked">Send Login Details to Phone</label></div>
                <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="sendlogintoemail" id="sendlogintoemail" value="1" /> &nbsp;
                <label class="lineblocked">Send Login Details to Email</label></div>
              </div>
            </div>
        <?php } ?>    
    <?php } ?>
</fieldset>
<div class="divider15"></div>
<fieldset class="fieldsetcontainer well">
    <legend>Location</legend>
    <div class="control-group">
      <label class="control-label" for="country"><?php echo $this->translate("global_country_label"); ?>:</label>
      <div class="controls">
        <?php
            $countries = getCountries();
            $countrydropdown = new Zend_Form_Element_Select('country',
                                array(
                                    'multiOptions' => array_merge_maintain_keys(array('' => "<Select One>", "UG"=>"Uganda"), $countries),
                                    'view' => new Zend_View(), 
                                    'decorators' => array('ViewHelper'),
                                    'class' => array('span2', 'disabledfield')                                                            )
                            );
            $countrydropdown->setValue($thecountry); 
            echo $countrydropdown->render(); 
        ?><input type="hidden" name="country" id="country" value="<?php echo $thecountry; ?>" />
        <div id="country_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="districtid"><?php echo $location_label; ?>:</label>
      <div class="controls">
            <?php
                $districts = getDistricts($session->getVar('country'));
                $districtdropdown = new Zend_Form_Element_Select('districtid',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districts),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $districtdropdown->setValue($user->getLocationID()); 
                echo $districtdropdown->render(); 
           ?>
           <div id="districtid_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="county"><?php echo $county_label; ?>:</label>
      <div class="controls">
        <select name="countyid" id="countyid" class="span2">
          <option value="">&lt;Select One&gt;</option>
        </select>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="subcounty"><?php echo $subcounty_label; ?>:</label>
      <div class="controls">
        <select name="subcountyid" id="subcountyid" class="span2">
          <option value="">&lt;Select One&gt;</option>
        </select>
      </div>
    </div>
    <?php if(isUganda()){ ?>
        <div class="control-group">
          <label class="control-label" for="parish"><?php echo $this->translate("global_parish_label"); ?>:</label>
          <div class="controls">
            <div class="parish_text inline">
                <input type="text" name="parishname" id="parishname" class="span2" value="<?php //echo $user->getVillageName(); ?>"  />
            </div>
            <div class="parish_select inline">
                <select name="parishid" id="parishid" class="span2">
                  <option value="">&lt;Select One&gt;</option>
                </select>
            </div>
            &nbsp;<input type="checkbox" name="parishtrigger" id="parishtrigger" class="lineblocked" value="1" title="Switch entry mode" placeholder="enter free text" /> 
            <div id="parishname_error"></div><div id="parishid_error"></div>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label" for="village"><?php echo $this->translate("global_village_label"); ?>:</label>
          <div class="controls">
            <div class="village_text inline">
                <input type="text" name="villagename" id="villagename" class="span2" value="<?php //echo $user->getVillageName(); ?>"  />
            </div>
            <div class="village_select inline">
                <select name="villageid" id="villageid" class="span2">
                  <option value="">&lt;Select One&gt;</option>
                </select>
            </div>
            &nbsp;<input type="checkbox" name="villagetrigger" id="villagetrigger" class="lineblocked" value="1" title="Switch entry mode" placeholder="enter free text" /> 
            <div id="villagename_error"></div><div id="villageid_error"></div>
          </div>
        </div>
        <?php } ?>
    <div class="control-group">
      <label class="control-label" for="address"><?php echo $this->translate("contact_address_label"); ?>:</label>
      <div class="controls">
        <textarea name="streetaddress" id="streetaddress" class="span4 expanding" style="min-height:60px;"><?php echo $user->getStreetAddress(); ?></textarea>
      </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="lat"><?php echo $this->translate("farmer_gps_label")." ".$this->translate("farmer_latitude_label"); ?>:</label>
        <div class="controls">
            <input name="lat" id="lat" type="text" class="span2 minwidth100" value="<?php echo $user->getLat(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="lng"><?php echo $this->translate("farmer_gps_label")." ".$this->translate("farmer_longitude_label"); ?>:</label>
        <div class="controls">
            <input name="lng" id="lng" type="text" class="span2 minwidth100" value="<?php echo $user->getLng(); ?>" />
        </div>
    </div>
</fieldset>
<fieldset class="fieldsetcontainer well hideonsuper">
    <legend>About</legend>            
    <div class="control-group">
        <label class="control-label" for="bio"><?php echo $this->translate("farmer_biography_label"); ?>:</label>
        <div class="controls">
            <textarea name="bio" id="bio" class="span4 expanding" style="min-height:65px;"><?php echo $user->getBio(); ?></textarea>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="educationlevel"><?php echo $this->translate("farmer_educlevel_label"); ?>:</label>
        <div class="controls">
            <?php
                $educlevels = getAllEducationLevels();
                $educleveldropdown = new Zend_Form_Element_Select('educationlevel',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $educlevels),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $educleveldropdown->setValue($user->getEducationLevel()); 
                echo $educleveldropdown->render(); 
           ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="maritalstatus"><?php echo $this->translate("farmer_maritalstatus_label"); ?>:</label>
        <div class="controls">
            <?php
                $maritalstatuses = getAllMaritalStatuses();
                $maritalstatusesdropdown = new Zend_Form_Element_Select('maritalstatus',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $maritalstatuses),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $maritalstatusesdropdown->setValue($user->getMaritalStatus()); 
                echo $maritalstatusesdropdown->render(); 
           ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="nochildren"><?php echo $this->translate("farmer_nochildren_label"); ?>:</label>
        <div class="controls">
            <input name="numberofchildren" id="numberofchildren" type="text" class="span2 minwidth100 centeralign isnumber" value="<?php echo $user->getNumberOfChildren(); ?>" /><div id="numberofchildren_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="numberofdependants"><?php echo $this->translate("farmer_nodependants_label"); ?>:</label>
        <div class="controls">
            <input name="numberofdependants" id="numberofdependants" type="text" class="span2 minwidth100 centeralign isnumber" value="<?php echo $user->getNumberOfDependants(); ?>" /><div id="numberofdependants_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="totalhousehold"><?php echo $this->translate("farmer_totalhousehold_label"); ?>:</label>
        <div class="controls">
            <input name="totalhousehold" id="totalhousehold" type="text" class="span2 minwidth100 centeralign isnumber" value="<?php echo $user->getTotalHousehold(); ?>" /><div id="totalhousehold_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="nextofkin_name"><?php echo $this->translate("farmer_nextofkin_label")." ".$this->translate("global_name_label"); ?>:</label>
        <div class="controls">
            <input name="nextofkin_name" id="nextofkin_name" type="text" class="span3" value="<?php echo $user->getNextofkin_Name(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="nextofkin_phone"><?php echo $this->translate("farmer_nextofkin_label")." ".$this->translate("global_phone_label"); ?>:</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><?php echo '+'.$countrycode; ?></span><input name="nextofkin_phone" id="nextofkin_phone" type="text" maxlength="10" class="span2 minwidth100 isnumber" value="<?php echo $user->getNextofkin_phone(); ?>" placeholder="e.g 0712123456" />
            </div>
            <div id="nextofkin_phone_error"></div>
        </div>
    </div>
</fieldset>
<fieldset class="fieldsetcontainer well hideonsuper">
    <legend>Farm</legend>            
    <div class="control-group">
      <label class="control-label" for="businessname"><?php echo $this->translate("farm_name_label"); ?>:</label>
      <div class="controls">
        <input type="text" name="businessname" id="businessname" value="<?php echo $user->getName(); ?>" class="span3" /><div id="businessname_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="startyear"><?php echo $this->translate("farm_since_label"); ?>:</label>
      <div class="controls">
        <?php
            $years = getAllYears("63","0");
            $yeardp = new Zend_Form_Element_Select('bizstartyear',
                                array(
                                    'multiOptions' => array_merge_maintain_keys(array('' => 'Year'), $years),	
                                    'view' => new Zend_View(),
                                    'decorators' => array('ViewHelper'),
                                    'class' => array('width80')
                                )
                            );
            $yeardp->setValue($user->getBizStartYear()); 
            echo $yeardp->render(); 
        ?>
        <?php
            $monthdp = new Zend_Form_Element_Select('bizstartmonth',
                                array(
                                    'multiOptions' => array_merge_maintain_keys(array('' => 'Month'), getAllMonthsAsShortNames()),	
                                    'view' => new Zend_View(),

                                    'decorators' => array('ViewHelper'),
                                    'class' => array('width80')
                                )
                            );
            $monthdp->setValue($user->getBizStartMonth()); 
            echo $monthdp->render(); 
        ?>
        <div id="bizstartyear_error"></div><div id="bizstartmonth_error"></div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="numberofemployees"><?php echo $this->translate("farm_numberofemployees_label"); ?>:</label>
      <div class="controls">
        <input name="numberofemployees" id="numberofemployees" type="text" class="span1 minwidth80" value="<?php echo $user->getNumberOfEmployees(); ?>" />
      </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="landsize"><?php echo $this->translate("farm_landsize_label"); ?>:</label>
        <div class="controls">
            <input name="landsize" id="landsize" type="text" class="span2 minwidth100" value="<?php echo clean_num($user->getLandSize()); ?>" />&nbsp;&nbsp;
            <?php
                $landunits = getAreaUnits();
                $landunitdropdown = new Zend_Form_Element_Select('landunits',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $landunits),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('width80')
                                    )
                                );
                $landunitdropdown->setValue($user->getLandUnits()); 
                echo $landunitdropdown->render(); 
           ?><div id="landsize_error"></div><div id="landunits_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="landacquiremethod"><?php echo $this->translate("farm_landacquiremethod_label"); ?>:</label>
        <div class="controls">
            <?php
                $landmethods = getLandAcquireMethods();
                $landmethoddropdown = new Zend_Form_Element_Select('landacquiremethod',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $landmethods),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $landmethoddropdown->setValue($user->getLandAcquireMethod()); 
                echo $landmethoddropdown->render(); 
           ?><div id="landacquiremethod_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="landsizeactive"><?php echo $this->translate("farm_landsizeactive_label"); ?>:</label>
        <div class="controls">
            <input name="landactivesize" id="landactivesize" type="text" class="span1 minwidth80" value="<?php echo clean_num($user->getLandActiveSize()); ?>" /> <span class="pagedescription" id="activeland"></span><div id="landactivesize_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="farmlands"><?php echo $this->translate("farm_farmlands_label"); ?>:</label>
        <div class="controls">
            <?php
                $fieldcount = array("1"=>"1","2"=>"2","3"=>"3","4"=>"4");
                $fieldsdropdown = new Zend_Form_Element_Select('numberoffields',
                                    array(
                                        'multiOptions' => $fieldcount,								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span1 minwidth80')
                                    )
                                );
                $fieldsdropdown->setValue($user->getNumberOfFields()); 
                echo $fieldsdropdown->render(); 
           ?><div id="numberoffields_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="crops">Crops:</label>
        <div class="divider10"></div>
        <span class="pagedescription blocked">Select your current priority Crop(s) or the Crops for which you would like too receive regular Market Information via SMS and Email</span>
		<?php 
            $commodities = getFarmisCommodities();
            $preselectarray = $user->getCropIDs();
            if(!isEmptyString($session->getVar(ERROR_MESSAGE))){
                $preselectarray = $formvalues['cropids'];
            }
            $crop1 = ''; $crop2 = ''; $crop3 = '';
            if(!isArrayKeyAnEmptyString(0, $preselectarray)){
                $crop1 = $preselectarray[0];
            }
            if(!isArrayKeyAnEmptyString(1, $preselectarray)){
                $crop2 = $preselectarray[1];
            }
            if(!isArrayKeyAnEmptyString(2, $preselectarray)){
                $crop3 = $preselectarray[2];
            }
        ?>
        <div class="controls blocked">
        	1. <?php
                $dropdown1 = new Zend_Form_Element_Select('crop_1',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $commodities),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $dropdown1->setValue($crop1); 
                echo $dropdown1->render(); 
           ?>
        </div>
        <div class="controls blocked" style="margin-top:5px;">
        	2. <?php
                $dropdown2 = new Zend_Form_Element_Select('crop_2',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $commodities),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $dropdown2->setValue($crop2); 
                echo $dropdown2->render(); 
           ?>
        </div>
        <div class="controls" style="margin-top:10px;">
        	3. <?php
                $dropdown3 = new Zend_Form_Element_Select('crop_3',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $commodities),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2')
                                    )
                                );
                $dropdown3->setValue($crop3); 
                echo $dropdown3->render(); 
           ?>
        </div>
    </div>
    <?php if(isUganda()){ ?>
    	<div class="control-group">
            <label class="control-label">Market Locations:</label>
            <div class="divider10"></div>
            <span class="pagedescription blocked">Select the Market(s) that you are Interested in or those Markets from which we shall send you weekly Prices and any other Market Information.</span>
            <?php 
                $markets = getMarkets();
				$preselectarray = $user->getMarketIDs();
				if(!isEmptyString($session->getVar(ERROR_MESSAGE))){
					if(!isArrayKeyAnEmptyString('market_1', $formvalues)){
						$formvalues['marketids'][0] = $formvalues['market_1'];
						$formvalues['marketids'][1] = $formvalues['market_2'];
						$formvalues['marketids'][2] = $formvalues['market_3'];
					}
					$preselectarray = $formvalues['marketids'];
				}
				$market1 = ''; $market2 = ''; $market3 = '';
				if(!isArrayKeyAnEmptyString(0, $preselectarray)){
					$market1 = $preselectarray[0];
				}
				if(!isArrayKeyAnEmptyString(1, $preselectarray)){
					$market2 = $preselectarray[1];
				}
				if(!isArrayKeyAnEmptyString(2, $preselectarray)){
					$market3 = $preselectarray[2];
				}
            ?>
            <div class="controls blocked">
                1. <?php
                    $dropdown1 = new Zend_Form_Element_Select('market_1',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $markets),								
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span2')
                                        )
                                    );
                    $dropdown1->setValue($market1); 
                    echo $dropdown1->render(); 
               ?>
            </div>
            <div class="controls blocked" style="margin-top:5px;">
                2. <?php
                    $dropdown2 = new Zend_Form_Element_Select('market_2',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $markets),								
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span2')
                                        )
                                    );
                    $dropdown2->setValue($market2); 
                    echo $dropdown2->render(); 
               ?>
            </div>
            <div class="controls" style="margin-top:10px;">
                3. <?php
                    $dropdown3 = new Zend_Form_Element_Select('market_3',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $markets),								
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span2')
                                        )
                                    );
                    $dropdown3->setValue($market3); 
                    echo $dropdown3->render(); 
               ?>
            </div>
       	</div>
    <?php } ?>
    <div class="control-group">
        <label class="control-label" for="enterpriseids">Other Enterprises:</label>
        <div class="controls">
        
            <?php
                $preselectarray = $user->getEnterpriseIDs();
                if(!isEmptyString($session->getVar(ERROR_MESSAGE))){
                    $preselectarray = $formvalues['cropids'];
                }
                // debugMessage($preselectarray);
                $enterprises = getOtherEnterprises();
            ?>
            <ul class="nav croplist">
                <?php foreach($enterprises as $key => $value){
                        $isselected = false;
                        if(in_array($key, $preselectarray)){
                            // debugMessage('is selected');
                            $isselected = true;
                        }
                ?>
                    <li><label for="cropids-<?php echo $key; ?>"><input type="checkbox" class="checkbox <?php echo $isselected == true ? 1 : 0; ?>" id="enterpriseids-<?php echo $key; ?>" name="cropids[]" value="<?php echo $key; ?>" />&nbsp; <?php echo $value; ?></label></li>
                <?php } ?>
            </ul>
        </div>
    </div>
</fieldset>
<?php if(isUganda() && isAdmin() && false){ ?>
<fieldset class="fieldsetcontainer well xhideonsuper">
    <legend>Intake Assessment</legend>  
    <div class="control-group">
        <label class="control-label maxwidth">Where do you sell your produce?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('WHERETO_SELL'); ?>
			<?php 
                $existing_values = getDataArray($user->getWhereToSell());
                foreach($options as $key => $value){
            ?>
                <label class="checkbox-inline notbolded inline" style="margin-right:10px;">
                  <input type="checkbox" id="workshiftids_<?php echo $key; ?>" name="wheretosellids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;"> <?php echo $value; ?>
                </label>
            <?php } ?>
            <input type="hidden" name="wheretosell_old" id="wheretosell_old" value="<?php echo $user->getWhereToSell(); ?>" />
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label maxwidth">Preferred Communication Methods:</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('PREFERRED_COMMUNICATION'); ?>
			<?php 
                $existing_values = getDataArray($user->getpreferredcommunication());
                foreach($options as $key => $value){
            ?>
                <label class="checkbox-inline notbolded inline" style="margin-right:10px;">
                  <input type="checkbox" id="preferredcommunicationids_<?php echo $key; ?>" name="preferredcommunicationids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;"> <?php echo $value; ?>
                </label>
            <?php } ?>
            <input type="hidden" name="preferredcommunication_old" id="preferredcommunication_old" value="<?php echo $user->getpreferredcommunication(); ?>" />
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label maxwidth">Are you willing to pay for Market Information?</label>
        <div class="controls" style="margin-left:0;">
        	<label class="radio-inline inline" style="margin-right:20px;">
            	<input type="radio" name="willingtopay" id="willingtopay_1" class="<?php echo $user->getwillingtopay() == '1' ? '1' : ''; ?>" value="1" style="margin-top:-2px;" /> &nbsp;Yes
            </label>
            <label class="radio-inline inline">
                <input type="radio" name="willingtopay" id="willingtopay_0" class="<?php echo $user->getwillingtopay() == '0' ? '1' : ''; ?>" value="0" style="margin-top:-2px;" /> &nbsp;No
            </label>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label maxwidth">If yes, when do you plan to pay?</label>
        <div class="controls" style="margin-left:0;">
        	<input type="text" class="form-control input-sm datefield readonly width100" name="whentopay" id="whentopay" value="<?php echo changeMySQLDateToPageFormat($user->getwhentopay()); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Is organisation paying for you?</label>
        <div class="controls" style="margin-left:0;">
        	<label class="radio-inline inline" style="margin-right:20px;">
            	<input type="radio" name="isorgpaying" id="isorgpaying_1" class="<?php echo $user->getisorgpaying() == '1' ? '1' : ''; ?>" value="1" style="margin-top:-2px;" /> &nbsp;Yes
            </label>
            <label class="radio-inline inline">
                <input type="radio" name="isorgpaying" id="isorgpaying_0" class="<?php echo $user->getisorgpaying() == '0' ? '1' : ''; ?>" value="0" style="margin-top:-2px;" /> &nbsp;No
            </label>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Give details of Organisation:</label>
        <div class="controls" style="margin-left:0;">
        	<input name="supportprovider" id="supportprovider" type="text" class="span6" value="<?php echo $user->getsupportprovider(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Which radio stations do you listen to?</label>
        <div class="controls" style="margin-left:0;">
        	<textarea name="radiostations" id="radiostations" type="text" class="span6 expanding"><?php echo $user->getradiostations(); ?></textarea>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Which agricultural programs do you listen to?</label>
        <div class="controls" style="margin-left:0;">
        	<textarea name="radioshows" id="radioshows" type="text" class="span6 expanding"><?php echo $user->getradioshows(); ?></textarea>
        </div>
    </div>
    <div class="divider10"></div>
    <div class="subheadcontainer"><label class="subheading">Saving Culture</label></div>
    <div class="control-group">
      <label class="control-label" style="width:100%;">Do you have a Mobile Money Account?</label>
      <div class="controls" style="margin-left:0;">
         <div class="inline" style="margin-right:20px;">
         	<input type="radio" name="hasmobilemoney" id="hasmobilemoney_1" class="<?php echo $user->gethasmobilemoney() == '1' ? '1' : ''; ?>" value="1" /> &nbsp;<label class="lineblocked">Yes</label>
         </div>
         <div class="inline">
         	<input type="radio" name="hasmobilemoney" id="hasmobilemoney_0" class="<?php echo $user->gethasmobilemoney() == '0' ? '1' : ''; ?>" value="0" /> &nbsp;<label class="lineblocked">No</label>
         </div>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" style="width:100%;">Do you have a Bank Account?</label>
      <div class="controls" style="margin-left:0;">
         <div class="inline" style="margin-right:20px;">
         	<input type="radio" name="hasbankaccount" id="hasbankaccount_1" class="<?php echo $user->gethasbankaccount() == '1' ? '1' : ''; ?>" value="1" /> &nbsp;<label class="lineblocked">Yes</label>
         </div>
         <div class="inline">
         	<input type="radio" name="hasbankaccount" id="hasbankaccount_0" class="<?php echo $user->gethasbankaccount() == '0' ? '1' : ''; ?>" value="0" /> &nbsp;<label class="lineblocked">No</label>
         </div>
      </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Which of these are you actually doing?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('MONEY_BEHAVIOR'); ?>
			<?php 
                $existing_values = getDataArray($user->getmoneybehavior());
                foreach($options as $key => $value){
            ?>
                <label class="checkbox-inline notbolded" style="margin-right:10px;">
                  <input type="checkbox" id="moneybehaviorids_<?php echo $key; ?>" name="moneybehaviorids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;"> <?php echo $value; ?>
                </label>
            <?php } ?>
            <input type="hidden" name="moneybehavior_old" id="moneybehavior_old" value="<?php echo $user->getmoneybehavior(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">If you put money in a safe place, where do you put it?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('MONEY_PLACES'); ?>
			<?php 
                $existing_values = getDataArray($user->getmoneyplace());
                foreach($options as $key => $value){
            ?>
                <label class="checkbox-inline inline notbolded" style="margin-right:10px;">
                  <input type="checkbox" id="moneyplaceids_<?php echo $key; ?>" name="moneyplaceids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="moneyplace_old" id="moneyplace_old" value="<?php echo $user->getmoneyplace(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">What do you do with your savings?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $savingoptions = getDataOptionsAsArray('SAVING_PLAN'); ?>
			<?php 
                $existing_values = getDataArray($user->getsavingplan());
                foreach($savingoptions as $key => $value){
            ?>
                <label class="checkbox-inline inline notbolded" style="margin-right:10px;">
                  <input type="checkbox" id="savingplanids_<?php echo $key; ?>" name="savingplanids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;"> <?php echo $value; ?>
                </label>
            <?php } ?>
            <input type="hidden" name="savingplan_old" id="savingplan_old" value="<?php echo $user->getsavingplan(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Have you ever taken loan?</label>
        <div class="controls" style="margin-left:0;">
        	<label class="radio-inline inline" style="margin-right:20px;">
            	<input type="radio" name="takenloan" id="takenloan_1" class="<?php echo $user->gettakenloan() == '1' ? '1' : ''; ?>" value="1" style="margin-top:-2px;" /> &nbsp;Yes
            </label>
            <label class="radio-inline inline">
                <input type="radio" name="takenloan" id="takenloan_0" class="<?php echo $user->gettakenloan() == '0' ? '1' : ''; ?>" value="0" style="margin-top:-2px;" /> &nbsp;No
            </label>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">How long did it take you to pay back the loan?</label>
        <div class="controls" style="margin-left:0;">
        	<input name="paybackperiod" id="paybackperiod" type="text" class="span2" value="<?php echo $user->getpaybackperiod(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Have you ever had difficulties to pay back a loan? </label>
        <div class="controls" style="margin-left:0;">
        	<label class="radio-inline inline" style="margin-right:20px;">
            	<input type="radio" name="paydifficulty" id="paydifficulty_1" class="<?php echo $user->getpaydifficulty() == '1' ? 1 : ''; ?>" value="1" style="margin-top:-2px;" /> &nbsp;Yes
            </label>
            <label class="radio-inline inline">
                <input type="radio" name="paydifficulty" id="paydifficulty_0" class="<?php echo $user->getpaydifficulty() == '0' ? 1 : ''; ?>" value="0" style="margin-top:-2px;" /> &nbsp;No
            </label>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">What arrangements have you made for old age?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('RETIREMENT_PLANS'); ?>
			<?php 
                $existing_values = getDataArray($user->getoldageplan());
                foreach($options as $key => $value){
            ?>
                <label class="checkbox-inline notbolded" style="margin-right:10px;">
                  <input type="checkbox" id="oldageplanids_<?php echo $key; ?>" name="oldageplanids[]" class="" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked' : 1; ?> style="margin-top:-2px;"> <?php echo $value; ?>
                </label>
            <?php } ?>
            <input type="hidden" name="oldageplan_old" id="oldageplan_old" value="<?php echo $user->getoldageplan(); ?>" />
        </div>
    </div>
    <div class="divider10"></div>
    <div class="subheadcontainer"><label class="subheading">Budgeting</label></div>
    <div class="control-group">
        <label class="control-label maxwidth">How do you keep track of your income and spending?</label>
        <div class="controls" style="margin-left:0;">
        	<?php
                $allvalues = getDataOptionsAsArray('BUDGET_METHODS');
                $dropdown = new Zend_Form_Element_Select('budgettracking',
                                    array(
                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array('span2 minwidth100')
                                    )
                                );
                $dropdown->setValue($user->getbudgettracking()); 
                echo $dropdown->render(); 
           ?><div id="updatesfrequency_error"></div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Do you know how much money you have earned and spent in the last week?</label>
        <div class="controls" style="margin-left:0;">
        	<span class="span2" style="margin-left:0; margin-right:5px; display:inline;">
            	<label class="control-label notbolded">Earned (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="earnedlastwk" id="earnedlastwk" type="text" class="span2" value="<?php echo $user->getearnedlastwk(); ?>" />
            </span>
            <span class="span2" style="margin-left:0; margin-right:0; display:inline;">
            	<label class="control-label notbolded">Spent (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="spentlastwk" id="spentlastwk" type="text" class="span2" value="<?php echo $user->getspentlastwk(); ?>" />
            </span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Do you know how much money you have earned and spent in the last month?</label>
        <div class="controls" style="margin-left:0;">
        	<span class="span2" style="margin-left:0; margin-right:5px; display:inline;">
            	<label class="control-label notbolded">Earned (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="earnedlastmonth" id="earnedlastmonth" type="text" class="span2" value="<?php echo $user->getearnedlastmonth(); ?>" />
            </span>
            <span class="span2" style="margin-left:0; margin-right:0; display:inline;">
            	<label class="control-label notbolded">Spent (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="spentlastmonth" id="spentlastmonth" type="text" class="span2" value="<?php echo $user->getspentlastmonth(); ?>" />
            </span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Do you know how much money you have earned and spent in the last year?</label>
        <div class="controls" style="margin-left:0;">
        	<span class="span2" style="margin-left:0; margin-right:5px; display:inline;">
            	<label class="control-label notbolded">Earned (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="earnedlastyear" id="earnedlastyear" type="text" class="span2" value="<?php echo $user->getearnedlastyear(); ?>" />
            </span>
            <span class="span2" style="margin-left:0; margin-right:0; display:inline;">
            	<label class="control-label notbolded">Spent (<?php echo getCurrencySymbol(); ?>):</label>
	        	<input name="spentlastyear" id="spentlastyear" type="text" class="span2" value="<?php echo $user->getspentlastyear(); ?>" />
            </span>
        </div>
    </div>
    <div class="divider10"></div>
    <div class="subheadcontainer"><label class="subheading">Financial Stress</label></div>
    <div class="control-group">
        <label class="control-label maxwidth">During the last month, did you eat less or of lower quality than usual because of lack of money?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->geteatless());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="eatless_<?php echo $key; ?>" name="eatless" class="<?php echo $key == $user->geteatless() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->geteatless() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="eatless_old" id="eatless_old" value="<?php echo $user->geteatless(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">During the last 6 Months, did you have to take out your children from school because of lacking funds?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->getchildlackoffunds());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="childlackoffunds_<?php echo $key; ?>" name="childlackoffunds" class="<?php echo $key == $user->getchildlackoffunds() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->getchildlackoffunds() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="childlackoffunds_old" id="childlackoffunds_old" value="<?php echo $user->getchildlackoffunds(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">During the last 6 Months, has/have any asset(s) of yours been seized by member(s) of your borrowing group or by your bank you failed to meet your (re-)payment obligations?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->getseizedforloan());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="seizedforloan_<?php echo $key; ?>" name="seizedforloan" class="<?php echo $key == $user->getseizedforloan() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->getseizedforloan() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="seizedforloan_old" id="seizedforloan_old" value="<?php echo $user->getseizedforloan(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">Do you (or any other member of your household) currently have any unpaid bills (open balance)?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->getunpaidbills());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="unpaidbills_<?php echo $key; ?>" name="unpaidbills" class="<?php echo $key == $user->getunpaidbills() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->getunpaidbills() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="unpaidbills_old" id="unpaidbills_old" value="<?php echo $user->getunpaidbills(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">During the last 6 Months, did your household have to sell any of its assets (i.e. land, motorcycle, etc.) to meet other payment obligations?</label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->getselloutassets());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="unpaidbills_<?php echo $key; ?>" name="unpaidbills" class="<?php echo $key == $user->getselloutassets() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->getselloutassets() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="selloutassets_old" id="selloutassets_old" value="<?php echo $user->getselloutassets(); ?>" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label maxwidth">How often during the last 6 Months did your household run out of money from previous revenues before the next revenues arrived (e.g. wages)? </label>
        <div class="controls" style="margin-left:0;">
        	<?php $options = getDataOptionsAsArray('DECISION_OPTIONS'); ?>
			<?php 
                $existing_values = getDataArray($user->getrunoutrevenue());
                foreach($options as $key => $value){
            ?>
                <label class="radio-inline inline notbolded" style="margin-right:10px;">
                  <input type="radio" id="unpaidbills_<?php echo $key; ?>" name="unpaidbills" class="<?php echo $key == $user->getrunoutrevenue() ? '1' : ''; ?>" value="<?php echo $key; ?>" <?php echo $key == $user->getrunoutrevenue() ? 'checked' : 1; ?> style="margin-top:-2px;" /> <?php echo htmlspecialchars($value); ?>
                </label>
            <?php } ?>
            <input type="hidden" name="runoutrevenue_old" id="runoutrevenue_old" value="<?php echo $user->getrunoutrevenue(); ?>" />
        </div>
    </div>
</fieldset>
<?php } ?>    
<fieldset class="fieldsetcontainer well xhideonsuper">
    <legend>Profile Settings</legend>  
    <?php if(($user->isFarmer() && !isEmptyString($user->getID())) || (isEmptyString($user->getID()) && in_array($request->getControllerName(), array('farmer','mobile')))){ ?>          
    	<?php require APPLICATION_PATH."/views/scripts/profile/settingfields.phtml"; ?>
    <?php } ?>
    <?php if(!$isme){ ?>
        <div class="control-group">
          <label class="control-label" style="width:100%;">Profiled By: <?php echo $this->translate("global_required_field_marker"); ?></label>
          <div class="controls" style="margin-left:0;">
            <?php if($acl->checkPermission('User Account', ACTION_CREATE)){ ?>
                <?php
                    $users = getProfilingUsers($session->getVar('country'));
                    $dropdown = new Zend_Form_Element_Select('profiledby',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $users),								
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span2')
                                        )
                                    );
                    $dropdown->setValue($user->getCreatedBy()); 
                    echo $dropdown->render(); 
                  ?>
            <?php } else { ?>
                <?php echo $loggedinuser->getName(); ?>
            <?php } ?>
            <div id="profiledby_error"></div>
          </div>
    </div>
    <?php } ?>
</fieldset>
<div class="control-group well actions" id="bottomactions"></div>
