<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	
	$theid = decode($request->id);
	if(isEmptyString($theid)){
		$theid = $userid;
	}
	if(!isEmptyString($theid)){
		$user->populate($theid);
	}
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya() || $user->isKenyan()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	
	// debugMessage($user->toArray()); exit();
	$id = $user->getID();	
	$name = $user->getName();
	$firstname = $user->getFirstName();
	
	# profile for one viewing
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	
	$tab = $request->tab;
	if(isEmptyString($tab)) {
		$request->setParam('tab', 'basics');
	}
	
	$loadgps = false;
	$title = $user->getName();
	$this->headTitle($title);
	
?>
<script>
$(document).ready(function() {
	
	// remove box style if person has no profile picture
	<?php if($user->hasProfileImage()){ ?>
		$("#profileinfo").addClass('new_pic');
	<?php } ?>
	
}); 
</script>
<style>
#map {
	width: 100%;
	height: 450px;
}
#center .ui-widget-content {
	width:100%;
	float:left;
}
.alert.alert-success {
	width:90%;
}

</style>
<?php if(!isFarmer()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">   
        <div id="basics">
            <form id="profileform-basics" class="form-horizontal basics">
            <?php if($request->tab == 'basics'){ ?>
        	<div class="row" style="margin-left:0px;">
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <span class="span6 marginleft0" style="width:70%;">
                    <div id="row1_left" class="well row marginleft0" style="min-height:250px; padding-left:10px;">                        
                        <table class="table noborder">                       
                           	<tr>
                                <td style="width:20%;"><label class="control-label"><?php echo "Full ".$this->translate("farmer_name_label"); ?>:</label></td>
                                <td style="width:32%;"><?php echo $user->getName(); ?><?php echo $user->getSalutationLabel(); ?></td>
                                <td style="width:23%;"><label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>:</label></td>
                                <td><?php echo $user->getGenderLabel(); ?></td>                                                             
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label></td>
                                <td><?php echo $user->getBirthDateFormatted(); ?></td>
                                <td><label class="control-label"><?php echo $this->translate("farmer_country_label"); ?>:</label></td>
                                <td><?php echo $user->getCountryName(); ?></td>
                                                           
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("farmer_dateregistered_label"); ?>:</label></td>
                                <td><?php echo isEmptyString($user->getRegDate()) ? '--' : changeMySQLDateToPageFormat($user->getRegDate()); ?></td>          
                                <td><label class="control-label"><?php echo $location_label; ?>:</label></td>
                                <td><?php echo isEmptyString($user->getLocationID()) ? '--' : $user->getLocation()->getName(); ?></td>
                            </tr>
                            <tr>		                    
                                <td><label class="control-label prefix"><?php echo strtolower($country) == 'ug' ? $this->translate("farmer_refno_label") : 'National ID/FIN'; ?>:</label></td>
                                <td><?php echo $user->getRefNo(); ?></td>
                                <?php if(strtolower($country) == 'ug'){ ?>
                                    <td><label class="control-label prefix"><?php echo $this->translate("farmer_regno_label"); ?>:</label></td>
                                    <td><?php echo $user->getRegNo(); ?></td>  
                                <?php } else { ?>
                                	<td></td>
                                    <td></td>  
                                <?php } ?>
                            </tr>       
                            <tr>
                                <td><label class="control-label"><?php //echo $this->translate("farmer_profilepath_label").':'; ?></label></td>
                                <td colspan="3"><?php //echo $user->getProfilePath(); ?></td>                                                             
                            </tr>
                            <?php if($user->hasFarmGroup()){ ?>  
                            <tr>
                                <td colspan="2"><label class="control-label"><?php echo $this->translate("farmer_dna_label"); ?>:</label>
									<?php echo isEmptyString($user->getFarmGroupID()) ? '--' : $user->getFarmGroup()->getName(); ?></td>
                                <td colspan="2">
                                	<?php if($user->hasSubGroup()){ ?>  
                                        <label class="control-label"><?php echo $this->translate("farmer_subgroup_label"); ?>:</label>
                                        <?php echo isEmptyString($user->getFarmGroupID()) ? '--' : $user->getSubGroup()->getName(); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                            <?php if($user->isFarmer()){ ?>
                            <tr>
                                <td colspan="2" style="width:50%;"><label class="control-label"><?php echo $this->translate("farmer_farminigtypes_label"); ?>: </label>
                                    <?php echo $user->getFarminigTypesLabel(); ?>
                                </td>
                                <td colspan="2">
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" style="width:50%;"><label class="control-label"><?php echo $this->translate("farmer_activities_label"); ?>:</label>
                                    <?php echo $user->getActivityTypesLabel(); ?>
                                </td>
                                <td colspan="2">
                                </td>
                            </tr>
                            <?php } ?>
                        </table>
                    </div>
                    <div id="xrow2_left" class="well row marginleft0" style="height:170px;">
                        <h3 class="well-legend margin0">About</h3>
                        <table class="table">                       
                           <tr>		                    
                                <td valign="top"><?php echo isEmptyString($user->getBio()) ? '--' : nl2br($user->getBio()); ?></td>
                           </tr>
                        </table>
                    </div>                    
                    
                </span> 
                <span class="span3 pull-right" style="width:24%; margin-right:20px; ">
                    <div id="xrow1_right" class="well row" style="min-height:115px;">
                        <h3 class="well-legend margin0">Quick Links</h3>
                        <table class="table">                       
                           <tr>		                    
                                <td class="formactions">
								<?php if($isme || isFarmGroupAdmin() || isAdmin()){ ?>
                          			<a class="btn btn-primary" style="width:65px;" href="<?php echo $this->baseUrl('profile/index/id/'.encode($id)); ?>" id="update"><i class="icon-pencil icon-white"></i> Update</a> &nbsp;
                                <?php } ?>
                                <?php if(!$isme && (isFarmGroupAdmin() || isAdmin())){ 
									$successpage = $this->baseUrl('profile/list');
									if(!$user->isFarmer()){
										$successpage = $this->baseUrl('profile/list');
									}
								?>
                                	<a style="display:inline-block; "href="javascript: void(0)" id="deleteline_multiple" title="Delete Entry" class="btn btn-mini deleteline noimgbutton" action="<?php echo $this->baseUrl('profile/delete/id/'.$user->getID()."/entityname/UserAccount/successurl/".encode($successpage)); ?>"><i class="icon-trash"></i></a>
                                <?php } ?>
                                <?php if(isFarmer()){ ?>
                                	<a class="btn" href="<?php echo $this->referer; ?>"><i class="icon-arrow-left"></i> Back</a>
                                <?php } else { ?>
                                	<a class="btn" href="<?php echo $this->baseUrl('profile/list'); ?>"><i class="icon-arrow-left"></i> Farmers</a>
                                <?php } ?>
                              	</td>
                           </tr>
                        </table>
                    </div>
                    <div id="xrow2_right" class="well row" style="min-height:305px;">
                        <h3 class="well-legend margin0">Summary</h3>
                        <table class="table table-striped table-bordered table-condensed" id="stats">
                            <tr>		                    
                                <td class="profilerightlabel">Account Type:</td>
                                <td class="profilerightvalue"><?php echo $user->getPlan()->getName(); ?></td>
                            </tr>
                            <tr>		                    
                                <td class="profilerightlabel">Date Joined:</td>
                                <td class="profilerightvalue"><?php echo isEmptyString($user->getActivationDate()) ? '--' : changeMySQLDateToPageFormat($user->getActivationDate()); ?></td>
                            </tr>
                            <tr>		                    
                                <td class="profilerightlabel">Subscription Start:</td>
                                <td class="profilerightvalue"><?php echo changeMySQLDateToPageFormat($user->getLatestSubscription()->getStartDate()); ?></td>
                            </tr>
                            <tr>		                    
                                <td class="profilerightlabel">Expiry Date:</td>
                                <td class="profilerightvalue"><?php echo changeMySQLDateToPageFormat($user->getLatestSubscription()->getEndDate()); ?></td>
                            </tr>
                            <tr>		                    
                                <td class="profilerightlabel">Profiled By:</td>
                                <td class="profilerightvalue"><?php echo $user->getCreator()->getName(); ?></td>
                            </tr>
                            <tr>		                    
                                <td class="profilerightlabel">Entry Date:</td>
                                <td class="profilerightvalue"><?php echo formatDateAndTime($user->getDateCreated(), true); ?></td>
                            </tr>
                        </table>
                    </div>
                </span>		
        	</div>
            <?php } ?>
        	</form> 
        </div>
        <div id="contacts">
            <h2>Gps</h2>
            <form id="profileform-contacts" class="form-horizontal contacts" action="<?php echo $this->baseUrl("profile/processgps"); ?>" method="post">
                <?php 
					$metxt = '';
					if($isme){
						$metxt = 'My ';
				?>
					<script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7" type="text/javascript"></script>
                    <script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/maps/maplace.min.js')); ?>"></script>
                <script>
					$(document).ready(function() {
						<?php if($user->hasGPSCoordinates() && isEmptyString($request->detect)){ ?>
							var gpslat = '0.313611';
							var gpslng = '32.581111';
							var title = "My Location"
						<?php } ?>
						<?php if(!isEmptyString($request->detect)){ ?>
							initialiseMap2();
							initialise2();
							var gpslat = '<?php echo $user->getlat(); ?>';
							var gpslng = '<?php echo $user->getlng(); ?>';
							$("#lat").val(gpslat);
							$("#lng").val(gpslng);
								
							$("#profileform-contacts").validate({		
								// define the validation rules one field at a time
								rules: {
									lat: {
										required: true, 					
										maxlength: 10
									},
									lng: {
										required: true, 					
										maxlength: 10
									}
								}, 
								// the messages for each of the fields being validated
								messages: {		
									lat: {
										required: "Please enter coordinates", 					
										maxlength: "Length must not exceed 10 characters"
									},
									lng: {
										required: "Please enter coordinates", 					
										maxlength: "Length must not exceed 10 characters"
									}
								},
								// custom error positions
								errorPlacement: function(error, element) {
									switch(element.attr("name")){					
										default:
											error.appendTo("#hasgps_error")
											break;
									}			
								}
							});
							
							// initialise the google map
							function initialiseMap2(){
								var myOptions = {
									  zoom: 14,
									  mapTypeControl: true,
									  mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
									  navigationControl: true,
									  navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
									  mapTypeId: google.maps.MapTypeId.ROADMAP      
									}        
								map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
							}
							function initialise2() {
								if(geoPosition.init()){
									document.getElementById('current').innerHTML="Receiving location... please wait... <br / ><br />Click on 'Share Location' to allow your browser to detect your current location";
									geoPosition.getCurrentPosition(
										showPosition,
										function(){
											document.getElementById('current').innerHTML="Couldn't get location"
										},
										{maximumAge:60000, timeout:10000, enableHighAccuracy:true}
									);
								} else {
									document.getElementById('current').innerHTML="Your Browser is not supported for this function";
								}
							}
						
							function showPosition(p){
								var latitude = parseFloat(p.coords.latitude);
								latitude = latitude.toFixed(6);
								
								var longitude = parseFloat(p.coords.longitude);
								longitude = longitude.toFixed(6);
								
								$("#lat").val(latitude);
								$("#lng").val(longitude);
								if(!isEmptyString(latitude) && !isEmptyString(longitude)){
									$("#hasgps").val(latitude+','+longitude);
								}
								document.getElementById('current').innerHTML=" Latitude: "+latitude+", Longitude: "+longitude+" <br /><br />Location successfully found. Click on 'Save Position' to update profile.<br />"
								
								$("#saveposition").show().removeClass('hide');
								
								var pos=new google.maps.LatLng(latitude, longitude);
								map.setCenter(pos);
								map.setZoom(18);
						
								var infowindow = new google.maps.InfoWindow({
									content: "<strong>New Location Found</strong> <br />Latitude: "+latitude+", <br /> Longitude: "+longitude+"<br /> "
								});
						
								var marker = new google.maps.Marker({
									position: pos,
									map: map,
									title:"You are here"
								});
						
								google.maps.event.addListener(marker, 'click', function() {
								  infowindow.open(map,marker);
								});
							} 
						<?php } ?>
					});
                </script>
                <div class="row marginleft0" style="width:96%;">
                    <h3 class="well-legend margin0">Location Map</h3>
                    <div class="divider5"></div>
                    <div class="well clearfix makerelative" style="min-height:500px; height:auto; background:none; background:url('<?php echo $this->baseUrl('images/uggoogle.png'); ?>') t; padding-bottom:10px; padding-top:10px;">
						<?php if(isEmptyString($request->detect)){ ?>
                            <a class="btn btn-primary makeabsolute" style="top:-25px; left:0;" href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/contacts/detect/1'); ?>"><?php echo $user->hasGPSCoordinates() ? 'Update '.$metxt.'Position' : 'Compute '.$metxt.'Location'; ?></a>
                            <!--<div id="map_canvas" class="gmaps"></div>-->
                            <div id="gmap"></div>
                        <?php } ?>
                        <?php if(!isEmptyString($request->detect)){ ?>
                            <div id="current" class="bolded">Initializing...</div>
                            <input type="text" id="lat" name="lat" value="" class="form-control input-width-small isdecimal" /> &nbsp;
                            <input type="text" id="lng" name="lng" value="" class="form-control input-width-small isdecimal" /><input type="hidden" id="hasgps" name="hasgps" value="" /><br /><br />
                            
                            <a href="<?php echo $this->referer; ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <a href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/contacts/detect/1'); ?>" class="btn"><i class="icon-refresh"></i> Reload</a>
                            <button type="submit" class="btn btn-primary hide" id="saveposition"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save')." Position"; ?></button>
                            <div class="form-group">
                                <div id="hasgps_error"></div>
                            </div>
                            <div id="map_canvas" class="gmaps"></div>
                            <div class="divider20"></div>	
                            <input type="hidden" name="entityname" value="UserAccount" />
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                            
                            
                            <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/contacts')); ?>" />
                            <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/contacts/detect/1')); ?>" />
                            <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                        <?php } ?>
                    </div>
                </div>
                <?php } ?>
            </form>
        </div>
    </div> 
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
