<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Load the profile, if no ID provided then use the profile of the currently logged in user
	$user = new UserAccount(); $loggedinuser = new UserAccount();
	if(isEmptyString($request->id)){
		$user->populate($userid);
	} else {
		$user->populate(decode($request->id));
	}
	
	$dob = ""; $dateofbirth = '';  $fdateofbirth = ''; $birthday = ''; $birthmonth = ''; $birthyear = '';
	
	$id = $user->getID();	
	$name = $user->getName();
	$firstname = $user->getFirstName();
	
	#cleanup address
	if(!isEmptyString($user->getID())){
		// $user->cleanUpAddress();
	}
	
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	
	$loggedinuser->populate($userid);
	
	$button_title = $this->translate("farmer_button_save");
	$posturl = $this->baseUrl("profile/edit"); 
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$user->processPost($session->getVar(FORM_VALUES));		
	}
	
	$tab = $request->tab;
	if(isEmptyString($tab)) {
		$tab = 'basics';
	}
	
	$thedays = getMonthDays();
	$themonths = getAllMonthsAsShortNames();
	
	// format date of birth
	if(!isEmptyString($user->getDateOfBirth())){
		$dob = $user->getDateOfBirth();
		$dateofbirth = date('M d, Y', strtotime($dob)); 
		$birthday = abs(date('d', strtotime($dob)));  $birthmonth = abs(date('m', strtotime($dob))); $birthyear = date('Y', strtotime($dob));
	}
	
	if(isEmptyString($tab)) {
		$request->setParam('tab', 'basics');
	}
	
	if($tab == 'contacts' || $tab == 'account') {
		$phone = $user->getFormattedPhone();
		$altphone = $user->getFormattedPhone2();
	}
	
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$locationerror = $this->translate("farmer_district_error");
	$country_params_refno_placeholder = 'placeholder="Auto" maxlength="8" ';
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya() || $user->isKenyan()){
		$session->setVar('country', 'ke');
		$country = 'KE';
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$locationerror = $this->translate("farmer_county_error");
		$country_params_refno_placeholder = 'placeholder="" maxlength="10" ';
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	
	$title = "Update Profile";
	$this->headTitle($title);
?>
<script>
$(document).ready(function() {
	// configure the date picker not to accept dates before today
	var dateofbirthOpts = datepickerOpts;
	var startfrom = '<?php echo date('Y') - 18; ?>';
	dateofbirthOpts.yearRange = "-100:-18"; 
	dateofbirthOpts.minDate = "-100Y";
	datepickerOpts.maxDate = new Date("Dec 31, "+startfrom);	
	$("#dateofbirth").datepicker(dateofbirthOpts);
	// disable editing counntry	
	disableField("country"); disableField("country2");	
	
	<?php if($tab == 'basics') { ?>
		$("#profileform-basics").validate({		
			// define the validation rules one field at a time
			rules: {
				gender: "required",
				firstname: "required",
				lastname: "required",
				country: "required",
				locationid2: "required",
				regdate: "required",
				profiledby: "required",
				<?php if(isKenya()){ ?>
					refno: {
						required: true, 					
						minlength: 6,
						maxlength: 10					
					},
				<?php } ?>
			}, 
			// the messages for each of the fields being validated
			messages: {		
				gender: "<?php echo $this->translate("farmer_gender_error"); ?>",
				firstname: "<?php echo $this->translate("farmer_firstname_error"); ?>",
				lastname: "<?php echo $this->translate("farmer_lastname_error"); ?>",
				country: "<?php echo $this->translate("farmer_country_error"); ?>",
				locationid2: "<?php echo $locationerror; ?>",
				regdate: "Please select Registration Date",
				profiledby: "Please select profiling user",
				<?php if(isKenya()){ ?>
					refno: {
						required: "Please enter ID Number", 					
						minlength: "ID must have more than 6 Digits",
						maxlength: "ID must not exceed 10 Digits"
					},
				<?php } ?>
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
		
		// basics custom failure and success url
		$("#profileform-basics .savethenview").click(function() {
			$("#profileform-basics .successurl").val('<?php echo encode($this->baseUrl('profile/view/tab/basics')); ?>');
			$("#profileform-basics .failureurl").val('<?php echo encode($this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/basics')); ?>');
		});
		
		var dateofregOpts = datepickerOpts;
		dateofregOpts.yearRange = "-5";
		dateofregOpts.maxDate = new Date();
		<?php if(!isFarmer()){ ?>
		$("#regdate").datepicker(dateofregOpts);
		<?php } ?>
		
		<?php if($user->isUgandan()){ ?>
			var refno = '<?php echo $user->getRefNo(); ?>';
			$("#refno").addClass('readonly');
			$("#refno").keyup(function(){
				$("#regno").val('<?php echo FARMER_REG_PREFIX.'/'.$user->getFarmGroup()->getRefNo(); ?>/'+$(this).val());
			});
			$(".readonly").each(function(){
				$(this).attr('readonly','readonly');
			});
			$("#refno").trigger('keyup');
		<?php } ?>
		
		<?php if($user->getFarmGroup()->hasSubGroups()){ ?>
			// chained select to load the subcounties for a county
			$('#farmgroupid').selectChain({
				target: $('#subgroupid'),
				url: '<?php echo $this->baseUrl('profile/selectchain/'.SELECT_CHAIN_TYPE.'/farmgroup_children/country/'.$country)?>',
				data: 'currentvalue=<?php echo $user->getSubGroupID(); ?>',
				type: 'get'
			});
			$('#farmgroupid, #subgroupid').trigger("change");
		<?php } ?>
		
	<?php } ?>
	
	<?php if($tab == 'personal') { ?>
		$("#profileform-personal").validate({		
			// define the validation rules one field at a time
			rules: {
				nextofkin_email: {
					required: false,
					email: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {		
				nextofkin_email: {
					email: "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
		
		// personal custom failure and success url
		$("#profileform-personal .savethenview").click(function() {
			$("#profileform-personal .successurl").val('<?php echo encode($this->baseUrl('profile/view/tab/personal')); ?>');
			$("#profileform-personal .failureurl").val('<?php echo encode($this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/personal')); ?>');
		}); 
	<?php } ?>
	
	<?php if($tab == 'contacts') { ?>
		$("#profileform-contacts").validate({		
			// define the validation rules one field at a time
			rules: {
				phone: {
					required: false, 					
					validnumber: true,
					maxlength: 10,
					minlength: 10,
					<?php if(isUganda()){ ?>
						validate_ug: true
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: true
					<?php } ?>
				},
				phone2: {
					required: false, 					
					validnumber: true,
					maxlength: 10,
					minlength: 10,
					<?php if(isUganda()){ ?>
						validate_ug: true
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: true
					<?php } ?>
				},
				email: {
					required: false, 
					email: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {		
				phone: {
					validnumber: "Please enter a valid Phone Number",
					maxlength: "Phone Number must have 10 Digits",
					minlength: "Phone Number must have 10 Digits",
					<?php if(isUganda()){ ?>
						validate_ug: "<?php echo $this->translate("globale_phonenumber_format"); ?>"
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: "<?php echo $this->translate("globale_phonenumber_format_ke"); ?>"
					<?php } ?>
				},
				phone2: {
					validnumber: "Please enter a valid Phone Number",
					maxlength: "Phone Number must have 10 Digits",
					minlength: "Phone Number must have 10 Digits",
					<?php if(isUganda()){ ?>
						validate_ug: "<?php echo $this->translate("globale_phonenumber_format"); ?>"
					<?php } ?>
					<?php if(isKenya()){ ?>
						validate_ke: "<?php echo $this->translate("globale_phonenumber_format_ke"); ?>"
					<?php } ?>
				},
				email: {
					"email": "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
		
		// add the validation for wholesale price to be less than retail price
		$.validator.addMethod("validnumber", function(value, element, params) { 
			if (IsValidAmount(value) || isEmptyString(value)) {
				return true; 
			}
			return false;        
		}, "Please enter a valid Phone Number");
		$.validator.addMethod("validate_ug", function(value, element, params) { 
			if(!isUgNumber(value) && !isEmptyString(value)) {
				return false; 
			}
			return true;        
		}, "<?php echo $this->translate("globale_phonenumber_format"); ?>");
		
		
		// contacts custom failure and success url
		$("#profileform-contacts .savethenview").click(function() {
			$("#profileform-contacts .successurl").val('<?php echo encode($this->baseUrl('profile/view/tab/contacts')); ?>');
			$("#profileform-contacts .failureurl").val('<?php echo encode($this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/contacts')); ?>');
		});
		
		$('#locationid').change(function() {
			var locationid = $(this).val();
			var currentvalue = "<?php echo $user->getCountyID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(locationid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/district_counties/districtid/'); ?>"+locationid;
				$("#countyid").find("option:gt(0)").remove();
   				$("#countyid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#countyid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#countyid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#countyid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				$('#countyid').trigger("change");
			}
		});
		<?php if(!isEmptyString($user->getLocationID())){ ?>
			$('#locationid').trigger("change");
		<?php } ?>
		
		$('#countyid').change(function() {
			var countyid = $(this).val();
			var currentvalue = "<?php echo $user->getSubCountyID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(countyid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/county_subcounties/countyid/'); ?>"+countyid;
				$("#subcountyid").find("option:gt(0)").remove();
   				$("#subcountyid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#subcountyid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#subcountyid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#subcountyid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
			}
		});
		<?php if(!isEmptyString($user->getCountyID())){ ?>
			$('#countyid').trigger("change");
		<?php } ?>
		
		$('#subcountyid').change(function() {
			var subcountyid = $(this).val();
			var currentvalue = "<?php echo $user->getParishID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(subcountyid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/subcounty_parishes/subcountyid/'); ?>"+subcountyid;
				$("#parishid").find("option:gt(0)").remove();
   				$("#parishid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#parishid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#parishid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#parishid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				// $('#subcountyid').trigger("change");
			}
		});
		<?php if(!isEmptyString($user->getSubcountyID())){ ?>
			$('#subcountyid').trigger("change");
		<?php } ?>
		
		$('#parishid').change(function() {
			var parishid = $(this).val();
			var currentvalue = "<?php echo $user->getVillageID(); ?>"; // alert('cur '+currentvalue);
			if(!isEmptyString(parishid)){
				var posturl = "<?php echo $this->baseUrl('mobile/selectchain/select_chain_type/parish_villages/parishid/'); ?>"+parishid;
				$("#villageid").find("option:gt(0)").remove();
   				$("#villageid").find("option:first").text("Loading...");
				$.getJSON(posturl, function (data) {
					$("#villageid").find("option:first").text("<Select One>").attr("value","").attr("selected", true);
					selectValues = data;
					$.each(selectValues, function(key, value) {
						if(!isEmptyString(currentvalue) && currentvalue == key){
							$('#villageid').append($("<option></option>").attr("value",key).text(value).attr("selected", true)).trigger("change"); 
						} else {
							$('#villageid').append($("<option></option>").attr("value",key).text(value).trigger("change")); 
						}
					});
				});
				// $('#subcountyid').trigger("change");
			}
		});
		<?php if(!isEmptyString($user->getParishID())){ ?>
			$('#parishid').trigger("change");
		<?php } ?>
		
		multipleDisableContainerByClass('parish_text');
		multipleEnableContainerByClass('parish_select');
		$("#parishtrigger").click(function(){
			if($(this).is(':checked')){
				disableContainerByClass('parish_select');
				enableContainerByClass('parish_text');
				$(".parish_select select").val('');
			} else {
				disableContainerByClass('parish_text');
				enableContainerByClass('parish_select');
				$(".parish_text input").val('');
			}
		});
		
		multipleDisableContainerByClass('village_text');
		multipleEnableContainerByClass('village_select');
		$("#villagetrigger").click(function(){
			if($(this).is(':checked')){
				disableContainerByClass('village_select');
				enableContainerByClass('village_text');
				$(".village_select select").val('');
			} else {
				disableContainerByClass('village_text');
				enableContainerByClass('village_select');
				$(".village_text input").val('');
			}
		});
		
		$("#isinvited-1").attr('checked', false);
		$("#isinvited-2").attr('checked', false);
	<?php } ?>
	
	<?php if($tab == 'farm') { ?>
		// farm custom failure and success url
		$("#profileform-farm .savethenview").click(function() {
			$("#profileform-farm .successurl").val('<?php echo encode($this->baseUrl('profile/view/tab/farm')); ?>');
			$("#profileform-farm .failureurl").val('<?php echo encode($this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/farm')); ?>');
		});
	<?php } ?>	
}); 
</script>
<style>
.form-horizontal .control-label {
	width:0;
	white-space:nowrap;
	text-align:left;
}
.form-horizontal div.radio.inline {
	padding-left:0;
	margin-left:5px;
}
.form-horizontal div.zendradio .radio {
	padding-left:15px;
	margin-left:0;
}
select.country {
	width:180px;
}
select.country2 {
	width:150px;
}
select.chzn-select#locationid, select.chzn-select#locationid2 {
	width:170px;
}
select#salutation {
	width:95px;
}
#phone, #phone2 {
	width:160px;
}
#email, #email2 {
	width:210px;
}
#center .ui-widget-content {
	width:100%;
	float:left;
}
.alert.alert-success {
	width:90%;
}
</style>
<?php if(!$isme){ ?>
	<h1><?php echo $user->getName(); ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">   
        <div id="basics">
            <h2>Update Profile</h2>
            <form id="profileform-basics" class="form-horizontal basics" action="<?php echo $posturl; ?>" method="post">
            <?php if($tab == 'basics'){ ?>
        	<div class="row" style="margin-left:0px;">
				<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>	
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0 pull-left">
                    <a href="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID())); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                    <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save_changes'); ?></button>
                    <input type="hidden" name="entityname" value="UserAccount" />
                    <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                    <input type="hidden" id="userid" name="userid" value="<?php echo $user->getID(); ?>" />
                    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="general" />
                    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="general" />
                    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Profile updated successfully" />    
                    <input type="hidden" name="type" id="type" value="<?php echo $user->getType(); ?>" />
                </div>
				<div class="divider10"></div>
                <span class="span6 marginleft0" style="width:97%;">
                    <div id="row1_left" class="well lighter row marginleft0" style="height:auto; padding-left:10px;">                        
                        <table class="table">                       
                           <tr>
                                <td width="54%"><label class="control-label"><?php echo $this->translate("farmer_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <input name="firstname" id="firstname" type="text" class="span3 hastooltip" value="<?php echo $user->getFirstName(); ?>" title="<?php echo $this->translate("farmer_firstname_tooltip"); ?>" /><div id="firstname_error"></div></td>
                                <td><label class="control-label"><?php echo $this->translate("farmer_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <input name="lastname" id="lastname" type="text" class="span3 hastooltip" value="<?php echo $user->getLastName(); ?>" title="<?php echo $this->translate("farmer_lastname_tooltip"); ?>" /><div id="lastname_error"></div></td>                                                             
                            </tr>
                            <tr>		                    
                                <td><label class="control-label"><?php echo $this->translate("farmer_othernames_label"); ?>:</label>
                                <input name="othernames" id="othernames" type="text" class="span3 hastooltip" value="<?php echo $user->getOtherNames(); ?>" title="<?php echo $this->translate("farmer_othernames_tooltip"); ?>" /></td>
                                <td><label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>: </label>
								<?php						  
                                      $genderradio = new Zend_Form_Element_Radio('gender',
                                              array(
                                                      'multiOptions' => array('1'=>'Male','2'=>'Female'), 
                                                      'view' => new Zend_View(),
                                                      'disableLoadDefaultDecorators' => true,
                                                      'separator' => '&nbsp;',										  
                                                      'decorators' => array('ViewHelper',
                                                                          array('HtmlTag', array('tag' => 'div', 'class' => array('inline', 'radio', 'zendradio'))) // use a sorrounding DIV with classes which are copied to the label by JQuery
                                                                      )
                                              )
                                      );
                                      $genderradio->setValue($user->getGender());
                                      echo $genderradio->render();
                                  ?><div id="gender_error"></div></td>  
                            </tr> 
                            <tr>
                                <td><label class="control-label dateofbirth"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label>
                                        <?php
                                            $daydp = new Zend_Form_Element_Select('birthday',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => 'Day'), getMonthDays()),	
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('birth'),
                                                                    'title' => 'Select Day'		
                                                                )
                                                            );
                                            $daydp->setValue($birthday); 
                                            echo $daydp->render(); 
                                        ?>
                                        <?php
                                            $monthdp = new Zend_Form_Element_Select('birthmonth',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => 'Month'), getAllMonthsAsShortNames()),	
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),

                                                                    'class' => array('birth'),
                                                                    'title' => 'Select Month'		
                                                                )
                                                            );
                                            $monthdp->setValue($birthmonth); 
                                            echo $monthdp->render(); 
                                        ?>
                                        <?php
                                            $years = getSubscribeBirthYears();
                                            $yeardp = new Zend_Form_Element_Select('birthyear',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => 'Year'), $years),	
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('birth'),
                                                                    'title' => 'Select Year'		
                                                                )
                                                            );
                                            $yeardp->setValue($birthyear); 
                                            echo $yeardp->render(); 
                                        ?>
                                        <input name="dateofbirth" id="dateofbirth" type="text" class="span2 datefield hastooltip" value="<?php echo $dateofbirth; ?>" title="<?php echo $this->translate("person_dateofbirth_tooltip"); ?>" />
                                    	<div id="dateofbirth_error"></div>
									</td>
                                    <td><label class="control-label suffix"><?php echo $this->translate("farmer_suffix_label"); ?>: </label>
                                        <?php
                                              $suffixlookup = new LookupType();
                                              $suffixlookup->setName("SALUTATION");
                                              $suffixselect = new Zend_Form_Element_Select('salutation',
                                                      array(
                                                              'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $suffixlookup->getOptionValuesAndDescription()),
                                                              'view' => new Zend_View(),
                                                              'decorators' => array(array('ViewHelper')),
                                                              'class' => array('chzn-selectX','span1','type','hastooltip'),
                                                              'title' => $this->translate("farmer_suffix_tooltip")	
                                                      )
                                              );
                                              
                                              $suffixselect->setValue($user->getSalutation());
                                              echo $suffixselect->render();
                                          ?><input type="hidden" id="salutation_old" name="salutation_old" value="<?php echo $user->getSalutation(); ?>" />
                                </td>
                            </tr>                                 
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("farmer_country_label"); ?>:</label>
									<?php
                                        $countries = getCountries();
                                        $countrydropdown = new Zend_Form_Element_Select('country2',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => "<Select One>", "UG"=>"Uganda"), $countries),
                                                                'view' => new Zend_View(), 
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('span3', 'country', 'xchzn-select', 'disabledfield')                                                            )
                                                        );
                                        $countrydropdown->setValue($user->getCountry()); 
                                        echo $countrydropdown->render(); 
                                    ?><input type="hidden" name="country2" id="country2" value="<?php echo $user->getCountry(); ?>" />
                                </td>
                                <td><label class="control-label"><?php echo $location_label; ?>:  <?php echo $this->translate("global_required_field_marker"); ?></label>
									<?php
                                        $districts = getDistricts($session->getVar('country'));
                                        $districtdropdown = new Zend_Form_Element_Select('locationid2',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districts),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('filterselect', 'hastooltip_custom', 'country'),
                                                                'title' => $this->translate("farmer_district_tooltip")
                                                            )
                                                        );
                                        $districtdropdown->setValue($user->getLocationID()); 
                                        echo $districtdropdown->render(); 
                                   ?>
                                   <span id="tooltip_locationid2"></span><div id="locationid2_error"></div></td>                           
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo isUganda() ? "FIN No#" : "National ID"; ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                	<input type="text" name="refno" id="refno" value="<?php echo $user->getRefNo(); ?>" class="span2 minwidth100" <?php echo $country_params_refno_placeholder; ?> />
                                    <?php if(isUganda()){ ?>
	                                    <input type="hidden" name="refno" id="refno" value="<?php echo $user->getRefNo(); ?>" />
                                    <?php } ?>
                                    <div id="refno_error"></div>
                                </td>
                                <td>
                                <?php if(isUganda()){ ?>	
                                    <label class="control-label">Ref No#:</label>
                                    <input type="hidden" name="regno" id="regno" value="<?php echo $user->getRegNo(); ?>" />
                                    <?php echo isEmptyString($user->getRegNo()) ? '--': $user->getRegNo(); ?>
                                    <div id="regno_error"></div>
                                <?php } ?>
                                <?php if(isKenya() && $user->isPIA()){ ?>	
                                    <label class="control-label">PID#:</label>                                    
                                    <?php echo isEmptyString($user->getID()) ? '--': $user->getID(); ?>
                                <?php } ?>
                                </td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("farmer_dateregistered_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <?php if(!isFarmer()){ ?>
                                        <input type="text" name="regdate" id="regdate" class="datefield width100" value="<?php echo changeMySQLDateToPageFormat($user->getRegDate()); ?>" />
                                    <?php } else { ?>
                                        <input type="hidden" name="regdate" id="regdate" value="<?php echo changeMySQLDateToPageFormat($user->getRegDate()); ?>" />
                                        <?php echo isEmptyString($user->getRegDate()) ? '--': changeMySQLDateToPageFormat($user->getRegDate()); ?>
                                    <?php } ?>   
                                    <div id="regdate_error"></div> 
                                </td>
                                <td>
                                	<?php if(!$isme){ ?>
                                        <label class="control-label">Profiled By: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <?php if(isAdmin()){ ?>
											<?php
                                                $users = getProfilingUsers($session->getVar('country'));
                                                $dropdown = new Zend_Form_Element_Select('profiledby',
                                                                    array(
                                                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $users),								
                                                                        'view' => new Zend_View(),
                                                                        'decorators' => array('ViewHelper'),
                                                                        'class' => array('span2')
                                                                    )
                                                                );
                                                $dropdown->setValue($user->getCreatedBy()); 
                                                echo $dropdown->render(); 
                                              ?>
                                    	<?php } else { ?>
                                        	<?php echo $loggedinuser->getName(); ?>
                                        <?php } ?>
                                        <div id="profiledby_error"></div>
                                	<?php } ?>
                                </td>
                            </tr>
                        </table>
                    </div>
                </span> 
        	</div>
            <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                <span class="pull-left well lighter margin0" style="width:95%; min-height:180px; height:auto; margin-bottom:10px;">
                	<table class="table">     
                    	<tr>
                            <td style="width:40%;">
								<?php if($user->isSelfRegistered()){ ?>
                                    <label class="control-label">Farmer Association / Group:</label>
                                    <input type="text" name="supportprovider" id="supportprovider" value="<?php echo $user->getSupportProvider(); ?>" class="hastooltip" style="width:88%;" title="<?php echo $this->translate("farmgroup_supportprovider_tooltip"); ?>" />
                                <?php } ?>
                                <?php if($user->getCreatedBy() != $user->getID() || !$user->isSelfRegistered()){ ?>
                                	<label class="control-label"><?php echo $this->translate("farmer_dna_label"); ?>:</label>
								   <?php if(!isFarmer()){ ?>
                                        <?php
                                            $groupdropdown = new Zend_Form_Element_Select('farmgroupid',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getAllFarmGroups('', $session->getVar('country'))),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('width300', 'hastooltip_custom'),
                                                                    'title' => $this->translate("farmer_farmgroupid_tooltip")
                                                                )
                                                            );
                                            $groupdropdown->setValue($user->getFarmGroupID()); 
                                            echo $groupdropdown->render(); 
                                       ?>
                                   <?php } else { ?>
                                        <?php echo !$user->hasFarmGroup() ? "--" : $user->getFarmGroup()->getName(); ?>
                                        <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $user->getFarmGroupID(); ?>" /> 
                                   <?php } ?>
                                <?php } ?>
                                <input type="hidden" id="farmgroupid_old" name="farmgroupid_old" value="<?php echo $user->getFarmGroupID(); ?>" />
                            </td>
                            <td>
                            	<?php if($user->getFarmGroup()->hasSubGroups()){ ?>
                                	<label class="control-label"><?php echo $this->translate("farmer_subgroup_label"); ?>:</label>
                                    <?php if(!isFarmer()){ ?>
                                    	<?php
                                            $groupdropdown = new Zend_Form_Element_Select('subgroupid',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), getSubGroups($user->getFarmGroupID(), $session->getVar('country'))),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('width300', 'hastooltip_custom'),
                                                                    'title' => $this->translate("farmer_subgroupid_tooltip")
                                                                )
                                                            );
                                            $groupdropdown->setValue($user->getSubGroupID()); 
                                            echo $groupdropdown->render(); 
                                       ?>
                                    <?php } else { ?>
                                        <?php echo isEmptyString($user->getSubGroupID()) ? "--" : $user->getSubGroup()->getName(); ?>
                                        <input type="hidden" id="subgroupid" name="subgroupid" value="<?php echo $user->getSubGroupID(); ?>" /> 
                                   <?php } ?>
                                <?php } else { ?>
                                	<input type="hidden" id="subgroupid" name="subgroupid" value="" /> 
                                <?php } ?>
                                <input type="hidden" id="subgroupid_old" name="subgroupid_old" value="<?php echo $user->getSubGroupID(); ?>" />
                            </td>
                        </tr>
                    </table>	
                </span>
            </div>
            <div class="well lighter row marginleft0" style="min-height:75px; width:95%;"> 
                <h3 class="well-legend">About</h3>
                <table class="table margin0">              
                    <tr>		  
                        <td style="padding-left:0;">
                        <textarea name="bio" id="bio" class="span4 expanding hastooltip" style="width:90%; min-height:100px;" title="<?php echo $this->translate("farmer_bio_tooltip"); ?>"><?php echo $user->getBio(); ?></textarea></td>
                    </tr>
                </table>
            </div>
            <?php } ?>
        	</form> 
        </div>
         <div id="contacts">
            <!--<h2>Contact Information</h2>-->
            <form id="profileform-contacts" class="form-horizontal contacts" action="<?php echo $posturl; ?>" method="post">
            <?php if($tab == 'contacts'){ ?>
            	<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>	
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0 padding0">
                	<div class="divider10"></div>
                    <a href="javascript:doNothing();" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                    <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save_changes'); ?></button>
                    <input type="hidden" name="entityname" value="UserAccount" />
                    <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" /> 
                    <input type="hidden" id="userid" name="userid" value="<?php echo $user->getID(); ?>" /> 
                    <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $user->getFarmGroupID(); ?>" /> 
                    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="general" />
                    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="general" />
                    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Profile updated successfully" />
                </div>
                <div class="divider10"></div>
                <div class="row" style="margin-left:0px;">
                    <span class="span6 marginleft0" style="width:96%;">
                        <div class="well lighter row marginleft0" style="min-height:150px;">     
                        <h3 class="well-legend">Contact Information</h3>                   
                            <table class="table">
                                <tr>
                                    <td width="50%"><label class="control-label">Phone:</label>
                                    	<div class="input-prepend">
                                        	<span class="add-on"><?php echo '+'.$countrycode; ?></span><input name="phone" id="phone" type="text" maxlength="10" class="span2 hastooltip" style="width:110px;" value="<?php echo $user->getFormattedPhone(); ?>" title="<?php echo $this->translate("farmer_phone_tooltip"); ?>" />
                                        </div>
                                        <?php if($user->isUserInActive() || isEmptyString($user->getID())){ ?>
                                             <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="isphoneinvited" id="isphoneinvited" value="1" style="margin-top:0;" /> &nbsp;
                                             <label class="lineblocked">Invite to activate via Phone</label></div>
                                        <?php } ?>
                                        <div id="phone_error"></div>
                                    </td>
                                    <td>
                                    	<label class="control-label">Alt Phone:</label>
                                        <div class="input-prepend">
                                        	<span class="add-on"><?php echo '+'.$countrycode; ?></span><input name="phone2" id="phone2" type="text" maxlength="10" class="span2 hastooltip" style="width:110px;" value="<?php echo $user->getFormattedPhone2(); ?>" title="<?php echo $this->translate("farmer_phone_tooltip"); ?>" />
                                        </div>
                                        <div id="phone2_error"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="control-label">Email:</label>
                                    	<input type="text" name="email" id="email" class="span3 hastooltip"  value="<?php echo isEmptyString($user->getEmail()) ? $user->getEmail() : $user->getEmail(); ?>" title="<?php echo $this->translate("farmer_email_tooltip"); ?>"/>
                                        <?php if($user->isUserInActive() || isEmptyString($user->getID())){ ?>
                                             <div class="blocked" style="margin-top:5px;"><input type="checkbox" name="isinvited" id="isinvited" value="1" /> &nbsp;
                                             <label class="lineblocked">Invite to activate via Email</label></div>
                                        <?php } ?>
                                    </td>
                                    <td>
                                    	<label class="control-label">Alt Email:</label>
                                        <input type="text" name="email2" id="email2" class="span3 hastooltip" value="<?php echo $user->getEmail2(); ?>" title="<?php echo $this->translate("farmer_phone2_tooltip"); ?>" />
                                    </td>
                                </tr>
                                
                            </table>
                        </div>
                    </span>
                </div>
                <div class="well lighter row marginleft0" style="min-height:100px; width:94%;">
                    <h3 class="well-legend">Address</h3>
                    <table class="table">                       
                       <tr>
                            <td width="35%"><label class="control-label">Country:</label>
								<?php
                                    $countries = getCountries();
                                    $countrydropdown = new Zend_Form_Element_Select('country',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => "<Select One>", "UG"=>"Uganda"), $countries),
                                                            'view' => new Zend_View(), 
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('country', 'xchzn-select', 'disabledfield')                                                            )
                                                    );
                                    $countrydropdown->setValue($user->getCountry()); 
                                    echo $countrydropdown->render(); 
                                ?><input type="hidden" name="country" id="country" value="<?php echo $user->getCountry(); ?>" />
                                <span id="tooltip_country"></span><div id="country_error"></div>
                            </td>
                            <td width="30%"><label class="control-label"><?php echo $location_label; ?>:</label>
                                <?php
									$districts = getDistricts($session->getVar('country'));
									$districtdropdown = new Zend_Form_Element_Select('locationid',
														array(
															'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districts),								
															'view' => new Zend_View(),
															'decorators' => array('ViewHelper'),
															'class' => array('filterselect', 'country')
														)
													);
									$districtdropdown->setValue($user->getLocationID()); 
									echo $districtdropdown->render(); 
							   ?>
							   <span id="tooltip_districtid"></span><div id="districtid_error"></div>
                            </td>
                            <td width="35%"><label class="control-label"><?php echo $county_label; ?>:</label>
                                <select name="countyid" id="countyid" class="country">
                                  <option value="">&lt;Select One&gt;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label"><?php echo $subcounty_label; ?>:</label>
                                <select name="subcountyid" id="subcountyid" class="country">
                                  <option value="">&lt;Select One&gt;</option>
                                </select>
                            </td>
                            <td><?php if($user->isUgandan()){ ?>
                            	<label class="control-label">Parish:</label>
                                <div class="parish_text inline">
                                    <input type="text" name="parishname" id="parishname" class="span2" value="<?php //echo $user->getVillageName(); ?>"  />
                                </div>
                                <div class="parish_select inline">
                                    <select name="parishid" id="parishid" class="span2">
                                      <option value="">&lt;Select One&gt;</option>
                                    </select>
                                </div>
                                &nbsp;<input type="checkbox" name="parishtrigger" id="parishtrigger" class="lineblocked" value="1" title="Switch entry mode" placeholder="enter free text" /> 
                                <div id="parishname_error"></div><div id="parishid_error"></div>
                                <?php } ?>
                            </td>
                            <td>
                            	<?php if($user->isUgandan()){ ?>
                            	<label class="control-label">Village:</label>
                            	<div class="village_text inline">
                                    <input type="text" name="villagename" id="villagename" class="span2" value="<?php //echo $user->getVillageName(); ?>"  />
                                </div>
                                <div class="village_select inline">
                                    <select name="villageid" id="villageid" class="span2">
                                      <option value="">&lt;Select One&gt;</option>
                                    </select>
                                </div>
                                &nbsp;<input type="checkbox" name="villagetrigger" id="villagetrigger" class="lineblocked" value="1" title="Switch entry mode" placeholder="enter free text" /> 
                                <div id="villagename_error"></div><div id="villageid_error"></div>
                                <?php } ?>
                            </td>
                        </tr>
                        <tr>
                            <td><label class="control-label">Postal/Street Address</label>
                              	<textarea name="streetaddress" id="streetaddress" class="span4 expanding" style="min-height:60px;"><?php echo $user->getStreetAddress(); ?></textarea>
                            </td>
                            <td><label class="control-label">GPS Latitude:</label>
                            	<input name="lat" id="lat" type="text" class="span2 hastooltip" value="<?php echo $user->getLat(); ?>" title="<?php echo $this->translate("farmer_latitude_tooltip"); ?>" />
                            </td>
                            <td><label class="control-label">GPS Longitude:</label>
                            	<input name="lng" id="lng" type="text" class="span2 hastooltip" value="<?php echo $user->getLng(); ?>" title="<?php echo $this->translate("farmer_longitude_tooltip"); ?>" />
                            </td>
                        </tr>
                    </table>
                </div>                
            <?php } ?>
            </form>   	
        </div>
        <div id="personal">
            <h2>Personal Information</h2>
            <form id="profileform-personal" class="form-horizontal personal" action="<?php echo $posturl; ?>" method="post">
            <?php if($tab == 'personal'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>	
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0 padding0">
                	<div class="divider10"></div>
                    <a href="javascript:doNothing();" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                    <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save_changes'); ?></button>
                    <input type="hidden" name="entityname" value="UserAccount" />
                    <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" /> 
                    <input type="hidden" id="userid" name="userid" value="<?php echo $user->getID(); ?>" /> 
                    <input type="hidden" id="farmgroupid" name="farmgroupid" value="<?php echo $user->getFarmGroupID(); ?>" /> 
                    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="general" />
                    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="general" />
                    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Profile updated successfully" />
                </div>
                <div class="divider10"></div>
                <div class="well row marginleft0" style="min-height:75px; width:94%;"> 
                    <h3 class="well-legend">Family</h3>
                    <table class="table margin0">                       
                       <tr>		  
                            <td width="30%" style="padding-left:0;"><label class="control-label"><?php echo $this->translate("farmer_maritalstatus_label"); ?>:</label>
                            <?php
                                $maritalstatuses = getAllMaritalStatuses();
                                $maritalstatusesdropdown = new Zend_Form_Element_Select('maritalstatus',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $maritalstatuses),								
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('filterselect', 'hastooltip', 'span2'),
                                                        'title' => $this->translate("farmer_maritalstatus_tooltip")
                                                    )
                                                );
                                $maritalstatusesdropdown->setValue($user->getMaritalStatus()); 
                                echo $maritalstatusesdropdown->render(); 
                           ?><input type="hidden" id="maritalstatus_old" name="maritalstatus_old" value="<?php echo $user->getMaritalStatus(); ?>" /></td>
                            <td width="20%"><label class="control-label"><?php echo $this->translate("farmer_nochildren_label"); ?>:</label>
                            <input name="numberofchildren" id="numberofchildren" type="text" class="span1 hastooltip centeralign isnumber" value="<?php echo $user->getNumberOfChildren(); ?>" title="<?php echo $this->translate("farmer_nochildren_tooltip"); ?>" />
                            <input type="hidden" id="numberofchildren_old" name="numberofchildren_old" value="<?php echo $user->getNumberOfChildren(); ?>" />
                            <div id="numberofchildren_error"></div></td>
                            <td width="20%"><label class="control-label"><?php echo $this->translate("farmer_nodependants_label"); ?>:</label>
                            <input name="numberofdependants" id="numberofdependants" type="text" class="span1 hastooltip centeralign isnumber" value="<?php echo $user->getNumberOfDependants(); ?>" title="<?php echo $this->translate("farmer_nodependants_tooltip"); ?>" />
                            <input type="hidden" id="numberofdependants_old" name="numberofdependants_old" value="<?php echo $user->getNumberOfDependants(); ?>" />
                            <div id="numberofdependants_error"></div></td>
                            <td><label class="control-label"><?php echo $this->translate("farmer_totalhousehold_label"); ?>:</label>
                            <input name="totalhousehold" id="totalhousehold" type="text" class="span1 hastooltip centeralign isnumber" value="<?php echo $user->getTotalHousehold(); ?>" title="<?php echo $this->translate("farmer_totalhousehold_tooltip"); ?>" />
                            <input type="hidden" id="totalhousehold_old" name="totalhousehold_old" value="<?php echo $user->getTotalHousehold(); ?>" />
                            <div id="totalhousehold_error"></div>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="well row marginleft0" style="min-height:100px; width:94%;">
                    <h3 class="well-legend"><?php echo $this->translate("farmer_nextofkin_label"); ?></h3>
                    <table class="table">                       
                       <tr>		  
                            <td width="30%"><label class="control-label"><?php echo $this->translate("global_name_label"); ?>:</label>
                            <input name="nextofkin_name" id="nextofkin_name" type="text" class="span3 hastooltip" style="width:150px;" value="<?php echo $user->getNextofkin_Name(); ?>" title="<?php echo $this->translate("farmer_nextofkin_name_label"); ?>" />
                            </td>
                            <td width="30%"><label class="control-label"><?php echo $this->translate("global_phone_label"); ?>:</label>
                                <div class="input-prepend">
                                    <span class="add-on"><?php echo '+'.$countrycode; ?></span><input name="nextofkin_phone" id="nextofkin_phone" type="text" maxlength="10" class="span2 hastooltip isnumber" style="width:110px;" value="<?php echo $user->getNextofkin_phone(); ?>" title="<?php echo $this->translate("farmer_phone_tooltip"); ?>" placeholder="e.g 0772123456" />
                                </div>
                                <div id="nextofkin_phone_error"></div>
                            </td>
                            <td><label class="control-label"><?php echo $this->translate("global_email_label"); ?>:</label>
                            <input name="nextofkin_email" id="nextofkin_email" type="text" class="span3 hastooltip" style="width:180px;" value="<?php echo $user->getNextofkin_email(); ?>" title="<?php echo $this->translate("farmer_nextofkin_email_label"); ?>" /><div id="nextofkin_email_error"></div>
                            </td>
                        </tr>
                    </table>
                </div>
				<div class="well row marginleft0" style="min-height:100px; width:94%;">
                    <h3 class="well-legend">Other Information</h3>                       
                    <table class="table">
                        <tr>		  
                            <td width="40%"><label class="control-label"><?php echo $this->translate("farmer_educlevel_label"); ?>:</label>
                                    <?php
                                        $educlevels = getAllEducationLevels();
                                        $educleveldropdown = new Zend_Form_Element_Select('educationlevel',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $educlevels),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('filterselect', 'hastooltip', 'span2'),
                                                                'title' => $this->translate("farmer_educationlevel_tooltip")
                                                            )
                                                        );
                                        $educleveldropdown->setValue($user->getEducationLevel()); 
                                        echo $educleveldropdown->render(); 
                                   ?>
                                   <input type="hidden" id="educationlevel_old" name="educationlevel_old" value="<?php echo $user->getEducationLevel(); ?>" /></td>
                            <td></td>
                        </tr>
                    </table>
                </div>                
            <?php } ?>
            </form>  	
        </div>
        <?php if($user->isFarmer()) {?>
            <div id="farm">
                <h2>Manage Farm</h2>
                <form id="profileform-farm" class="form-horizontal farm" action="<?php echo $posturl; ?>" method="post">
                    <?php if($tab == 'farm'){ ?>
                        <div class="divider5"></div>
                        <div class="row margin0 padding0">
							 <a href="javascript:doNothing();" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save_changes'); ?></button>
                            <input type="hidden" name="entityname" value="UserAccount" />
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" /> 
                            <input type="hidden" id="userid" name="userid" value="<?php echo $user->getID(); ?>" /> 
                            <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="general" />
                            <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="general" />
                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Profile updated successfully" />
                        </div> 
                        <div class="divider10"></div>
                        <div class="row margin0 padding0" style="width:96%;">
                            <span style="width:49%; float:left;">
                                <div class="well lighter row marginleft0" id="farmleft" style="min-height:325px;"> 
                                    <h3 class="well-legend">Manage Farm</h3>
                                    <table class="table"> 
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farm_name_label"); ?>:</label>
                                            <input type="text" name="businessname" id="businessname" value="<?php echo $user->getName(); ?>" class="hastooltip" style="width:80%;" title="<?php echo $this->translate("farm_businessname_tooltip"); ?>" /><div id="businessname_error"></div>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Practicing Farming Since:</label>
                                                <div class="blocked">
                                                    <?php
                                                        $years = getAllYears("63","0");
                                                        $yeardp = new Zend_Form_Element_Select('bizstartyear',
                                                                            array(
                                                                                'multiOptions' => array_merge_maintain_keys(array('' => 'Year'), $years),	
                                                                                'view' => new Zend_View(),
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('birth'),
                                                                                'title' => 'Select Year'		
                                                                            )
                                                                        );
                                                        $yeardp->setValue($user->getBizStartYear()); 
                                                        echo $yeardp->render(); 
                                                    ?>
                                                    <?php
                                                        $monthdp = new Zend_Form_Element_Select('bizstartmonth',
                                                                            array(
                                                                                'multiOptions' => array_merge_maintain_keys(array('' => 'Month'), getAllMonthsAsShortNames()),	
                                                                                'view' => new Zend_View(),
                
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('span2x'),
                                                                                'style' => "width:75px;",
                                                                                'title' => 'Select Month'		
                                                                            )
                                                                        );
                                                        $monthdp->setValue($user->getBizStartMonth()); 
                                                        echo $monthdp->render(); 
                                                    ?>
                                                    <div id="bizstartyear_error"></div><div id="bizstartmonth_error"></div>
                                                    <input type="hidden" id="bizstartyear_old" name="bizstartyear_old" value="<?php echo $user->getbizstartyear(); ?>" />
                                                    <input type="hidden" id="bizstartmonth_old" name="bizstartmonth_old" value="<?php echo $user->getbizstartmonth(); ?>" />
                                                </div>
											</td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farm_numberofemployees_label"); ?>:</label>
                                            <input name="numberofemployees" id="numberofemployees" type="text" class="span1 isnumber hastooltip" value="<?php echo $user->getNumberOfEmployees(); ?>" title="<?php echo $this->translate("farm_numberofemployees_tooltip"); ?>" /><div class="numberofemployees_error"></div>
                                            <input type="hidden" id="numberofemployees_old" name="numberofemployees_old" value="<?php echo $user->getnumberofemployees(); ?>" />
                                            </td>
                                        </tr>
                                        <?php if($user->isFarmer()){ ?>
                                        <tr>
                                            <td><label class="control-label">Types of Farming Practiced</label>
                                                <?php
                                                      $listdropdown = new Zend_Form_Element_Multiselect('farmingtypeids',
                                                              array(
                                                                      'multiOptions' => getFarmingTypes(),
                                                                      'view' => new Zend_View(),
                                                                      'decorators' => array(array('ViewHelper')),
                                                                      'class' => array('chzn-select','multipleselect','span5','hastooltip_custom'),
                                                                      'title' => $this->translate("farmer_farmingtypes_tooltip")
                                                              )
                                                      );
                                                      
                                                      $listdropdown->setValue($user->getFarmingTypeIDs());
                                                      $listdropdown->setAttrib("data-placeholder", 'Select all in category');
                                                      echo $listdropdown->render();
                                                  ?><input type="hidden" id="farmingtypeids_old" name="farmingtypeids_old" value="<?php echo $user->getfarmingtypes(); ?>" />
                                                  <span id="tooltip_farmingtypes"></span>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Farming Tools Used</label>
												<?php
                                                  $listdropdown = new Zend_Form_Element_Multiselect('farmingtoolsids',
                                                          array(
                                                              'multiOptions' => getFarmingTools(),
                                                              'view' => new Zend_View(),
                                                              'decorators' => array(array('ViewHelper')),
                                                              'class' => array('chzn-select','multipleselect','span4','hastooltip_custom'),
                                                              'title' => $this->translate("farmer_farmingtools_tooltip")
                                                          )
                                                  );
                                                  
                                                  $listdropdown->setValue($user->getFarmingToolsIDs());
                                                  $listdropdown->setAttrib("data-placeholder", 'Select all in category');
                                                  echo $listdropdown->render();
                                              ?><span id="tooltip_farmingtoolsids"></span>
                                              <input type="hidden" id="farmingtoolsids_old" name="farmingtoolsids_old" value="<?php echo $user->getfarmingtools(); ?>" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Other Income Generating Activities</label>
                                                <?php
                                                      $listdropdown = new Zend_Form_Element_Multiselect('activitytypeids',
                                                              array(
                                                                      'multiOptions' => getOtherActivityTypes(),
                                                                      'view' => new Zend_View(),
                                                                      'decorators' => array(array('ViewHelper')),
                                                                      'class' => array('chzn-select','multipleselect','span5','hastooltip_custom'),
                                                                      'title' => $this->translate("farmer_activitytypes_tooltip")
                                                              )
                                                      );
                                                      
                                                      $listdropdown->setValue($user->getActivityTypeIDs());
                                                      $listdropdown->setAttrib("data-placeholder", 'Select all in category');
                                                      echo $listdropdown->render();
                                                  ?><input type="hidden" id="activitytypeids_old" name="activitytypeids_old" value="<?php echo $user->getactivitytypes(); ?>" />
                                                  <span id="tooltip_activitytypes"></span>
                                            </td>
                                        </tr>
                                        <?php } ?>
                                    </table>
                                </div>
                            </span>
                            <span style="width:49%; float:right;">
                                <div class="well lighter row marginleft0" id="farmright" style="min-height:450px; width:98%">
                                    <h3 class="well-legend">Land Usage</h3>                       
                                    <table class="table higherpadding"> 
                                        <tr>
                                            <td width="50%" class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landsize_label"); ?>:</label></td>
                                            <td><input name="landsize" id="landsize" type="text" class="span1 isnumber" value="<?php echo clean_num($user->getLandSize()); ?>" />&nbsp;&nbsp;
												<?php
                                                    $landunits = getAreaUnits();
                                                    $landunitdropdown = new Zend_Form_Element_Select('landunits',
                                                                        array(
                                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $landunits),								
                                                                            'view' => new Zend_View(),
                                                                            'decorators' => array('ViewHelper'),
                                                                            'class' => array('filterselect', 'hastooltip', 'unitselect'),
                                                                            'title' => $this->translate("farm_landunits_tooltip"),
																			'style' => 'width:80px;'
                                                                        )
                                                                    );
                                                    $landunitdropdown->setValue($user->getLandUnits()); 
                                                    echo $landunitdropdown->render(); 
                                               ?><div id="landsize_error"></div><div id="landunits_error"></div>
                                               <input type="hidden" id="landsize_old" name="landsize_old" value="<?php echo $user->getlandsize(); ?>" />
                                               <input type="hidden" id="landunits_old" name="landunits_old" value="<?php echo $user->getlandunits(); ?>" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landsizeactive_label"); ?>:</label></td>
                                            <td><input name="landactivesize" id="landactivesize" type="text" class="span1 isnumber hastooltip" value="<?php echo clean_num($user->getLandActiveSize()); ?>" title="<?php echo $this->translate("farm_landsize_tooltip"); ?>" /> <span class="pagedescription" id="activeland"></span><div id="landactivesize_error"></div>
                                            <input type="hidden" id="landactivesize_old" name="landactivesize_old" value="<?php echo $user->getlandactivesize(); ?>" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landacquiremethod_label"); ?>:</label></td>
                                            <td><?php
													$landmethods = getLandAcquireMethods();
													$landmethoddropdown = new Zend_Form_Element_Select('landacquiremethod',
																		array(
																			'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $landmethods),								
																			'view' => new Zend_View(),
																			'decorators' => array('ViewHelper'),
																			'class' => array('filterselect', 'hastooltip', 'span2'),
																			'title' => $this->translate("farm_landacquiremethod_tooltip"),
																			'style' => 'width:80px;'
																		)
																	);
													$landmethoddropdown->setValue($user->getLandAcquireMethod()); 
													echo $landmethoddropdown->render(); 
											   ?><div id="landacquiremethod_error"></div>
                                               <input type="hidden" id="landacquiremethod_old" name="landacquiremethod_old" value="<?php echo $user->getlandacquiremethod(); ?>" />
                                       		</td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">No of Farm Lands / Fields:</label></td>
                                            <td colspan="2">
												<?php
                                                    $fieldcount = array("1"=>"1","2"=>"2","3"=>"3","4"=>"4");
                                                    $fieldsdropdown = new Zend_Form_Element_Select('numberoffields',
                                                                        array(
                                                                            'multiOptions' => $fieldcount,								
                                                                            'view' => new Zend_View(),
                                                                            'decorators' => array('ViewHelper'),
                                                                            'class' => array('filterselect', 'hastooltip', 'unitselect'),
                                                                            'title' => $this->translate("farm_numberoffields_tooltip"),
																			'style' => 'width:80px;'
                                                                        )
                                                                    );
                                                    $fieldsdropdown->setValue($user->getNumberOfFields()); 
                                                    echo $fieldsdropdown->render(); 
                                               ?><div id="numberoffields_error"></div>
                                         		<input type="hidden" id="numberoffields_old" name="numberoffields_old" value="<?php echo $user->getnumberoffields(); ?>" />
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </span>
                        </div>
                        <div class="row" style="margin-left:0px; position:relative;">
                            <h2>Crops</h2>
                            <?php require APPLICATION_PATH."/views/scripts/profile/cropscolumn.phtml"; ?>
                        </div> 
                    <?php } ?>
                </form>
            </div>
        <?php } ?>    
        <div id="seasons">
        	<h2>Manage Seasons</h2>
            <form id="profileform-seasons" class="form-horizontal seasons"></form>
        </div>
        <div id="calendar">
        	<h2>Season Activity Calendar</h2>
            <form id="profileform-calendar" class="form-horizontal calendar clearfix"></form>
        </div>
        <div id="inventory">
        	<h2>Farm Inventory</h2>
            <form id="profileform-inventory" class="form-horizontal inventory"></form>
        </div>
        <div id="finance">
        	<h2>Reports</h2>
            <form id="profileform-finance" class="form-horizontal finance"></form>
        </div>
        <div id="subscription">
        	<h2>Payment History</h2>
            <form id="profileform-subscription" class="form-horizontal subscription"></form>
        </div>
        <?php require APPLICATION_PATH."/views/scripts/profile/settings.phtml"; ?>
    </div> 
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
