<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$controller = $request->getControllerName();
	$action = $request->getActionName();
	if($controller == 'profile' && isEmptyString($request->tab)){
		$request->setParam('tab', 'basics'); 
	}
	
	$resourcename = 'Farmer';
	if($controllername == 'profile'){
		$resourcename == 'User Account';
	}
	
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	
	// debugMessage($user->toArray());
?>
<script>
$(document).ready(function() {
	// override default tab
	<?php if(!isEmptyString($request->tab)){ ?>
		$("#tabs").tabs({ selected:'<?php echo $request->tab; ?>', fx: {opacity: 'toggle'} });	   
	<?php } ?>
	$('#tabs').tabs({
		// the selected tab
		selected: '<?php echo $request->tab; ?>'
	});
	
	<?php if($controller != 'profile'){ ?>
		$("#tabs ul li#tab_summary").removeClass("ui-state-active").removeClass("ui-tabs-selected");
	<?php } ?>
	
	$("#tabs ul#leftnav li a").click(function(e){
		var currentclass = $(this).attr('class');
		var oldclass = '<?php echo $request->tab; ?>';
		if(currentclass != oldclass  || currentclass == 'seasons' || currentclass == 'inventory' || currentclass == 'finance' || currentclass == 'subscription'){
			$(".form-horizontal."+currentclass).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
			var url = '';
			var controller = '<?php echo $controller; ?>';
			var action = '<?php echo $action; ?>';
			
			if(controller == '<?php echo $controller; ?>' && action == 'index'){
				var url = "<?php echo $this->baseUrl($controller."/index/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
				if(controller != 'farmer' && controller != 'profile'){
					var url = "<?php echo $this->baseUrl("farmer/index/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
				}
			}
			if((controller == '<?php echo $controller; ?>' && action == 'view') || action == 'picture' || currentclass == 'seasons' || currentclass == 'calendar'|| currentclass == 'inventory' || currentclass == 'finance' || currentclass == 'account'){
				var url = "<?php echo $this->baseUrl($controller."/view/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
				if(controller != 'farmer' && controller != 'profile'){
					var url = "<?php echo $this->baseUrl("farmer/view/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
				}
			}
			if(!isEmptyString(url)){
				location.href = url;  
			} else {
				location.href = "<?php echo $this->baseUrl($controller."/view/id/".encode($user->getID())."/tab/"); ?>"+currentclass;  
			}
			// alert(url); alert(currentclass);
		}
	});
	
	$("#tabs").tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
	$("#tabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	
}); 
</script>
<div class="span3 marginleft0" id="left">    
    <div class="well" id="profiletop">
        <div id="profileinfo"> 
			<?php if(($isme || $acl->checkPermission($resourcename, ACTION_EDIT)) && !isEmptyString($user->getID())){ ?>
                <a href="<?php echo $this->baseUrl($controller.'/picture/id/'.encode($user->getID()).'/type/photo'); ?>" class="editpic" title="Update Profile Photo"><img id="profileimage" src="<?php echo $user->getMediumPicturePath(); ?>" /><pre id="uploadlink" class="hide absoluteupload"><i class="icon-pencil"></i> Upload Photo</pre></a>
            <?php } else { ?>
                <img id="profileimage" src="<?php echo $user->getMediumPicturePath(); ?>" alt="Update Profile Photo" />
            <?php } ?>
            <?php if(($isme || $acl->checkPermission($resourcename, ACTION_EDIT)) && !isEmptyString($user->getID())){ ?>
                <a style="display:block; width:155px; text-align:center;" href="<?php echo $this->baseUrl($controller.'/picture/id/'.encode($user->getID()).'/type/photo'); ?>" class="btn btn-mini noround">Upload Photo</a>
            <?php } ?>
        </div>
    </div>
    <ul id="leftnav" style="width:97%;">
        <li id="tab_basics"><a href="#basics" class="basics">Profile</a></li>
        <?php if(!isEmptyString($user->getID())){ ?>
			<?php if($user->isFarmer()){ ?>
                <li id="tab_farm"><a href="#farm" class="farm">Farm</a></li>
                <?php if($acl->checkPermission('Farmer Seasons', ACTION_LIST)){ ?>
                <li id="tab_seasons"><a href="#seasons" tab="seasons" class="seasons">Seasons</a></li>
                <?php } ?>
                <?php if($acl->checkPermission('Farmer Calendar', ACTION_VIEW)){ ?>  
	                <li id="tab_calendar"><a href="#calendar" tab="calendar" class="calendar">Activity Calendar</a></li>
                <?php } ?>
                <?php if($acl->checkPermission('Farmer Inventory', ACTION_LIST)){ ?>    
	                <li id="tab_inventory"><a href="#inventory" tab="inventory" class="inventory">Inventory</a></li>
                <?php } ?>    
                <li id="tab_finance"><a href="#finance" tab="finance" class="finance">Reports</a></li>
            <?php } ?>
            <?php if($acl->checkPermission('Payments', ACTION_LIST)){ ?> 
            	<li id="tab_subscription"><a href="#subscription" class="subscription">Subscription History</a></li>
           	<?php } ?>
            <?php if(($isme || $acl->checkPermission($resourcename, ACTION_EDIT))){ ?>    
            	<li id="tab_account"><a href="#account" class="account">Account Settings</a></li>   
            <?php } ?>
        <?php } ?>
    </ul>
</div>
