<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$controller = $request->getControllerName();
	$action = $request->getActionName();
	if($controller == 'profile' && isEmptyString($request->tab)){
		$request->setParam('tab', 'basics'); 
	}
	// debugMessage($user->toArray());
?>
<script>
$(document).ready(function() {
	// override default tab
	<?php if(!isEmptyString($request->tab)){ ?>
		$("#tabs").tabs({ selected:'<?php echo $request->tab; ?>', fx: {opacity: 'toggle'} });	   
	<?php } ?>
	$('#tabs').tabs({
		// the selected tab
		selected: '<?php echo $request->tab; ?>'
	});
	
	<?php if($controller != 'profile'){ ?>
		$("#tabs ul li#tab_summary").removeClass("ui-state-active").removeClass("ui-tabs-selected");
	<?php } ?>
	
	$("#tabs ul#leftnav li a").click(function(e){
		var currentclass = $(this).attr('class');
		var oldclass = '<?php echo $request->tab; ?>';
		if(currentclass != oldclass  || currentclass == 'seasons' || currentclass == 'inventory' || currentclass == 'finance' || currentclass == 'subscription'){
			$(".form-horizontal."+currentclass).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
			var url = '';
			var controller = '<?php echo $controller; ?>';
			var action = '<?php echo $action; ?>';
			
			if(controller == 'profile' && action == 'index'){
				var url = "<?php echo $this->baseUrl("profile/index/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
			}
			if((controller == 'profile' && action == 'view') || action == 'picture' || currentclass == 'seasons' || currentclass == 'calendar'|| currentclass == 'inventory' || currentclass == 'finance' || currentclass == 'account'){
				var url = "<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())."/tab/"); ?>"+currentclass;
			}
			if(currentclass == 'subscription'){
				var url = "<?php echo $this->baseUrl('payment/list/id/'.encode($user->getID())); ?>";
			}
			if(!isEmptyString(url)){
				location.href = url;  
			}
			// alert(url); alert(currentclass);
		}
	});
	
	$("#tabs").tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
	$("#tabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	
}); 
</script>
<div class="span3 marginleft0" id="left">    
    <div class="well" id="profiletop">
        <div id="profileinfo"> 
			<?php if($userid == $user->getID() || isFarmGroupAdmin() || isAdmin() || isDataClerk()){ ?>
                <a href="<?php echo $this->baseUrl('profile/picture/id/'.encode($user->getID()).'/type/photo'); ?>" class="editpic" title="Update Profile Photo"><img id="profileimage" src="<?php echo $user->getMediumPicturePath(); ?>" /><pre id="uploadlink" class="hide absoluteupload"><i class="icon-pencil"></i> Upload Photo</pre></a>
            <?php } else { ?>
                <img id="profileimage" src="<?php echo $user->getMediumPicturePath(); ?>" alt="Update Profile Photo" />
            <?php } ?>
            <?php if($userid == $user->getID() || isFarmGroupAdmin() || isAdmin() || isDataClerk()){ ?>
                <a style="display:block; width:155px; text-align:center;" href="<?php echo $this->baseUrl('profile/picture/id/'.encode($user->getID()).'/type/photo'); ?>" class="btn btn-mini">Upload Photo</a>
            <?php } ?>
        </div>
    </div>
    <ul id="leftnav" style="width:97%;">
        <li id="tab_basics"><a href="#basics" class="basics">Profile Summary </a></li>
        <li id="tab_contacts"><a href="#contacts" class="contacts">Contacts</a></li>
        <li id="tab_personal"><a href="#personal" class="personal">Biography</a></li>
        <li id="tab_farm"><a href="#farm" class="farm">Manage Farm</a></li>
        <li id="tab_seasons"><a href="#seasons" tab="seasons" class="seasons">Manage Seasons</a></li>
        <li id="tab_calendar"><a href="#calendar" tab="calendar" class="calendar">Activity Calendar</a></li>
        <li id="tab_inventory"><a href="#inventory" tab="inventory" class="inventory">Inventory</a></li>
        <li id="tab_finance"><a href="#finance" tab="finance" class="finance">Finance and Reports</a></li>
        <li id="tab_subscription"><a href="#subscription" class="subscription">Subscription History</a></li>
        <li id="tab_account"><a href="#account" class="account">Account Settings</a></li>   
    </ul>
</div>
