<div id="account">
            <h2>Account Settings</h2>
            <form id="profileform-account" class="form-horizontal account">
                <?php if($request->tab == 'account'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?> 
                <?php if(isEmptyString($request->section)){ ?>
                <div class="row margin0 padding0">
                    <fieldset class="fieldsetcontainer well">
                        <legend>Login Credentials</legend>
                   		<table class="table nohover noborder margin10" style="width:550px;">                       
                           <tr>		                    
                                <td><label class="control-label leftalign">Login Status: </label></td>
                                <td><?php echo $user->isUserActive() ? 'Active' : 'In Active'; ?></td>
                           </tr>
                           <tr>		                    
                                <td width="20%"><label class="control-label leftalign">Email: </label></td>
                                <td><?php echo isEmptyString($user->getEmail()) ? '--' : $user->getEmail(); ?> &nbsp;
                                    <a href="<?php echo $this->baseUrl($controllername.'/changeemail/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeemail pull-right" title="Change Email" rel="Change Email" id="changeemail" formtitle="indexform" successurl="<?php echo $this->baseUrl($controllername.'/view/id/'.encode($user->getID()).'/tab/account'); ?>" action="<?php echo $this->baseUrl($controllername."/processchangeemail"); ?>">Change Email</a></td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Username: </label></td>
                                <td><?php echo isEmptyString($user->getUserName()) ? '--' : $user->getUserName(); ?> &nbsp;
                                    <a href="<?php echo $this->baseUrl($controllername.'/changeusername/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeusername pull-right" title="Change Username" rel="Change Username" id="changeusername" formtitle="indexform" successurl="<?php echo $this->baseUrl($controllername.'/view/id/'.encode($user->getID()).'/tab/account'); ?>" action="<?php echo $this->baseUrl($controllername."/processchangeusername"); ?>">Change Username</a>
                               	</td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Phone: </label></td>
                                <td><div class="makerelative"><?php echo isEmptyString($user->getFormattedPhone()) ? '--' : $user->getFormattedPhone(); ?></div></td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign"><?php echo $this->translate("useraccount_password_label"); ?>: </label></td>
                                <td><?php if($user->isUserActive()){ ?>
                                        <b style="font-size:16px;">&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;</b> &nbsp;
                                    <?php } else { ?>
                                        --
                                    <?php } ?>
                                    <?php if($isme){ ?>
                                        <a class="changepassword pull-right" id="changepassword" rel="Change Password" href="<?php echo $this->baseUrl($controllername.'/changepassword/pgc/true/id/'.encode($user->getID())); ?>">Change Password</a>
                                    <?php } else { ?>
                                        <a class="confirm-dialog pull-right" id="resetpassword" href="<?php echo $this->baseUrl($controllername.'/resetpassword/id/'.encode($user->getID())); ?>" message="Are you sure you want to reset <?php echo $user->getName() ?>'s Password?">Reset Password</a>
                                    <?php } ?>
                                </td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Account Type: </label></td>
                                <td><?php echo $user->getTypeLabel(); ?></td>
                           </tr>
                           <tr>		                    
                          		<td colspan="2">
									<?php if($acl->checkPermission($resourcename, ACTION_DELETE) && !$isme && $user->isUserInActive()){ ?>
                                        <a class="btn btn-danger deleteline gonowhere" action="<?php echo $this->baseUrl($controllername.'/delete/id/'.encode($user->getID())."/entityname/UserAccount/successurl/".encode($this->baseUrl($controllername.'/list'))); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>"><i class="icon-trash icon-white"></i> Delete Profile</a>
                                    <?php } ?> 
									<?php if($acl->checkPermission($resourcename, ACTION_DELETE) && !$isme && $user->isUserActive()){ ?>
                                        <a class="btn btn-warning deactivate noimgbutton confirm-dialog" href="<?php echo $this->baseUrl($controllername.'/deactivate/id/'.$user->getID()."/status/2/entityname/UserAccount/successurl/".encode($this->viewurl).'/successmessage/Profile successfully Deactivated'); ?>" message="Are you sure you want to Deactivate this profile? Please note that user will not be able to login after this."><i class="icon-arrow-down icon-white"></i> Deactivate</a>
                                    <?php } ?>
                                    <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && $user->isDeactivated() && !$isme){ ?>
                                        <a class="btn btn-primary reactivate noimgbutton confirm-dialog" href="<?php echo $this->baseUrl($controllername.'/deactivate/id/'.$user->getID()."/status/1/entityname/UserAccount/successurl/".encode($this->viewurl).'/successmessage/Profile successfully Re-Aactivated'); ?>" message="Are you sure you want to Re-Activate this profile?"><i class="icon-arrow-up icon-white"></i> Re-Activate</a>
                                    <?php } ?>
                            	</td>
                    		</tr>
                        </table>
                	</fieldset>
                </div>
                <?php } ?>
                <?php if(isEmptyString($request->section)){ ?>
                    <div class="row margin0 padding0" style="min-height:200px;">
                        <fieldset class="fieldsetcontainer well">
                            <legend>Settings</legend>
                            <table class="table nohover noborder margin10" style="width:700px;">
                                <?php if($user->isFarmer()){ ?>
                                <tr>
                                    <td style="width:25%;"><label class="control-label" style="width:100%;">Mobile Money Account?</label></td>
                                    <td><?php echo $user->gethasmobilemoney() == 1 ? 'Yes' : 'No'; ?></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label" style="width:100%;">Bank Account?</label></td>
                                    <td><?php echo $user->gethasbankaccount() == 1 ? 'Yes' : 'No'; ?></td>
                                </tr>
                                <tr>
                                    <td style="width:20%;"><label class="control-label">Services Profiled:</label></td>
                                    <td><label class="lineblocked"><?php echo $user->getListOfServices(); ?></label></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label">Preferred Language:</label></td>
                                    <td><label class="lineblocked"><?php echo $user->getLanguagePreferrence(); ?></label></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                          <label class="control-label" style="width:100%;">Market Information Alert Settingss:</label>
                                          <div class="controls" style="margin-left:0;">
                                             <div class="blocked" style="margin-top:5px;"><label class="lineblocked">Send updates and alerts to Phone?</label> <?php echo $user->getreceivephonealerts() == 0 ? 'No' : 'Yes'; ?></div>
                                             <div class="blocked" style="margin-top:5px;"><label class="lineblocked">Send updates and alerts to Email?</label> <?php echo $user->getreceiveemailalerts() == 0 ? 'No' : 'Yes'; ?></div>
                                          </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="control-label" for="updatesfrequency">Frequency of Updates:</label></td>
                                    <td>
                                        <div class="controls" style="margin-left:0;">
                                            <div class="blocked">
                                                <?php
                                                    $values = array("1"=>"Weekly","2"=>"Bi-weekly","3"=>"Fortnightly","4"=>"Monthly");
                                                    echo $values[$user->getUpdatesFrequency()]; 
                                                ?>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                <?php } ?>
                                <tr>
                                    <td colspan="2">
                                        <label class="control-label">System Notification Settings:</label>
                                        <div class="lineblocked" style="vertical-align:top;"><?php echo $this->translate("useraccount_emailmeonmessage_label"); ?>? &nbsp; <?php echo $user->getEmailMeOnMessage() == 1 ? 'Yes' : 'No'; ?></div>  
                                        <div class="lineblocked" style="margin-top:6px; vertical-align:top;"><?php echo $this->translate("useraccount_emailmeoncomment_label"); ?>? &nbsp; <?php echo $user->getEmailMeOnComment() == 1 ? 'Yes' : 'No'; ?></div> 
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
										<?php if($acl->checkPermission($resourcename, ACTION_EDIT) || $isme){ ?>
                                            <a class="btn btn-primary" href="<?php echo $this->baseUrl($request->getControllerName().'/view/id/'.encode($user->getID()).'/tab/account/section/edit'); ?>"><i class="icon-pencil icon-white"></i> Update Settings</a>
                                        <?php } ?>
                                   	</td>
                               	</tr>
                            </table>
                        </fieldset>
                    </div>
                	<?php } else { ?>
                    	<script>
                        $(document).ready(function(){
							$("form#profileform-account").attr('method','post').attr('action', '<?php echo $this->baseUrl('mobile/edit'); ?>');
						});
                        </script>
                    	<div class="control-group well actions" id="topactions">
                              <a href="<?php echo $this->referer; ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                              <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save'); ?></button>
                              <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $this->translate("global_save_success"); ?>" /> 
                        </div>  
                    	<fieldset class="fieldsetcontainer well" style="padding-left:20px; width:98%;">
                            <legend>Update Settings</legend> 
                            <input type="hidden" name="entityname" value="Farmer" />
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                            <input type="hidden" id="thecontroller" name="thecontroller" value="<?php echo $request->getControllerName(); ?>" />
                            <input type="hidden" id="theaction" name="theaction" value="<?php echo $request->getActionName(); ?>" />
                            <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl($request->getControllerName().'/view/id/'.encode($user->getID()).'/tab/account')); ?>" />
                            <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->viewurl); ?>" />
                            <?php require APPLICATION_PATH."/views/scripts/profile/settingfields.phtml"; ?>
                        </fieldset>
                    <?php } ?>
                <?php } ?>
            </form>
        </div>