<div id="account">
            <h2>Account Settings</h2>
            <form id="profileform-account" class="form-horizontal account">
                <?php if($request->tab == 'account'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?> 
                <div class="row margin0 padding0">
                    <fieldset class="fieldsetcontainer well">
                        <legend>Login Credentials</legend>
                   		<table class="table nohover noborder margin10" style="width:550px;">                       
                           <tr>		                    
                                <td><label class="control-label leftalign">Login Status: </label></td>
                                <td><?php echo $user->isUserActive() ? 'Active' : 'In Active'; ?></td>
                           </tr>
                           <tr>		                    
                                <td width="20%"><label class="control-label leftalign">Email: </label></td>
                                <td><?php echo isEmptyString($user->getEmail()) ? '--' : $user->getEmail(); ?> &nbsp;
                                    <a href="<?php echo $this->baseUrl($controllername.'/changeemail/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeemail pull-right" title="Change Email" rel="Change Email" id="changeemail" formtitle="indexform" successurl="<?php echo $this->baseUrl($controllername.'/view/id/'.encode($user->getID()).'/tab/account'); ?>" action="<?php echo $this->baseUrl($controllername."/processchangeemail"); ?>">Change Email</a></td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Username: </label></td>
                                <td><?php echo isEmptyString($user->getUserName()) ? '--' : $user->getUserName(); ?> &nbsp;
                                    <a href="<?php echo $this->baseUrl($controllername.'/changeusername/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeusername pull-right" title="Change Username" rel="Change Username" id="changeusername" formtitle="indexform" successurl="<?php echo $this->baseUrl($controllername.'/view/id/'.encode($user->getID()).'/tab/account'); ?>" action="<?php echo $this->baseUrl($controllername."/processchangeusername"); ?>">Change Username</a>
                               	</td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Phone: </label></td>
                                <td><div class="makerelative"><?php echo isEmptyString($user->getFormattedPhone()) ? '--' : $user->getFormattedPhone(); ?></div></td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign"><?php echo $this->translate("useraccount_password_label"); ?>: </label></td>
                                <td><?php if($user->isUserActive()){ ?>
                                        <b style="font-size:16px;">&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;</b> &nbsp;
                                    <?php } else { ?>
                                        --
                                    <?php } ?>
                                    <?php if($isme){ ?>
                                        <a class="changepassword pull-right" id="changepassword" rel="Change Password" href="<?php echo $this->baseUrl($controllername.'/changepassword/pgc/true/id/'.encode($user->getID())); ?>">Change Password</a>
                                    <?php } else { ?>
                                        <a class="confirm-dialog pull-right" id="resetpassword" href="<?php echo $this->baseUrl($controllername.'/resetpassword/id/'.encode($user->getID())); ?>" message="Are you sure you want to reset <?php echo $user->getName() ?>'s Password?">Reset Password</a>
                                    <?php } ?>
                                </td>
                           </tr>
                           <tr>		                    
                                <td><label class="control-label leftalign">Account Type: </label></td>
                                <td><?php echo $user->getTypeLabel(); ?></td>
                           </tr>
                           
                           <tr>		                    
                          		<td colspan="2">
									<?php if($acl->checkPermission($resourcename, ACTION_DELETE) && !$isme && $user->isUserInActive()){ ?>
                                        <a class="btn btn-danger deleteline gonowhere" action="<?php echo $this->baseUrl($controllername.'/delete/id/'.encode($user->getID())."/entityname/UserAccount/successurl/".encode($this->baseUrl($controllername.'/list'))); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>"><i class="icon-trash icon-white"></i> Delete Profile</a>
                                    <?php } ?> 
									<?php if($acl->checkPermission($resourcename, ACTION_DELETE) && !$isme && $user->isUserActive()){ ?>
                                        <a class="btn btn-warning deactivate noimgbutton confirm-dialog" href="<?php echo $this->baseUrl($controllername.'/deactivate/id/'.$user->getID()."/status/2/entityname/UserAccount/successurl/".encode($this->viewurl).'/successmessage/Profile successfully Deactivated'); ?>" message="Are you sure you want to Deactivate this profile? Please note that user will not be able to login after this."><i class="icon-arrow-down icon-white"></i> Deactivate</a>
                                    <?php } ?>
                                    <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && $user->isDeactivated() && !$isme){ ?>
                                        <a class="btn btn-primary reactivate noimgbutton confirm-dialog" href="<?php echo $this->baseUrl($controllername.'/deactivate/id/'.$user->getID()."/status/1/entityname/UserAccount/successurl/".encode($this->viewurl).'/successmessage/Profile successfully Re-Aactivated'); ?>" message="Are you sure you want to Re-Activate this profile?"><i class="icon-arrow-up icon-white"></i> Re-Activate</a>
                                    <?php } ?>
                            	</td>
                    		</tr>
                        </table>
                	</fieldset>
                </div>
                <div class="row margin0 padding0" style="min-height:200px;">
                	<fieldset class="fieldsetcontainer well">
                        <legend>Settings</legend>
                   		<table class="table nohover noborder margin10" style="width:550px;">
                        	<tr>
                                <td style="padding-left:10px;">
                                    <div class="makerelative">
                                        <span id="emailmeonmessage_wait" class="hidden" style="position:absolute; left:-5px; top:0;">
                                            <img style="width:20px;" src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' />
                                        </span>
                                        <fieldset id="emailmeonmessage" class="radio btn-group lineblocked" style="width:85px;">
                                            <input type="radio" id="emailmeonmessage1" name="emailmeonmessage" class="changesetting <?php echo $user->getEmailMeOnMessage() == 1 ? 1 : 0; ?>" value="1" field="emailmeonmessage" userid="<?php echo $user->getID(); ?>" /><label id="lbl-emailmeonmessage1" for="emailmeonmessage1">Yes</label>
                                            <input type="radio" id="emailmeonmessage0" name="emailmeonmessage" class="changesetting <?php echo $user->getEmailMeOnMessage() == 0 ? 1 : 0; ?>" value="0" field="emailmeonmessage" userid="<?php echo $user->getID(); ?>" /><label id="lbl-emailmeonmessage0" for="emailmeonmessage0">No</label>
                                        </fieldset>
                                        &nbsp;<div class="lineblocked" style="margin-top:6px; vertical-align:top;"><?php echo $this->translate("useraccount_emailmeonmessage_label"); ?></div>
                                    </div>   
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:10px;">
                                    <div class="makerelative">
                                        <span id="emailmeoncomment_wait" class="hidden" style="position:absolute; left:-5px; top:0;">
                                            <img style="width:20px;" src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' />
                                        </span>
                                        <fieldset id="emailmeoncomment" class="radio btn-group lineblocked" style="width:85px;">
                                            <input type="radio" id="emailmeoncomment1" name="emailmeoncomment" class="changesetting <?php echo $user->getEmailMeOnComment() == 1 ? 1 : 0; ?>" value="1" field="emailmeoncomment" userid="<?php echo $user->getID(); ?>" /><label id="lbl-emailmeoncomment1" for="emailmeoncomment1">Yes</label>
                                            <input type="radio" id="emailmeoncomment0" name="emailmeoncomment" class="changesetting <?php echo $user->getEmailMeOnComment() == 0 ? 1 : 0; ?>" value="0" field="emailmeoncomment" userid="<?php echo $user->getID(); ?>" /><label id="lbl-emailmeoncomment0" for="emailmeoncomment0">No</label>
                                        </fieldset>
                                        &nbsp;<div class="lineblocked" style="margin-top:6px; vertical-align:top;"><?php echo $this->translate("useraccount_emailmeoncomment_label"); ?></div>
                                    </div>   
                                </td>
                            </tr>
                            <?php if($user->isFarmer()){ ?>
                                <tr>
                                    <td style="padding-left:30px;">
                                        <div class="control-group">
                                          <label class="control-label" style="width:100%;">Recieve Market Information alerts?</label>
                                          <div class="controls" style="margin-left:0;">
                                             <div class="blocked" style="margin-top:5px;"><label class="lineblocked">Send updates and alerts to Phone?</label> <?php echo $user->getreceivephonealerts() == 0 ? 'No' : 'Yes'; ?></div>
                                             <div class="blocked" style="margin-top:5px;"><label class="lineblocked">Send updates and alerts to Email?</label> <?php echo $user->getreceiveemailalerts() == 0 ? 'No' : 'Yes'; ?></div>
                                          </div>
                                        </div>
                                        <div class="control-group">
                                            <label class="control-label" for="updatesfrequency">Frequency of Updates:</label>
                                            <div class="controls" style="margin-left:0;">
                                                <div class="blocked" style="margin-top:5px;">
                                                    <?php
                                                    $values = array("1"=>"Weekly","2"=>"Bi-weekly","3"=>"Fortnightly","4"=>"Monthly");
                                                    echo $values[$user->getUpdatesFrequency()]; 
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            <?php } ?>
                        </table>
                  	</fieldset>
                </div>
                <?php } ?>
            </form>
        </div>