<div class="peoplelist">
	<?php 				  
        $counter = 1;		
		foreach($result as $line){
			$id = $line['id'];	
			$name = $line['firstname']." ".$line['lastname']." ".$line['othernames'];
			$firstname = $line['firstname'];
			$lastname = $line['lastname'];
			$groupname = $line['orgname'];
			$thefarmgroupid = $line['fmgroupid'];
			$subgroupname = '';
			if(!isEmptyString($line['subgroupid'])){
				$subgroupname = $line['sorgname'];
			}
			$refno = $line['regno'];
			if(isKenya()){
				$refno = $line['refno'];
			}
			
			$hasprofileimage = false;
			$real_path = BASE_PATH.DIRECTORY_SEPARATOR."uploads".DIRECTORY_SEPARATOR."user_";
			$real_path = $real_path.$line['userid'].DIRECTORY_SEPARATOR."avatar".DIRECTORY_SEPARATOR."large_".$line['profilephoto'];
			
			if(file_exists($real_path) && !isEmptyString($line['profilephoto'])){
				$hasprofileimage = true;
			}
			$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
			
			$photo_path = '';
			$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_male.jpg';
			if($line['gender'] == 2){
				$photo_path = $baseUrl.'/uploads/user_0/avatar/default_thumbnail_female.jpg'; 
			}
			if($hasprofileimage){
				$photo_path = $this->serverUrl($this->baseUrl('/uploads/user_'.$line['userid'].'/avatar/medium_'.$line['profilephoto']));
			}
			$hasdfa = true; $hasgroup = true;
			if(isEmptyString($thefarmgroupid)){
				$hasdfa = false;
			}
			if(isEmptyString($line['subgroupid'])){
				$hasgroup = false;
			}
            
    ?>
        <?php if($counter % 2 == 1){ ?>
        <div class="row-fluid">
        <?php } ?>
          <div class="span6">
            <div class="peoplewrapper well">
              <div class="thumbwrapper">
                    <div class="thumb">
                        <div id="thumbinfo" class="<?php echo $hasprofileimage ? 'new_pic' : 'default_pic'; ?>"> 
                            <a href="<?php echo $this->baseUrl($controllername."/view/id/".encode($id)); ?>"><img class="profileimage" src="<?php echo $photo_path; ?>" /></a>
                        </div>
                    </div>
					<?php if($line['usertype'] == 4){ ?>
                        <div class="blocked bolded" style="font-size:10px; padding-left:5px;"><span>PID#:</span> <?php echo $line['id']; ?></div>
                    <?php } ?>
              </div>
              <div class="peopleinfo">
                <h4><a href="<?php echo $this->baseUrl($controllername."/view/id/".encode($id)); ?>"><?php echo $name; ?></a></h4>
                <ul>
                    <li><span>Type:</span> 
						<?php echo getUserType($line['usertype']); ?>
                        <?php if($line['usertype'] == 3){
                            echo ' (<a href="'.$this->baseUrl('farmgroup/view/id/'.encode($line['fmgroupid'])).'">'.$line['orgname'].'</a>)';
                        } 
                        ?>
                      </li>
                      <li><span>Phone:</span> <?php echo isEmptyString($line['phone']) ? '--' : getShortPhone($line['phone']); ?></li>
                      <li><span>Email:</span> <?php echo isEmptyString($line['email']) ? '--' : $line['email']; ?></li>
                      <li><span>Username:</span> <?php echo isEmptyString($line['username']) ? '--' : $line['username']; ?></li>
                      <li><span>Status:</span> <?php echo $line['isactive'] == 1 ? 'Activated' : 'Inactive'; ?></li>
                      <li><span>Profiled By:</span> <?php echo $line['addedby']; ?></li>
                      <li><span>Date:</span> <?php echo formatDateAndTime($line['dateadded'], true); ?></li>
                </ul>
              </div>
              <!--peopleinfo--> 
            </div>
            <!--peoplewrapper--> 
          <?php if($counter % 2 == 0){ ?>
          </div>
          <?php } ?>
        </div>
    <?php $counter++; } ?>
  </div>
<?php echo $paginate->getPaginationLinks(); ?>  