<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	// debugMessage($request);
	$theid = is_numeric($request->id) ? $request->id : decode($request->id);
	if(isEmptyString($theid)){
		$theid = $userid;
	}
	if(!isEmptyString($theid)){
		$user->populate($theid);
	}
	if(!isEmptyString($request->username)){
		$user->findByUsername($request->username);
	}
	$country = 'UG';
	$location_label = 'District';
	$locations_label = 'Districts';
	$countrycode = COUNTRY_CODE_UG;
	$county_label = $this->translate("global_county_label");
	$subcounty_label = $this->translate("global_subcounty_label");
	
	if(isKenya() || $user->isKenyan()){
		$country = 'KE';
		$session->setVar('country', 'ke');
		$location_label = 'County';
		$locations_label = 'Counties';
		$countrycode = COUNTRY_CODE_KE;
		$county_label = $this->translate("global_subcounty_label");
		$subcounty_label = $this->translate("global_ward_label");
	}
	
	// debugMessage($user->toArray()); exit();
	$id = $user->getID();	
	$name = $user->getName();
	$firstname = $user->getFirstName();
	$resourcename = 'Farmer';
	if($controllername == 'profile'){
		$resourcename == 'User Account';
	}
	
	# profile for one viewing
	$isme = false;
	if($userid == $user->getID()){
		$isme = true;
	}
	
	$tab = $request->tab;
	if(isEmptyString($tab)) {
		$tab = 'basics';
	}
	
	$metxt = '';
	if($isme){
		$metxt = 'My ';
	}
	
	$loadgps = true;
	$title = $user->getName();
	$this->headTitle($title);
	
?>
<?php if(($user->hasGPSCoordinates() || !isEmptyString($request->detect)) && $loadgps){ ?>
<script src="<?php echo $this->serverUrl($this->baseUrl('assets/js/maps/geoPosition.js')); ?>"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true&key=AIzaSyAjkTHnLzEkyF1ntVoUkZthaZWV4VN5DJE"></script>
<?php } ?>
<script>
$(document).ready(function(){
	<?php if($user->hasGPSCoordinates() && isEmptyString($request->detect) && $loadgps){ ?>
		var gpslat = '<?php echo $user->getlat(); ?>';
		var gpslng = '<?php echo $user->getlng(); ?>';
		var title = "<?php echo $isme ? 'My Location' : $user->getFirstName()."'s Location "; ?>";
	<?php } ?>
	
});

$(window).load(function() {
	<?php if(!isEmptyString($request->detect) && $loadgps){ ?>
		(function() {
	    	// initialise the google map
			function initialiseMap(){
				var myOptions = {
					  zoom: 14,
					  mapTypeControl: true,
					  mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
					  navigationControl: true,
					  navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
					  mapTypeId: google.maps.MapTypeId.ROADMAP      
					}        
				map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
			}
			function initialise() {
				if(geoPosition.init()){
					document.getElementById('current').innerHTML="<b>Click 'Allow' to grant the browser access your location.</b> <br />Receiving location... please wait...";
					geoPosition.getCurrentPosition(
						showPosition,
						function(){
							document.getElementById('current').innerHTML="Couldn't get location"
						},
						{maximumAge:60000, timeout:10000, enableHighAccuracy:true}
					);
				} else {
					document.getElementById('current').innerHTML="Your Browser is not supported for this function";
				}
			}
		
			function showPosition(p){
				var latitude = parseFloat(p.coords.latitude);
				latitude = latitude.toFixed(6);
				
				var longitude = parseFloat(p.coords.longitude);
				longitude = longitude.toFixed(6);
				
				//$("#lat").val(latitude);
				//$("#lng").val(longitude);
				if(!isEmptyString(latitude) && !isEmptyString(longitude)){
					$("#hasgps").val(latitude+','+longitude);
				}
				document.getElementById('current').innerHTML='Click Save Position to save changes. <br /> Latitude: <input type="text" class="isdecimal width100" name="lat" id="lat" value="'+latitude+'" /><br /><br />Longitude: <input type="text" class="form-control input-width-small isdecimal width100" name="lng" id="lng" value="'+longitude+'" /> <div id="lat_error"></div><div id="lng_error"></div>';
				var pos=new google.maps.LatLng(latitude, longitude);
				map.setCenter(pos);
				map.setZoom(18);
		
				var infowindow = new google.maps.InfoWindow({
					content: "<strong>Farmer's Location</strong>"
				});
		
				var marker = new google.maps.Marker({
					position: pos,
					map: map,
					title:"You are here"
				});
		
				google.maps.event.addListener(marker, 'click', function() {
				  infowindow.open(map,marker);
				});
			}
			
			initialiseMap();
			initialise();
	    	
	    })();
	<?php } ?>
	
	<?php if(isEmptyString($request->detect) && $user->hasGPSCoordinates() && $loadgps){ ?>
		// initialise the google map
		function initialiseMap(){
			var myOptions = {
				  zoom: 4,
				  mapTypeControl: true,
				  mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
				  navigationControl: true,
				  navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
				  mapTypeId: google.maps.MapTypeId.ROADMAP      
				}        
			map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
		}
		
		function showPosition(){
			var latitude = '<?php echo $user->getLat(); ?>';
			var longitude = '<?php echo $user->getLng(); ?>';
			var pos = new google.maps.LatLng(latitude, longitude);
			map.setCenter(pos);
			map.setZoom(14);
	
			var infowindow = new google.maps.InfoWindow({
				content: "<b><?php echo $user->getName(); ?>'s Location</b> <br /><br /> Latitude = "+latitude+ " <br />Longitude = "+longitude
			});
	
			var marker = new google.maps.Marker({
				position: pos,
				map: map,
				title:"<?php echo $user->getName(); ?>'s Location"
			});
	
			google.maps.event.addListener(marker, 'click', function() {
			  infowindow.open(map,marker);
			});
		}
		
		<?php if($user->hasGPSCoordinates()){ ?>
			initialiseMap(); 
			showPosition(); 
		<?php } ?>
	<?php } ?>
});	
</script>

<?php if(!isFarmer()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">   
        <div id="basics">
            <form id="profileform-basics" class="form-horizontal basics">
            <?php if($tab == 'basics'){ ?>
				<?php if($sessionhaserror) { ?>
                  <div class="row-fluid">
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                  </div>
                <?php } ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                <div class="row-fluid">
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                </div>
                <?php } ?>
                <?php if(!isEmptyString($session->getVar("custommessage")) ){ ?>
                <div class="row-fluid">
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("custommessage"); ?></div>
                </div>
                <?php } ?>
                <?php if(!isEmptyString($session->getVar("emailinvitesuccess")) ){ ?>
                <div class="row-fluid">
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("emailinvitesuccess"); ?></div>
                </div>
                <?php } ?>
                <?php if(!isEmptyString($session->getVar("phoneinvitesuccess")) ){ ?>
                <div class="row-fluid">
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("phoneinvitesuccess"); ?></div>
                </div>
                <?php } ?>
                <div class="row margin0">
                	<?php if(isEmptyString($request->detect)){ ?>
                    <div class="row margin0 pull-left">
                        <?php if($isme || $acl->checkPermission($resourcename, ACTION_EDIT)){ ?>
                            <a class="btn btn-primary" href="<?php echo $this->baseUrl($controllername.'/index/id/'.encode($id)); ?>" id="update"><i class="icon-pencil icon-white"></i> Update Profile</a>
                        <?php } ?>
                        <?php if($acl->checkPermission($resourcename, ACTION_LIST)){ ?>
                            <?php if($user->isFarmer()){ ?>
                                <a class="btn" href="<?php echo $this->baseUrl('farmer/list'); ?>"><i class="icon-list"></i> Farmers</a>
                            <?php } ?>
                            <?php if(!$user->isFarmer()){ ?>
                                <a class="btn" href="<?php echo $this->baseUrl('profile/list'); ?>"><i class="icon-list"></i> User Profiles</a>
                            <?php } ?>
                        <?php } ?>
                    </div>
                    <?php } ?>
                    
                    <div class="divider10"></div>
                    <span class="span6 marginleft0" style="width:72%;">
                        <?php if(isEmptyString($request->detect)){ ?>
                            <fieldset class="fieldsetcontainer well">
                                <legend>Summary</legend>
                                <table class="table noborder noborder nohover margin10">                       
                                    <?php if($user->isFarmer()){ ?>
                                        <?php if(strtolower($country) == 'ug'){ ?>
                                            <tr>		                    
                                                <td><label class="control-label prefix">FIN#:</label></td>
                                                <td><?php echo $user->getRefNo(); ?></td>
                                                <td><label class="control-label prefix">Ref#:</label></td>
                                                <td><?php echo $user->getRegNo(); ?></td>
                                            </tr>
                                        <?php } ?>
                                        <?php if(strtolower($country) == 'ke'){ ?>
                                            <tr>		                    
                                                <td><label class="control-label">National ID#:</label></td>
                                                <td><?php echo $user->getRefNo(); ?></td>
                                                <?php if($user->isPIA()){ ?>
                                                    <td><label class="control-label">PID#</label></td>
                                                    <td><?php echo $user->getID(); ?></td>
                                                <?php } else { ?>
                                                    <td></td>
                                                    <td></td>
                                                <?php } ?>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>
                                    <tr>
                                        <td style="width:18%;"><label class="control-label"><?php echo "Full ".$this->translate("farmer_name_label"); ?>:</label></td>
                                        <td style="width:32%;"><?php echo $user->getName(); ?><?php echo $user->getSalutationLabel(); ?></td>
                                        <td style="width:18%;"><label class="control-label"><?php echo $this->translate("farmer_gender_label"); ?>:</label></td>
                                        <td><?php echo $user->getGenderLabel(); ?></td>                                                             
                                    </tr>
                                    <tr>
                                        <td><label class="control-label"><?php echo $this->translate("farmer_dateofbirth_label"); ?>:</label></td>
                                        <td><?php echo $user->getBirthDateFormatted(); ?></td>
                                        <td><label class="control-label"><?php echo $this->translate("farmer_dateregistered_label"); ?>:</label></td>
                                        <td><?php echo isEmptyString($user->getRegDate()) ? '--' : changeMySQLDateToPageFormat($user->getRegDate()); ?></td>
                                    </tr>
                                    <tr>
                                        <td><label class="control-label">Phone:</label></td>
                                        <td><?php echo isEmptyString($user->getFormattedPhone()) ? '--' : $user->getFormattedPhone(); ?></td>
                                        <td><label class="control-label">Email:</label></td>
                                        <td><?php echo isEmptyString($user->getEmail()) ? '--' : $user->getEmail(); ?></td>
                                    </tr>
                                    <tr>
                                        <td><label class="control-label">Alt Phone:</label></td>
                                        <td><?php echo isEmptyString($user->getFormattedPhone2()) ? '--' : $user->getFormattedPhone2(); ?></td>
                                        <td><label class="control-label">Alt Email:</label></td>
                                        <td><?php echo isEmptyString($user->getEmail2()) ? '--' : $user->getEmail2(); ?></td>
                                    </tr>
                                    <?php if($user->hasFarmGroup()){ ?>  
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_dna_label"); ?>:</label></td>
                                            <td><?php if($acl->checkPermission('DNA', ACTION_LIST)){ ?>
                                                    <a href="<?php echo $this->baseUrl('farmgroup/view/id/'.encode($user->getFarmGroupID())); ?>"><?php echo $user->getFarmGroup()->getName(); ?></a>
                                                <?php } else { ?>
                                                    <?php echo $user->getFarmGroup()->getName(); ?>
                                                <?php } ?>
                                            </td>
                                            <?php if($user->hasSubGroup()){ ?> 
                                                <td><label class="control-label"><?php echo $this->translate("farmer_subgroup_label"); ?>:</label></td>
                                                <td><?php echo $user->getSubGroup()->getName(); ?></td>
                                            <?php } else { ?>
                                                <td colspan="2"></td>
                                            <?php } ?>
                                        </tr>
                                    <?php } ?>
                                    <?php if(!$isme && $acl->checkPermission($resourcename, ACTION_LIST)){ ?>
                                        <tr>
                                            <td><label class="control-label">Type: </label></td>
                                            <td><?php echo $user->getTypeLabel(); ?></td>
                                            <?php if($user->isPartner()){ ?>
                                                <td><label class="control-label">Name of Partner:</label></td>
                                                <td><?php if($acl->checkPermission('Partner', ACTION_LIST)){ ?>
                                                        <a href="<?php echo $this->baseUrl('company/view/id/'.encode($user->getCompanyID())); ?>"><?php echo $user->getCompany()->getName(); ?></a>
                                                    <?php } else { ?>
                                                        <?php echo $user->getCompany()->getName(); ?>
                                                    <?php } ?>
                                                </td>
                                            <?php } else { ?>
                                                <td colspan="2"></td>
                                            <?php } ?>
                                        </tr>
                                    <?php } ?>
                                </table>
                            </fieldset>
                            <?php if($user->isFarmer()){ ?>
                                <fieldset class="fieldsetcontainer well">
                                    <legend>About</legend>
                                    <div class="padding10" style="min-height:30px; margin-left:10px;"><label class="control-label">Bio:</label>
                                    <?php echo isEmptyString($user->getBio()) ? '--' : nl2br($user->getBio()); ?></div>
                                    <table class="table margin10 noborder nohover">  
                                        <tr>		  
                                            <td width="35%"><label class="control-label"><?php echo $this->translate("farmer_maritalstatus_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getMaritalStatusText()) ? '--': $user->getMaritalStatusText(); ?></td>
                                            <td width="30%"><label class="control-label"><?php echo $this->translate("farmer_educlevel_label"); ?>:</label>
                                            <?php echo $user->getEducationLevelText(); ?></td>
                                            <td></td>
                                        </tr>
                                        <tr>		  
                                            <td><label class="control-label"><?php echo $this->translate("farmer_nochildren_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNumberOfChildren()) ? '--': $user->getNumberOfChildren(); ?></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_nodependants_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNumberOfDependants()) ? '--': $user->getNumberOfDependants(); ?></td>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_totalhousehold_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getTotalHousehold()) ? '--': $user->getTotalHousehold(); ?></td>
                                        </tr>
                                       <tr>		  
                                            <td width="35%"><label class="control-label"><?php echo $this->translate("farmer_nextofkin_label"); ?> <?php echo $this->translate("global_name_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNextofkin_Name()) ? '--': $user->getNextofkin_Name(); ?>
                                            </td>
                                            <td width="30%"><label class="control-label"><?php echo $this->translate("farmer_nextofkin_label"); ?> <?php echo $this->translate("global_phone_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNextofkin_phone()) ? '--': $user->getNextofkin_phone(); ?>
                                            </td>
                                            <td width="35%"><label class="control-label"><?php echo $this->translate("farmer_nextofkin_label"); ?> <?php echo $this->translate("global_email_label"); ?>:</label>
                                            <?php echo isEmptyString($user->getNextofkin_email()) ? '--': $user->getNextofkin_email(); ?>
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            <?php } ?>
                        <?php } ?>
                        <fieldset class="fieldsetcontainer well">
                            <legend>Location</legend>
                            <?php if(isEmptyString($request->detect)){ ?>
                                <table class="table margin10 noborder nohover">                       
                                    <tr>
                                        <td width="35%"><label class="control-label">Country:</label>
                                            <?php echo isEmptyString($user->getCountry()) ? '--' : $user->getCountryName(); ?>
                                        </td>
                                        <td width="30%"><label class="control-label"><?php echo $location_label; ?>:</label>
                                            <?php echo isEmptyString($user->getLocationID()) ? '--' : $user->getLocation()->getName(); ?>
                                        </td>
                                        <td width="35%"><label class="control-label"><?php echo $county_label; ?>:</label>
                                            <?php echo isEmptyString($user->getCountyID()) ? '--' : $user->getCounty()->getName(); ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label class="control-label"><?php echo $subcounty_label; ?>:</label>
                                            <?php echo isEmptyString($user->getSubCountyID()) ? '--' : $user->getSubCounty()->getName(); ?>
                                        </td>
                                        <td>
                                        <?php if($user->isUgandan()){ ?>
                                            <label class="control-label">Parish:</label>
                                            <?php echo isEmptyString($user->getParishID()) ? '--' : $user->getParish()->getName(); ?>
                                        <?php } ?>
                                        </td>
                                        <td>
                                        <?php if($user->isUgandan()){ ?>
                                            <label class="control-label">Village:</label>
                                            <?php echo isEmptyString($user->getVillageID()) ? '--' : $user->getVillage()->getName(); ?>
                                        <?php } ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td><label class="control-label">Postal/Street Address</label>
                                            <?php echo isEmptyString($user->getStreetAddress()) ? '--' : nl2br($user->getStreetAddress()); ?>
                                        </td>
                                        <td><label class="control-label">GPS Latitude:</label><?php echo $user->getLat(); ?></td>
                                        <td><label class="control-label">GPS Longitude:</label><?php echo $user->getLng(); ?></td>
                                    </tr>
                                </table>
                            <?php } ?>
                            <div style="margin: 10px 10px 10px 15px;">
                                <div class="divider10"></div>
                                <label class="control-label">Map:</label>
                                <?php if(!isEmptyString($request->detect)){ ?>
                                    <div class="row-fluid control-group well actions" id="topactions" style="width:97%;">
                                        <a href="<?php echo $this->referer; ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                        <a href="<?php echo $this->viewurl; ?>" class="btn"><i class="icon-refresh"></i> Reload</a>
                                        <button type="submit" class="btn btn-primary"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save')." Position"; ?></button>
                                        <input type="hidden" name="entityname" value="Farmer" />
                                        <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                                        <input type="text" id="hasgps" name="hasgps" value="" style="background:none; background-color:#F5F5F5; border:none; box-shadow:none;"/>
                                        <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->viewurl); ?>" />
                                        <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
                                        <input type="hidden" id="thecontroller" name="thecontroller" value="<?php echo $request->getControllerName(); ?>" />
                            			<input type="hidden" id="theaction" name="theaction" value="<?php echo $request->getActionName(); ?>" />
                                        <script>
										$(document).ready(function(){
											$("#profileform-basics").attr('method','post').attr('action', '<?php echo $this->baseUrl('mobile/edit'); ?>');
											
											$("#profileform-basics").validate({		
												// define the validation rules one field at a time
												rules: {
													hasgps: "required",
													lat: "required",
													lng: "required"													
												}, 
												// the messages for each of the fields being validated
												messages: {		
													hasgps: "No location detected",
													lat: "Latitude is required",
													lng: "Longitude is required"
												},
												// custom error positions
												errorPlacement: function(error, element) {
													switch(element.attr("name")){					
														default:
															error.appendTo("#"+element.attr("name")+"_error")
															break;
													}			
												}
											});
										});
										</script>
                                    </div>
                                    <div class="well lighter clearfix makerelative" style="min-height:405px; padding:10px;">
                                        <div class="control-group">
                                            <div id="hasgps_error"></div>
                                        </div>
                                        <div class="row-fluid">
                                          <div id="current">Initializing...</div>
                                          <div id="map_canvas" class="span12" style="height:400px; width:100%; margin-left:0;"></div>
                                        </div>
                                    </div>
                               	<?php } else { ?>
                                    <a href="<?php echo $this->baseUrl($controllername.'/view/id/'.encode($user->getID()).'/detect/1'); ?>" class="btn btn-primary btn-mini"><?php echo $user->hasGPSCoordinates() ? 'Recompute Position' : 'Compute Position'; ?></a>
                                    <div class="well lighter clearfix makerelative" style="min-height:405px; padding:10px; margin-top:5px;">
                                    	<div id="map_canvas" class="span12" style="height:400px; width:100%; margin-left:0;"></div>
                                    </div>
                              	<?php } ?>
                            </div>
                        </fieldset>    
                    </span>
                    <?php if(isEmptyString($request->detect)){ ?>
                    	<span class="span3 pull-right" style="width:24%;">
                        <div id="xrow2_right" class="well lighter row" style="height:550px;">
                            <h3 class="well-legend margin0">Account Summary</h3>
                            <table class="table table-striped table-bordered xtable-condensed" id="stats">
                                <?php if($user->isDataClerk() || $user->isFarmer()){ ?>
                                    <tr>             
                                        <td class="profilerightlabel nullifempty">
                                        <?php if($user->isDataClerk()){ ?>
                                            PID#:
                                        <?php } ?>
                                        <?php if($user->isFarmer()){ ?>
                                            FIN#:
                                        <?php } ?>
                                        </td>
                                        <td class="profilerightvalue nullifempty"><?php echo $user->isPIA() ? $user->getID() : $user->getRefNo(); ?></td>
                                    </tr>
                                <?php } ?>
                                <tr>		                    
                                    <td class="profilerightlabel">Account Type:</td>
                                    <td class="profilerightvalue nullifempty"><?php echo $user->getTypeLabel(); ?></td>
                                </tr>
                                <tr>		                    
                                    <td class="profilerightlabel">Login Status:</td>
                                    <td class="profilerightvalue nullifempty"><?php echo $user->getLoginStatus(); ?></td>
                                </tr>
                                <?php if($user->isFarmer()){ ?>
                                    <tr>		                    
                                        <td class="profilerightlabel">Service Status:</td>
                                        <td class="profilerightvalue nullifempty"><?php echo $user->getServiceStatus(); ?></td>
                                    </tr>
                                    <tr>		                    
                                        <td class="profilerightlabel">Payment Date:</td>
                                        <td class="profilerightvalue nullifempty"><?php echo changeMySQLDateToPageFormat($user->getPayment()->getTrxDate()); ?></td>
                                    </tr>
                                    <tr>		                    
                                        <td class="profilerightlabel">Service Start:</td>
                                        <td class="profilerightvalue nullifempty"><?php echo changeMySQLDateToPageFormat($user->getStartDate()); ?></td>
                                    </tr>
                                    <tr>		                    
                                        <td class="profilerightlabel">Expiry Date:</td>
                                        <td class="profilerightvalue nullifempty"><?php echo changeMySQLDateToPageFormat($user->getEndDate()); ?></td>
                                    </tr>
                                <?php } else { ?>
                                    <tr>		                    
                                        <td class="profilerightlabel">Activation Date:</td>
                                        <td class="profilerightvalue nullifempty"><?php echo isEmptyString($user->getActivationDate()) ? '--' : changeMySQLDateToPageFormat($user->getActivationDate()); ?></td>
                                    </tr>
                                <?php } ?>
                                <?php if($user->isFarmer()){ ?>
                                    <tr>             
                                        <td class="profilerightlabel">No of Crops:</td>
                                        <td class="profilerightvalue nullifempty"><a href="<?php echo $this->baseUrl('farmer/view/id/'.$user->getID().'/tab/farm'); ?>"><?php echo $user->getCrops()->count(); ?></a></td>
                                    </tr>
                                    <tr>             
                                        <td class="profilerightlabel">No of Seasons:</td>
                                        <td class="profilerightvalue nullifempty"><a href="<?php echo $this->baseUrl('farmer/view/id/'.$user->getID().'/tab/seasons'); ?>"><?php echo $user->getSeasons()->count(); ?></a></td>
                                    </tr>
                                <?php } ?>
                                <tr>		                    
                                    <td class="profilerightlabel">Entry Date:</td>
                                    <td class="profilerightvalue nullifempty"><?php echo formatDateAndTime($user->getDateCreated(), true); ?></td>
                                </tr>
                                <tr>		                    
                                    <td class="profilerightlabel">Profiled By:</td>
                                    <td class="profilerightvalue nullifempty"><?php echo $user->getCreator()->getName(); ?></td>
                                </tr>
                            </table>
                        </div>
                    </span>		
                    <?php } ?>
                </div>
            <?php } ?>
        	</form> 
        </div>
        <?php if($user->isFarmer()){ ?>
            <div id="farm">
                <h2>Manage Farm</h2>
                <form id="profileform-farm" class="form-horizontal farm">
                    <?php if($tab == 'farm'){ ?>
                        <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                            <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <div class="row margin0 padding0">
                             <?php if($isme || $acl->checkPermission($resourcename, ACTION_EDIT)){ ?>
                                <a class="btn btn-primary" href="<?php echo $this->baseUrl($controllername.'/index/id/'.encode($id).'/tab/farm'); ?>" id="update"><i class="icon-pencil icon-white"></i> Update Profile</a>                                       
                            <?php } ?>
                        </div> 
                        <div class="divider10"></div>
                        <div class="row margin0 padding0" style="width:100%;">
                            <span style="width:49%; float:left;">
                                <div class="well lighter row marginleft0" id="farmleft" style="min-height:325px;"> 
                                    <h3 class="well-legend">Manage Farm</h3>
                                    <table class="table"> 
                                        <tr>
                                            <td width="40%"><label class="control-label" style="display:inline-block;"><?php echo $this->translate("farm_name_label"); ?>:</label></td>
                                            <td><?php echo $user->getName(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Practicing Farming Since:</label></td>
                                            <td><?php echo $user->getFullStartDate(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farm_numberofemployees_label"); ?>:</label></td>
                                            <td><?php echo isEmptyString($user->getNumberOfEmployees()) ? '0' : $user->getNumberOfEmployees(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_farminigtypes_label"); ?>: </label></td>
                                            <td><?php echo $user->getFarminigTypesLabel(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">Farming Tools Used</label></td>
                                            <td><?php echo $user->getFarmingToolsLabel(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label"><?php echo $this->translate("farmer_activities_label"); ?>: </label></td>
                                            <td><?php echo $user->getActivityTypesLabel(); ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </span>
                            <span style="width:49%; float:right;">
                                <div class="well lighter row marginleft0" id="farmright" style="min-height:325px;">
                                    <h3 class="well-legend">Land Usage</h3>                       
                                    <table class="table higherpadding"> 
                                        <tr>
                                            <td width="50%" class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landsize_label"); ?>:</label></td>
                                            <td><?php echo $user->displayLandSize(); ?></td>
                                        </tr>
                                        <tr>
                                            <td class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landsizeactive_label"); ?>:</label></td>
                                            <td><?php echo $user->displayActiveLandSize(); ?></td>
                                        </tr>
                                        <tr>
                                            <td class="nowrapping"><label class="control-label"><?php echo $this->translate("farm_landacquiremethod_label"); ?>:</label></td>
                                            <td><?php echo $user->getLandAcquireMethodLabel(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><label class="control-label">No of Farm Lands / Fields:</label></td>
                                            <td><?php echo $user->getNumberOfFields(); ?></td>
                                        </tr>
                                    </table>
                                </div>
                            </span>
                        </div>
                        <div class="row" style="margin-left:0px; position:relative;">
                            <?php require APPLICATION_PATH."/views/scripts/profile/cropscolumn.phtml"; ?>
                        </div>
                    <?php } ?>
                </form>
            </div>
            <?php if($acl->checkPermission('Farmer Seasons', ACTION_LIST)){ ?> 
                <div id="seasons">
                    <h2>Manage Seasons</h2>
                    <form id="profileform-seasons" class="form-horizontal seasons">
                        <?php if($tab == 'seasons'){ ?>
                            <div class="row" style="margin-left:0px;">
                                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                                <?php } ?>  
                                <div class="margin0">
                                    <?php if($isme || $acl->checkPermission("Farmer Seasons", ACTION_CREATE)){ ?>
                                        <a class="btn btn-primary" href="<?php echo $this->baseUrl('season/index/userid/'.encode($user->getID())); ?>" title="Setup New Season"><i class="icon-plus icon-white"></i> Setup Season</a>
                                    <?php } ?>
                                </div> 
                                <div class="divider10"></div>
                                <span class="span6 marginleft0" style="width:100%;">
                                    <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                                    <?php 
                                        $seasons = $user->getSeasons();
                                        $scount = $seasons->count();
                                        if($scount == 0) { ?>
                                        <div class="alert alert-info">No seasons have been Setup. Click on 'Setup Season' to get started</div>
                                    <?php } else { ?>                
                                        <label class="labeldescription">Viewing <?php echo $scount; ?> <?php echo $scount == 1 ? 'season' : 'seasons'; ?></label>
                                        <ul id="datalist" class="nav nav-stacked">
                                            <?php 
                                                foreach($seasons as $season){
                                            ?>
                                            <li style="min-height:150px;">
                                                <table class="table noborder margin0">
                                                    <tr>                                
                                                        <td width="30%" style="padding-top:20px;">
                                                            <div class="imagecontainer" style="width:90%; min-height:90px; padding:2px;">
                                                                <img style="width:100%;" src="<?php echo $season->getCrop()->getImagePath(); ?>" />
                                                            </div>
                                                        </td>
                                                        <td class="padding0">
                                                            <div style="position:relative;">
                                                                <table class="itemlist table noborder margin0">
                                                                    <tr>
                                                                        <td colspan="4"><h2 style="font-size:15px;"><a href="<?php echo $this->baseUrl("season/view/id/".encode($season->getID())); ?>" title="Season Details"><?php echo $season->getName()." - ".$season->getRef(); ?></a></h2>
                                                                        </td>
                                                                        <td class="actionbuttons" rowspan="4" style="padding-top:5px;">
                                                                            <a class="btn btn-primary wrap" style="position:absolute; top:35px; right:10px;" href="<?php echo $this->baseUrl("season/view/id/".encode($season->getID())); ?>">View Details</a>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td width="90"><label class="control-label">Season Start: </label></td>
                                                                        <td width="140" class="nowrapping"><span><?php echo $season->getFullStartDate(); ?></span></td>
                                                                        <td width="60"><label class="control-label"></label></td>
                                                                        <td width="100" class="nowrapping"><span></span></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td><label class="control-label">Projected End: </label></td>
                                                                        <td class="nowrapping"><span><?php echo $season->getFullEndDate(); ?></span></td>
                                                                        <td></td>
                                                                        <td class="nowrapping"><span></span></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td><label class="control-label">Status: </label></td>
                                                                        <td class="nowrapping"><span><?php echo $season->getStatusText(); ?></span></td>
                                                                        <td></td>
                                                                        <td class="nowrapping"><span></span></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td><label class="control-label">Crop: </label></td>
                                                                        <td class="nowrapping"><span><?php echo $season->getCrop()->getName(); ?></span></td>
                                                                        <td></td>
                                                                        <td class="nowrapping"><span></span></td>
                                                                    </tr>
                                                                </table>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </li>
                                            <?php } ?>    
                                        </ul>
                                        <?php } ?>           
                                    </div>
                                </span>
                            </div>
                        <?php } ?>
                    </form>
                </div>
            <?php } ?>
            <?php if($acl->checkPermission('Farmer Calendar', ACTION_VIEW)){ ?>  
                <div id="calendar">
                    <h2>Season Activity Calendar</h2>
                    <form id="profileform-calendar" class="form-horizontal calendar clearfix">
                        <?php if($tab == 'calendar'){ ?>
                            <script>
                            $(document).ready(function() {
                                $('#calendarcontainer').fullCalendar({
                                    header: {
                                        left: 'prev,next today',
                                        center: 'title',
                                        right: 'month,basicWeek,basicDay'
                                    },
                                    defaultView: 'month',
                                    editable: false,
                                    events: "<?php echo $this->baseUrl('profile/events/id/'.$user->getID()); ?>",
                                    eventRender: function(event, element) {
                                        var type = $("#targetposition").html();
                                        var tippos = $("#tipposition").html();
                                        var tooltip_title = event.formatedstart+': '+event.title+' - ['+event.seasonref+']';
                                        var idclass = event.className;
                                        if(!isEmptyString(event.end)){
                                            tooltip_title = event.formatedstart+' - '+event.formatedend+'<br> '+event.title+' - ['+event.seasonref+']';
                                        }
                                        element.qtip({
                                            content: {
                                                text: '<a id="loading"><img style="margin-left:250px;" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>',
                                                title: {
                                                    text: tooltip_title
                                                }
                                            },
                                            hide: { when: 'mouseout', fixed: true },
                                            show: { solo: true, effect: 'slide'},
                                            position: {adjust: {x: 30, y: 0} },
                                            position: {
                                                corner: {target: 'bottomMiddle', tooltip: 'topMiddle'}
                                            },
                                            style: { 
                                                name: 'blue', width: 350, height: 175, padding: 5, background: '#F9F9F9',
                                                tip: {corner: 'topMiddle', size: {x: 20, y : 10 }},
                                                border:{width: 2,radius: 4, color: '#8F8F8F'},
                                                title: { 'color': 'white', 'background': '#81D122'}
                                            },
                                            api: {
                                                onShow: function(){
                                                    $(".qtip-content").html($("ul#"+idclass).html());
                                                }
                                            }
                                        });
                                    }
                                });
                            }); 
                            </script>
                            <div class="row margin0 padding0">
                                <div class="divider10"></div>
                            </div>
                            <div id='calendarcontainer' class="padding0 margin0 row clearfix" style="margin-top:10px; width:100%;"></div>
                            <?php
                                $seasons = $user->getOrderedSeasons();
                                foreach ($seasons as $season){
                                    $timeline = sort_multi_array($season->getTimeLineDetails(), 'order');
                                    foreach($timeline as $activity){
                            ?>
                                <ul id="<?php echo $activity['uniqueid']; ?>" class="nav nav-stacked datalist hide" style="width:360px;">
                                    <li>
                                        <table class="table noborder margin0">
                                            <tr>                                
                                                <td class="padding0">
                                                    <div style="position:relative;">
                                                        <div style="position:absolute; top:5px; right:15px;">
                                                            <a class="btn btn-primary btn-mini wrap"  href="<?php echo $activity['url']; ?>" title="View all details">View</a>
                                                            <a class="btn btn-primary btn-mini wrap"  href="<?php echo $activity['editurl']; ?>" title="Update Activity">Update</a>
                                                        </div>
                                                        <table class="itemlist table noborder margin0">
                                                            <tr>
                                                                <td style="width:65px;"><label class="control-label pull-left">Ref#:</label></td>
                                                                <td><span><?php echo $activity['ref']; ?></span></td>    
                                                            </tr>      
                                                            <tr>
                                                                <td><label class="control-label pull-left">Details:</label></td>
                                                                <td><span><?php echo snippet($activity['description'], 300, '...'); ?></span></td>    
                                                            </tr>
                                                            <tr>
                                                                <td><label class="control-label pull-left">Status:</label></td>
                                                                <td><span><?php echo $activity['status']; ?></span></td>    
                                                            </tr>
                                                            <?php if(in_array($activity['type'], array("1","2","3","4","5","6")) && $activity['expenses'] > 0){ ?>
                                                                <tr>
                                                                    <td><label class="control-label pull-left">Expenses:</label></td>
                                                                    <td><span><?php echo formatNumber($activity['expenses']); ?></span></td>    
                                                                </tr>  
                                                            <?php } ?> 
                                                            <?php if($activity['type'] == "7" && $activity['sale'] > 0){ ?>
                                                                <tr>
                                                                    <td><label class="control-label pull-left">Revenue:</label></td>
                                                                    <td><span><?php echo formatNumber($activity['sale']); ?></span></td>    
                                                                </tr>  
                                                            <?php } ?>      
                                                        </table>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                </ul>       
                            <?php } } ?>	
                        <?php } ?>
                    </form>
                </div>
            <?php } ?>
            <?php if($acl->checkPermission('Farmer Inventory', ACTION_LIST)){ ?> 
                <div id="inventory">
                    <h2>Farm Inventory</h2>
                    <form id="profileform-inventory" class="form-horizontal inventory">
                        <?php if($tab == 'inventory'){ 
                            $inventories = $user->getInventoryDetails();
                            $tcount = $inventories->count();
                        ?>
                            <div class="row" style="margin-left:0px;">
                                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                                <?php } ?>
                                <div class="margin0">
                                    <?php if($isme || $acl->checkPermission("Farmer Inventory", ACTION_CREATE)){ ?>
                                        <a class="btn btn-primary" href="<?php echo $this->baseUrl('inventory/index/userid/'.encode($user->getID())); ?>" title="Add Inventory Item"><i class="icon-plus icon-white"></i> Add Item</a>                                       
                                    <?php } ?>
                                </div>
                                <div class="divider10"></div>
                                <span class="span6 marginleft0" style="width:100%;">
                                    <div class="well row marginleft0" style="min-height:60px; padding-left:10px; position:relative;">
                                    <?php 
                                        if($tcount == 0) { ?>
                                        <div class="alert alert-info" style="margin-top:35px;">No inventory has been done yet. Click on 'Add Item' to get started</div>
                                    <?php } else { ?>                
                                        <label class="labeldescription">Viewing <?php echo $tcount; ?> <?php echo $tcount == 1 ? 'item' : 'inventory items'; ?></label>
                                        
                                        <ul id="datalist" class="nav nav-stacked">
                                            <?php 
                                                foreach($inventories as $inventory){
                                            ?>
                                            <li style="min-height:130px;">
                                                <table class="table noborder margin0">
                                                    <tr>                                
                                                        <td width="10%" style="padding-top:10px; padding-right:15px; vertical-align:middle;">
                                                            <div class="<?php echo $inventory->hasProfileImage() ? 'imagecontainer':''; ?>" style="">
                                                                <img style="width:140px;" src="<?php echo $inventory->getLargePicturePath(); ?>" />
                                                            </div>
                                                        </td>
                                                        <td class="padding0" style="padding-right:15px;">
                                                            <div style="position:relative;">
                                                                <table class="itemlist table noborder margin0">
                                                                    <tr>
                                                                        <td colspan="4"><h2 style="font-size:15px;"><a href="<?php echo $this->baseUrl("inventory/view/id/".encode($inventory->getID())); ?>" title="Details"><?php echo $inventory->getItemName(); ?></a></h2>
                                                                        </td>
                                                                        <td class="actionbuttons" rowspan="4" style="padding-top:5px;">
                                                                            <a class="btn btn-primary btn-mini wrap" style="position:absolute; top:25px; right:10px;" href="<?php echo $this->baseUrl("inventory/view/id/".encode($inventory->getID())); ?>">Details</a>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td style="width:25%;"><label class="control-label">Category: </label></td>
                                                                        <td class="nowrapping"><span><?php echo $inventory->getCategory()->getName(); ?></span></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td><label class="control-label">Description: </label></td>
                                                                        <td colspan="3" class="nowrapping"><span><?php echo nl2br($inventory->getDescription()); ?></span></td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td><label class="control-label">Quantity: </label></td>
                                                                        <td class="nowrapping"><span><?php echo $inventory->getQuantityText(); ?></span></td>
                                                                    </tr>
                                                                </table>
                                                            </div>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </li>
                                            <?php } ?>    
                                        </ul>
                                        <?php } ?>           
                                    </div>
                                </span>
                            </div>
                        <?php } ?>
                    </form>
                </div>
            <?php } ?>
            <div id="finance">
                <h2>Reports</h2>
                <form id="profileform-finance" class="form-horizontal finance">
                    <?php if($tab == 'finance'){ ?>
                        <div class="row" style="margin-left:0px;">
                            <span class="marginleft0 span9" style="width:100%;">
                                <ul class="sectionitems">
                                    <?php if($acl->checkPermission('Farmer Credit History', ACTION_LIST)){ ?>
                                        <li>
                                            <a class="list" href="<?php echo $this->baseUrl("finance/credithistory/id/".encode($user->getID())); ?>" title="Credit History"><img src="<?php echo $this->baseUrl('images/topmenu_market.png'); ?>" /><br /><h2>Credit History</h2></a>
                                        </li>
                                    <?php } ?>      
                                    <?php if($acl->checkPermission('Profit and Loss Statement', ACTION_VIEW)){ ?>
                                        <li>
                                            <a class="list" href="<?php echo $this->baseUrl("report/statement/userid/".$user->getID()); ?>" title="Profit and Loss Statement"><img src="<?php echo $this->baseUrl('images/topmenu_market.png'); ?>" /><br /><h2>Profit & Loss <br />Statement</h2></a>
                                        </li>
                                    <?php } ?>  
                                    <?php if($acl->checkPermission('Farmers Baseline Summary Report', ACTION_VIEW)){ ?>
                                        <li><a class="list" href="<?php echo $this->baseUrl('report/primarybaseline/id/'.$user->getID()); ?>" title="Farmis Baseline Summary Report"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmis Baseline <br />Summary Report</h2></a>
                                        </li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Farmers Baseline Detail Report', ACTION_VIEW)){ ?>
                                        <li>
                                            <a class="list" href="<?php echo $this->baseUrl('report/baselinedetail/id/'.$user->getID()); ?>" title="Farmis Baseline Detailed Report"><img src="<?php echo $this->baseUrl('images/benefit_report.png'); ?>" /><br /><h2>Farmis Baseline <br />Detailed Report</h2></a>
                                        </li>
                                    <?php } ?>
                                </ul>
                            </span>
                        </div>
                    <?php } ?>
                </form>
            </div>
        <?php } ?>
        <?php if($acl->checkPermission('Payments', ACTION_LIST)){ ?> 
            <div id="subscription">
                <h2>Payment History</h2>
                <form id="profileform-subscription" class="form-horizontal subscription">
                    <?php if($tab == 'subscription'){ ?>
                        <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                            <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <?php if($sessionhaserror) { ?>
                            <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar("emailinvitesuccess")) ){ ?>
                            <div class="row-fluid">
                                <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("emailinvitesuccess"); ?></div>
                            </div>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar("phoneinvitesuccess")) ){ ?>
                            <div class="row-fluid">
                                <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar("phoneinvitesuccess"); ?></div>
                            </div>
                        <?php } ?>
                        <span class="span6 marginleft0" style="width:100%;">
                            <div class="well row marginleft0 nobg" style="min-height:60px; padding-left:10px; position:relative;">
                                <div class="margin0" style="position:absolute; right:10px; top:5px;">
                                    <?php if($acl->checkPermission('Payments', ACTION_CREATE)){ ?>
                                        <a href="<?php echo $this->baseUrl('payment/index/userid/'.encode($user->getID()).'/country/'.$country); ?>" class="btn btn-primary " title="New Payment"><i class="icon-plus icon-white"></i> New Payment</a>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Payments', ACTION_LIST)){ ?> 
                                    	<a href="<?php echo $this->baseUrl('payment/list'); ?>" class="btn" title="List Payment"><i class="icon-list"></i> All Payments</a>
                                    <?php } ?>
                                </div>
                                <?php
                                    $payments = $user->getAllPayments();
                                    $pcount = $payments->count();
                                    if($pcount == 0) { ?>
                                    <div class="alert alert-info" style="margin-top:35px;">No payments available</div>
                                <?php } else { ?>                
                                    <label class="labeldescription">Viewing <?php echo $pcount; ?> <?php echo $pcount == 1 ? 'payment' : 'payments'; ?></label>
                                    
                                    <ul id="datalist" class="nav nav-stacked">
                                        <?php 
                                            foreach($payments as $payment){
                                        ?>
                                        <li>
                                            <table class="table noborder margin0">
                                                <tr>                                
                                                    <td width="15%">
                                                    	<label class="control-label" style="margin-bottom:10px; font-size:14px;"><?php echo changeMySQLDateToPageFormat($payment->getTrxDate()); ?></label>
                                                        <label class="control-label">Trx Ref#:</label> <span><?php echo $payment->getTrxCode(); ?></span>
                                                        <label class="control-label">Trx Date#:</label> <span><?php echo formatDateAndTime($payment->getTrxDate(), false); ?></span>
                                                    </td>
                                                    <td class="padding0">
                                                        <div style="position:relative;">
                                                            <table class="itemlist table noborder margin0">
                                                                <tr>
                                                                    <td colspan="4" style="height:28px;">
                                                                        <div style="position:relative;">
                                                                            <div style="position:absolute; right:5px; top:5px;">
                                                                                <?php if($acl->checkPermission('Payments', ACTION_UPDATE)){ ?>
                                                                                    <a href="<?php echo $this->baseUrl('payment/index/id/'.encode($payment->getID()).'/country/'.$country); ?>" class="btn btn-mini" title="Edit Payment" style="margin-bottom:5px;"><i class="icon-pencil"></i></a>
                                                                                    <div class="divider10"></div>
                                                                                <?php } ?>
                                                                                <?php if($acl->checkPermission('Payments', ACTION_DELETE)){ ?>
                                                                                    <a href="javascript: void(0)" title="Delete Entry" class="btn btn-mini deleteline removebutton close" action="<?php echo $this->baseUrl('payment/delete/id/'.$payment->getID()."/entityname/Payment/successurl/".encode($this->viewurl)); ?>" message="Are you sure you want to delete this Payment?">&times;</a>
                                                                                <?php } ?>
                                                                            </div>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td> <label class="control-label">Subject </label><span><?php echo $payment->getSubject(); ?></span></td>
                                                                    <td style="width:24%;"><label class="control-label">Method</label><span><?php echo $payment->getMethod(); ?></span></td>
                                                                    <td style="width:24%;"><label class="control-label">Amount</label><span><?php echo formatMoney($payment->getAmount()); ?></span></td>
                                                                    <td style="width:24%;"><label class="control-label">Status</label><span><?php echo $payment->getPaymentStatus(); ?></span></td>
                                                                </tr>
                                                                <tr>
                                                                    <td><label class="control-label">Description </label><span class="nullifempty"><?php echo $payment->getDescription(); ?></span></td>
                                                                    <td><label class="control-label">Phone</label><span class="nullifempty"><?php echo getShortPhone($payment->getPhone()); ?></span></td>
                                                                    <td><label class="control-label">Verified By</label><span class="nullifempty"><?php echo $payment->getVerifier(); ?></span></td>
                                                                    
                                                                    <td><label class="control-label">Logged By</label><span class="nullifempty"><?php echo $payment->getverifiedby()->getName(); ?></span></td>
                                                                </tr>
                                                                <tr>
                                                                    <td></td>
                                                                    <td><label class="control-label">Service Start</label><span class="nullifempty"><?php echo formatDateAndTime($payment->getSubscription()->getStartDate(), false); ?></span></td>
                                                                    <td><label class="control-label">Service Expiry</label><span class="nullifempty"><?php echo formatDateAndTime($payment->getSubscription()->getEndDate(), false); ?></span></td>
                                                                    
                                                                    <td><label class="control-label">Log Date</label><span class="nullifempty"><?php echo formatDateAndTime($payment->getDateCreated(), true); ?></span></td>
                                                                </tr>
                                                            </table>
                                                        </div>
                                                    </td>
                                                </tr>
                                            </table>
                                        </li>
                                        <?php } ?>
                                    </ul>
                                <?php } ?>
                            </div>
                        </span>
                    <?php } ?>
                </form>
            </div>
        <?php } ?>
        <?php if(($isme || $acl->checkPermission($resourcename, ACTION_EDIT)) && !isEmptyString($user->getID())){ ?> 
        	<?php require APPLICATION_PATH."/views/scripts/profile/settings.phtml"; ?>
        <?php } ?>    
    </div> 
</div>
<script>
	$(document).ready(function() {
		equalHeight($("#farmleft, #farmright"));
	});
</script>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
	