<label id="intro" class="calfont" style="color:#595757; font-size:18px; margin:0; line-height:22px;">FARMIS is the easy way to manage your <br /> agricultural business online allowing you to <br />quickly evaluate your income and expenses.</label>
                <ul id="loginleft">
                	<li>
                    	<img src="<?php echo $this->baseUrl('images/login1.png'); ?>" />
                        <span>
                        	<h2>Capture Activities</h2>
                            <label>Start a season and capture all the activities that you want to track...</label>
                        </span>
                    </li>
                    <li>
                    	<img src="<?php echo $this->baseUrl('images/login2.png'); ?>" />
                        <span>
                        	<h2>Track Expenditures</h2>
                            <label>Find out how much overhead is incured by your farming business...</label>
                        </span>
                    </li>
                    <li>
                    	<img src="<?php echo $this->baseUrl('images/login3.png'); ?>" />
                        <span>
                        	<h2>Find Anything Fast</h2>
                            <label>Search for anything you want to know about your business and find it easily...</label>
                        </span>
                    </li>
                </ul>