<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$controller = $request->getControllerName();
	$action = $request->getActionName();
	
	switch($action){
		case 'input':
			$financetype = $input->getFinanceType();
			break;
		case 'tillage':
			$financetype = $tillage->getFinanceType();
			break;
		case 'plant':
			$financetype = $plant->getFinanceType();
			break;
		case 'treat':
			$financetype = $treat->getFinanceType();
			break;
		case 'harvest':
			$financetype = $harvest->getFinanceType();
			break;
		case 'activity':
			$financetype = $activity->getFinanceType();
			break;
		case 'sale':
			$financetype = $sale->getFinanceType();
			break;
		default:
			break;
	}
	
?>
<div class="row margin0" style="padding:2px; margin-bottom:10px;">
    <span class="pull-left" style="width:100%; margin-right:5px;">
        <div id="location_left" class="well lighter margin0" style="min-height:150px;"> 
            <h3 class="well-legend"><?php echo $this->translate("season_credit_finance_title"); ?></h3>
            <table class="table">
                <tr>
                    <td style="width:35%; padding-left:0;">
                        <table class="table">
                            <tr>
                                <td><label class="control-label" style="font-size:14px;"><?php echo $this->translate("season_credit_type_label"); ?></label></td>
                            </tr>
                            <tr>
                                <td id="sourceradio">
                                <?php
                                     $data = getActivityFinanceSources(2);						  
                                     $capitalradio = new Zend_Form_Element_Radio('financetype',
                                              array(
                                                      'multiOptions' => $data, 
                                                      'view' => new Zend_View(),
                                                      'disableLoadDefaultDecorators' => true,
                                                      'class' => array('financetype'),
                                                      'decorators' => array('ViewHelper',
                                                                          array('HtmlTag', array('tag' => 'div', 'class' => array('inline', 'radio', 'zendradio'))) // use a sorrounding DIV with classes which are copied to the label by JQuery
                                                                      )
                                              )
                                      );
                                      $capitalradio->setValue($financetype);
                                      echo $capitalradio->render();
                                ?>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        <table class="table">
                            <tbody id="hasloan" class="hide">
                                <tr>
                                    <td colspan="2"><label class="control-label" style="font-size:14px;"><?php echo $this->translate("season_credit_finance_details"); ?></label></td>
                                </tr>
                                <tr>
                                    <td style="width:40%;"><label class="control-label"><?php echo $this->translate("season_credit_principal_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <div class="input-prepend"><span class="add-on"><?php echo getCurrencySymbol(); ?></span><input type="text" style="width:80px;" name="principal" id="principal" class="width100 hastooltip isamount rightalign inputrequired greaterthanzero" value="<?php echo $loan->getPrincipal(); ?>" title="<?php echo $this->translate("season_principal_tooltip"); ?>" /></div><div id="principal_error"></div></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_interestrate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <input style="width:50px;" type="text" name="interestrate" id="interestrate" class="centeralign isdecimal hastooltip inputrequired greaterthanzero" value="<?php echo $loan->getInterestRate(); ?>" title="<?php echo $this->translate("season_interestrate_tooltip"); ?>" />&nbsp;<span class="pagedescription">(%)</span><div id="interestrate_error"></div>
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_repayment_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <div class="input-prepend"><span class="add-on"><?php echo getCurrencySymbol(); ?></span><input type="text" style="width:80px;" name="paybackamount" id="paybackamount" class="width100 hastooltip isamount rightalign inputrequired greaterthanzero" value="<?php echo $loan->getPayBackAmount(); ?>" title="<?php echo $this->translate("season_paybackamount_tooltip"); ?>" /></div><div id="paybackamount_error"></div></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_payperiod_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <input style="width:50px;" type="text" name="paybackperiod" id="paybackperiod" class="centeralign isnumber inputrequired greaterthanzero" value="<?php echo $loan->getPayBackPeriod(); ?>" />
                                        <?php
                                            $univalues = getLoanFrequencyValues();
                                            $unitdropdown = new Zend_Form_Element_Select('paybackperiodunit',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $univalues),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('span2','width100','hastooltip', 'selectrequired'),
                                                                    'title' => $this->translate("season_paybackperiod_tooltip")
                                                                )
                                                            );
                                            $unitdropdown->setValue($loan->getPayBackPeriodUnit()); 
                                            echo $unitdropdown->render(); 
                                        ?>
                                        <div id="paybackperiod_error"></div><div id="paybackperiodunit_error"></div></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_datereceived_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <input type="text" name="creditdate" id="creditdate" class="datefield width100 selectrequired" value="<?php echo changeMySQLDateToPageFormat($loan->getcreditdate()); ?>" /><div id="creditdate_error"></div></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_regularpay_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                        <div class="input-prepend"><span class="add-on"><?php echo getCurrencySymbol(); ?></span><input type="text" style="width:65px;" name="installment" id="installment" class="width50 isamount rightalign inputrequired greaterthanzero" value="<?php echo $loan->getInstallment(); ?>" /></div>
                                        &nbsp;/&nbsp;
                                        <?php
                                            $univalues = getLoanRepaymentFrequencyValues();
                                            $unitdropdown = new Zend_Form_Element_Select('installmentunit',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $univalues),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('span2','width80','hastooltip', 'selectrequired'),
                                                                    'title' => $this->translate("season_installment_tooltip")
                                                                )
                                                            );
                                            $unitdropdown->setValue($loan->getInstallmentUnit()); 
                                            echo $unitdropdown->render(); 
                                        ?>
                                        <div id="installment_error"></div><div id="installmentunit_error"></div></td>
                                </tr>
                                <tr>
                                    <td colspan="2"><label class="control-label"><?php echo $this->translate("season_credit_source_label"); ?>:</label>
                                        <span id="bankrow">
                                        <?php
                                            $allsources = getAllFinancialInstitutions();
                                            $sourcedropdown = new Zend_Form_Element_Select('financesourceid',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allsources),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('hastooltip', 'width150'),
                                                                    'style' => 'width:215px;',
                                                                    'title' => $this->translate("season_financesource_tooltip")
                                                                )
                                                            );
                                            
                                            $sourcedropdown->setValue($loan->getFinanceSourceID());
                                            echo $sourcedropdown->render();
                                       ?>
                                       </span>
                                       <span id="softrow">
                                        <input type="text" name="financesourcetext" id="financesourcetext" class="width150 hastooltip" value="<?php echo $loan->getFinanceSourceText(); ?>" placeholder="" title="<?php echo $this->translate("season_financesource_tooltip"); ?>" />
                                       </span>
                                       <div id="financesource_error"></div>
                                    </td>
                                </tr>
                            </tbody>
                            
                            <tbody id="cropfinancing" class="hide">
                                <tr>
                                    <td colspan="2">
                                        <label class="control-label"><?php echo $this->translate("season_credit_client_label"); ?>:</label>
                                        <?php
                                            $allclients = getAllClients();
                                            $sourcedropdown = new Zend_Form_Element_Select('clientid',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allclients),								
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('hastooltip', 'width150'),
                                                                    'style' => 'width:215px;',
                                                                    'title' => $this->translate("season_credit_clientid_tooltip")
                                                                )
                                                            );
                                            
                                            $sourcedropdown->setValue($loan->getClientID());
                                            echo $sourcedropdown->render();
                                       ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><label class="control-label"><?php echo $this->translate("season_credit_value_label"); ?>:</label>
                                        <div class="input-prepend"><span class="add-on"><?php echo getCurrencySymbol(); ?></span><input type="text" style="width:80px;" name="price" id="price" class="width100 hastooltip isamount rightalign" value="<?php echo $loan->getPrice(); ?>" title="<?php echo $this->translate("season_creditvalue_tooltip"); ?>" /></div><div id="price_error"></div></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <label class="control-label"><?php echo $this->translate("season_credit_terms_label"); ?>:</label>
                                        <textarea id="contract" name="contract" class="hastooltip" title="<?php echo $this->translate("season_contract_tooltip"); ?>" style="width:85%;"><?php echo $loan->getContract(); ?></textarea>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </table>
        </div>
    </span>
</div>