<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$harvest = new SeasonHarvest();
	$season = new Season(); 
	$hcounter = "";
	if(!isEmptyString($request->sid)){
		$season->populate(decode($request->sid));
		$harvest->setSeasonID($season->getID());
		$harvest->setUserID($season->getUserID());
		$harvest->setStartDate(date('Y-m-d'));
		$harvest->setStatus(3);
		$hcounter = $harvest->getNextReferencePointer();
		$harvest->setYieldUnit('1');
		$harvest->setTotalHarvestUnit('1');
		$harvest->setFieldSizeUnit('1');
		$harvest->setActivityName('Harvesting');
		$successurl = encode($this->baseUrl("season/harvest/sid/".$request->sid));
	}
	
	// default title is to enable adding any payee
	$title = $this->translate("season_harvest_pagetitle_new"); 
	$posturl = $this->baseUrl("season/harvestcreate");
	$button_title = $this->translate("global_button_save"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$harvest->populate(decode($request->id));
		$title = $this->translate("season_harvest_pagetitle_edit"); 
		$button_title = $this->translate("global_button_save_changes");
		$hcounter = substr($harvest->getRef(), -3);
		$successurl = encode($this->baseUrl("season/harvest/id/".$request->id));
	}
	$loan = $harvest->getCreditDetails();
	$request->setParam('tab', 'seasons');
	$user = $harvest->getUser();
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$harvest->processPost($session->getVar(FORM_VALUES));	
	}
	
	$title = 'Manage Season: '.$harvest->getActivityName();
	$farmtitle = $harvest->getUser()->getName();
	$this->headTitle($title.$browserappend);  
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				activityname: {
					required: true,
					maxlength: 25,
					minlength: 4
				},
				ref: "required",
				startdate: "required",
				enddate: {
					required: true
				},
				method: "required",
				status: "required",
				totalharvest: {
					required: true
				},
				fieldsize: {
					required: true
				},
				yield: {
					required: true
				}
			}, 
			// the messages for each of the fields being validated
			messages: {		
				activityname: {
					required: "Please specify activity name",
					maxlength: "Maximum of 25 character needed",
					minlength: "Minimum of 4 characters needed"
				},
				ref: "Reference not specified",		
				startdate: "<?php echo $this->translate("season_activity_startdate_error"); ?>",
				enddate: {
					required: "<?php echo $this->translate("season_activity_enddate_error"); ?>"
				},
				method: "<?php echo $this->translate("season_method_error"); ?>",
				status: "<?php echo $this->translate("season_status_error"); ?>",
				totalharvest: {
					required: "<?php echo $this->translate("season_harvest_totalharvest_error"); ?>"
				},
				fieldsize: {
					required: "<?php echo $this->translate("season_harvest_fieldsize_error"); ?>"
				},
				yield: {
					required: "<?php echo $this->translate("season_harvest_yield_error"); ?>"
				}
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
		
		// datepickerOpts = new Date();   
		$("#startdate, #enddate").datepicker(datepickerOpts);
		
		// compute activity reference
		$("#startdate").change(function(){
			var label = '';
			var counter = '<?php echo $hcounter; ?>';
			var date = new Date($(this).val());
			var year = date.getFullYear();
			var month = date.getShortMonthName();
			var label = "<?php echo ACTIVITY_HARVESTING_PREFIX; ?>"+month+"/"+year+"/"+counter;
			$("#reflabel").html(label);
			$("#ref").val(label);
		});
		$("#startdate").change();
		
		$("#creditdate").datepicker(datepickerOpts);
		$("#sourcetype").val("");
		$("#clienttype").val("");
		$("#financetype-1, #financetype-2").click(function(){
			multipleDisableContainerByID('hasloan,bankrow,softrow,cropfinancing');
		});
		$("#financetype-3").click(function(){
			multipleEnableContainerByID('hasloan,softrow');
			multipleDisableContainerByID('bankrow','cropfinancing');
			$("#sourcetype").val(2);
		});
		$("#financetype-4").click(function(){
			enableContainerByID('hasloan');
			enableContainerByID('bankrow');
			multipleDisableContainerByID('cropfinancing,softrow');
			$("#sourcetype").val(1);
		});
		$("#financetype-5").click(function(){
			enableContainerByID('cropfinancing');
			multipleDisableContainerByID('hasloan,bankrow,softrow');
			$("#clienttype").val(1);
		});
		<?php if(!isEmptyString($harvest->getFinanceType())){ ?>
			var currentval = '<?php echo $harvest->getFinanceType(); ?>';
			$("#financetype-"+currentval).click();
		<?php } ?>
		
		$("#fieldsize, #totalharvest").keyup(function(){
			var size = $("#fieldsize").val();
			var harv = $("#totalharvest").val();
		
			computed = 0;
			if(!isEmptyString(size) && parseInt(size)> 0 && !isEmptyString(harv) && parseInt(harv)>0){
				var computed = harv / size;
			}
			
			$("#yield").val(computed.toFixed(2));
		});
	}); 
</script>
<h1><?php echo $farmtitle; ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="seasons">
            <form id="indexform" class="form-horizontal seasons" action="<?php echo $posturl; ?>" method="post">
            <?php if($request->tab == 'seasons'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" style="width:72%; min-height:160px;">
                        <h3 class="well-legend"><?php echo $title; ?></h3>
                        <table class="table margin0" style="margin-top:15px;">
                            <tr>
                                <td style="width:20%;"><label class="control-label"><?php echo $this->translate("season_activity_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td style="width:35%;"><input type="text" name="activityname" id="activityname" class="hastooltip" style="width:80%;" title="<?php echo $this->translate("season_activityname_tooltip"); ?>" value="<?php echo $harvest->getActivityName(); ?>" /><div id="activityname_error"></div></td>
                                <td style="width:15%;"><label class="control-label"><?php echo $this->translate("season_activity_ref_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><span id="reflabel"></span><input type="hidden" id="ref" name="ref" value="<?php echo $harvest->getRef(); ?>" /><div id="ref_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_activitystartdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="startdate" id="startdate" class="datefield width100 startdate" value="<?php echo changeMySQLDateToPageFormat($harvest->getStartDate()); ?>" /><div id="startdate_error"></div></td>
                                <td><label class="control-label"><?php echo $this->translate("season_activityenddate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="enddate" id="enddate" class="datefield width100 endafterstart" value="<?php echo changeMySQLDateToPageFormat($harvest->getEndDate()); ?>" /><div id="enddate_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_status_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td colspan="3">
                                    <?php
                                        $allstatuses = getStatusValues();
                                        $statusesdropdown = new Zend_Form_Element_Select('status',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allstatuses),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('hastooltip', 'span2'),
                                                                'title' => $this->translate("season_status_tooltip")
                                                            )
                                                        );
                                        $statusesdropdown->setValue($harvest->getStatus()); 
                                        echo $statusesdropdown->render(); 
                                   ?><div id="status_error"></div>
                                </td>
                            </tr>
                        </table>
                    </span>
                    <span class="pull-right padding0" style="width:24%; margin-left:5px;">
                        <div class="well margin0" style="height:160px;">
                                <h3 class="well-legend">Quick Links</h3>
                                <table class="table noborder" >                       
                                   <tr>		                    
                                        <td class="formactions">
                                            <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $button_title; ?></button>
                                            <a href="<?php echo $this->baseUrl('season/view/id/'.encode($season->getID())); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                            <input type="hidden" name="entityname" value="SeasonHarvest" />
                                            <input type="hidden" id="id" name="id" value="<?php echo encode($harvest->getID()); ?>" />
                                            <input type="hidden" id="seasonid" name="seasonid" value="<?php echo $harvest->getSeasonID(); ?>" />
                                            <input type="hidden" id="userid" name="userid" value="<?php echo $harvest->getSeason()->getUserID(); ?>" />
                                            <input type="hidden" id="stage" name="stage" value="9" />
                                            <input type="hidden" name="sourcetype" id="sourcetype" value="<?php echo $loan->getSourceType(); ?>" />
                                            <input type="hidden" name="clienttype" id="clienttype" value="<?php echo $loan->getClientType(); ?>" />
                                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $this->translate("global_save_success"); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("season/harvestview")); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo $successurl; ?>" /> 
                                        </td>
                                   </tr>
                                </table>                           
                            </div>
                    </span>
                </div>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left" style="width:100%; margin-right:5px;">
                        <div id="location_left" class="well lighter margin0" style="min-height:150px;"> 
                            <h3 class="well-legend">Harvest Details</h3>
                            <table class="table margin0">
                                <tr>
                                    <td style="width:45%; padding-left:0;">
                                        <table class="table">
                                            <tr>
                                                <td style="width:35%;"><label class="control-label"><?php echo $this->translate("season_commodity_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                <td><?php
														$availablecrops = array($harvest->getSeason()->getCropID() => $harvest->getSeason()->getCrop()->getName());
														$cropdropdown = new Zend_Form_Element_Select('cropid',
																			array(
																				'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $availablecrops),								
																				'view' => new Zend_View(),
																				'decorators' => array('ViewHelper'),
																				'class' => array('hastooltip', 'width150'),
																				'title' => $this->translate("season_commodity_tooltip")
																			)
																		);
														$cropdropdown->setValue($harvest->getSeason()->getCropID()); 
														echo $cropdropdown->render();
												   ?><div id="cropid_error"></div></td>
                                            </tr>
                                            <tr>
                                                <td><label class="control-label"><?php echo $this->translate("season_methodused_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                <td><?php
														$alltypes = getHarvestMethods();
														$methoddropdown = new Zend_Form_Element_Select('method',
																			array(
																				'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $alltypes),								
																				'view' => new Zend_View(),
																				'decorators' => array('ViewHelper'),
																				'class' => array('hastooltip', 'width150'),
																				'title' => $this->translate("season_harvest_type_tooltip")
																			)
																		);
														
														$methoddropdown->setValue($harvest->getMethod());
														echo $methoddropdown->render();
												   ?><div id="method_error"></div></td>
                                            </tr>
                                            <tr>
                                            	<td><label class="control-label"><?php echo $this->translate("season_activity_damage_label"); ?>:</label></td>
                                                <td><input style="width:50px;" type="text" name="damaged" id="damaged" class="centeralign isdecimal" value="<?php echo clean_num($harvest->getDamaged()); ?>" />&nbsp;
													<?php
                                                        $damagevalues = getHarvestQuantityUnits();
                                                        $unitdropdown = new Zend_Form_Element_Select('damagedunit',
                                                                            array(
                                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $damagevalues),								
                                                                                'view' => new Zend_View(),
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('hastooltip', 'span2','width100'),
                                                                                'title' => $this->translate("season_harvest_damage_tooltip")
                                                                            )
                                                                        );
                                                        $unitdropdown->setValue($harvest->getDamagedUnit()); 
                                                        echo $unitdropdown->render(); 
                                                   ?><div id="damageunit_error"></div><div id="damage_error"></div></td>
                                            </tr>
                                        </table>
                                    </td>
                                    <td style="padding-left:0;">
                                        <table class="table">
                                            <tr>
                                                <td style="width:32%;"><label class="control-label"><?php echo $this->translate("season_harvest_area_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                <td><input style="width:50px;" type="text" name="fieldsize" id="fieldsize" class="centeralign isdecimal" value="<?php echo clean_num($harvest->getFieldSize()); ?>" />&nbsp;
												<?php
                                                    $areavalues = getAreaUnits();
                                                    $unitdropdown = new Zend_Form_Element_Select('fieldsizeunit',
                                                                        array(
                                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $areavalues),								
                                                                            'view' => new Zend_View(),
                                                                            'decorators' => array('ViewHelper'),
                                                                            'class' => array('hastooltip', 'span2','width100', 'selectrequired'),
                                                                            'title' => $this->translate("season_harvest_fieldsize_tooltip")
                                                                        )
                                                                    );
                                                    $unitdropdown->setValue($harvest->getFieldSizeUnit()); 
                                                    echo $unitdropdown->render(); 
                                               ?><div id="fieldsize_error"></div><div id="fieldsizeunit_error"></div></td>
                                            </tr>
                                            <tr>
                                                <td><label class="control-label"><?php echo $this->translate("season_harvest_quantity_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                <td><input style="width:50px;" type="text" name="totalharvest" id="totalharvest" class="centeralign isdecimal" value="<?php echo clean_num($harvest->getTotalHarvest()); ?>" />&nbsp;
													<?php
                                                        $univalues = getHarvestQuantityUnits();
                                                        $unitdropdown = new Zend_Form_Element_Select('totalharvestunit',
                                                                            array(
                                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $univalues),								
                                                                                'view' => new Zend_View(),
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('hastooltip', 'span2','width100', 'selectrequired'),
                                                                                'title' => $this->translate("season_harvest_totalharvest_tooltip")
                                                                            )
                                                                        );
                                                        $unitdropdown->setValue($harvest->getTotalHarvestUnit()); 
                                                        echo $unitdropdown->render(); 
                                                    ?>
                                                    <div id="totalharvest_error"></div><div id="totalharvestunit_error"></div></td>
                                            </tr>
                                            <tr>
                                                <td><label class="control-label"><?php echo $this->translate("season_harvest_yield_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                <td><input style="width:50px;" type="text" name="yield" id="yield" class="centeralign isdecimal" value="<?php echo clean_num($harvest->getYield()); ?>" />&nbsp;
													<?php
                                                        $yieldvalues = getHarvestYieldUnits();
                                                        $unitdropdown = new Zend_Form_Element_Select('yieldunit',
                                                                            array(
                                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $yieldvalues),								
                                                                                'view' => new Zend_View(),
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('hastooltip', 'span2','width100', 'selectrequired'),
                                                                                'title' => $this->translate("season_harvest_yield_tooltip")
                                                                            )
                                                                        );
                                                        $unitdropdown->setValue($harvest->getYieldUnit()); 
                                                        echo $unitdropdown->render(); 
                                                   ?><div id="yield_error"></div><div id="yieldunit_error"></div></td>
                                            </tr>
                                            <tr>
                                            	<td></td><td></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </span>
                </div>
                <?php require APPLICATION_PATH."/views/scripts/season/finance.phtml"; ?>  
                <?php require APPLICATION_PATH."/views/scripts/season/labour.phtml"; ?>
            <?php } ?>    
            </form>
		</div>
		<?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?>  
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>