<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$plant = new SeasonPlanting();
	$season = new Season(); 
	$pcounter = "";
	if(!isEmptyString($request->sid)){
		$season->populate(decode($request->sid));
		$plant->setSeasonID($season->getID());
		$plant->setUserID($season->getUserID());
		$plant->setStartDate(date('Y-m-d'));
		$pcounter = $plant->getNextReferencePointer();
		$plant->setSeedingRateUnit('2');
		$plant->setFieldSizeUnit('1');
		$plant->setStatus('2');
		$plant->setTotalPlantedUnit(1);
		$plant->setActivityName('Planting');
		$successurl = encode($this->baseUrl("season/plant/sid/".$request->sid));
	}
	
	// default title is to enable adding any payee
	$title = $this->translate("season_plant_pagetitle_new"); 
	$posturl = $this->baseUrl("season/plantcreate");
	$button_title = $this->translate("global_button_save"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$plant->populate(decode($request->id));
		$title = $this->translate("season_plant_pagetitle_edit"); 
		$button_title = $this->translate("global_button_save_changes");
		$pcounter = substr($plant->getRef(), -3);
		$successurl = encode($this->baseUrl("season/plant/id/".$request->id));
	}
	$request->setParam('tab', 'seasons');
	$user = $plant->getUser();
	$loan = $plant->getCreditDetails();
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$plant->processPost($session->getVar(FORM_VALUES));	
	}
	
	$title = 'Manage Season: '.$plant->getActivityName();
	$farmtitle = $plant->getUser()->getName();
	$this->headTitle($title.$browserappend);  
?>
<script>
$(document).ready(function() {
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			activityname: {
				required: true,
				maxlength: 25,
				minlength: 4
			},
			ref: "required",
			startdate: "required",
			enddate: {
				required: true
			},
			method: "required",
			status: "required",
			totalplanted: {
				required: true
			},
			cropid: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {
			activityname: {
				required: "Please specify activity name",
				maxlength: "Maximum of 25 character needed",
				minlength: "Minimum of 4 characters needed"
			},
			ref: "Reference not specified",		
			startdate: "<?php echo $this->translate("season_activity_startdate_error"); ?>",
			enddate: {
				required: "<?php echo $this->translate("season_activity_enddate_error"); ?>"
			},
			method: "<?php echo $this->translate("season_method_error"); ?>",
			status: "<?php echo $this->translate("season_status_error"); ?>",
			totalplanted: {
				required: "<?php echo $this->translate("season_plant_totalplanted_error"); ?>"
			},
			cropid: "<?php echo $this->translate("season_cropid_error"); ?>"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		}
	});
	
	// datepickerOpts = new Date();   
	$("#startdate, #enddate").datepicker(datepickerOpts);
	
	// compute activity reference
	$("#startdate").change(function(){
		var label = '';
		var counter = '<?php echo $pcounter; ?>';
		var date = new Date($(this).val());
		var year = date.getFullYear();
		var month = date.getShortMonthName();
		var label = "<?php echo ACTIVITY_PLANTING_PREFIX; ?>"+month+"/"+year+"/"+counter;
		$("#reflabel").html(label);
		$("#ref").val(label);
	});
	$("#startdate").change();
	
	$("#creditdate").datepicker(datepickerOpts);
	$("#sourcetype").val("");
	$("#clienttype").val("");
	$("#financetype-1, #financetype-2").click(function(){
		multipleDisableContainerByID('hasloan,bankrow,softrow,cropfinancing');
	});
	$("#financetype-3").click(function(){
		multipleEnableContainerByID('hasloan,softrow');
		multipleDisableContainerByID('bankrow','cropfinancing');
		$("#sourcetype").val(2);
	});
	$("#financetype-4").click(function(){
		enableContainerByID('hasloan');
		enableContainerByID('bankrow');
		multipleDisableContainerByID('cropfinancing,softrow');
		$("#sourcetype").val(1);
	});
	$("#financetype-5").click(function(){
		enableContainerByID('cropfinancing');
		multipleDisableContainerByID('hasloan,bankrow,softrow');
		$("#clienttype").val(1);
	});
	<?php if(!isEmptyString($plant->getFinanceType())){ ?>
		var currentval = '<?php echo $plant->getFinanceType(); ?>';
		$("#financetype-"+currentval).click();
	<?php } ?>
}); 
</script>
<h1><?php echo $farmtitle; ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="seasons">
            <form id="indexform" class="form-horizontal seasons" action="<?php echo $posturl; ?>" method="post">
            <?php if($request->tab == 'seasons'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" style="width:72%; min-height:160px;">
                        <h3 class="well-legend"><?php echo $title; ?></h3>
                        <table class="table margin0" style="margin-top:15px;">
                            <tr>
                                <td style="width:20%;"><label class="control-label"><?php echo $this->translate("season_activity_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td style="width:35%;"><input type="text" name="activityname" id="activityname" class="hastooltip" style="width:80%;" title="<?php echo $this->translate("season_activityname_tooltip"); ?>" value="<?php echo $plant->getActivityName(); ?>" /><div id="activityname_error"></div></td>
                                <td style="width:15%;"><label class="control-label"><?php echo $this->translate("season_activity_ref_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><span id="reflabel"></span><input type="hidden" id="ref" name="ref" value="<?php echo $plant->getRef(); ?>" /><div id="ref_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_activitystartdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="startdate" id="startdate" class="datefield width100 startdate" value="<?php echo changeMySQLDateToPageFormat($plant->getStartDate()); ?>" /><div id="startdate_error"></div></td>
                                <td><label class="control-label"><?php echo $this->translate("season_activityenddate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="enddate" id="enddate" class="datefield width100 endafterstart" value="<?php echo changeMySQLDateToPageFormat($plant->getEndDate()); ?>" /><div id="enddate_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_status_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td colspan="3">
                                    <?php
                                        $allstatuses = getStatusValues();
                                        $statusesdropdown = new Zend_Form_Element_Select('status',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allstatuses),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('hastooltip', 'span2'),
                                                                'title' => $this->translate("season_status_tooltip")
                                                            )
                                                        );
                                        $statusesdropdown->setValue($plant->getStatus()); 
                                        echo $statusesdropdown->render(); 
                                   ?><div id="status_error"></div>
                                </td>
                            </tr>
                        </table>
                    </span>
                    <span class="pull-right padding0" style="width:24%; margin-left:5px;">
                        <div class="well margin0" style="height:160px;">
                                <h3 class="well-legend">Quick Links</h3>
                                <table class="table noborder" >                       
                                   <tr>		                    
                                        <td class="formactions">
                                            <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $button_title; ?></button>
                                            <a href="<?php echo $this->baseUrl('season/view/id/'.encode($season->getID())); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                            <input type="hidden" name="entityname" value="SeasonPlanting" />
                                            <input type="hidden" id="id" name="id" value="<?php echo encode($plant->getID()); ?>" />
                                            <input type="hidden" id="seasonid" name="seasonid" value="<?php echo $plant->getSeasonID(); ?>" />
                                            <input type="hidden" id="userid" name="userid" value="<?php echo $plant->getSeason()->getUserID(); ?>" />
                                            <input type="hidden" id="stage" name="stage" value="7" />
                                            <input type="hidden" id="type" name="type" value="1" />
                                            <input type="hidden" name="sourcetype" id="sourcetype" value="<?php echo $loan->getSourceType(); ?>" />
                                            <input type="hidden" name="clienttype" id="clienttype" value="<?php echo $loan->getClientType(); ?>" />
                                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $this->translate("global_save_success"); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("season/plantview")); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo $successurl; ?>" /> 
                                        </td>
                                   </tr>
                                </table>                           
                            </div>
                    </span>
            	</div>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left" style="width:100%; margin-right:5px;">
                        <div id="location_left" class="well lighter margin0" style="min-height:150px;"> 
                                <h3 class="well-legend">Planting Details</h3>
                                <table class="table margin0">
                                    <tr>
                                        <td style="width:45%; padding-left:0;">
                                            <table class="table">
                                                <tr>
                                                    <td style="width:25%;"><label class="control-label"><?php echo $this->translate("season_commodity_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><?php
															$availablecrops = array($plant->getSeason()->getCropID() => $plant->getSeason()->getCrop()->getName());
															$cropdropdown = new Zend_Form_Element_Select('cropid',
																				array(
																					'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $availablecrops),								
																					'view' => new Zend_View(),
																					'decorators' => array('ViewHelper'),
																					'class' => array('hastooltip', 'width150'),
																					'title' => $this->translate("season_commodity_tooltip")
																				)
																			);
															$cropdropdown->setValue($plant->getSeason()->getCropID()); 
															echo $cropdropdown->render();
													   ?><div id="cropid_error"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_plant_method_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><?php
															$alltypes = getPlantingMethods();
															$methoddropdown = new Zend_Form_Element_Select('method',
																				array(
																					'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $alltypes),								
																					'view' => new Zend_View(),
																					'decorators' => array('ViewHelper'),
																					'class' => array('hastooltip', 'span2'),
																					'title' => $this->translate("season_plant_type_tooltip")
																				)
																			);
															
															$methoddropdown->setValue($plant->getMethod());
															echo $methoddropdown->render();
													   ?><div id="method_error"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_plant_area_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><input style="width:50px;" type="text" name="fieldsize" id="fieldsize" class="centeralign isdecimal inputrequired" value="<?php echo clean_num($plant->getFieldSize()); ?>" />
                                                        &nbsp;
                                                        <?php
                                                            $areavalues = getAreaUnits();
                                                            $unitdropdown = new Zend_Form_Element_Select('fieldsizeunit',
                                                                                array(
                                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $areavalues),								
                                                                                    'view' => new Zend_View(),
                                                                                    'decorators' => array('ViewHelper'),
                                                                                    'class' => array('hastooltip', 'span2','selectrequired'),
                                                                                    'title' => $this->translate("season_plant_fieldsize_tooltip")
                                                                                )
                                                                            );
                                                            $unitdropdown->setValue($plant->getFieldSizeUnit()); 
                                                            echo $unitdropdown->render(); 
                                                       ?><div id="fieldsize_error"></div></td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td>
                                            <table class="table">
                                                <tr>
                                                    <td style="width:35%;"><label class="control-label"><?php echo $this->translate("season_plant_quantity_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td>
                                                        <input type="text" name="totalplanted" id="totalplanted" class="centeralign isdecimal" style="width:50px;" value="<?php echo clean_num($plant->getTotalPlanted()); ?>" />&nbsp;
                                                        <?php
                                                            $univalues = getHarvestQuantityUnits();
                                                            $unitdropdown = new Zend_Form_Element_Select('totalplantedunit',
                                                                                array(
                                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $univalues),								
                                                                                    'view' => new Zend_View(),
                                                                                    'decorators' => array('ViewHelper'),
                                                                                    'class' => array('hastooltip', 'span2','width100', 'selectrequired'),
                                                                                    'title' => $this->translate("season_harvest_totalharvest_tooltip")
                                                                                )
                                                                            );
                                                            $unitdropdown->setValue($plant->getTotalPlantedUnit()); 
                                                            echo $unitdropdown->render(); 
                                                        ?>
                                                        <div id="totalplanted_error"></div><div id="totalplantedunit_error"></div>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_plant_rate_label"); ?>:</label></td>
                                                    <td><input style="width:50px;" type="text" name="seedingrate" id="seedingrate" class="centeralign isdecimal" value="<?php echo clean_num($plant->getSeedingRate()); ?>" />&nbsp;
                                                    	<?php
                                                            $ratevalues = getSeedingUnits();
                                                            $unitdropdown = new Zend_Form_Element_Select('seedingrateunit',
                                                                                array(
                                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $ratevalues),								
                                                                                    'view' => new Zend_View(),
                                                                                    'decorators' => array('ViewHelper'),
                                                                                    'class' => array('hastooltip', 'span2'),
                                                                                    'title' => $this->translate("season_plant_seedingrate_tooltip")
                                                                                )
                                                                            );
                                                            $unitdropdown->setValue($plant->getSeedingRateUnit()); 
                                                            echo $unitdropdown->render(); 
                                                       ?><div id="seedingrate_error"></div></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                    </span>
                </div>
                <?php require APPLICATION_PATH."/views/scripts/season/finance.phtml"; ?>  
                <?php require APPLICATION_PATH."/views/scripts/season/labour.phtml"; ?>
            <?php } ?>    
            </form>
		</div>
		<?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?>  
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>