<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$tillage = new SeasonTillage();
	$tillage->populate(decode($request->id));	
	
	$title = "Activity: ".$tillage->getActivityName(); 
	$request->setParam('tab', 'seasons');
	$user = $tillage->getUser();
			
	$title = "Activity: ".$tillage->getActivityName();	
	$farmtitle = $tillage->getUser()->getName();
	$this->headTitle($title.$browserappend);  
?>
<script>
	$(document).ready(function() {
		
	}); 
</script>
<h1><?php echo $farmtitle; ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="seasons">
            <form id="viewform" class="form-horizontal seasons">
            <?php if($request->tab == 'seasons'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" style="width:72%; min-height:160px;">
                        <h3 class="well-legend"><?php echo $title; ?></h3>
                        <table class="table noborder margin0" style="margin-top:15px;">
                            <tr>
                                <td style="width:15%;"><label class="control-label"><?php echo $this->translate("season_activitystartdate_label"); ?>:</label></td>
                                <td style="width:30%;"><?php echo changeMySQLDateToPageFormat($tillage->getStartDate()); ?></td>
                                <td style="width:15%;"><label class="control-label"><?php echo $this->translate("season_activityenddate_label"); ?>:</label></td>
                                <td><?php echo changeMySQLDateToPageFormat($tillage->getEndDate()); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_activity_ref_label"); ?>:</label></td>
                                <td><?php echo $tillage->getRef(); ?></td>
                                <td><label class="control-label"><?php echo $this->translate("season_status_label"); ?>:</label></td>
                                <td><?php echo getStatusText($tillage->getStatus()); ?></td>
                            </tr>
                        </table>
                    </span>
                    <span class="pull-right padding0" style="width:24%; margin-left:5px;">
                        <div class="well margin0" style="height:160px;">
                            <h3 class="well-legend">Quick Links</h3>
                            <table class="table noborder" >                       
                               <tr>		                    
                                    <td class="formactions">
                                       	<a class="btn btn-primary" href="<?php echo $this->baseUrl('season/tillage/id/'.encode($tillage->getID())); ?>" id="update"><i class="icon-pencil icon-white"></i> Update</a>
                                        <a href="javascript: void(0)" id="deleteline" title="Delete Activity" class="btn deleteline noimgbutton" action="<?php echo $this->baseUrl('season/delete/id/'.$tillage->getID()."/entityname/SeasonTillage/successurl/".encode($this->baseUrl('season/view/id/'.encode($tillage->getSeasonID())))); ?>"><i class="icon-trash"></i></a>
                                        <a class="btn" href="<?php echo $this->baseUrl('season/view/id/'.encode($tillage->getSeasonID())); ?>" title="Return to Timeline"><i class="icon-list"></i> View Season</a>  
                                        <?php if($tillage->getUser()->getSeasons()->count() > 1){ ?>           
                                        	<a class="btn" href="<?php echo $this->baseUrl('profile/view/id/'.encode($tillage->getUserID()).'/tab/seasons'); ?>"><i class="icon-list"></i> All Seasons</a>
                                        <?php } ?>      
                                    </td>
                               </tr>
                            </table>                           
                        </div>
                    </span>
            	</div>
            	<div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left" style="width:100%; margin-right:5px;">
                        <div id="location_left" class="well lighter margin0" style="min-height:150px;"> 
                                <h3 class="well-legend">Tillage Details</h3>
                                <table class="table noborder">
                                    <tr>
                                        <td style="width:40%; padding-left:0;">
                                            <table class="table">
                                                <tr>
                                                    <td style="width:35%;"><label class="control-label"><?php echo $this->translate("season_tillage_method_label"); ?>:</label></td>
                                                    <td><?php echo $tillage->getMethodText(); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_tillage_area_label"); ?>: </label></td>
                                                    <td><?php echo isEmptyString($tillage->getFieldSize()) ? '--' : clean_num($tillage->getFieldSize())."&nbsp;<span class='pagedescription'>(".$tillage->getFieldSizeUnitText().")</span>"; ?></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_tillage_depth_label"); ?>:</label></td>
                                                    <td><?php echo isEmptyString($tillage->getDepth()) ? '--' : clean_num($tillage->getDepth())."&nbsp;<span class='pagedescription'>(".$tillage->getDepthUnitText().")</span>"; ?></td>
                                                </tr>
                                            </table>
                                        </td>
                                        <td>
                                            <table class="table">
                                                <tr>
                                                    <td style="width:40%;"><label class="control-label"><?php echo $this->translate("season_tillage_primaryimplements_label"); ?>: </label></td>
                                                    <td><?php echo $tillage->getPrimaryImplementsText(); ?></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_tillage_secondaryimplements_label"); ?>: </label></td>
                                                    <td><?php echo $tillage->getSecondaryImplementsText(); ?></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                    </span>
                </div>
                <?php require APPLICATION_PATH."/views/scripts/season/financeview.phtml"; ?>
                <?php require APPLICATION_PATH."/views/scripts/season/labourview.phtml"; ?>
                <?php require APPLICATION_PATH."/views/scripts/season/expenseview.phtml"; ?>
                <?php require APPLICATION_PATH."/views/scripts/season/notesview.phtml"; ?>
            <?php } ?>    
            </form>
		</div>
		<?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?>  
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>