<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$treat = new SeasonTracking();
	
	$season = new Season(); 
	$tcounter = "";
	if(!isEmptyString($request->sid)){
		$season->populate(decode($request->sid));
		$treat->setSeasonID($season->getID());
		$treat->setUserID($season->getUserID());
		$treat->setStartDate(date('Y-m-d'));
		$treat->setStatus('3');
		$treat->setType("");
		$tcounter = $treat->getNextReferencePointer();
		$treat->setActivityName('Treatment');
		$successurl = encode($this->baseUrl("season/treat/sid/".$request->sid));
	}
	
	// debugMessage($treat->toArray());
	$typename = "Item";
	// default title is to enable adding any payee
	$title = $this->translate("season_treat_pagetitle_new"); 
	$posturl = $this->baseUrl("season/treatcreate");
	$button_title = $this->translate("global_button_save"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$treat->populate(decode($request->id));
		$title = $this->translate("season_treat_pagetitle_edit"); 
		$button_title = $this->translate("global_button_save_changes");
		$tcounter = substr($treat->getRef(), -3);
		$successurl = encode($this->baseUrl("season/treat/id/".$request->id));
	}
	$request->setParam('tab', 'seasons');
	$user = $treat->getUser();
	$loan = $treat->getCreditDetails();
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$treat->processPost($session->getVar(FORM_VALUES));	
	}
	
	$title = 'Manage Season: '.$treat->getActivityName();
	$farmtitle = $treat->getUser()->getName();
	$this->headTitle($title.$browserappend);  
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				activityname: {
					required: true,
					maxlength: 25,
					minlength: 4
				},
				ref: "required",
				startdate: "required",
				enddate: {
					required: true
				},
				method: "required",
				status: "required",
				totalapplied: {
					required: true
				},
				cropid: "required",
				type: "required",
				itemname: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				activityname: {
					required: "Please specify activity name",
					maxlength: "Maximum of 25 character needed",
					minlength: "Minimum of 4 characters needed"
				},
				ref: "Reference not specified",		
				startdate: "<?php echo $this->translate("season_activity_startdate_error"); ?>",
				enddate: {
					required: "<?php echo $this->translate("season_activity_enddate_error"); ?>"
				},
				method: "<?php echo $this->translate("season_treat_method_error"); ?>",
				status: "<?php echo $this->translate("season_status_error"); ?>",
				totalapplied: {
					required: "<?php echo $this->translate("season_plant_totalplanted_error"); ?>"
				},
				cropid: "<?php echo $this->translate("season_cropid_error"); ?>",
				type: "<?php echo $this->translate("season_treat_type_error"); ?>",
				itemname: "<?php echo $this->translate("global_name_error"); ?>"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
		
		// datepickerOpts = new Date();   
		$("#startdate, #enddate").datepicker(datepickerOpts);
		
		// compute activity reference
		$("#startdate").change(function(){
			var label = '';
			var counter = '<?php echo $tcounter; ?>';
			var date = new Date($(this).val());
			var year = date.getFullYear();
			var month = date.getShortMonthName();
			var label = "<?php echo ACTIVITY_TREATMENT_PREFIX; ?>"+month+"/"+year+"/"+counter;
			$("#reflabel").html(label);
			$("#ref").val(label);
		});
		$("#startdate").change();
		
		$("#type").change(function(){
			var id = $(this).val();
			var label = $("option:selected", this).text();
			if(!isEmptyString(id)){
				// alert(id+' '+label);
				$(".typename").html(label);
			}
		});
		$("#type").change();
		
		$("#creditdate").datepicker(datepickerOpts);
		
		$("#sourcetype").val("");
		$("#clienttype").val("");
		$("#financetype-1, #financetype-2").click(function(){
			multipleDisableContainerByID('hasloan,bankrow,softrow,cropfinancing');
		});
		$("#financetype-3").click(function(){
			multipleEnableContainerByID('hasloan,softrow');
			multipleDisableContainerByID('bankrow','cropfinancing');
			$("#sourcetype").val(2);
		});
		$("#financetype-4").click(function(){
			enableContainerByID('hasloan');
			enableContainerByID('bankrow');
			multipleDisableContainerByID('cropfinancing,softrow');
			$("#sourcetype").val(1);
		});
		$("#financetype-5").click(function(){
			enableContainerByID('cropfinancing');
			multipleDisableContainerByID('hasloan,bankrow,softrow');
			$("#clienttype").val(1);
		});
		<?php if(!isEmptyString($treat->getFinanceType())){ ?>
			var currentval = '<?php echo $treat->getFinanceType(); ?>';
			$("#financetype-"+currentval).click();
		<?php } ?>
	}); 
</script>
<style>
.80width, td.80width, .form-horizontal input.80width, .form-horizontal select.80width, select.80width  {
	width:80%;
}
</style>
<h1><?php echo $farmtitle; ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="seasons">
            <form id="indexform" class="form-horizontal seasons" action="<?php echo $posturl; ?>" method="post">
            <?php if($request->tab == 'seasons'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <?php if($sessionhaserror) { ?>
                    <div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" style="width:72%; min-height:160px;">
                        <h3 class="well-legend"><?php echo $title; ?></h3>
                        <table class="table margin0" style="margin-top:15px;">
                            <tr>
                                <td style="width:20%;"><label class="control-label"><?php echo $this->translate("season_activity_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td style="width:35%;"><input type="text" name="activityname" id="activityname" class="hastooltip" style="width:80%;" title="<?php echo $this->translate("season_activityname_tooltip"); ?>" value="<?php echo $treat->getActivityName(); ?>" /><div id="activityname_error"></div></td>
                                <td style="width:15%;"><label class="control-label"><?php echo $this->translate("season_activity_ref_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><span id="reflabel"></span><input type="hidden" id="ref" name="ref" value="<?php echo $treat->getRef(); ?>" /><div id="ref_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_activitystartdate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="startdate" id="startdate" class="datefield width100 startdate" value="<?php echo changeMySQLDateToPageFormat($treat->getStartDate()); ?>" /><div id="startdate_error"></div></td>
                                <td><label class="control-label"><?php echo $this->translate("season_activityenddate_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><input type="text" name="enddate" id="enddate" class="datefield width100 endafterstart" value="<?php echo changeMySQLDateToPageFormat($treat->getEndDate()); ?>" /><div id="enddate_error"></div></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_activitytype_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td>
                                    <?php
                                        $alltypes = getTreatmentTypes();
                                        $typedropdown = new Zend_Form_Element_Select('type',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $alltypes),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('hastooltip'),
                                                                'title' => $this->translate("season_treat_type_tooltip"),
                                                                'style' => "width:80%;"
                                                            )
                                                        );
                                        
                                        $typedropdown->setValue($treat->getType());
                                        echo $typedropdown->render();
                                   ?><div id="type_error"></div>
                                </td>
                                <td><label class="control-label"><?php echo $this->translate("season_status_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                <td><?php
                                        $allstatuses = getStatusValues();
                                        $statusesdropdown = new Zend_Form_Element_Select('status',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $allstatuses),								
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('hastooltip', '80width'),
                                                                'title' => $this->translate("season_status_tooltip"),
                                                                'style' => "width:80%;"
                                                            )
                                                        );
                                        $statusesdropdown->setValue($treat->getStatus()); 
                                        echo $statusesdropdown->render(); 
                                   ?><div id="status_error"></div>
                                </td>
                            </tr>
                        </table>
                    </span>
                    <span class="pull-right padding0" style="width:24%; margin-left:5px;">
                        <div class="well margin0" style="height:160px;">
                                <h3 class="well-legend">Quick Links</h3>
                                <table class="table noborder" >                       
                                   <tr>		                    
                                        <td class="formactions">
                                            <button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $button_title; ?></button>
                                            <a href="<?php echo $this->baseUrl('season/view/id/'.encode($season->getID())); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                                            <input type="hidden" name="entityname" value="SeasonTracking" />
                                            <input type="hidden" id="id" name="id" value="<?php echo encode($treat->getID()); ?>" />
                                            <input type="hidden" id="seasonid" name="seasonid" value="<?php echo $treat->getSeasonID(); ?>" />
                                            <input type="hidden" id="userid" name="userid" value="<?php echo $treat->getUserID(); ?>" />
                                            <input type="hidden" id="cropid" name="cropid" value="<?php echo $treat->getSeason()->getCropID(); ?>" />
                                            <input type="hidden" id="stage" name="stage" value="8" />
                                            <input type="hidden" name="sourcetype" id="sourcetype" value="<?php echo $loan->getSourceType(); ?>" />
                                            <input type="hidden" name="clienttype" id="clienttype" value="<?php echo $loan->getClientType(); ?>" />
                                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $this->translate("global_save_success"); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("season/treatview")); ?>" /> 
                                            <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo $successurl; ?>" /> 
                                        </td>
                                   </tr>
                                </table>                           
                            </div>
                    </span>
                </div>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left" style="width:100%; margin-right:5px;">
                        <div id="location_left" class="well lighter margin0" style="min-height:150px;"> 
                                <h3 class="well-legend"><span class="typename"><?php echo $typename; ?></span> Details</h3>
                                <table class="table margin0">
                                    <tr>
                                        <td style="width:50%; padding-left:0;">
                                            <table class="table">
                                                <tr>
                                                    <td style="width:30%;"><label class="control-label"><?php echo "Name of "; ?><span class="typename"><?php echo $typename; ?></span>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><input style="width:170px;" type="text" name="itemname" id="itemname" class="hastooltip" value="<?php echo $treat->getitemname(); ?>" title="<?php echo $this->translate("season_treat_itemname_tooltip"); ?>" /><div id="itemname_error"></div></td>
                                                </tr>
                                                
                                                <tr>
                                                    <td><label class="control-label">Method Used<?php //echo $this->translate("season_treat_method_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><?php
															$alltypes = getTreatmentMethods();
															$methoddropdown = new Zend_Form_Element_Select('method',
																				array(
																					'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $alltypes),								
																					'view' => new Zend_View(),
																					'decorators' => array('ViewHelper'),
																					'class' => array('hastooltip', 'span2'),
																					'title' => $this->translate("season_treat_method_tooltip")
																				)
																			);
															
															$methoddropdown->setValue($treat->getMethod());
															echo $methoddropdown->render();
													   ?><div id="method_error"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_treat_timing_label"); ?>: </label></td>
                                                    <td><?php
															$alltypes = getTimingValues();
															$timedropdown = new Zend_Form_Element_Select('timing',
																				array(
																					'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $alltypes),								
																					'view' => new Zend_View(),
																					'decorators' => array('ViewHelper'),
																					'class' => array('hastooltip', 'span2'),
																					'title' => $this->translate("season_treat_timing_tooltip")
																				)
																			);
															
															$timedropdown->setValue($treat->getTiming());
															echo $timedropdown->render();
													   ?></td>
                                                </tr>
                                                
                                            </table>
                                        </td>
                                        <td style="padding-left:0;">
                                            <table class="table">
                                                <tr>
                                                    <td style="width:30%;"><label class="control-label"><?php echo $this->translate("season_treat_quantity_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
                                                    <td><input style="width:50px;" type="text" name="totalapplied" id="totalapplied" class="centeralign isdecimal width80" value="<?php echo clean_num($treat->getTotalApplied()); ?>" />&nbsp;
													<?php
                                                            $ratevalues = getTreatmentTotalUnits();
                                                            $unitdropdown = new Zend_Form_Element_Select('totalappliedunit',
                                                                                array(
                                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $ratevalues),								
                                                                                    'view' => new Zend_View(),
                                                                                    'decorators' => array('ViewHelper'),
                                                                                    'class' => array('hastooltip', 'span2'),
                                                                                    'title' => $this->translate("season_treat_totalapplied_tooltip")
                                                                                )
                                                                            );
                                                            $unitdropdown->setValue($treat->getTotalAppliedUnit()); 
                                                            echo $unitdropdown->render(); 
                                                       ?>
                                                    <div id="totalapplied_error"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><span class="typename"><?php echo $typename; ?></span><?php echo " Rate"; ?>:</label></td>
                                                    <td><input style="width:50px;" type="text" name="itemrate" id="itemrate" class="centeralign isdecimal" value="<?php echo clean_num($treat->getItemRate()); ?>" />
                                                        &nbsp;
                                                        <?php
                                                            $ratevalues = getTreatmentMeasureUnits();
                                                            $unitdropdown = new Zend_Form_Element_Select('itemrateunit',
                                                                                array(
                                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select>'), $ratevalues),								
                                                                                    'view' => new Zend_View(),
                                                                                    'decorators' => array('ViewHelper'),
                                                                                    'class' => array('hastooltip', 'span2'),
                                                                                    'title' => $this->translate("season_treat_seedingrate_tooltip")
                                                                                )
                                                                            );
                                                            $unitdropdown->setValue($treat->getItemRateUnit()); 
                                                            echo $unitdropdown->render(); 
                                                       ?><div id="itemrate_error"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><label class="control-label"><?php echo $this->translate("season_treat_target_label"); ?>: </label></td>
                                                    <td><input type="text" name="target" id="target" class="span2 hastooltip" style="width:175px;" value="<?php echo $treat->getTarget(); ?>" title="<?php echo $this->translate("season_treat_target_tooltip"); ?>" /></td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                    </span>
                </div>
                <?php require APPLICATION_PATH."/views/scripts/season/finance.phtml"; ?>  
                <?php require APPLICATION_PATH."/views/scripts/season/labour.phtml"; ?>
            <?php } ?>    
            </form>
		</div>
		<?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?>  
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>