<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$season = new Season(); 
	$season->populate(decode($request->id));
	
	$plant = $season->getSeasonPlants()->get(0);
	$hasplanted = false;
	if(!isEmptyString($plant->getID())){
		$hasplanted = true;
	}
	$crop = $season->getCrop();
	$loan = $season->getLoans()->get(0);
	$user = $season->getUser();
	$request->setParam('tab', 'seasons');
	
	// default title is to enable adding any payee
	$title = $season->getName()." - ".$season->getRef();
	$farmtitle = $season->getUser()->getName();
	$this->headTitle('Season Details '.$browserappend);  
?>
<script>
	$(document).ready(function() {
		equalHeight($("#row1_left, #row1_right"));
		
	}); 
</script>
<style>
.croplist li {
	width:100%;
}
</style>
<h1><?php echo $farmtitle; ?></h1>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/profile/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">
    	<?php require APPLICATION_PATH."/views/scripts/profile/tabstop.phtml"; ?>
		<div id="seasons">
            <form id="profileform-seasons" class="form-horizontal seasons">
            <?php if($request->tab == 'seasons'){ ?>
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <div class="row margin0" style="padding:2px; margin-bottom:0;">
                    <span class="pull-left well lighter margin0" style="width:71%; height:140px;">
                        <h3 class="well-legend"><?php echo $title; ?></h3>
                        <table class="table noborder margin0" style="margin-top:15px;">
                            <tr>
                                <td style="width:20%"><label class="control-label"><?php echo $this->translate("season_startdate_label"); ?>:</label></td>
                                <td style="width:30%"><?php echo $season->getFullStartDate(); ?></td>
                                <td style="width:20%"><label class="control-label"><?php echo $this->translate("season_enddate_label"); ?>:</label></td>
                                <td><?php echo $season->getFullEndDate(); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label">Current Status:</label></td>
                                <td><?php echo $season->getStatusText(); ?></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </table>
                    </span>
                    <span class="pull-right padding0" style="width:25%; margin-left:5px;">
                        <div class="well margin0" id="row1_right" style="height:140px; margin-bottom:10px;">
                            <h3 class="well-legend">Quick Links</h3>
                            <table class="table">                       
                               <tr>		                    
                                    <td class="formactions" style="padding-right:0;">
                                        <a class="btn btn-primary" href="<?php echo $this->baseUrl('season/index/id/'.encode($season->getID())); ?>" title="Update Season" id="update"><i class="icon-pencil icon-white"></i> Update</a>
                                        <a href="javascript: void(0)" id="deleteline" title="Delete Season" class="btn deleteline noimgbutton" action="<?php echo $this->baseUrl('season/delete/id/'.$season->getID()."/entityname/Season/successurl/".encode($this->baseUrl('profile/view/tab/seasons/id/'.encode($season->getUserID())))); ?>"><i class="icon-trash"></i></a>            
                                        <div class="btn-group">
                                            <button class="btn btn-primary dropdown-toggle centeralign" data-toggle="dropdown" id="" href="javascript: void(0)" style="width:110px; padding-left:0;"><i class="icon-plus icon-white"></i> Log Activity</button>
                                            <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="padding-bottom:11px;"><span class="caret"></span></button>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->baseUrl('season/input/sid/'.encode($season->getID())."/type/1"); ?>"><i class="icon-plus"></i> Season Inputs</a></li>
                                                <li><a href="<?php echo $this->baseUrl('season/tillage/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Tillage</a></li>
                                                <li><a href="<?php echo $this->baseUrl('season/plant/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Planting</a></li>
                                                <li><a href="<?php echo $this->baseUrl('season/treat/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Treatment & Pesticides</a></li>
                                                <li><a href="<?php echo $this->baseUrl('season/harvest/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Harvesting</a></li>
                                                <?php //if(false){ ?>
                                                <li><a href="<?php echo $this->baseUrl('season/activity/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Post Harvest</a></li>
                                                <?php // } ?>
                                                <li><a href="<?php echo $this->baseUrl('season/sale/sid/'.encode($season->getID())); ?>"><i class="icon-plus"></i> Season Sales</a></li>
                                            </ul>
                                        </div>
                                        <?php if($season->getUser()->getSeasons()->count() > 1){ ?>           
                                        	<a class="btn" href="<?php echo $this->baseUrl('profile/view/id/'.encode($season->getUserID()).'/tab/seasons'); ?>" title="Return to Timeline"><i class="icon-list"></i> All Seasons</a>
                                        <?php } ?>
                                    </td>
                               </tr>
                            </table>                           
                        </div>
                    </span>
                </div>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" id="row2_left" style="width:97%; min-height:180px; height:auto;">
                        <h3 class="well-legend">Crop Details</h3>
                        <table class="table noborder margin0" style="margin-top:10px;">
                            <tr>
                                <td>
                                    <ul class="croplist">
                                        <li>
                                            <table class="table noborder margin0">
                                                <tr>
                                                    <td width="25%;" class="padding0">
                                                        <div class="imagecontainer" style="width:90%; min-height:90px; padding:2px;">
                                                            <img style="width:100%;" src="<?php echo $crop->getImagePath(); ?>" />
                                                        </div></td>
                                                    <td class="padding4" style="padding-top:0;">
                                                        <table class="table noborder margin0">
                                                            <tr>
                                                                <td class="padding0">
                                                                    <table class="table noborder margin0">
                                                                        <tr>
                                                                            <td colspan="2" class="widgetlabel padding0"><label class="control-label"><?php echo $crop->getName(); ?></label></td>
                                                                        </tr>
                                                                    <?php if($hasplanted){ ?>
                                                                        <tr>
                                                                            <td class="" style="padding-left:0; width:20%;"><?php echo $this->translate("season_plant_area_label"); ?>:</td>
                                                                            <td class="" style=""><?php echo clean_num($plant->getFieldSize())."&nbsp;<span class='pagedescription'>(".$plant->getFieldSizeUnitText().")</span>"; ?></td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td class="" style="padding-left:0;"><?php echo $this->translate("season_plant_quantity_label"); ?>:</td>
                                                                            <td class="" style=""><?php echo clean_num($plant->getTotalPlanted())."&nbsp;<span class='pagedescription'>(".$plant->getTotalPlantedUnitText().")</span>"; ?></td>
                                                                        </tr>
                                                                    <?php } else { ?>
                                                                        <tr>
                                                                            <td class="" style="padding-left:0; width:20%;">Land Size:</td>
                                                                            <td class="" style=""><?php echo clean_num($season->getFieldSize())."&nbsp;<span class='pagedescription'>(".$season->getFieldSizeUnitText().")</span>"; ?></td>
                                                                        </tr>
                                                                    <?php } ?>        
                                                                    </table>
                                                                </td>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                            </table>
                                        </li>
                                   </ul>
                                </td>
                            </tr>
                        </table>
                    </span>
                </div>
                <div class="row margin0" style="padding:2px; margin-bottom:10px;">
                    <span class="pull-left well lighter margin0" id="row2_left" style="width:97%; min-height:50px; height:auto;">
                        <h3 class="well-legend"><?php echo $this->translate("season_credit_finance_title"); ?></h3>
                        <table class="table noborder margin0" style="margin-top:10px;">
                            <tr>
                                <td style="width:20%;"><label class="control-label"><?php echo $this->translate("season_credit_type_label"); ?>:</label></td>
                                <td style="width:20%;"><?php $data = getCapitalSources(); echo $data[$season->getFinanceType()]; ?></td>
                                <td style="width:20%;"><label class="control-label">Net Startup Capital:</label></td>
                                <td><?php echo formatMoney($season->getNetCapital()); ?></td>
                            </tr>
                            <?php if($season->getFinanceType() == 5){ ?>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_credit_client_label"); ?>:</label></td>
                                <td colspan="3"><?php echo $loan->getTheClient(); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_credit_value_label"); ?>:</label></td>
                                <td colspan="3"><?php echo isEmptyString($loan->getPrice()) ? '--' : nl2br($loan->getPrice()); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("season_credit_terms_label"); ?>:</label></td>
                                <td colspan="3"><?php echo isEmptyString($loan->getContract()) ? '--' : nl2br($loan->getContract()); ?></td>
                            </tr>
                            <?php } ?>
                            <tbody id="hasloan">
								<?php if($season->getFinanceType() == 3 || $season->getFinanceType() == 4){ ?>
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_principal_label"); ?>:</label>
                                    <?php echo formatMoney($loan->getPrincipal()); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_interestrate_label"); ?>:</label>
                                    <?php echo $loan->getInterestRate().'&nbsp;<span class="pagedescription">(%)</span>'; ?>&nbsp;</td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_payperiod_label"); ?>:</label>
                                    <?php echo isEmptyString($loan->getPayBackPeriodText()) ? '--' : $loan->getPayBackPeriodText(); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_repayment_label"); ?>:</label>
                                    <?php echo formatMoney($loan->getPayBackAmount()); ?></td>
                                </tr>
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_regularpay_label"); ?>:</label>
                                    <?php echo $loan->getInstallmentText(); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("season_credit_datereceived_label"); ?>:</label>
                                    <?php echo isEmptyString($loan->getcreditdate()) ? '--' : changeMySQLDateToPageFormat($loan->getcreditdate()); ?></td>
                                    <td colspan="2">
                                    <?php if($season->getFinanceType() == 4){ ?>
                                        <label class="control-label"><?php echo $this->translate("season_credit_source_label"); ?>:</label>
                                        <?php echo $loan->getFinancialSourceValue(); ?>
                                    <?php } ?>
                                    <?php if($season->getFinanceType() == 3){ ?>
                                        <label class="control-label"><?php echo $this->translate("season_credit_source_label"); ?>:</label>
                                        <?php echo isEmptyString($loan->getFinanceSourceText()) ? '--' : $loan->getFinanceSourceText(); ?>
                                    <?php } ?>
                                    </td>
                                </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </span>
                </div>
                <div class="row margin0" style="padding:2px;">
                    <span class="pull-left well lighter margin0" style="width:97%; min-height:200px; position:relative;">
                        <h3 class="well-legend margin0">Season Activity Timeline</h3>
                        <a style="position:absolute; right:30px; top:10px; font-size:16px; font-weight:bold;" href="<?php echo $this->baseUrl('profile/view/tab/calendar/id/'.encode($season->getUserID())); ?>" id="calendar" title="View Season Calendar">View Calendar</a>
                        <?php 
                            $timeline = sort_multi_array($season->getTimeLineDetails(), 'order');
                            $acount = count($timeline);
                            if($acount == 0) { ?>
                            <div class="alert alert-info margin10">No activities have been logged. Click on 'Log Activity' to record activities.</div>
                        <?php } else { ?>
                            <ul id="datalist" class="nav nav-stacked">
                            <?php 				  		
                                foreach($timeline as $activity){
                            ?>
                                <li>
                                    <table class="table noborder margin0">
                                        <tr>                                
                                            <td width="15%"><?php echo $activity['date']; ?></a></td>
                                            <td class="padding0">
                                                <div style="position:relative;">
                                                    <table class="itemlist table noborder margin0">
                                                        <tr>
                                                            <td colspan="4"><h2 style="font-size:15px;"><a href="<?php echo $activity['url']; ?>"><?php echo $activity['activityname']; ?></a></h2>
                                                            </td>
                                                            <td class="actionbuttons" rowspan="4" style="padding-top:5px;">
                                                                <a class="btn btn-primary btn-mini wrap" style="position:absolute; top:5px; right:20px;" href="<?php echo $activity['url']; ?>">Details</a>
                                                            </td>
                                                        </tr>
                                                        <tr>
                                                            <td style="width:150px;">
                                                                <label class="control-label">Ref#:</label>
                                                                <span><?php echo $activity['ref']; ?></span></td>
                                                            <td style="width:180px;">
                                                                <label class="control-label">Details </label>
                                                                <span><?php echo snippet($activity['description'], 300, '...'); ?></span></td>
                                                            <td style="width:100px;">
                                                                <label class="control-label">Status</label><span><?php echo $activity['status']; ?></span></td>
                                                            <td>
                                                                <?php if(in_array($activity['type'], array("1","2","3","4","5","6")) && $activity['expenses'] > 0){ ?>
                                                                    <label class="control-label">Expenses</label><span><?php echo formatNumber($activity['expenses']); ?></span>
                                                                <?php } ?>
                                                                <?php if($activity['type'] == "7" && $activity['sale'] > 0){ ?>
                                                                    <label class="control-label">Revenue</label><span><?php echo formatNumber($activity['sale']); ?></span>
                                                                <?php } ?>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                            <?php } ?>    
                            </ul>
                        <?php } ?> 
                    </span>
                </div>
            <?php } ?>
        	</form>
    	</div>
        <?php require APPLICATION_PATH."/views/scripts/profile/tabsbottom.phtml"; ?> 
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>