<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Weather";
	$this->headTitle($title.$browserappend); 
	$locationid = $request->getParam('locationid');
	if(isEmptyString($locationid)){
		$locationid = 35;
	}
	$location = new Location();
	$location->populate($locationid);
	
	$gpslat = $location->getGpsLat();
	$gpslng = $location->getGpsLng();
	$locationstring = $gpslat.','.$gpslng;
	$weatherurl_wu = "http://www.wunderground.com/cgi-bin/findweather/getForecast?brand=wxmap&query=".$locationstring."&zoom=9";
	$timestamp = mktime();
	$weatherurl_fc = "http://forecast.io/#/f/".$locationstring."/".$timestamp;
	
	$type = $request->getParam('state');
	if(isEmptyString($type)){
		$type = 'forecast';
	}
	// debugMessage($weatherurl_fc); 
?>
<script>
$(document).ready(function() {
	// breadcrumb config
	$("#levelone_icon").addClass('icon-list');
	$("#levelone_link").attr('href', '<?php echo $this->viewurl; ?>').html('<?php echo $title; ?>');
	$("#leveltwo_link").html('');
	
	var apiKey = '507a232d6fe4c5dd408b9cda4b2b4010';
	var url = 'https://api.forecast.io/forecast/';
	var lati = 0.313611;
	var longi = 32.581111;
	var data;
	
	$.getJSON(url + apiKey + "/" + lati + "," + longi + "?callback=?", function(data) {
		// alert(data);
		// $('#weather').html(' temperature - ' + data.currently.temperature+', <br />summary - '+data.currently.summary);
	});
	
	$("#locationid").change(function(){
		var id = $(this).val();
		var state = '<?php echo $type; ?>';
		url = '<?php echo $this->baseUrl('weather/index/locationid/'); ?>'+id+'/state/'+state;
		window.location.href = url;
	});
});
</script>
<div>
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
        <div class="container-fluid">
            <div class="row margin0 maxwidth">
            	<form method="get" id="viewform" class="form-horizontal clearfix desktop">
                    <h1><?php echo $title; ?></h1>
                    <div class="wellcontent">
                    	<div class="blocked clear makerelative">
                            <ul class="peoplegroup">
                                <li>
                                   <?php
										$values = getDistricts();
										$dropdown = new Zend_Form_Element_Select('locationid',
															array(
																'multiOptions' => array_merge_maintain_keys(array('' => 'Search locations'), $values),								
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																'class' => array("form-control", 'chzn-select'),
																'style' => 'width:180px; display:inline;'
															)
														);
										$dropdown->setValue($locationid); 
										echo $dropdown->render();
									?>
                                </li>
                                <li>
                                <a href="<?php echo $this->baseUrl('weather/index/state/forecast/locationid/'.$locationid); ?>" class="btn noround <?php echo $type != 'forecast' ? 'btn-primary': ''; ?> inline">Hourly Forecast</a>
                                <a href="<?php echo $this->baseUrl('weather/index/state/current/locationid/'.$locationid); ?>" class="btn noround <?php echo $type != 'current' ? 'btn-primary': ''; ?> inline" style="margin-left:-5px;">Current Conditions</a>
                    				
                                </li>
                            </ul>
                      	</div>
						<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                            <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                        <?php } ?>
                        <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                            <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                        <?php } ?>
                        <div class="widget box makerelative">
                            <div class="widget-header">
                                <h4><i class="icon-th"></i> Weather forecast and current conditions near <?php echo $location->getName(); ?></h4>
                                <div class="toolbar no-padding">
                                    <div class="btn-group">
                                        <a class="gonowhere reloadall btn noround padding10"><i class="icon-refresh"></i></a>
                                    </div>
                                </div>
                            </div>
                            <div class="widget-content no-padding" style="padding:5px;">
								<?php if($type == 'current'){ ?>
                                    <iframe id="forecast_embed" type="text/html" frameborder="0" height="900" width="100%" src="<?php echo $weatherurl_wu; ?>"></iframe>
                                <?php } ?>
                                <?php if($type == 'forecast'){ ?>
                                    <iframe id="forecast_embed" type="text/html" frameborder="0" height="900" width="100%" src="<?php echo $weatherurl_fc; ?>"></iframe>
                                <?php } ?>
                          	</div>
                       	</div>
                  </div>
              	</form>
            </div>
      	</div>
    </div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
